### ISSUE TITLE
Image Rotation Function

### ISSUE THREAD

**Issue by tonyc770** [Bodmer/TFT_eSPI#1010]
I was looking to see if there was a function that could rotate an image (either BMP or JPG) on the screen in 1 degree increments.
My application is a simple compass that can rotate based on input from a compass sensor.
I was looking at sprites, but they are too primative for my application which would require a more graphic rich image.

Thanks...

**Comment by Bodmer** [comment]
The simple answer is no.

I had thought about this but see that there are other well funded developers that are doing a better job than I could! I suggest you look at lvgl as this includes anti-aliased transformations as a good speed. See [here](https://lvgl.github.io/lv_examples/lv_ex_img_3/index.html). An I am sure the other advanced features of that library will prove useful.

I may add a simple super-sampled anti-aliased rotation function at some point but I have other projects that are taking my attention at the moment.
