### ISSUE TITLE
Can a JPG be pushed out in a sprite

### ISSUE THREAD

**Issue by stephensaid** [Bodmer/TFT_eSPI#1018]
Can I push a JPG to a Sprite instead of outputting it right after the sprite?

**Comment by Bodmer** [comment]
Yes, see the [example here](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Sprite/Rotated_Sprite_3).

**Comment by stephensaid** [comment]
Thanks, Bodmer.

I've implemented TFT_eFEX.

I now have a problem with the images. The following image is not right.
![IMG_20210302_205633](https://user-images.githubusercontent.com/1961430/109707375-ff61b580-7b91-11eb-8b69-8cfe05b8e4f6.jpg)

It should look like:
![image](https://user-images.githubusercontent.com/1961430/109707546-30da8100-7b92-11eb-844e-50d4c9cf14f4.png)

I have other images with the same behaviour.

I've tried changing tft.setSwapBytes(true); to tft.setSwapBytes(false); but it has no effect.

Please help.
