### ISSUE TITLE
TOUCH_CS ?

### ISSUE THREAD

**Issue by fungreenfox** [Bodmer/TFT_eSPI#1021]
This display is a ILI9486 8 parraleled, (but doesnt accept that option in the script).
Description link: http://www.lcdwiki.com/3.5inch_Arduino_Display-UNO?fbclid=IwAR3U-K4QBvfifUTyh0xamGr_GV50PNiE5oiAV2CkFI8J4cFvSgnhIec3ocs

The issue is, that Touch_CS can't be defined, as there is no pin labelled by this at the display. 
There is a TFT_CS, can it be re-used as same pin nr. as the Touch_CS pin?

**Comment by Bodmer** [comment]
Touch with parallel displays is not supported by the library. [See here](https://github.com/s60sc/Adafruit_TouchScreen) for the required connection and interface and a compatible touch library.

Check the board you have is fitted with a touch screen, the link you provided does not show that one is fitted.  The typical UNO style TFT boards do not use a touch controller chip so there is no touch CS pin, instead the touch screen resistance must be measured with analogue ports.
