### ISSUE TITLE
problem with fillCircleHelper

### ISSUE THREAD

**Issue by toosimit** [Bodmer/TFT_eSPI#1031]
I have problem with fillCircleHelper i change the corner but doesn't work probably I want select   IV quadrants
![71769277-4267c080-2edc-11ea-9bf8-bf54c3f07c5b](https://user-images.githubusercontent.com/69083993/109206846-9d820400-77bd-11eb-9778-7a83603062ce.JPG)

` tft.fillCircleHelper(240, 160, 140, 4, 0, TFT_BLUE);`
![WhatsApp Image 2021-02-25 at 22 48 26](https://user-images.githubusercontent.com/69083993/109205977-8c84c300-77bc-11eb-8b80-e03852bdd18d.jpeg)
`tft.fillCircleHelper(240, 160, 140, 3, 0, TFT_BLUE);`
![WhatsApp Image 2021-02-25 at 22 50 07](https://user-images.githubusercontent.com/69083993/109205999-94dcfe00-77bc-11eb-860a-14c913475266.jpeg)
`tft.fillCircleHelper(240, 160, 140, 2, 0, TFT_BLUE);`
![WhatsApp Image 2021-02-25 at 22 51 11](https://user-images.githubusercontent.com/69083993/109206178-c8b82380-77bc-11eb-9889-8fdc8961c003.jpeg)

`tft.fillCircleHelper(240, 160, 140,1, 0, TFT_BLUE);`

![WhatsApp Image 2021-02-25 at 22 52 28](https://user-images.githubusercontent.com/69083993/109206228-d8d00300-77bc-11eb-8a0f-c305f03e4419.jpeg)

**Comment by Bodmer** [comment]
The finction does not draw quadrants. You can only draw the top or bottom half. The functon is used to support fillRoundRect().

You have 3 options to achive what you want:
1. Use the setViewport() function (see Viewport_Demo example) to define a window for the quadrant you wish , then use the fillCircleHelper() function
2. Use the [TFT_Shape library](https://github.com/androdlang/TFTShape)
3. Create a new fillQuadrant() function
