### ISSUE TITLE
GC9A01 Animated_dial needle "trailing shadow " issue

### ISSUE THREAD

**Issue by flykarlos** [Bodmer/TFT_eSPI#1034]
Hi Bodmer
I would like to report issue with example Animated_dial on GC9A01 display. Needle is leaving Black shadow efectively clearing dial behind it when it moves. Is the TFT CGRAM not accessible on GC9A01? If yes, is there any workaround?
Thanks!

https://user-images.githubusercontent.com/18057422/109553521-6b311900-7ad3-11eb-8557-9914ff7eef69.mov

EDIT:
some additional info I found describes procedure of "MCU to memory write/read direction", so I am assuming there is CGRAM read possibility.
Page 71 in document linked below.
https://www.buydisplay.com/download/ic/GC9A01A.pdf

**Comment by Bodmer** [comment]
Assuming you are using the small circular screen available from China, then my tests indcate the screen cannot be read. I suspect the display board has hardwired the IM(x) pins into the wrong state.  The display has a single SDA pin (no MOSI+MISO pins) so if it could be read then the library must be configured using  **_#define TFT_SDA_READ_** in the setup file. As this appears to be a limitation of the way the display is built, then nothing can fix this in the library (unless there is a command that I have missed after reading through the datasheet!).

If your ESP32 has PSRAM then a fulls creen 240x240 sprite could be created and used as a frame buffer.

The GC9A01 support is still in the "experimental" phase and thus is currently not listed as a supported device in the ReadMe. I received one of these displays a few days ago and can confirm that sprite plotting with a transparent colour (used for needle in you sketch) does not work properly. I noticed this with the Orrery sketch, however that sketch works fine on other dsplays, so there is something different about in the way the GC9A01 must be driven compared to other displays. This is under investigation.

**Comment by Bodmer** [comment]
See also #867

**Comment by flykarlos** [comment]
Thanks for explanation. I tried to enable `#define TFT_SDA_READ`, but effect was that display was flickering once in every few seconds with strange artifacts and then it was slowly fading out. So `#define TFT_SDA_READ` is clearly not applicable to this Chinese display using GC9A01 driver. 
Waiting for any news regarding Your investigation about this issue. Once again thanks for Your hard work.

**Comment by serdargoksal** [comment]
According to my experience you can read screen with readRect(), when you uncomment 
#define  USE_HSPI_PORT in user_setup.h
However in this case drawLine(), drawText() does not work.

**Comment by Bodmer** [comment]
I have investigated this and it appears that some GC9A01 screens cannot be read.

**Comment by zweann** [comment]
Hi Bodmer,
i tried two different GC9A01 displays, but both can't be read. It's so annoying!
Can you provide a link list with working GC9A01 round displays?

**Comment by RickJHarris** [comment]
> Assuming you are using the small circular screen available from China, then my tests indcate the screen cannot be read. I suspect the display board has hardwired the IM(x) pins into the wrong state. The display has a single SDA pin (no MOSI+MISO pins) so if it could be read then the library must be configured using **_#define TFT_SDA_READ_** in the setup file. As this appears to be a limitation of the way the display is built, then nothing can fix this in the library (unless there is a command that I have missed after reading through the datasheet!).
> 
> If your ESP32 has PSRAM then a full screen 240x240 sprite could be created and used as a frame buffer.
> 
> The GC9A01 support is still in the "experimental" phase and thus is currently not listed as a supported device in the ReadMe. I received one of these displays a few days ago and can confirm that sprite plotting with a transparent colour (used for needle in you sketch) does not work properly. I noticed this with the Orrery sketch, however that sketch works fine on other dsplays, so there is something different about in the way the GC9A01 must be driven compared to other displays. This is under investigation.

I've been trying to get the Animated_dial to work properly on a GC9A01. If I define TFT_SDA_READ do I need to define an SDA pin and connect it to the  GC9A01? If so, which pin? Thanks!

**Comment by 01GOD** [comment]
Sigh...saw now. There are white square graphics artifacts that follow the indicator around. I'm visiting shenzhen now (not chinese) and hoping that gets solved. By the way, the adafruit library example DOES display properly. So that is some hope! 

I think bodmer will get it solved soon.

**Comment by bluecraank** [comment]
Any news on this?

I bought the waveshare gc9a01 round display and it have cgram of about 192,000 bytes.

Reading the display is not working.

Tried everthing mentioned here.
