### ISSUE TITLE
Problem with 4" tft arduino shield display

### ISSUE THREAD

**Issue by adrianiancu** [Bodmer/TFT_eSPI#1044]
Hello, My name is Adrian and I am not able to make a 4" tft display (arduino shield, SKU 13587 - waveshare) working. I was using another display using ILI9341 and I had no problem. I modified the User_Setup.h for ILI9486 and my pin connections but... 
Any suggestion? 
Thank you,
Adrian.

**Comment by adrianiancu** [comment]
I forgot to mention that the display is functional with Arduino uno and Waveshare_4_Inch_Tft_Touchscreen library.

**Comment by Bodmer** [comment]
The Waveshare screen you have is fitted with a 16 bit serial shift register. If this is the same circuit as the Waveshare Raspberry Pi displays then the TFT_eSPI setup option **_#define RPI_DISPLAY_TYPE_** may work. See [setup 11](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup11_RPi_touch_ILI9486.h).

**Comment by Bodmer** [comment]
Assumed resolved by user.

**Comment by adrianiancu** [comment]
I apologies for the delay. I had to take care of my mom in the hospital. Thank you a lot for your answer. It works. I appreciate the energy, time and passion you invest in this.
Adrian
