### ISSUE TITLE
any library information about the 3.2 inch 320*480 screen driven by S6D05A1X

### ISSUE THREAD

**Issue by Renlong2020** [Bodmer/TFT_eSPI#1053]
Hello, do you have any library information about the 3.2 inch 320*480 screen driven by S6D05A1X, or if there is any suggestion that I can use this screen to run on ardiuno uno or 8266 or mega2560.
I saw S6D02... in your library, but I don't know if it can be used with S6D05A1X.

**Comment by Bodmer** [comment]
I do not have any suggestions or information for you.  Hopefully Google will be able to help you.

The chip appears to be a Samsung one, the S6D02 library is for small 160x128 displays and is unlikelyu to work as the setup registers are likely to be different.
