### ISSUE TITLE
How can I control TFT_CS, TFT_DC and TOUCH_CS with a pcf8574??

### ISSUE THREAD

**Issue by sebarch** [Bodmer/TFT_eSPI#1057]
Hi. It's possible to control TFT_CS, TFT_DC and TOUCH_CS with a pcf8574. I need to change code inside the library? I'm using a esp8266 nodemcu v3. Thanks!

**Comment by Bodmer** [comment]
This has been done by some users, search for pcf8574  in closed Issues.

This is not something I have tried and the library does not provide direct support for this.
