### ISSUE TITLE
Help Needed: how to hok up the display

### ISSUE THREAD

**Issue by rahmanshaber** [Bodmer/TFT_eSPI#1058]
I have a waveshare display that i want to hook up with ESP32-s2, but i can't find any guide that shows the hookup guide with those display. 
https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(B)

![image](https://user-images.githubusercontent.com/30831735/110283175-9909e680-801a-11eb-8476-c542d58e7be7.png)

**Comment by Bodmer** [comment]
The library does not support the new ESP32-S2 yet. However for the dual core chip [this is a suggested setup](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup11_RPi_touch_ILI9486.h).

See also [this picture.](https://github.com/Bodmer/TFT_eSPI/blob/master/Tools/RPi_TFT_Connections.png)

These RPi displays vary in design and there is no guarantee that the particular display you have chosen will work. There are variations in the circuit, timings required and the display driver chip fitted, so I am unable to support them all.
