### ISSUE TITLE
colors problem

### ISSUE THREAD

**Issue by ESPboy-edu** [Bodmer/TFT_eSPI#1073]
I'm using excellent TFT_eSPI lib for my www.espboy.com project
LCD ST7735 128х128  ESP8266
it worked fine with 2.2.0 all the written code
but with 2.3.61 there is a problem with colors

it seemed that R and B in 565RGB has swapped

using for setting color this function will solve the problem
#define RBSWAP(w) ( (w>>11) | (w&0b0000011111100000) | (w<<11) )

for example
if I use tft.settextcolor(TFT_YELLOW); I see LIGHT BLUE 
if I use tft.settextcolor(RBSWAP (TFT_YELLOW)); I see YELLOW

it's not difficult to add this function to all my code or to redefine all standard colors, but we lose back-compatibility and performance (

**Comment by Bodmer** [comment]
Different suppliers build the displays with different colour orders so the library accommodates this. The display has a control register to select the colour order.

The settings in the user setup can be used to swap red and green with no performance impact, see lines 68 and 69 in User_Setup.h 

Make sure the right "colour tab" option is also selected in your user setup file.
