### ISSUE TITLE
Playing with Uncanny Eyes

### ISSUE THREAD

**Issue by ismaelit** [Bodmer/TFT_eSPI#108]
Hey all! 
Today I'm just playing with the uncanny eyes (because I've finally received my two ST7735 displays).

But I'm in doubt: is the example only compatible with one eye and not two at the same time for now? 

I have successful displaying one eye (CS=D8), changed only de CS port for the second one(CS=D2, and D1, and D0...), but no image at all.

**Comment by Bodmer** [comment]
I did not try to get the example working with 2 displays.  So the code will need some work to get two displays running... at the moment I do not have time to try and do this.  If you read the header of the sketch you will see the "to-do"list !
