### ISSUE TITLE
help ili9488

### ISSUE THREAD

**Issue by Roman26rus** [Bodmer/TFT_eSPI#1090]
hello. help please I use esp32 I connect the LCD via the parallel interface, I connect the touchscreen via SPI, how to use the touch screen via SPI code the mode of inclusion is parallel ? The ILI9488 LCD controller .touch screen XPT2046 .the problem is that the LCD only works on a parallel 8bit interface ,and the touch is connected to SPI,can you somehow make it work with the built-in library of the touch screen?

**Comment by Pablo2048** [comment]
https://github.com/Bodmer/TFT_eSPI#touch-controller-support - read the first sentence in the paragraph...

**Comment by Roman26rus** [comment]
![800px-3 95-Mega2560-002](https://user-images.githubusercontent.com/42438844/111869362-212faa80-8990-11eb-9daf-f00957711fda.jpg)

**Comment by Roman26rus** [comment]
well, in fact, you can make it work, but I tried the library <XPT2046_Touchscreen.h> it works in conjunction with TFT_eSPI
just I would like to just enable SPI reading of the touch screen in the display connection mode via a parallel bus

**Comment by Pablo2048** [comment]
There is clearly written "The XPT2046 touch screen controller is supported for SPI based displays only." There was many discussions about this (did you search the closed issues?), for example here https://github.com/Bodmer/TFT_eSPI/issues/979#issuecomment-772109636 , https://github.com/Bodmer/TFT_eSPI/discussions/895 ...

**Comment by Bodmer** [comment]
As noted by others above. #895 gives example code.
