### ISSUE TITLE
TFT_eSPI gives issues with dual core

### ISSUE THREAD

**Issue by videobuff** [Bodmer/TFT_eSPI#1095]
I have succesfully build an adaptation of the sprite animated dial becoming a 360 degrees antenna compass. Modified the picture etc, and all is working.
Now i would like to split my code into one task for getting compass data, and another to draw the compass.
So i took a working esp32 dual core example, and created a task2 on core 1 running the plotNeedle(angle,30)  function.
And then the esp32 crashes. Backtracing the crash i get the following:

`PC: 0x400d4b5a: TFT_eSPI::readRect(int, int, int, int, unsigned short*) at /Users/erikschott/Documents/Arduino/libraries/TFT_eSPI-master/TFT_eSPI.cpp line 1168
EXCVADDR: 0x00000000

Decoding stack results
0x400d4b5a: TFT_eSPI::readRect(int, int, int, int, unsigned short*) at /Users/erikschott/Documents/Arduino/libraries/TFT_eSPI-master/TFT_eSPI.cpp line 1168
0x400d11a1: plotNeedle(short, unsigned short) at /Users/erikschott/Documents/Arduino/Webrotor_dual_core/Webroto_dualcore/Webroto_dualcore.ino line 250
0x400d127b: Task2code(void*) at /Users/erikschott/Documents/Arduino/Webrotor_dual_core/Webroto_dualcore/Webroto_dualcore.ino line 170
0x40089d91: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143
`
Attached is the complete code , and I make use of a 2.8" TFT SPI screen.

Is there a way to overcome this issue ?

Erik

[Webroto_dualcore.zip](https://github.com/Bodmer/TFT_eSPI/files/6183491/Webroto_dualcore.zip)

**Comment by Bodmer** [comment]
The problem appears to be that the two processors clash over I/O access. Note that the library is not intended for dual core use and is not thread safe, so it must run in a single partition.  If you come up with a simple way to solve this then let me know!

The second processor can however be used for complex stuff like decoding image data since this just involves normal memory access.
