### ISSUE TITLE
User_Setups

### ISSUE THREAD

**Issue by nopnop2002** [Bodmer/TFT_eSPI#110]
Please tell me how to use User_Setup_Select.h

User_Setup_Select.hの使い方を教えてください

**Comment by Bodmer** [comment]
This is described in the header of the file:

https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L1-L20

By default the User_Setup.h fiel is slected. the comments lines describe the features.

**Comment by nopnop2002** [comment]
Thank you for your explanation.
I tried [User_Setups/Setup14_ILI9341_Parallel.h].
Your Exsample is wonderful.

Most examples sketch work fine, but the following examples sketch will be a compile error.
TFT_eSPI-master\examples\320 x 240\Read_ID_bitbash
TFT_eSPI-master\examples\320 x 240\TFT_Flash_Bitmap

**Comment by Bodmer** [comment]
Great to hear it is working.

Thanks for reporting those issues. The read ID sketch was written for SPI displays so I will need to update to support a parallel display.   I will investigate why the bitmap sketch is not working.

**Comment by nopnop2002** [comment]
If you fix compile error, please close this isuue.
Thank you for Your wonderful examples.

**Comment by Bodmer** [comment]
Flash bitmap example fixed, this was a name clash between the array close[] and an ESP32 library function.

The Read ID sketch is for SPI displays only. I have added a further note to highlight this.
