### ISSUE TITLE
Q: STM32F407 + SSD1963 

### ISSUE THREAD

**Issue by dronecz** [Bodmer/TFT_eSPI#1100]
Hi @Bodmer , 

I bought [this](https://www.aliexpress.com/item/32890948123.html) screen and because I do not like stock FW, I would like to write my own in Arduino IDE. I can change stock FW but there are some limits (especially price of IAR workbench) but before I start, I would like to confirm myself that this is doable (at least in HW point of view). I´m just hobby programmer so maybe some stuff will be wrong. 

1) I can [see](https://github.com/makerbase-mks/MKS-TFT-Hardware/blob/master/MKS%20TFT70/MKS%20TFT70%20V1.1_004/MKS%20TFT70%20V1.1_004%20SCH.pdf) that LCD is connected via 16-bit bus, but if I got info for this library right, you support just 8-bit parallel, is that right? I assume that in 8-bit setup should LCD work as well. 
2) I can not use touch driver with parallel connection so I have to use separate library for this, is that right?

EDIT:

I setup STM32 support for Arduino, set pins for this board and tried to compile Colour_test example and I get a lot of time similar error (just on different lines): 

`C:\Users\Miroslav Zuzelka\Dropbox\@Arduino\Arduino\libraries\arduino_565604\Processors/TFT_eSPI_STM32.c: In member function 'void TFT_eSPI::pushBlock(uint16_t, uint32_t)':
C:\Users\Miroslav Zuzelka\Dropbox\@Arduino\Arduino\libraries\arduino_565604\Processors/TFT_eSPI_STM32.h:888:38: error: redeclaration of 'uint8_t r'
  888 |     #define tft_Write_16(C)  uint8_t r = (((C) & 0xF800)>> 8); uint8_t g = (((C) & 0x07E0)>> 3); uint8_t b = (((C) & 0x001F)<< 3); \
      |                                      ^
C:\Users\Miroslav Zuzelka\Dropbox\@Arduino\Arduino\libraries\arduino_565604\Processors/TFT_eSPI_STM32.c:100:28: note: in expansion of macro 'tft_Write_16'
  100 |       tft_Write_16(color); tft_Write_16(color); tft_Write_16(color); tft_Write_16(color);
      |                            ^~~~~~~~~~~~
C:\Users\Miroslav Zuzelka\Dropbox\@Arduino\Arduino\libraries\arduino_565604\Processors/TFT_eSPI_STM32.h:888:38: note: 'uint8_t r' previously declared here
  888 |     #define tft_Write_16(C)  uint8_t r = (((C) & 0xF800)>> 8); uint8_t g = (((C) & 0x07E0)>> 3); uint8_t b = (((C) & 0x001F)<< 3); \
      |                                      ^
C:\Users\Miroslav Zuzelka\Dropbox\@Arduino\Arduino\libraries\arduino_565604\Processors/TFT_eSPI_STM32.c:100:7: note: in expansion of macro 'tft_Write_16'
  100 |       tft_Write_16(color); tft_Write_16(color); tft_Write_16(color); tft_Write_16(color);
      |       ^~~~~~~~~~~~`

Here is my settings:
[Setup52_MKSTFT70.txt](https://github.com/Bodmer/TFT_eSPI/files/6198181/Setup52_MKSTFT70.txt)

Here is my board settings (not in English but I think you can see the important stuff): 
![image](https://user-images.githubusercontent.com/16454728/112332769-51da5180-8cba-11eb-8870-aed0bf036c7e.png)

Thanks for reply.

**Comment by Bodmer** [comment]
1. Correct, 8 bit only.
2. Correct, a nother library is needed so suit the touch controller installed on the screen.

The errors look like you have multiple copies of the library installed. Look at the errors and see where the conflicting files are located.

If you can, run the Read_User_Setup example to and post the settings report picked up by the compiler.

**Comment by dronecz** [comment]
I did find some issues with more than one instances of library so I update and deleted old TFT_eSPI lib folder before I edited my post with my porblem. I have no other folder with library in my folder: 

![image](https://user-images.githubusercontent.com/16454728/112398189-e74e0380-8d03-11eb-9956-41279012ea86.png)

I tried to compile recomended sktech but result is the same. Here is log from compilation: 
[tft_espi_read_user_setup_log.txt](https://github.com/Bodmer/TFT_eSPI/files/6201087/tft_espi_read_user_setup_log.txt)

Thanks for your help.

**Comment by Bodmer** [comment]
You appear to have renamed the library "arduino_565604", the library name should be TFT_eSPI.

Download and install via the IDE menu if you are having problems installing libraries.

**Comment by Bodmer** [comment]
I have checked and the renaming of the library is not important, I can see a problem in the processor file TFT_eSPI_STM32.h

I will investigate the fix.

**Comment by dronecz** [comment]
> You appear to have renamed the library "arduino_565604", the library name should be TFT_eSPI.
> 
> Download and install via the IDE menu if you are having problems installing libraries.

This name comes from library manager. I install all libraries via library manager if possible. 


> I have checked and the renaming of the library is not important, I can see a problem in the processor file TFT_eSPI_STM32.h
> 
> I will investigate the fix.

Ok, thank you very much!

**Comment by Bodmer** [comment]
I have updated the [main repository](https://github.com/Bodmer/TFT_eSPI), you will need to download from Github (not using IDE as it has not been released yet). I have updated TFT_eSPI_STM32.h

I see the code was marked as "untested" so please report any problems as I do not have a suitable hardware environment to test it.

Keep a copy of your setup if you over-write your complete library.
