### ISSUE TITLE
drop down menu

### ISSUE THREAD

**Issue by clear-sky** [Bodmer/TFT_eSPI#1102]
hi thanks for your great work
this lib runs my lcd faster than i thought
i decided to use drop down menu like below but did not find any way
will be very useful to add this functions to examples if possible
regards
![1-final-listbox-matrix](https://user-images.githubusercontent.com/6883905/112510581-2d13d600-8daf-11eb-9154-caf8e21ea82a.jpg)

**Comment by Bodmer** [comment]
The library does not provide GUI style functions. There are libraries on Github such as GUIslice and lvgl that provide menus and are compatible with the TFT_eSPI library.

I have too many other things on my TODO list to write my own GUI library as I tend to use displays for sensor and status information only.
