### ISSUE TITLE
The Button class from Adafruit_GFX example keypad

### ISSUE THREAD

**Issue by dragospascale** [Bodmer/TFT_eSPI#112]
if tft.setRotation(1);
touch coordinates are not rotated and therefor buttons respond to touches outside their boundaries.
You can check this in your own example keypad_480x320 where you set tft.setRotation(1);

**Comment by Bodmer** [comment]
Run the example/Generic/Touch_calibrate sketch.

Do the white spots appear at the touch positions once calibration is complete?

**Comment by dragospascale** [comment]
No. The x and y axes seem to be reversed.

**Comment by dragospascale** [comment]
I'm using ILI9431 with XPT2040 320x240 display. The problem is with touch. Graphics are ok.

**Comment by dragospascale** [comment]
In Touch.cpp I've forced touchCalibration_invert_x = false; and touchCalibration_invert_y = true;
The if X test returned true and if Y test returned false. Now everything is ok but it is not an elegant solution.

**Comment by Bodmer** [comment]
Are you using a Raspberry Pi display, if not can you provide a web link to the item?

**Comment by dragospascale** [comment]
https://www.aliexpress.com/item/2-8-inch-240-320-HD-color-display-SPI-with-touch-panel-TFT-LCD-module-11pins/32795001104.html

**Comment by Bodmer** [comment]
OK, thanks for the link, I guessed it was a display that I have not tested!

I suspect the touch rotation code is not handling all the 8 possible TFT to touch coordinate conversions needed. I will have to investigate further.

**Comment by Bodmer** [comment]
I have reversed the coordinate transform, that should fix it for your TFT.

I will close this but I have raised Issue #115 to investigate further as I think the transform does not cater for all possible orientations.
