### ISSUE TITLE
pushImage transparent not working. Need transparent instead TFT_WHITE

### ISSUE THREAD

**Issue by dsiberia9s** [Bodmer/TFT_eSPI#1124]
```
// const unsigned char player_1[1320] = {0xff, 0xff, 0xff, ....

void setup() {
  M5Stack();
  tft.pushImage(0, 0, 320, 240, (const uint16_t*)img_1);
  s.createSprite(40, 66);
}

void loop() {
  for (int i = 0; i < 160; i++) {    
    s.pushImage(10, 15, 20, 33, (uint16_t*)player_1, TFT_WHITE);
    s.pushSprite(i, 10);
    delay(40);
  }
}
```

![IMG_2277](https://user-images.githubusercontent.com/34534835/114254703-20ac9180-99db-11eb-9f4a-99df11bb8795.JPG)

**Comment by Bodmer** [comment]
The transparent colour needs to be specified when pushing to the screen, try:
```
s.pushSprite(i, 10, TFT_WHITE);
```
Altough you can push an image to a sprite with a transparent colour I suspect tis line could be used instead with a slight performance advantage:
```
s.pushImage(10, 15, 20, 33, (uint16_t*)player_1);
```

**Comment by dsiberia9s** [comment]
```
void loop() {
  for (int i = 0; i < 160; i++) {    
    s.pushImage(10, 15, 20, 33, (uint16_t*)player_1);
    s.pushSprite(i, 10, TFT_WHITE);
    delay(40);
  }
}
```

![IMG_2281](https://user-images.githubusercontent.com/34534835/114274341-27252280-9a48-11eb-9d26-234be6501be6.jpg)

**Comment by Bodmer** [comment]
Looks like it is working now. Since parts on the image are not white they will not draw as transparent.

**Comment by dsiberia9s** [comment]
Understand. Thanks!
