### ISSUE TITLE
No touch function in de latest version

### ISSUE THREAD

**Issue by Nulista** [Bodmer/TFT_eSPI#114]
Hello Bodmer,

You removed de touch function from the latest version.
Why? 

Thx
Ludo

**Comment by Bodmer** [comment]
Oh! That was not intentional, I will investigate.
Thanks for reporting this.

**Comment by Bodmer** [comment]
Incidentaly, the touch functions have been moved to the "Extensions" folder, in case you were looking for them!

**Comment by Nulista** [comment]
thanks, but now i tested the library with the ESP32, and the TFT did not work, example "meters"
I don't no wat is wrong..??

**Comment by Bodmer** [comment]
Do the other examples work?
Have you configured the User_Setup.h file for the pins you use. If you used the User_Setup_Select.h then which setup have you chosen.

What display do you have (size, driver etc)?

**Comment by Nulista** [comment]
Hello,
Yes i have configured the User_Setup.h file. I use the RPi 3.5 SPI LCD wih the ESP32.
And it is with all the examples.
With the older version it works fine, but with the latest version, there is something wrong...
No properly reset,  perhaps there is something with the pins allocation in the program??

I hope that you could help me?
Thanks

**Comment by Bodmer** [comment]
I will try connecting an ESP32 to my RPi TFT and see what is wrong. I will post back soon.

Meanwhile, can you temporarily revert back to the older wotking TFT_eSPI?

**Comment by Bodmer** [comment]
Hi,

I have fixed part of the problem, the Git repository has been updated.  The RPi TFT now works with the ESP32.

I have not looked at the Touch issue yet.

**Comment by Bodmer** [comment]
Touch is also fixed.

Thanks for reporting this. If you still have problems please raise a new Issue.

**Comment by Nulista** [comment]
Hello,

 

Indeed, all is working fine now! 

Thx a lot!

 

Mvg

Ludo

 

Van: Bodmer [mailto:notifications@github.com] 
Verzonden: zondag 1 april 2018 17:43
Aan: Bodmer/TFT_eSPI <TFT_eSPI@noreply.github.com>
CC: Nulista <ludo.nulens@pandora.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Bodmer/TFT_eSPI] No touch function in de latest version (#114)

 

Closed #114 <https://github.com/Bodmer/TFT_eSPI/issues/114> .
