### ISSUE TITLE
TFT_eSPI_RP2040.c: 'buffer' not defined in TFT_eSPI::pushPixelsDMA

### ISSUE THREAD

**Issue by tooltime60** [Bodmer/TFT_eSPI#1151]
in the function
void TFT_eSPI::pushPixelsDMA(uint16_t* image, uint32_t len)
{
    .....
    dma_channel_configure(dma_tx_channel, &dma_tx_config, &spi_get_hw(spi0)->dr, (uint16_t*)buffer, len, true);
}

buffer is not defined

**Comment by Bodmer** [comment]
Thanks, should be fixed now.
