### ISSUE TITLE
SSD1963 DBC mode

### ISSUE THREAD

**Issue by pipikupi** [Bodmer/TFT_eSPI#1162]
Hi

Does the library support DBC for SSD1963 tft display? I have 7 inch one and it has an option for choose the backlight mode 
![c0f81bb449d14e32b4d6f52ec328cae8](https://user-images.githubusercontent.com/76049929/116398796-19c9af80-a820-11eb-9de0-cb2421bb6d8a.jpg)

**Comment by Bodmer** [comment]
No built in support but a sketch could send the required commands. Check the vendors datasheet.
