### ISSUE TITLE
TTGO T2 0.95 oled not work

### ISSUE THREAD

**Issue by tnthdrhks1** [Bodmer/TFT_eSPI#1166]
i use this library to set text in ttgo t2 0.95 oled's led(https://ko.aliexpress.com/item/32843038592.html).
but it didn't work
i use "Setup22_TTGO_T4" and "Setup25_TTGO_T_Display" to change pin number as this

#define TFT_MOSI            13
#define TFT_MISO            12
#define TFT_SCLK            14
#define TFT_CS              15
#define TFT_DC              16
#define TFT_RST             4

sorry for my bad english and I hope you give me an answer 
Thank you

**Comment by Bodmer** [comment]
The library does not support the SSD1331 display fitted to that board.
Support for new displays is added from time to time.

**Comment by tnthdrhks1** [comment]
Thanks bro
