### ISSUE TITLE
[Question] Set User_Setup.h

### ISSUE THREAD

**Issue by kramer04** [Bodmer/TFT_eSPI#1167]
I've NodeMCU ESP8266-12F and TFT 2.4 8-bit parallel bus 320X240 resolution
Is it correct to set User_Setup.h like this ?

`
#define TFT_PARALLEL_8_BIT`
`#define TFT_HEIGHT 320`
`#define TFT_CS   PIN_D8  // Chip select control pin D8 GPIO 15`
`#define TFT_DC   PIN_D3  // Data Command control pin GPIO 0`
`#define TFT_RST  PIN_D4`
`#define TFT_D0   16  // Must use pins in the range 0-31 for the data bus`
`#define TFT_D1   5  // so a single register write sets/clears all bits.`
`#define TFT_D2   14  // Pins can be randomly assigned, this does not affect`
`#define TFT_D3   12  // TFT screen update performance.`
`#define TFT_D4   13`
`#define TFT_D5   3`
`#define TFT_D6   1`
`#define TFT_D7   10`
`#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH`
`#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters`
`#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters`
`#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm`
`#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.`
`#define LOAD_FONT8`
`#define LOAD_GFXFF`
`#define SMOOTH_FONT`

How to define LCD_RD and LCD_WR ?

I uploaded UTFT_demo but screen stays white

**Comment by Bodmer** [comment]
The library does not support 8 bit parallel displays with the ESP8266  (this is stated in the readme file).
