### ISSUE TITLE
Is there a way to detect if display exist ?

### ISSUE THREAD

**Issue by nielsnl68** [Bodmer/TFT_eSPI#1186]
Hello,

Is there a way to detect if the display exist. i have many esp32's with and without a display and i want to use the same code base when possible.

thanks.

**Comment by Bodmer** [comment]
One way is to perform a write+read to the display CGRAM, see the TFT_ReadWrite_Test example. This would require a display that ca be read and not all displays can be read.

Another very simple common approach used in idustry is to have a configuration pin that is pulled high by say a 10K resistor when a display is fitted,  (this could be the TFT_CS pin), and pulled low with 10K when the display is not fitted.  Then read the state of that pin in the sketch. This is trivial to do if you have different hardware designs.
