### ISSUE TITLE
esp32 reboot when long touch bank screen area

### ISSUE THREAD

**Issue by chenguoping76** [Bodmer/TFT_eSPI#1199]
hi,
I study to use tft_espi with lvgl  GUI, design a simple push button， the event is the button is pressed, coved labal will change it text. Hardware is esp32 with intergal a xpt2046 touch ili9488 3.5' TFT. 

![pushButton](https://user-images.githubusercontent.com/35511222/118905509-6d767700-b94e-11eb-98df-6b5e1732c4aa.png)

I port NXP gui guider's generated code to arduino IDE.

All work fine,  but today when I long touch screen bank area, that is, outside the push button area, esp32 reboot!

The below are some tft_espi  config and event code,  wish somebady give me some hints. thanks!

#include <lvgl.h>
#include <TFT_eSPI.h>

//Ticker tick; /* timer for interrupt handler */
TFT_eSPI tft = TFT_eSPI(); /* TFT instance */
static lv_disp_buf_t disp_buf;
static lv_color_t buf[LV_HOR_RES_MAX * 10];
bool my_touchpad_read(lv_indev_drv_t * indev_driver, lv_indev_data_t * data)
{
    uint16_t touchX, touchY;

    bool touched = tft.getTouch(&touchX, &touchY, 600);

    if(!touched)
    {
      return false;
    }

    if(touchX>LV_HOR_RES_MAX || touchY > LV_VER_RES_MAX)
    {
      Serial.println("Y or y outside of expected parameters..");
      Serial.print("y:");
      Serial.print(touchX);
      Serial.print(" x:");
      Serial.print(touchY);
    }
    else
    {

      data->state = touched ? LV_INDEV_STATE_PR : LV_INDEV_STATE_REL; 
  
      /*Save the state and save the pressed coordinate*/
      //if(data->state == LV_INDEV_STATE_PR) touchpad_get_xy(&last_x, &last_y);
     
      /*Set the coordinates (if released use the last pressed coordinates)*/
      data->point.x = touchX;   // change from data->point.x = touchX;  by cgp, 2021.05.01
      data->point.y = LV_VER_RES_MAX - touchY;   // change from data->point.y = touchY;  by cgp, 2021.05.01
     
      Serial.print("Data x");
      Serial.println(touchX);
      
      Serial.print("Data y");
      Serial.println(LV_VER_RES_MAX - touchY);

    }

    return false; /*Return `false` because we are not buffering and no more data to read*/
}

#include "gui_guider.h"

hw_timer_t * timer = NULL;
const int Timeout = 50;//ms

void IRAM_ATTR onTimer(){
  lv_task_handler(); /* LVGL 工作函数 */
}

lv_ui guider_ui;      // 全局ui结构，由NXP GUI_GUDIER产生

void GUI( void *pvParameters ) {

  ledcSetup(10, 5000/*freq*/, 10 /*resolution*/);
  ledcAttachPin(22, 10);
  analogReadResolution(10);
  ledcWrite(10,768);

  timer = timerBegin(0, 80, true);              //开启定时器 选择timer0，分频系数为80，向上计数
  timerAttachInterrupt(timer, &onTimer, true);  //开启定时器中断函数
  timerAlarmWrite(timer, Timeout * 1000, true); //保护值  开启自动重载
  timerAlarmEnable(timer);                      //使能定时器

  tft.begin();                                  /* TFT init */
  tft.setRotation(3);                           // 3 is ok， 1 系统重启

  uint16_t calData[5] = {269, 3432, 231, 3596, 5}; // change from { 275, 3620, 264, 3532, 1 }; by cgp, 2021.05.01
  tft.setTouch(calData);

  lv_init();
  lv_disp_buf_init(&disp_buf, buf, NULL, LV_HOR_RES_MAX * 10);

  /*Initialize the display*/
  lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);
  disp_drv.hor_res = LV_HOR_RES_MAX;
  disp_drv.ver_res = LV_VER_RES_MAX;
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.buffer = &disp_buf;
  lv_disp_drv_register(&disp_drv);

  /*Initialize the input device driver*/
  lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);             /*Descriptor of a input device driver*/
  indev_drv.type = LV_INDEV_TYPE_POINTER;    /*Touch pad is a pointer-like device*/
  indev_drv.read_cb = my_touchpad_read;      /*Set your driver function*/
  lv_indev_drv_register(&indev_drv);         /*Finally register the driver*/
  
  setup_ui(&guider_ui);
  
  for(;;) {
    //vTaskDelay(500);
  }
  
}

**Comment by Bodmer** [comment]
This appears to be related to the lvgl handler rather than the TFT_eSPI library.  I suspect the watchdog is timing out, in that case adding yield(); in the loop it gets stuck in may fix the problem.  Alternatively perhaps there is an interrupt occurings that is causing a problem.

As I think this is not something that can be fixed in the TFT_eSPI library I will close this issue.  It is probably a good idea to raise it with the lvgl library team to see if they can help.
