### ISSUE TITLE
ILI9163_Init.h

### ISSUE THREAD

**Issue by pipi61** [Bodmer/TFT_eSPI#12]
Hi!
bad text in .h files: st7735, ili9341??

// This is the command sequence that initialises the ST7735 driver
//
// This setup information is in a format accecpted by the commandList() function
// which reduces FLASH space, but on an ESP8266 there is plenty available!
//
// See ILI9341_Setup.h file for an alternative simpler format

**Comment by Bodmer** [comment]
Yes, that is legacy cut and paste stuff that has not been tidied up yet!

Thanks for bringing it to my attention.

**Comment by pipi61** [comment]
Hi!
"Add ILI9163 129 x 128 display support"
this 128*128, or 128*160?
