### ISSUE TITLE
Example 'TFT_Meter_linear' - scale down

### ISSUE THREAD

**Issue by dl5dla** [Bodmer/TFT_eSPI#1212]
I would like to use the meter just on one quarter of the display (ILI9341). I guess in general I can do this by reducing M_SIZE, but the font size still remains the same as before. As far as I understood the font size can be changed within the lines 
```
  case -2: tft.drawCentreString("0", x0, y0 - 12, **2**); 
  ...
```
but it seems that I can only make the font bigger, not smaller. I am wondering whether the used font is already the smallest possible (?).
Thank you for any tipps or clarification.

**Comment by Bodmer** [comment]
You can try the GLCD font (font 1) but you may have to adjust the x,y positions of the values:
```
case -2: tft.drawCentreString("0", x0, y0 - 12, 1); break;
```

**Comment by dl5dla** [comment]
Thanks for your answer. I changed the font to "1" for the scale point "0" and "25" but now they are even a little bit bigger.

<img width="387" alt="Bildschirmfoto 2021-05-25 um 09 17 39" src="https://user-images.githubusercontent.com/37237379/119455671-1e5b8800-bd3a-11eb-8fbf-ef7c9c7a55ac.png">

**Comment by Bodmer** [comment]
This happens because you have changed the example to load a free font, so that font replaces the GLCD font. Use this line before printing the scale to select the GLCD font.
```
tft.setTextFont(1);
```
There is also a smaller Tomthumb free font.

**Comment by dl5dla** [comment]
Thank al ot - that solved it.
