### ISSUE TITLE
Sprite Rotation

### ISSUE THREAD

**Issue by Builder212** [Bodmer/TFT_eSPI#1222]
I've been playing around with sprite rotation, but as far as I can tell the sprite rotation copies the sprite? Is there a simple way to rotate a sprite itself on a point? Or can it only be rotated around the specified tft point? Overall, I could be completely misunderstanding this as well, so clarification on how sprites are rotated would be helpful, as I am certainly not the most knowledgeable person myself.

**Comment by Paulie92** [comment]
Only one sprite can be rotated to another one, which can be after that pushed on the screen - as far as I know.

**Comment by Builder212** [comment]
Ah, that's what I was afraid of. Thank you for the clarification. :)
