### ISSUE TITLE
Just some questions ;)

### ISSUE THREAD

**Issue by Arsen474** [Bodmer/TFT_eSPI#1225]
Hi! Honestly, I am newcomer in all this and probably my questions will be stupid for you :) 
Can i use this driver on raspberry pi zero w?
Will be connected display work as a main?
How to connect display? 

I wanna buy [this display](https://aliexpress.ru/item/32859772356.html?spm=a2g0o.detail.1000060.2.63c2628cH6A8qO&gps-id=aerPdpSubstituteRcmd&scm=1007.33958.210224.0&scm_id=1007.33958.210224.0&scm-url=1007.33958.210224.0&pvid=10e4a165-c804-4c21-afdc-1594bf2eccc1&_t=gps-id:aerPdpSubstituteRcmd,scm-url:1007.33958.210224.0,pvid:10e4a165-c804-4c21-afdc-1594bf2eccc1,tpp_buckets:21387%230%23218179%230&_ga=2.192315693.662443575.1622168881-1684680615.1605642503&_gac=1.162395470.1622170208.Cj0KCQjwhr2FBhDbARIsACjwLo06qKqt0Rmlekj8Gz67ajZhM5bl9_muJ84k42_8VsrAcJ9AFhel8EcaApGVEALw_wcB&sku_id=66440982937)

Thnx for all your answers!

**Comment by Bodmer** [comment]
The library will not work on a RPi Zero. It is intended for Arduino IDE compatible board.
