### ISSUE TITLE
pushScaled();  sprite question

### ISSUE THREAD

**Issue by ESPboy-edu** [Bodmer/TFT_eSPI#1234]
As I see there is no way to scale images and put scaled images or sprites to the TFT.
Only rotated.
Am I right?

**Comment by Bodmer** [comment]
Yes, that is correct.

**Comment by ESPboy-edu** [comment]
is it possible to add to the toDo list this function
pushScaled()
and
pushScaledRotated()

for tft and sprites
for images in RAM and PROGMEM
and for 1,4,8,16 bit images
