### ISSUE TITLE
 Is there a way to adjust the brightness of Dispay in ILI9486_DRIVER?

### ISSUE THREAD

**Issue by TaDi2S** [Bodmer/TFT_eSPI#1235]
When the LCD using the ILI9486 driver uses the same image, the screen is displayed brighter than the existing ILI9488 driver. Is there a way to adjust the brightness of the LCD output screen in software rather than hardware?

**Comment by Bodmer** [comment]
The brightness of the screen is primarily due to the current in the backlight LEDs.

Some displays are fitted with a transistor and thus the backlight brightness can be controlled with a PWM pin.  Others have fixed brightness determined by a resistor soldered to the PCB.
