### ISSUE TITLE
White Screen on st7735 with NodeMCU ESP32S

### ISSUE THREAD

**Issue by OnRaptor** [Bodmer/TFT_eSPI#1236]
[User_Setup and Sketch.zip](https://github.com/Bodmer/TFT_eSPI/files/6671630/User_Setup.and.Sketch.zip)

Maybe you will need a pinout 
![image](https://user-images.githubusercontent.com/58369670/122433751-f0233e00-cfaf-11eb-8427-7f5bc831844b.png)

**Comment by Bodmer** [comment]
Check you user setup configuration is corrent and being picked up by the compiler, by running the Read_User_Setup diagnostic sketch.
