### ISSUE TITLE
Faster driver and DMA for STM32L4xx implemented. Question before PullRequest

### ISSUE THREAD

**Issue by microtronics** [Bodmer/TFT_eSPI#1238]
Hi!

First of all: nice library!

I just extended your STM32 support for L4 variants. However, before I open a pull request I have a question regarding the initialization of spiHal:
In TFT_eSPI\Processors\TFT_eSPI_STM32.h you only seem to initialize spiHal like this:
`#define INIT_TFT_DATA_BUS spiHal.Instance = SPI1;`
This is not sufficient for me, though. The HAL_SPI_(TX/RX/TXRX...) primitives also use and check lots of other parts of spiHal. How does it work for you? If I leave out the other initialization and the call to HAL_SPI_INIT it won't work for me. What am I missing?
Currently, for the L4xx the code looks like this:
```
      #define INIT_TFT_DATA_BUS spiHal.Instance = SPI1;\
        spiHal.Instance = SPI1;\
        spiHal.Init.Mode = SPI_MODE_MASTER;\
        spiHal.Init.Direction = SPI_DIRECTION_2LINES;\
        spiHal.Init.DataSize = SPI_DATASIZE_4BIT;\
        spiHal.Init.CLKPolarity = SPI_POLARITY_LOW;\
        spiHal.Init.CLKPhase = SPI_PHASE_1EDGE;\
        spiHal.Init.NSS = SPI_NSS_SOFT;\
        spiHal.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2;\
        spiHal.Init.FirstBit = SPI_FIRSTBIT_MSB;\
        spiHal.Init.TIMode = SPI_TIMODE_DISABLE;\
        spiHal.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;\
        spiHal.Init.CRCPolynomial = 7;\
        spiHal.Init.CRCLength = SPI_CRC_LENGTH_DATASIZE;\
        spiHal.Init.NSSPMode = SPI_NSS_PULSE_DISABLE;\
        HAL_SPI_Init(&spiHal);\
        dmaHal.Instance = DMA1_Channel3;
```

**Comment by Bodmer** [comment]
STM32 DMA support has been tested on selected "Arduino" Nucleo boards STM32F103/411/446/767/7xx and works fine.

I do not have any L series boards to test both SPI and 8 bit parallel operation, and hence I would not be able to support users who have problems in future. Sadly I do not have the time to support more processor variants at the moment.
