### ISSUE TITLE
does not show anything TFT7789 screen

### ISSUE THREAD

**Issue by mavilas2096** [Bodmer/TFT_eSPI#1249]
Good afternoon. First of all, it must say that it is an excellent bookstore.

I am having trouble displaying 7789.
 
I have managed to make it work with the adafruit 7789 library, I want to use yours but nothing.

I had previously occupied it and it had worked without problems, but now with a new screen nothing ...

It is worth mentioning that I am using a screen that I remove from a Chinese relog that they sell, specifically D20, I know that the driver is 7789 because it works with the adafruir library.
Might you help me?

**Comment by Bodmer** [comment]
I have been busy with other priority activities... do you still need support?
