### ISSUE TITLE
using ILI9486 with SPI

### ISSUE THREAD

**Issue by ayashkant** [Bodmer/TFT_eSPI#1252]
Hello sir, 
I am using this driver using SPI i have selected the ILI9486 in the user_setup.h and uncommented the esp32 pins with MOSI = 13, MISO = 12, SCK = 14, CS = 27 and DC = 19 but it is not able communicate properly using SPI and I am not able to print anything in the display. Plz help if u have any solution

**Comment by Bodmer** [comment]
I have been busy with other priority activities... do you still need support?

**Comment by nicolasaw** [comment]
> I have been busy with other priority activities... do you still need support?

Hi, I might have the same issue. I am using ILI9488 SPI and I am confused which pin configurations should I use, any guidance for that?

**Comment by Bodmer** [comment]
Assumed resolved.

@nicolasaw please raise a new issue and explain what you need to know.
