### ISSUE TITLE
GC9A01 display using 8 bit Parallel on ESP32

### ISSUE THREAD

**Issue by srudrawadayermath** [Bodmer/TFT_eSPI#1260]
Hello. I am trying to get my display to work. I am using 8bit 8080 with GC9A01 driver. 

I have also replaced Setup46_GC9A01.h with  lines from User_Setup.h which are effectively as below:

#define GC9A01_DRIVER
	
#define ESP32_PARALLEL
	
#define TFT_WIDTH  240
#define TFT_HEIGHT 240

#define TFT_CS   33  // Chip select control pin
#define TFT_DC   15  // Data Command control pin - must use a pin in the range 0-31
#define TFT_RST  32  // Reset pin

#define TFT_WR    4  // Write strobe control pin - must use a pin in the range 0-31
#define TFT_RD    2

#define TFT_D0   12  // Must use pins in the range 0-31 for the data bus
#define TFT_D1   13  // so a single register write sets/clears all bits
#define TFT_D2   26
#define TFT_D3   25
#define TFT_D4   17
#define TFT_D5   16
#define TFT_D6   27
#define TFT_D7   14

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
//#define LOAD_FONT8N // Font 8. Alternative to Font 8 above, slightly narrower, so 3 digits fit a 160 pixel TFT
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

#define SMOOTH_FONT

Could someone please help me figure out where I am wrong? Thank you in advance

**Comment by Bodmer** [comment]
Sorry about the slow response. At the moment that display has not been tested in parallel mode as I do not have a suitable display. At the moment SPI is the only tested interface for it.
