### ISSUE TITLE
Using on Arduino Mega with 9486

### ISSUE THREAD

**Issue by dineshhops** [Bodmer/TFT_eSPI#1262]
I am trying to hooking up 3.5 inch TFT library with Arduino Mega. I am programming it successfully using MCUFriend library. However I want to TFT_eSPI library. I have gone through library but not able to use it with mega.

I think, it is because drivers are not defined in the library. Can you please help in drivers for arduino mega.

**Comment by Bodmer** [comment]
The Mega does not have sufficient RAM to use the advanced library features. Essentially you could run it in a very basic mode with minimal fonts, but then the functionality would be similar to MCUfriendKbv.
