### ISSUE TITLE
Create_Font Processing Sketch Issue

### ISSUE THREAD

**Issue by tonyc770** [Bodmer/TFT_eSPI#1273]
I installed Processing 3.5.4 and tried to run the Create_Font sketch, but it appears there are some errors in the code that it doesn't like.

Is there an update to this sketch for it to working in this version of Processsing?

Thanks...

**Comment by Bodmer** [comment]
I can run the original sketch that comes with the library using Processing 3.5.4 and do not get an error. This is under Windows 10.

Have you made and changes to the sketch?

**Comment by Bodmer** [comment]
Perhaps you did not include the required folders with the sketch?  [See here.](https://github.com/Bodmer/TFT_eSPI/tree/master/Tools/Create_Smooth_Font/Create_font)
