### ISSUE TITLE
Support for unicode characters

### ISSUE THREAD

**Issue by luizoti** [Bodmer/TFT_eSPI#1275]
Is possible to add support for charters like?

❤ --> â\u009d¤

In my the result is a square.

**Comment by Bodmer** [comment]
These formats should work:
```
tft.println("€"); // €
tft.println("\u20AC"); // €
```
Note that 0x9D is not a valid UTF8 code point, [see here](https://en.wikipedia.org/wiki/UTF-8). The square (often called Tofu!) means that either the character is illegal or is not present in the loaded font.
