### ISSUE TITLE
Request Support for ST7789 on new Adafruit 1.54" 240x240

### ISSUE THREAD

**Issue by ferazambuja** [Bodmer/TFT_eSPI#128]
Hi, I've got the new Adafruit 1.54" 240x240 Wide Angle TFT LCD Display with MicroSD - ST7789 (https://www.adafruit.com/product/3787). Adafruit-ST7735-Library was updated with the changes.

Would be too complicated to bring them to TFT_eSPI?

**Comment by Bodmer** [comment]
I can add the display, it is just a case of adding a few files that define the init and rotation control commands.

I may be able to find time to do this over the coming weekend if you are prepared to run some tests as I do not have one of those displays.

Do you have a display that will work with TFT_eSPI as currently written, so you can gain familiarity with how to setup the library?

**Comment by ferazambuja** [comment]
Yes, I have the new display. It actually "works", but like on the pre updated adafruit library it gets the rotations and colors wrong.

**Comment by Bodmer** [comment]
Been rather busy recently, this is still near the top of my "todo" list!

**Comment by Bodmer** [comment]
I have updated the library to support the ST7789.

If you can test it for me that would be great.  Let me know if it works. I do not have a ST7789 display but it compiles OK and shows inverted colours on a ILI9341 with mirroring, this suggests it should be OK with a ST7789 driver.

**Comment by ferazambuja** [comment]
I will give it a try. Thanks

**Comment by ferazambuja** [comment]
Rotation seems to be off.
Using the 320x240 examples fill the screen and display the colors correctly.
However, the rotation is off. I even try with a simple print example.

**Comment by Bodmer** [comment]
OK, thanks for testing. Do any of the rotations look OK, if so which ones?

**Comment by ferazambuja** [comment]
All of them seem to be off almost to the center of the screen. 

I even try the: 
#define TFT_WIDTH  240
#define TFT_HEIGHT 240

If you have any specific code that you want me to try let me know. I can photograph and post here.

**Comment by Bodmer** [comment]
OK, I had a look at the Adafruit code and see that they use an ofset of 80 pixels so that explains what you see. I will update the code to add the offset.

**Comment by ferazambuja** [comment]
Yeah, it does look like an offset.

**Comment by Bodmer** [comment]
It should all work fine now. I have added in the rotation offset.

You can tie the chip select low if you wish to save a pin provising there are no other functions on the same SPI bus.
