### ISSUE TITLE
how i create one new class that inherited tft_eSprite?

### ISSUE THREAD

**Issue by alieslamibidgoli** [Bodmer/TFT_eSPI#1292]
I wrote this code but Compiler gets an error 

public class Box : tft_eSprite{
}

**Comment by Pablo2048** [comment]
https://www.geeksforgeeks.org/inheritance-in-c/

```cpp
class Box : public TFT_eSprite {
};
```

same way as in https://github.com/Bodmer/TFT_eSPI/blob/58f457ba9703613bfcd70b411d66bbbc948fa815/Extensions/Sprite.h#L8

**Comment by alieslamibidgoli** [comment]
> 
> 
> https://www.geeksforgeeks.org/inheritance-in-c/
> 
> ```c++
> class Box : public TFT_eSprite {
> };
> ```
> 
> same way as in
> 
> https://github.com/Bodmer/TFT_eSPI/blob/58f457ba9703613bfcd70b411d66bbbc948fa815/Extensions/Sprite.h#L8

thank you.
but "class Box : public TFT_eSprite {};" gets error.

**Comment by Pablo2048** [comment]
... and the error is?

**Comment by Bodmer** [comment]
If you have spotted an issue with the library I can help, but it is not clear to me what issue you have with the library.
