### ISSUE TITLE
1 and 8 bit sprites much slower on esp32

### ISSUE THREAD

**Issue by laurentopia** [Bodmer/TFT_eSPI#130]
I think the pixels are not packed together into 16 or 32 bit words so a 32 bit CPU needs to cast constantly.

**Comment by Bodmer** [comment]
The drawing of graphics in Sprites involves many steps and bounds checks so the casting imapct would be negligible. The rendering of Sprites to screen also requires more processing steps. If you examine the underlying cide in the library you will see what I mean.
