### ISSUE TITLE
Lolin D32 Pro with ili9431

### ISSUE THREAD

**Issue by ghost** [Bodmer/TFT_eSPI#1307]
I have an ili9431 display that I've used before successfully with an ESP32 Devkit-V1. I'd like to use it for another project that I'm using a Lolin D32 Pro for, but I'm having trouble getting the two to work together. Is there some sort of special user config changes I need to make? Or is this board not able to be used with this library? I've tried wiring it up with the same wiring I used on the devkit-v1 with no luck. The display doesn't seem to be getting power, which might have to do with my wiring. I fixed the previous issues I was having with the multiple declarations of things by commenting out lines in the d32_pro/arduino_pins.h as suggested in another issue, but while the code uploads it appears that there is no power to the display.

**Comment by Bodmer** [comment]
The display and processor combination should work. Check the setup file you are using in "User_Setup_Select.h".

Check the correct one is being compiled in uby runnung the "Read_User_Setup" diagnostic sketch.

**Comment by Bodmer** [comment]
Assumed resolved.
