### ISSUE TITLE
$ sign prints as £ in font 4

### ISSUE THREAD

**Issue by kondorcl** [Bodmer/TFT_eSPI#1314]
Pleae help me. I have spanish keyboard. When I put "tft.drawString("$", 64, 67, 4);" display sign "£" and not "$".

**Comment by Bodmer** [comment]
Unfortunately I replaced $ with £ many years ago for my own use and thus $ is not available in that font :-(

**Comment by Bodmer** [comment]
I have re-instated the $ sign in Font 4

**Comment by kondorcl** [comment]
Thanks very much Bodmer.
