### ISSUE TITLE
dark side of the moon

### ISSUE THREAD

**Issue by wysiecki** [Bodmer/TFT_eSPI#132]
Hi all,

got a short question about the moon in weather example.
When it runs for a longer period of time, the moon is getting distorted and finally disappears.

Any hint on this ?

THX
Martin

**Comment by Bodmer** [comment]
Interesting! Have you allocated 3M to SPIFFS?

**Comment by wysiecki** [comment]
Hi, yes, and also tried to convert the images to JPEG to save space.
And the images are correct, no faults, but still, check please the image.

Any idea ?

Thank you
Martin
![moon](https://user-images.githubusercontent.com/3341435/39572601-16420d82-4ed0-11e8-8add-46c839714f69.jpg)

**Comment by wysiecki** [comment]
OK ! got my new nodeMCU today, and all is working fine, must have been some kind of bad chip.

THX
