### ISSUE TITLE
PlatformIO and VSCode library integration

### ISSUE THREAD

**Issue by LiveRock** [Bodmer/TFT_eSPI#1321]
Hi

I have the TTGO T8 v1.7 ESP32 board.
I tried to update TFT_eSPI to the latest but cannot as it is dimmed out in VSCode with PlatformIO.

![image](https://user-images.githubusercontent.com/211891/132083089-a3c0536b-09da-4121-ad89-7451c430d457.png)

Why is it incompatible?

**Comment by Bodmer** [comment]
I do not use Platformio but other users have had success. Maybe this is down to the environment settings?

**Comment by maciekr1234** [comment]
you probably specified exact version in library dependencies try either removing the version specifier or set it to @^2.3.70.

you can read more about semanting versioning [here](https://devhints.io/semver).

**Comment by Bodmer** [comment]
@maciekr1234 
Seems reasonable, will wait for feedback.

**Comment by LiveRock** [comment]
Thanks. It works. I just need to manually update platformio.ini
