### ISSUE TITLE
missing dots when print line ST7735 1.8" display

### ISSUE THREAD

**Issue by Pedroalbuquerque** [Bodmer/TFT_eSPI#133]
Hi Boomer,

first of thank you so much for make this driver available, that is allowing me to use ESP32 with adafruit displays. Nice !

So my setup is a ST7735 1.8" display connected to ESP32 and a was making the first print test with this setup.

something like
`  
int32_t color = RED;

  for(int i= 0; i < 63;i++){
    display.drawLine(i,50,0,159,color);
    Serial.println(i);
    delay(500);
    if(i%2 == 0) color = RED; else color = WHITE;
  }

`
this should print alternate white and red line starting from same point and ending up in a triangular shape.
![img_20180502_195845](https://user-images.githubusercontent.com/8660169/39544543-4f6b5cb0-4e46-11e8-825a-22c73822a94a.jpg)

almost all first lines did not print (~55 of 63), and the last ones were missing most of the dots.
![img_20180502_195438](https://user-images.githubusercontent.com/8660169/39544526-3f653de0-4e46-11e8-9065-b4a659e4f5f5.jpg)

I tested the display.drawPixel and it was not failing any dot , so the display is working fine.

So I decided to write my own draw line routine ending up with a very similar code as yours but it is now working.
There are though some major approach diferences , reason why I am not proposing pull request for the moment. 

Can you confirm there is the need to correct your code ?

Here is my code in case you can consider adjust your code with this approach
`
 void drLine(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color){
    boolean swap = abs(y1 - y0) > abs(x1 - x0);
    if (swap) {
      swap_coord(x0, y0);
      swap_coord(x1, y1);
    }

    if( x1 < x0){
      swap_coord(x1,x0);
      swap_coord(y1,y0);
    }

    int16_t dx = x1-x0,
            dy = y1-y0,
            incX = 1;

    if( dx < 0) incX = -1;

    double incY = (double)dy / abs(dx),
           y = y0;

    if(swap){
      for(;x0 < x1; x0++){
        y += incY;
        display.drawPixel((int)y,x0,color);
      }
    }
    else {
      for(;x0 < x1; x0++){
        y += incY;
        display.drawPixel(x0,(int)y,color);
      }

    }
  }

`

**Comment by Bodmer** [comment]
I have connected up a ST7735 screen and only get lost pixels at high SPI rates.  At 27MHz and below the pattern is correctly drawn.

Post a picture of the back of your TFT if you are still having problems, I'm interested to see what might be unique about your setup to cause so many pixels to get lost.

**Comment by Pedroalbuquerque** [comment]
![img_20180506_224812](https://user-images.githubusercontent.com/8660169/39678206-444826d2-5180-11e8-938d-bd20ef526b5a.png)
Hi Bodmer, thank you for the replies.

My display is from ITEAD,

I have modified the User_Setup.h to adjust the SPI baud to 20K, but still the problem persists


`
// #define SPI_FREQUENCY   1000000

// #define SPI_FREQUENCY   5000000
// #define SPI_FREQUENCY  10000000
 #define SPI_FREQUENCY  20000000
//#define SPI_FREQUENCY  27000000 // Actually sets it to 26.67MHz = 80/3
// #define SPI_FREQUENCY  40000000 // Maximum to use SPIFFS
// #define SPI_FREQUENCY  80000000
`

So I went to the darwLine function and added a few line to debug if it is being skipped

  // Split into steep and not steep for FastH/V separation
  if (steep) {
    for (; x0 <= x1; x0++) {
      dlen++;
      err -= dy;
      if (err < 0) {
        err += dx;
        if (dlen == 1) {
          drawPixel(y0, xs, color);
          Serial.print("dot:");
          Serial.print(y0);
          Serial.print(",");
          Serial.println(xs);
        }
        else drawFastVLine(y0, xs, dlen, color);


Then just tried to print a single line

  display.drawLine(1,1,6,10,WHITE);

and the output is

> dot:1,1
dot:6,10

So it seems to me that the algorithm is "jumping" a few dots

Can you confirm you do not get this skips ?

Note that is I print from 1,1 to 10,10, there are no Skips, only if I print 1,1 to 6,10 (where x1 < y1)
