### ISSUE TITLE
tft.fillScreen() generate a wdt reset when TFT is disconnected

### ISSUE THREAD

**Issue by sebarch** [Bodmer/TFT_eSPI#1338]
Hi to all! I just was troubleshooting a proyect and notice that when i disconnect the TFT (2.8TFT SPI 240x320 ili9341 with XPT2046) the function TFT_eSPI::fillScreen generate a wdt reset. I'm pretty sure that the HW serial hangs up waiting an answer. How can i detect the screen before call any function??
Thanks

**Comment by Bodmer** [comment]
It is not clear what you mean my discoonect. If you mean physically disconnect wires then this is not a good idea as it is likely to cause unwnated electrical transients or damage to I/O pins when the connections are broken in a random order.  As an example removing 0V from a 5V device will place 5V on the lobic lines which is not good for most 3.3V devices.

It may appear that fillScreen() is causing the issue in your setup, however that function ONLY writes to the SPI port and it does not matter whather the TFT is physically connected or not.

Also the XPT2046 disconnect will affect the I2C bus and the I2C library (not part of TFT_eSPI) may hang as aresult.

These things cannot be cured by changes to the TFT_eSPI library.
