### ISSUE TITLE
ESP32 (DOIT devkit 1), ILI9481 ("Red board") & XPT2046 cannot get touch working

### ISSUE THREAD

**Issue by vehvis** [Bodmer/TFT_eSPI#1342]
Hello, and first of all, thanks for this great library!

I've a cheap AliExpress ILI9481 board which works fine except for some flicker, however I haven't been able to get touch working at all.

It's this (specifically the 9481+Touch version, the XPT chip is physically present as is the touch film): https://www.aliexpress.com/item/1005001999296476.html

I've connected the TCK, TDI, TDO pins to the corresponding display pins and the TCS pin to its own GPIO, and set up the User_Setup.h file as follows (omitted the fonts for brevity):

```
#define ILI9481_DRIVER

#define TFT_CS    4   // Chip select control pin
#define TFT_RST   16  // Reset pin (could connect to RST pin)
#define TFT_DC    17  // Data Command control pin
#define TFT_MOSI  5   // SDI
#define TFT_SCLK  18
#define TFT_MISO  21  // (leave TFT SDO disconnected if other SPI devices share MISO)
#define TOUCH_CS  22  // Chip select pin (T_CS) of touch screen

#define SPI_FREQUENCY  10000000
#define SPI_TOUCH_FREQUENCY  2500000
```

Running the Test_Touch_Controller example outputs this:

```
Starting...
x: 0     y: 3711     z: 33
x: 0     y: 3893     z: 50
x: 0     y: 3897     z: 49
x: 0     y: 3874     z: 5
x: 737     y: 3191     z: 25
x: 0     y: 3612     z: 29
x: 0     y: 3816     z: 45
x: 0     y: 3627     z: 41
x: 66     y: 3302     z: 33
x: 172     y: 3200     z: 34
x: 343     y: 3045     z: 36
x: 363     y: 3351     z: 34
```

~~Poking the screen does not cause any of the values to materially change.~~ UPDATE this was actually a VSCode artifact, the serial console lags an awful lot. Using the Arduino IDE I can get the Z values to react to touch:

```
16:11:32.235 -> x: 24     y: 3893     z: 41 
16:11:32.474 -> x: 256     y: 3065     z: 39 
16:11:32.715 -> x: 112     y: 3174     z: 34 
16:11:32.955 -> x: 0     y: 2234     z: 36 
16:11:33.195 -> x: 2428     y: 1861     z: 2041    // here
16:11:33.483 -> x: 1735     y: 1763     z: 1514 
16:11:33.724 -> x: 2093     y: 1632     z: 1948 
16:11:33.963 -> x: 1940     y: 2238     z: 1785 
16:11:34.202 -> x: 0     y: 3681     z: 57 
16:11:34.489 -> x: 288     y: 3999     z: 40 
16:11:34.729 -> x: 0     y: 3577     z: 45 
16:11:34.970 -> x: 92     y: 3928     z: 34 
16:11:35.210 -> x: 0     y: 3623     z: 8 
16:11:35.450 -> x: 696     y: 2859     z: 28 
16:11:35.738 -> x: 2703     y: 1965     z: 1961  // and here
16:11:35.978 -> x: 1696     y: 1953     z: 1623 
16:11:36.216 -> x: 2094     y: 1481     z: 2181 
16:11:36.456 -> x: 366     y: 3070     z: 33 
16:11:36.696 -> x: 83     y: 3476     z: 31 
16:11:36.984 -> x: 692     y: 2824     z: 31 
16:11:37.223 -> x: 0     y: 3718     z: 107 
```

However, the Test_Touch_Controller demo shows just a blank white screen, and does not output anything after "starting" so there is still something iffy here.

I've attached a photo showing the wiring. Shared wires are blue/orange for TCK/SCK (CLK), gray/red for TDI/SDI (MOSI), and white/green for TDO/SDO (MISO). I've confirmed with a multimeter that they are electrically connected.

![20210919_153905](https://user-images.githubusercontent.com/17703323/133927929-578e306a-c4da-4df1-ba6f-9dc436c21bc8.jpg)

I have multiple copies of this particular display all exhibiting the same issue, so if it's hardware-related then it's a whole bad batch.

**Comment by Bodmer** [comment]
It looks like your touch screen is working fine.  As noted in the [sketch comments...](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Test%20and%20diagnostics/Test_Touch_Controller/Test_Touch_Controller.ino#L1-L2) the Test Touch Controller disgnostic sketch does not output anything to the screen. It only tests the touch screen.
