### ISSUE TITLE
Support for ESP32 + RA8875 + 800x480px screen

### ISSUE THREAD

**Issue by yashm** [Bodmer/TFT_eSPI#1346]
Hello,
Any plans to add support for ESP32 + RA8875 + 7" 800x480px screens?
I am happy to send you a setup for development and testing.
Thanks!

**Comment by Bodmer** [comment]
Thanks for the offer, no plans to support that screen at the moment. It is a bit of an oddball from the command viewpoint so I suspect it would take some significant effort to add it.
