### ISSUE TITLE
esp32s2 

### ISSUE THREAD

**Issue by Startech-tuncer** [Bodmer/TFT_eSPI#1353]
Hi bodmer My name is tuncer from turkey. esp32s2 de çok uğraştım ama hallettim müthiş bir süratle çalıştırmayı başardım.İyi bir kod yazan olarak herşeye yetişemezsin. Yardıma ihtiyacın olursa yanındayım.Happy days.

**Comment by Bodmer** [comment]
ESP32 S2 is now supported.
