### ISSUE TITLE
STM32 NUCLEO-F446RE  Nucleo-64 - Adafruit HX8357D SPI

### ISSUE THREAD

**Issue by Egon466** [Bodmer/TFT_eSPI#1357]
Issue - Mirrored Display.

Standard STM32 Nucleo SPI configuration running example code TFT_Meters.ino. I also tried all 4 rotation modes with the same mirrored result.

help with fix would be appreciated.

![Nucleo](https://user-images.githubusercontent.com/92088157/136506318-4fe0d0d6-f509-434a-87b5-40905f93eb56.jpeg)

User_Setup.h definitions -

#define STM32
#define NUCLEO_64_TFT
#define HX8357D_DRIVER
#define TFT_WIDTH  320
#define TFT_HEIGHT 480

#define TFT_SPI_PORT 1 	       // SPI port 1 maximum clock rate is 55MHz
#define TFT_MOSI PA7		       // D13
#define TFT_MISO PA6		// D12
#define TFT_SCLK PA5		// D11

#define TFT_CS   D5 		
#define TFT_DC   D6 		
#define TFT_RST  D7 		
#define TFT_BL   -1  

#define LOAD_GLCD   
#define LOAD_FONT2  
#define LOAD_FONT4  
#define LOAD_FONT6  
#define LOAD_FONT7  
#define LOAD_FONT8  
#define LOAD_GFXFF  
#define SMOOTH_FONT

#define SPI_FREQUENCY  27000000
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY  2500000
------------------------------------
Output from Read_User_Setup.ino - 

[code]
TFT_eSPI ver = 2.3.70
Processor    = STM32
Transactions = Yes
Interface    = SPI
Display driver = 8357
Display width  = 320
Display height = 480

MOSI    = GPIO 5959
MISO    = GPIO 6060
SCK     = GPIO 6161

>>>>> Note: STM32 pin references above D15 may not reflect board markings <<<<<
TFT_CS   = D5
TFT_DC   = D6
TFT_RST  = D7

TFT_BL           = D0

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.00
[/code]

**Comment by Bodmer** [comment]
It looks like both a colour problem and a mirroring.  Unfortunately I do not have an HX8357D display and the init code was provided by a user as "working".

For a possible fix, see #1356 and let me know if that solves the problem.

**Comment by Egon466** [comment]
Hello Bobmer,
Sorry I sorted out this issue in #1326.
All my issues are resolved.
Thanks.
