### ISSUE TITLE
Rotated_Sprite_3 example

### ISSUE THREAD

**Issue by luxxtek** [Bodmer/TFT_eSPI#1359]
Great library, still exploring all the possibilities.
This is what I see on my320x480 ILI9488 TFT using version 2.3.70 of TFT_eSPI.
Any help is appreciated.
![IMG_2197](https://user-images.githubusercontent.com/6260582/136700017-965ed942-cf89-4e2b-b057-e8b24cce0f18.JPG)

**Comment by Bodmer** [comment]
Run the Colour_Test sketch (in Test and diagnostics examples) and make sure the colours are correct.

It looks like the colours in the images are byte swapped. Which processor are you using?

**Comment by Bodmer** [comment]
Glad you have solved this. Unfortunately swap bytes can get confusing as the tft and sprite classes have their own swap bytes state, so tft.setSwapBytes(true); is for tft. functions and spr.setSwapBytes(true); can be used for sprite functions.
