### ISSUE TITLE
Esp8266 pin D6 problem.

### ISSUE THREAD

**Issue by limaomerces** [Bodmer/TFT_eSPI#1364]
Hi. I'm trying to use any screen with esp8266, WITHOUT MISO. It works perfectly, however, I noticed that pin D6 becomes unusable.

Is there anything I can do to resolve this issue?

I'm trying to read the ds18b20 sensor on the D6.

**Comment by Bodmer** [comment]
Unfortunately that pin is allocated by the board package (not TFT_eSPI) during the SPI initialisation. One option is to put the display on the FLASH SPI pins, this is called OVERLAP mode.

[See setup 9](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup9_ST7735_Overlap.h#L18-L30).

**Comment by Bodmer** [comment]
Assumed resolved.
