### ISSUE TITLE
Experiencing white screen with ESP32 + ILI9341, but Adafruit library working

### ISSUE THREAD

**Issue by takakka** [Bodmer/TFT_eSPI#1365]
Hello,
I'm having a white screen with ESP32 + ILI9341 with TFT_eSPI library, but with original Adafruit library, it's working fine with same pin configs.

Attached User_Setup.h, and the log of diagnostics below.

I noticed that MISO pin is missing from the Read_User_Setup log, and also pin numbers for DC & RST are different from the setup and actual connections. Even if I change DC & RST pins to different ones (I tried 26 & 25), the log remains the same. 

Any idea for fixing this problem?

User_Setup.h
[code]
#define ILI9341_DRIVER 
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   15 
#define TFT_DC    2
#define TFT_RST   4 
#define LOAD_GLCD 
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7 
#define LOAD_FONT8
#define LOAD_GFXFF
#define SMOOTH_FONT
#define SPI_FREQUENCY  27000000
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY  2500000
[/code]

Read_User_Setup Log
[code]
TFT_eSPI ver = 2.3.70
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320
MOSI    = GPIO 23
SCK     = GPIO 18
TFT_CS   = GPIO 15
TFT_DC   = GPIO 0
TFT_RST  = GPIO 2
Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled
Display SPI frequency = 27.00
[/code]

TFT_ReadWrite_Test Result
[code]
Pixel value written = 1
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 2
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 4
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 8
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 10
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 20
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 40
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 80
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 100
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 200
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 400
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 800
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 1000
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 2000
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 4000
Pixel value read    = 0
ERROR                 ^^^^
Pixel value written = 8000
Pixel value read    = 0
ERROR                 ^^^^
[/code]

**Comment by sagits1201** [comment]
Hi~
Its seems that u have the wrong User_Setup.h/User_Setup_Select.h.
Check these 2 file,and made the pin setting right.
The Adafruit lib work,just cause at the sketch,its will set the pin at the setup(),
Tft_eSpi lib need a little adjust,u can reinstall and dont make any change, build and run the 
Read_User_Setup ,lets see hows going~

Good Luck

**Comment by sagits1201** [comment]
So maybe we should check what board we r use ,
maybe the problem is something else.
Can u try to connect ur pin to the pin the read_user_setup print out?

**Comment by Bodmer** [comment]
These are the pins you think you have specified in the setup:
```
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS 15
#define TFT_DC 2
#define TFT_RST 4
```
But the Read_User_Setup sketch reports that these are the pins the compiler has picked up, possibly from a different setup file:
```
MOSI = GPIO 23
SCK = GPIO 18
TFT_CS = GPIO 15
TFT_DC = GPIO 0
TFT_RST = GPIO 2
```
You need to either look at why the setup file you think is being used is not, or correctly edit the one that is being used.

**Comment by takakka** [comment]
Hi all, thanks for kind replies.

Looks like it was a board issue, since it worked fine on the new board.

The new one is genuine WROVER-E board from Expressif, and the previous one was some third-party board with WROOM32.
