### ISSUE TITLE
ili9341 and esp32 touch not response.

### ISSUE THREAD

**Issue by kannanarulmurugan786** [Bodmer/TFT_eSPI#1369]
Hello,
I have espwroom32 board and ili9341 2.8 TFT SPI 240 x 320 V1.2 Display.
I Run Read_User_Setup example from this github.
OutPut is :
[code]
TFT_eSPI ver = 2.3.70
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 23
MOSI    =
23MISO    =
-1SCK     = GPIO 18
SCK    = 18
CS    = -1
DC    = -1
LED_ON    = 0
RESET    = -1
TOUCH_CS    = -1

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 5.00
TOUCH_CS  = -1
[/code]

My [User_Setup.h](https://drive.google.com/file/d/1XnXpi38W8OkgR1o7sn2uzKMJ9m5u3K5r/view?usp=sharing) Code

When i run the same User_Setup file to use keypad example. even the keypad is showing but when touch any button it is not respond.

**Comment by Bodmer** [comment]
@kannanarulmurugan786 
These lines from your setup output indicate you have not defined some pins (-1 means not defined):
```
CS = -1
DC = -1
RESET = -1
TOUCH_CS = -1
```

**Comment by Bodmer** [comment]
Assumed resolved.
