### ISSUE TITLE
Detect screen deattachment or sync lost

### ISSUE THREAD

**Issue by beckmx** [Bodmer/TFT_eSPI#1386]
Hello guys, I have been using the library with no problems at all, but I have found some minor details I would like to workaround, I have an AC circuit, with pcb and everything, so no loose cables, and the screen is attached on top of if, sometimes I have noticed the screen stops responding, it just freezes, and also freezes the touch. I know for a fact that the mcu (esp32) keeps running because it still has its backend accessible, so my guess is that somehow it just lost sync with the screen, I was wondering if there is a method to get data from a screen just to see it is still alive, I was using previously:
```
if(tft.readPixel(0,0) == 0){
//code
}
```

but I am not very convinced
Greetings!

**Comment by Bodmer** [comment]
I suspect this is an EMC issue, AC circuits, relays, motors etc can all generate large voltage spikes that can couple into low voltage digital circuits. I suspect the display is seeing duff data/commands, or the reset line is being glitched which then puts the display into an unitialised reset state. In these situations the CGRAM is preserved so reading a pixel will only show that data can be read, not that the display is initialised.  It would be better to call tft.init() periodically if you can not fix the glitching.

To check for AC EMC issues try running as a test with the displays etc nowhere near the AC circuits and not connected to any related AC equipment.  Assuming the display is SPI, then keep the wires short, use thick GND wires between CPU and display, bundle the wires to the display with a dedicated GND wire, and make sure the AC circuits have spike suppressions circuits.

**Comment by Bodmer** [comment]
Assumed resolved.
