### ISSUE TITLE
Bug FreeFonts FSS9

### ISSUE THREAD

**Issue by limaomerces** [Bodmer/TFT_eSPI#1387]
Hello how are you?
I made a simple code to display a clock, using FSS9 freefonts and got overlapping problems when using tft.print, even though I declared tft.setTextColor(TFT_WHITE, TFT_BLACK).

To solve this, I used "tft.drawString()". It works fine, it erases the old text and puts in the new one, however some letters are not completely erased.

[See the video](https://youtu.be/mKUJ1rHEEhg)

Note: FF5 has the same problem.
Note 2: Other fonts may have this issue, but I haven't tested it.

**Comment by Bodmer** [comment]
The problem arises with proportional fonts which have variable with characters, so "ii" would not overwrite "WW" for example, as they occupy different widths on the screen, the same goes for numbers, 11 will not always overwrite say 77.  The library has no knowledge of what is on the screen so, in these cases, the user must specify the blanking width to a suitable value using setTextPadding as @dheydeck suggests.
