### ISSUE TITLE
Touch problem with ILI9341 3.2" TFT 240x320 v1.0

### ISSUE THREAD

**Issue by pkrssy** [Bodmer/TFT_eSPI#1394]
Display function works well with the library but running Test_Touch_Controller.ino x y z change even if screen is not touched:

x: 139     y: 3536     z: 67 
x: 0     y: 3903     z: 2 
x: 397     y: 3231     z: 2 
x: 0     y: 3935     z: 2 
x: 0     y: 3936     z: 2 
x: 0     y: 3872     z: 2 
x: 451     y: 3392     z: 34 
x: 0     y: 3936     z: 4 
x: 1     y: 3952     z: 58 
x: 134     y: 3551     z: 2 
x: 0     y: 3889     z: 2 
x: 0     y: 3119     z: 33 
x: 0     y: 3839     z: 50 
x: 176     y: 3487     z: 32 
x: 0     y: 3760     z: 2 
x: 0     y: 2992     z: 64 
x: 0     y: 3232     z: 35 

Output of Read_User_Setup:

[code]
TFT_eSPI ver = 2.3.70
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 23
MISO    = GPIO 19
SCK     = GPIO 18
TFT_CS   = GPIO 5
TFT_DC   = GPIO 2
TOUCH_CS = GPIO 21

TFT_BL           = GPIO 32
TFT_BACKLIGHT_ON = HIGH

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.00
Touch SPI frequency   = 2.50
[/code]

**Comment by Bodmer** [comment]
The x and y readings will be noisy, expecially if the power supply rails have noise on them. The low cost resistive screens fitted to these displays do tend to have jittery outputs so some multi-sample filtering is used in the library.

The x, and y readings will only be valid when the z value is high, that is when the display is touched.
