### ISSUE TITLE
Regarding: "18-bit colour support #725"

### ISSUE THREAD

**Issue by Prenamix** [Bodmer/TFT_eSPI#1396]
Hi,

In #725 a question was asked about using 18 bit color. But I'm not sure I understand the answer.

Does it mean that TFT_eSPI "upscales" the 16 bit color value to 18 bit to accommodate the ILI9488? Meaning that the display is capable of displaying 18 bit color but TFT_eSPI will not let you use more than 16 bit colors? 

Thanks.

**Comment by Bodmer** [comment]
Your understanding is correct.
