### ISSUE TITLE
graphicstest_one doesn't fill the 480x320 mcu friend

### ISSUE THREAD

**Issue by laurentopia** [Bodmer/TFT_eSPI#140]
I caved in and got a r32 board, soldered the 3 wires in the back and now it works!
But there is static below, white on the right and the display size is smaller than 480x320, I use the 480x example. 9341 selected.
 What's the solution?
![img_2200](https://user-images.githubusercontent.com/26075468/40038324-68d196c2-57c6-11e8-8c71-85f73f424df9.JPG)
![img_2201](https://user-images.githubusercontent.com/26075468/40038325-68e728c0-57c6-11e8-9e00-bef6f653bd86.JPG)

**Comment by laurentopia** [comment]
I switched to the smaller 320x240 screen and it works perfectly.
I wonder how eSPI gathers the information on screen size because it's nowhere in the .ino

**Comment by Bodmer** [comment]
The screen driver and resolution are defined in [the setup](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup2_ST7735.h#L27) and/or [driver code.](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/ILI9481_Defines.h)
