### ISSUE TITLE
ST7789v readRect() error

### ISSUE THREAD

**Issue by yiming564** [Bodmer/TFT_eSPI#1406]
this is my code:
tft.readRect(100, 100, 8, 8, buffer);
this is the result:
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
...
the screen was just filled by blue, but readRect() didn't read anything.

ESP32 + ST7789v

**Comment by Bodmer** [comment]
Run the TFT_ReadWrite_Test example to see if reading the TFT is working OK.

**Comment by Bodmer** [comment]
Assumed resolved.
