### ISSUE TITLE
When compiling error:  'class TFT_eSPI' has no member named 'getTouch'

### ISSUE THREAD

**Issue by Nulista** [Bodmer/TFT_eSPI#1408]
Hello, i get this error by compiling this example....

D:\Arduino\libraries\TFT_eSPI-master\examples\480 x 320\Keypad_480x320\Keypad_480x320.ino: In function 'void loop()':
Keypad_480x320:114:22: error: 'class TFT_eSPI' has no member named 'getTouch'
   bool pressed = tft.getTouch(&t_x, &t_y);

Thx
Ludo

**Comment by brian-not-the-messiah** [comment]
You haven't defined `Touch_CS` in User_setup... 

if the touch CS is connected to pin 21, you can simply uncomment `#define TOUCH_CS 21`

**Comment by Nulista** [comment]
Hello, bodmer,

Yes indeed, after updating the library I have to adjust those things 
too...... stupid of me, sorry.
Thanks for the quick response!

thx Ludo


------ Origineel bericht ------
Van: "brian-not-the-messiah" ***@***.***>
Aan: "Bodmer/TFT_eSPI" ***@***.***>
CC: "ludo nulens" ***@***.***>; "Author" 
***@***.***>
Verzonden: 11/11/2021 18:50:44
Onderwerp: Re: [Bodmer/TFT_eSPI] When compiling error: 'class TFT_eSPI' 
has no member named 'getTouch' (Issue #1408)

**Comment by brian-not-the-messiah** [comment]
No problem! This isn't Bodmer by the way!

**Comment by Bodmer** [comment]
Glad this is solved.
