### ISSUE TITLE
Performances of a parallel screen, is it worth it?

### ISSUE THREAD

**Issue by laurentopia** [Bodmer/TFT_eSPI#141]
I ran the PDQ benchmark and got this.
I'd run the same in SPI but I don't have an SPI display lying around. Maybe someone can test that for me?

![38031ae3-eccb-4965-a6f8-dd2aa98c07e7](https://user-images.githubusercontent.com/26075468/40039914-0eed762e-57cd-11e8-95e4-303969747144.jpg)

**Comment by laurentopia** [comment]
the answer in a sprite heavy scenario is 2x speed up compared to SPI.

![76ccd70f-86d2-4310-892d-0316ff5b5221](https://user-images.githubusercontent.com/26075468/40042869-9e7dfbc4-57d7-11e8-879b-29794a4e1adc.jpg)
![img_2207](https://user-images.githubusercontent.com/26075468/40042875-9ffea278-57d7-11e8-80d1-fc2af90f5580.JPG)

**Comment by Bodmer** [comment]
The ESP32 can only toggle a GPIO pin every 50ns so the maximum 8 bit parallel interface bit rate is 80Mbps.

The serial SPI mode ILI9341 almost works at 80MHz SPI clock rate but I recommend 40MHz maximum.

**Comment by laurentopia** [comment]
I think in my early tests I pushed to 80 Mhz and it was full of glitches.
How can SPI push nearly as much as parallel with 4x less wires?

**Comment by Bodmer** [comment]
Because it is the bit rate that counts.

**Comment by laurentopia** [comment]
I get it : 50ns is not per GPIO, it's for all the GPIO combined
