### ISSUE TITLE
4.3 inch LCD 480x272 SSD1963 not working with ESP32 using TFT_eSPI library

### ISSUE THREAD

**Issue by tinhvega** [Bodmer/TFT_eSPI#1420]
I am programming a 4.3 inch 480x272 SSD 1963 with ESP32 using TFT_eSPI library.
I fixed the library as per the instructions:
- #define SSD1963_480_DRIVER
- #include <User_Setups/Setup50_SSD1963_Parallel.h>
- #define SSD1963_480_DRIVER // 272 x 480 display
// ESP32 pins used
#define TFT_CS 33 // Chip select control pin
#define TFT_DC 15
#define TFT_RST 32 // Reset battery

#define TFT_WR 4
#define TFT_RD 2

#define TFT_D0 12
#define TFT_D1 13 // so a single register write sets/clears all bits
#define TFT_D2 26
#define TFT_D3 25
#define TFT_D4 17
#define TFT_D5 16
#define TFT_D6 27
#define TFT_D7 14

I have checked the wire connection, the ESP32 is running but the LCD is still not working.
Please help me. thanks so mu
![254834469_318128319766483_2712845800469218673_n](https://user-images.githubusercontent.com/93909353/141422664-aa5c8405-861f-4d82-8871-d90b6d4f8219.jpg)
![250055837_3115863875350302_44593610181618911_n](https://user-images.githubusercontent.com/93909353/141422670-0d1646e3-aa8c-4db4-8472-4e5a25b3520b.jpg)
ch

**Comment by IanBUK** [comment]
One quick thing to check that's caught me out - ensure that you're turning the backlight on.

**Comment by tinhvega** [comment]
I have connected LED pin of LCD to 3.3V. On the picture you can see that the light is on

**Comment by tinhvega** [comment]
I was able to fix it.
Connect the STBYB (Standby) pin to high.
All solved
