### ISSUE TITLE
XPT2046 touch screen fails when SPI.begin() is used

### ISSUE THREAD

**Issue by Mark-FS** [Bodmer/TFT_eSPI#1422]
I am trying to set up an ili9341 TFT with XPT2046 touch screen and an RC522 RFID reader on an ESP32 Dev Kit C v4.

The TFT and Touch screen are on HSPI (GPIO13 (MOSI), GPIO12(MISO), GPIO14(CLK) and GPIO15 (CS) GPIO 26 (touch CS)).  The RC522 is on VSPI (GPIO23 (MOSI), GPIO19(MISO), GPIO18(CLK) and GPIO5 (CS)).

The TFT/Touch works fine separately as does the RC522 RFID reader but put them together and the touch fails.  tft.getTouch(&x, &y) always returns false and so never responds to the touch with new x. y values.  If I comment out the SPI.begin() the RC522 stops working but the touch function returns.  The RC522 is running from library MFRC522.h.

Any ideas as to what I might be missing or not understanding?  Thank you...

**Comment by Mark-FS** [comment]
All sorted.  If it helps someone else the noob mistake was not reading enough.  Right at the bottom of User_Setup is the solution, if you are using the HSPI port on an ESP32 you have to uncomment the line #define USE_HSPI_PORT.  Do that and it works great.  Good luck all...

**Comment by Bodmer** [comment]
Thanks for finding the solution!

**Comment by TDVSVI** [comment]
> All sorted. If it helps someone else the noob mistake was not reading enough. Right at the bottom of User_Setup is the solution, if you are using the HSPI port on an ESP32 you have to uncomment the line #define USE_HSPI_PORT. Do that and it works great. Good luck all...

Can you give me a code? I found problem like you but not solve it. thank you :)
