### ISSUE TITLE
ST7735 INITB is mirrored

### ISSUE THREAD

**Issue by brownjd** [Bodmer/TFT_eSPI#143]
I modified ST7735_Rotation.h to handle my screen. It was sold as an ST7735R, but I'm guessing it is a B because no other combination worked. I noticed INITB is not explicitly handled, so I added conditions for INITB. The issue I was trying to handle is that no matter what rotation I set, the text was reversed, as in a mirror.

Being new to Git I'm not sure how I'm supposed to propose changes, so I'm opening an issue. I'm happy to push, branch, or pull, or whatever if you're good with it. Just let me know. 

Here are my edits.

ST7735_Rotation.h

case 0:
 } else if(tabcolor == INITB) {
       writedata(TFT_MAD_MX | TFT_MAD_BGR);
     }

case 1:
} else if(tabcolor == INITB) {
       writedata(TFT_MAD_MV | TFT_MAD_MX | TFT_MAD_MY | TFT_MAD_BGR);
     }

case 2:
} else if(tabcolor == INITB) {
       writedata(TFT_MAD_MY | TFT_MAD_RGB);
     }

case 3:
} else if(tabcolor == INITB) {
       writedata(TFT_MAD_MV | TFT_MAD_RGB);
     }

**Comment by Bodmer** [comment]
Thanks, I have updated the files to include your suggested code.

**Comment by brownjd** [comment]
I think TFT_RGB should be used in all 4 cases.

**Comment by Bodmer** [comment]
OK, thanks I blindly copied your code and did not notice the differences. Thanks for pointing this out.
