### ISSUE TITLE
undefined reference to `BYTECLIP' compiling on ESP32

### ISSUE THREAD

**Issue by ajacobs-github** [Bodmer/TFT_eSPI#1445]
When compiling for board ESP32S2 Dev Module I get the error undefined reference to `BYTECLIP' in tjpgd.c.   Using arduino ESP32 version 2.0.1.  Board is a sparkfun ESP32-S2 Thing Plus.  Connected display is Adafruit 2.8" TFT LCD shield with cap touch and micro SD.   Sorry for the double post on this.

**Comment by Bodmer** [comment]
This is due to changes in the board package for the ESP32. Use the latest version 1.0.2 of the jpeg library.
