### ISSUE TITLE
Custom Eye on the Animated Eye example.

### ISSUE THREAD

**Issue by BishoPower** [Bodmer/TFT_eSPI#1449]
Can anyone give me some pointers on going about creating a custom eye for the animated eye example?

**Comment by Bodmer** [comment]
You need to create a set of image files or adapt the ones provided. Example images are here:
https://github.com/adafruit/Uncanny_Eyes/tree/master/convert/defaultEye

The python script to convert these images to a header file for inclusion in the sketch are here.
https://github.com/adafruit/Uncanny_Eyes/tree/master/convert

The sketch is adapted from on by Adafruit, so you may find help on the Adafruit website.

**Comment by Bodmer** [comment]
Have a look here also as someone has created a custom eye and describes the process:
https://makezine.com/projects/eye-of-newt-keep-watch-with-a-creepy-compact-animated-eyeball/
