### ISSUE TITLE
ST7789 135x240 display fix

### ISSUE THREAD

**Issue by AidanHolmes** [Bodmer/TFT_eSPI#1473]
Adafruit 1.14" screen doesn't enable correct offsets in ST7789_Rotation.h when width and height set to 135x240. Simple fix in ST7789_Defines.h required to set CGRAM_OFFSET by checking for 135 width and then it works.

// Add for Adafruit 1.44 TFT support
#if (TFT_HEIGHT == 240) && (TFT_WIDTH == 135)
  #define CGRAM_OFFSET
#endif

**Comment by Bodmer** [comment]
Added, thanks.
