### ISSUE TITLE
Display problem on a TTGO T-display

### ISSUE THREAD

**Issue by kalon33** [Bodmer/TFT_eSPI#1484]
Using a TTGO T-display, I got only part of the display used, with the remaining of the display with glitches. T-display is properly chosen in `User_Setup_Select.h`.

I tried rotating without success. It also seems that the colors are inverted, as I should got that result:

![screenshot](https://user-images.githubusercontent.com/460731/145710836-8f6b3ff9-08a4-451d-849c-d6c25d4991c3.jpg)
 
But got this one:
![IMG_20211212_123654](https://user-images.githubusercontent.com/460731/145710855-dd2f8b4f-f96c-40f7-bd8e-1129978e51f0.jpg)

For more info about my board, I took a picture from the other side:
![IMG_20211212_123701](https://user-images.githubusercontent.com/460731/145710867-8628bcd2-2caa-4fb4-a2c5-f9dc87fc4f17.jpg)

Could you help me fix that problem? Thanks!

**Comment by Bodmer** [comment]
I have an identical looking board and it seems to work fine with setup 25 and the library examples.

To test for colour run the Test and diagnostics example Colour_Test. This is what you should see:

![screenshot_2021_12_12_19_35_36](https://user-images.githubusercontent.com/15824805/145726877-159627f3-4ae4-42e0-86e2-3771c3fb26f5.png)

To check your setup file is correctly selected run the Read_User_Setup example and look at the serial monitor output.  Here's a copy of what I see when I do this (with latest Github version of library):
```
TFT_eSPI ver = 2.3.88
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = SPI
Display driver = 7789
Display width  = 135
Display height = 240

R0 x offset = 52
R0 y offset = 40
MOSI    = GPIO 19
SCK     = GPIO 18
TFT_CS   = GPIO 5
TFT_DC   = GPIO 16
TFT_RST  = GPIO 23

TFT_BL           = GPIO 4
TFT_BACKLIGHT_ON = HIGH

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 40.00
```
If this looks good then I will need a complete example sketch that demonstrates the problem to see where the problem is.

**Comment by kalon33** [comment]
[code]
TFT_eSPI ver = 2.3.70
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 19
SCK     = GPIO 18
TFT_CS   = GPIO 5
TFT_DC   = GPIO 16
TFT_RST  = GPIO 23

TFT_BL           = GPIO 4
TFT_BACKLIGHT_ON = HIGH

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 40.00
[/code]

Could it be possible that I don't have the appriopriate driver?

**Comment by kalon33** [comment]
For the color test, I got that:
![IMG_20211213_171300](https://user-images.githubusercontent.com/460731/145847917-eb328633-f5c9-469d-9d2e-fb936ea5c998.jpg)
![IMG_20211213_171257](https://user-images.githubusercontent.com/460731/145847922-810ca3e1-94eb-4be9-aa84-32e350e775ed.jpg)

**Comment by Bodmer** [comment]
The following lines indicate the setup file is not correct:
```
Display driver = 9341
Display width = 240
Display height = 320
```
This should read the same as mine, viz:
```
Display driver = 7789
Display width  = 135
Display height = 240

R0 x offset = 52
R0 y offset = 40
```
Probably [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L20-L22) has not been commented out?  Typically this leads to warning message during compile time but you will need to check that only ONE setup file is being called up.

**Comment by kalon33** [comment]
@Bodmer : That was the problem... Sorry... Thanks a lot for your help!

**Comment by Bodmer** [comment]
No problem. Have made the same mistake myself!
