### ISSUE TITLE
Lilygo t8 display

### ISSUE THREAD

**Issue by maxim05gromov** [Bodmer/TFT_eSPI#1491]
Hello. Im using a liligo t8 board based on esp32-s2. It doesn’t work with this library. What should I do to make it work? All I have is this link:
https://github.com/Xinyuan-LilyGO/LilyGoesp32s2-base

**Comment by maxim05gromov** [comment]
For the library to work, we need to select SPI HOST 2

**Comment by Bodmer** [comment]
The FSPI port will be used by default, you can use the HSPI port, see example setup here:
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup70_ESP32_S2_ILI9341.h#L27-L28

Port mapping information is here:
https://github.com/Bodmer/TFT_eSPI/blob/master/Processors/TFT_eSPI_ESP32.h#L43-L46

**Comment by maxim05gromov** [comment]
Now everything is working, thank you
