### ISSUE TITLE
Strange LCD problem. a question for LCD gurus.. :-)

### ISSUE THREAD

**Issue by Mike-the-one** [Bodmer/TFT_eSPI#150]
I have an ili9488 based TFT LCD.  We use it in 4 wire SPI mode in Arduino, and this TFT_eSPI Here is the pin configuration:

```sh
#define TFT_MOSI  4
#define TFT_MISO 34 // Does this work? 34 can be MISO?
#define TFT_SCLK  2 
#define TFT_CS    5
#define TFT_DC   14
#define TFT_RST  12
#define TOUCH_CS 15
```

It works fine with Doit ESP32 Kit.  (well, colors are off, because 16bit/18 bit color issue, but we can see it works).

I also have my own hardware, it has ESP32 and other components that are not available on the DoIt kit.  So if I install the same LCD on my own hardware, it doesn't work. just white background (or back light) at this point I would think it is my hardware's problem.

However, if we use a Raspberry Pi LCD (also ili9488 based) with my hardware, it works!  The Rpi LCD is also ili9488, but I think it is hardware configured to 16bit color, and my ili9488 LCD is 18bit color.  But this should not make any difference, at least I should see something on the LCD...

This is so strange, any suggestions?

thanks!

**Comment by Bodmer** [comment]
In SPI mode the ILI9488 expects 18 bit colours (3 bytes with 6 bits in each) and 8 bit commands. TheTFT_eSPI library operates with 16 bit colours in 2 bytes and 8 bit commands.  In 8 bit or 16 bit parallel mode the display accepts 16 bit colours.

Some Raspberry Pi screens actually operate in parallel mode with an additional hardware 16 bit serial shift register. In this case the display expects commands to be 16 bits.

Unfortunately there are so many display types and configurations that it does get confusing!  Often sellers in China do not correctly state what controller is fitted to the display so some experimentation is needed.
