### ISSUE TITLE
[Question]: Can this lib also be used for the Arduino Nano?

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#1541]
in short....

Can this lib also be used for the Arduino Nano?

**Comment by Bodmer** [comment]
Arduino have a range of Nano board. If you mean the original ATmega328 based one then the answer is: No

It does not have enough memory.

By cutting down on all the fonts and features in the setup except perhaps the GLCD font then it may be able to run a Hello World program, but that is about it!
