### ISSUE TITLE
SPIFFS deprecated

### ISSUE THREAD

**Issue by MaWo2** [Bodmer/TFT_eSPI#1556]
As in the title: As SPIFFS is deprecated, at least the example `Keypad_480x320.ini` does not compile any longer.

An easy workaround is presented [here](https://www.esp8266.com/viewtopic.php?f=6&t=21801). The suggestion is to include the following lines, to make LittleFS handle all the SPIFFS-calls:
`#include <LittleFS.h>
#define SPIFFS LittleFS`
(Note, that the sample for the link does not work properly, because "LITTLEFS.h" cannot be found.)

I suggest to include this in the examples, that rely on SPIFFS.
(I only checked the Keypad-example, so I am not sure, whether other samples also rely on this.)

**Comment by Bodmer** [comment]
Yes, that will work for some sketches. There are legacy differences between the SPIFFS and LittleFS API's so that will not work for all SPIFFS sketches.

Sketches will be updated at some point to give filling system options.
