### ISSUE TITLE
Font Ascent / how to center numbers vertically

### ISSUE THREAD

**Issue by timothyblue** [Bodmer/TFT_eSPI#1562]
I'm trying to vertically align numbers in a rectangle. 

I can get the font height using `tft.fontHeight(font);`
This gives me a measurement that includes empty space at the bottom of the number and so the text is always a bit high in the rectangle.

I'm assuming that the extra space at the bottom is from the decent of the font. 

I could not find a method to return the true size height of the number without the descent.

**Comment by Bodmer** [comment]
The siplest way is probably to use the setTextDatum function and use the drawString function ,then it is all done for you.

See Free_Font_Demo and TFT_String_Align examples.

See also TFT_Padding_Demo which is useful.
