### ISSUE TITLE
VNC for TFT_eSPI

### ISSUE THREAD

**Issue by Ierlandfan** [Bodmer/TFT_eSPI#157]
Would be cool if we can port this VNC code (designed for a Ili9341) 
(https://github.com/Links2004/arduinoVNC) to TFT_eSPI so we can let another (more powerfull) device do the actual math or just to show some webpage or whatever you can think of in your choice of (code) language.  That would give endless possibilities.

**Comment by Bodmer** [comment]
I will add this to the wish list but do not have time at the moment to incorporate and debug a new VNC support class.
