### ISSUE TITLE
User_Setup.h and multiple devices

### ISSUE THREAD

**Issue by FredGenius** [Bodmer/TFT_eSPI#1572]
I have many ongoing projects that use various tft displays, it is pain having to change the user_setup.h each time - is it possible to override the critical lines in the project ino file? Or, move the user_setup.h to the project folder?

**Comment by Bodmer** [comment]
The only way with the Arduino IDE is to copy the whole library into the sketch folder. When using PlatformIO the configuration can be in the projects platformio.ini file (see tools folder). PlatformIO is better for project based development.

The User_Setup_Select.h file reduces the effort of changing the settings by just adding // and deleting // on another line which just takes a few seconds. The advantage being that all examples then run.
