### ISSUE TITLE
New RLE font

### ISSUE THREAD

**Issue by Satanpit** [Bodmer/TFT_eSPI#1576]
Hi, @Bodmer, can you have any instruments for create RLE font with custom size and symbols? 
I need RLE font with size 58px with only numbers, and 42px only with "V", "A", "W" symbols.

**Comment by Bodmer** [comment]
Unfortunately the tools for this have been lost long ago and I do not plan to try and recreate them.

For information the encoding method is:
```
A character is drawn as a raster scan within a box size of the characters width and height. The RLE format is a byte, the top bit is a flag, the least significant 7 bits are a 7 bit number (0-127). If the flag is 1 then foreground pixels are plotted, if it is 0 the background pixels are plotted. The number of pixels to plot is the 7 bit number +1.

So, for example, the encoded sequence "0x81, 0x1F" means plot 2 pixels in foreground then 32 pixels in background.
```
Options for you are to use the Smooth font format and there is a processing sketch in the Tools folder to create these with any character selection. Another option is to use one of these "add on" libraries which have a big range of fonts and sizes available:
https://github.com/Bodmer/U8g2_for_TFT_eSPI
Or:
https://github.com/FrankBoesing/TFT_eSPI_ext

**Comment by Bodmer** [comment]
I will close as this is not a bug, but do post back here if you have any more questions.

**Comment by Satanpit** [comment]
@Bodmer thank you for your answer, but i have small memory STM for this project and i think its not possible to use Smooth font

**Comment by Bodmer** [comment]
Try the smooth fonts, you only need a few characters in the font so it may be OK for size.
