### ISSUE TITLE
drawBmp SD

### ISSUE THREAD

**Issue by podaen** [Bodmer/TFT_eSPI#1595]
I am trying to run  TFT_SD_BMP.zip from topic #95 . I am able to show the image but not correct.

`drawBmp("/data/clear-day.bmp", 0, 0);//, 16);`

Than in the line below I get an error: expression must have a constant value.. The value of the variable w can not be used as a const.

uint8_t lineBuffer[w * 3];

This is the picture I get.

![20220201_083238](https://user-images.githubusercontent.com/63886347/151932917-10e18c78-d33a-4b6d-9cda-8dbda1b8ab5d.jpg)

I first make the tft black and when the image shows it turns white, after that the bmp is shown. Whitout the drawBmp the sd and tft works (tested).

![Screenshot_20220201-085647_Gallery](https://user-images.githubusercontent.com/63886347/151932822-4bd8ff04-59e4-476a-a419-c03c57ccad39.jpg)
![Screenshot_20220201-090106_Gallery](https://user-images.githubusercontent.com/63886347/151932838-41c46154-7fec-42ea-aed0-75b1cc4d5630.jpg)

**Comment by Bodmer** [comment]
This looks like exchanges with the SD card are somehow corrupting the screen.

Have you tried the example parrot image to check if the BMP image format is the problem?

What hardware are you using?

**Comment by podaen** [comment]
I have multieple sd card reader, but I currently using this one.

![2021-12-27_112211](https://user-images.githubusercontent.com/63886347/152026891-42bad58d-b3f0-4745-add4-9ae523f7802f.jpg)

**Comment by Bodmer** [comment]
The first 3 cards have 5V to 3.3V buffers so are designed to connect to 5V boards like the UNO. You will need to power those from 3.3V only.

The last one might not have the buffer, but it might be other other side.

Ideally an unbuffered card would be better.

**Comment by podaen** [comment]
That's true. That is wat I can tell out of my previous experiences too. Except the second from below works also on 3.3v. But with multiple spi devices it fails too, like the two above with a bufferchip.

**Comment by Bodmer** [comment]
I just tested this sketch and it works fine. This uses the SD_MMC library with the SD card on different pins.
[TFT_SD_MMC_BMP.zip](https://github.com/Bodmer/TFT_eSPI/files/7982440/TFT_SD_MMC_BMP.zip)

**Comment by podaen** [comment]
I just tested the first example TFT_SD_BMP.zip from topic #95 and it is still working. 

I did made some changes to my config before testing again see #1596 and did also solve this issue.

**Comment by Bodmer** [comment]
Great, thanks for letting me know.
