### ISSUE TITLE
freefonds

### ISSUE THREAD

**Issue by podaen** [Bodmer/TFT_eSPI#1596]
I try to use free fonds and text is show strang on the screen

I have added this to freefonts.h

```
#include <Fonts\GFXFF\FreeSerifBold12pt7b.h>
#include <Fonts\GFXFF\FreeSerifBold18pt7b.h>
#include <Fonts\GFXFF\FreeSerifBold24pt7b.h>
```

otherwise tft.setFreeFont(FSB18);  was not recognized.

```
	tft.setTextDatum(MC_DATUM);
	tft.fillScreen(TFT_BLACK);
	tft.setTextColor(TFT_WHITE, TFT_BLACK);
	tft.setTextDatum(TC_DATUM); // Centre text on x,y position
	tft.setFreeFont(FSB18); 
	//tft.setFreeFont(&FreeSerifBold18pt7b);// Select the font
	tft.drawString("Serif Bold 9pt", 60, 18, GFXFF);  // Draw the text string in the selected GFX free font
```

![20220201_180115](https://user-images.githubusercontent.com/63886347/152016629-17a11ea5-48d2-4c42-a5a2-5547a6330890.jpg)

**Comment by Bodmer** [comment]
Do you get these problems with one of the example sketches, or is it your own sketch?

What is your hardware setup?

**Comment by podaen** [comment]
It is a software problem. I tested it. No sure what could be the issue. I do not any different than this example...

https://github.com/Bodmer/TFT_eSPI/blob/master/examples/480%20x%20320/Free_Font_Demo/Free_Font_Demo.ino#L64

**Comment by Bodmer** [comment]
I suspect you have not included this file in your sketch:
https://github.com/Bodmer/TFT_eSPI/blob/master/examples/480%20x%20320/Free_Font_Demo/Free_Fonts.h

And have this line in your sketch:
https://github.com/Bodmer/TFT_eSPI/blob/master/examples/480%20x%20320/Free_Font_Demo/Free_Font_Demo.ino#L29

**Comment by podaen** [comment]
The cs pin is 22 of the sd card but I removed now from my setup for testing

I copyed the example free font demo in to my shetch and I get a lot of errors of redefinitions

Soo I had to comment the lines I had added into the Free_Fonts.h

```
//#include <Fonts\GFXFF\FreeSerifBold12pt7b.h>
//#include <Fonts\GFXFF\FreeSerifBold18pt7b.h>
//#include <Fonts\GFXFF\FreeSerifBold24pt7b.h>
```
and now the fonts shows up. After the upload i doesn't work. I need to restart it twice to make it work. verry odd.

**Comment by podaen** [comment]
I am now running on the minimum of code that still works... after rebooting twice.

```
 #include <TFT_eSPI.h> // Hardware-specific library
#include <SPI.h>

#include "Free_Fonts.h" // Include the header file attached to this sketch

TFT_eSPI tft = TFT_eSPI();                   // Invoke custom library with default width and height

unsigned long drawTime = 0;

void setup(void) {

    tft.begin();

    tft.setRotation(1);

}

void loop() {

    int xpos = 0;
    int ypos = 40;


   tft.fillScreen(TFT_BLACK);

    //header("Draw with background using drawString()");

    tft.setTextColor(TFT_WHITE, TFT_BLACK);

    tft.setTextDatum(TC_DATUM); // Centre text on x,y position

    xpos = tft.width() / 2; // Half the screen width
    ypos = 50;

    tft.setFreeFont(FSB9);                              // Select the font
    tft.drawString("Serif Bold 9pt", xpos, ypos, GFXFF);  // Draw the text string in the selected GFX free font
    ypos += tft.fontHeight(GFXFF);                      // Get the font height and move ypos down

    tft.setFreeFont(FSB12);
    tft.drawString("Serif Bold 12pt", xpos, ypos, GFXFF);
    ypos += tft.fontHeight(GFXFF);

    tft.setFreeFont(FSB18);
    tft.drawString("Serif Bold 18pt", xpos, ypos, GFXFF);
    ypos += tft.fontHeight(GFXFF);

    tft.setFreeFont(FSB24);
    tft.drawString("Serif Bold 24pt", xpos, ypos, GFXFF);
    ypos += tft.fontHeight(GFXFF);


}
```

**Comment by Bodmer** [comment]
If you are not driving the SD card, then remove the card to avoid SPI bus problems.

**Comment by podaen** [comment]
I don that.

**Comment by podaen** [comment]
Ooo I see now. The cs line is missing from the display..

**Comment by podaen** [comment]
Now It shows up immediately. Curious if it will work when I copy it in to my shetch.

**Comment by podaen** [comment]
I found the second problem. This was why  I had to include the fonds in to the Free_Font.h file. 

`#include <Adafruit_GFX.h>`

I once added this line before I was using this library and was still in it. I removed it... and voila!

**Comment by podaen** [comment]
Can I use a free font like FreeSerifBold18pt7b.h as a smooth font. The flash array file looks different than the examples. I tried

```
           tft.setTextColor(TFT_WHITE, TFT_BLACK); // Set the font colour and the background colour
	tft.loadFont(FreeSerifBold18pt7bBitmaps);
	tft.drawString("19-04-20", 60, 20);
	tft.unloadFont(); 
```

but it crashes.

**Comment by Bodmer** [comment]
No, smooth fonts have a special file format (.vlw).

**Comment by Bodmer** [comment]
Since the original issue is resolved I will close. Glad you have it working now.
