### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by horendus** [Bodmer/TFT_eSPI#16]
Will you be adding esp32 support soon?

**Comment by Bodmer** [comment]
I have added ESP32 support.
Define the pins you use in User_Setup.h
Only tested with an ILI9341 so far.

Let me know if you have problems.

**Comment by Bodmer** [comment]
Thanks for reporting this, it is likely that I have introduced a bug at some point. I will run some tests and see if I can reproduce the problem.

**Comment by Bodmer** [comment]
Issue #274 covers this.
