### ISSUE TITLE
Slow Jpeg from SDcard

### ISSUE THREAD

**Issue by momosh13** [Bodmer/TFT_eSPI#162]
Hi 
Jpeg or BMP from SD card is loading very slow, I'm thinking maybe, if I call HEX(convert BMP or Jpeg to HEX) form SD  card, it will be faster.
Please help me, how I can do that.
Thank you in advance

**Comment by Bodmer** [comment]
The speed of reading the SD card is associated with the SD library, not TFT_eSPI, so you need to contact the author of that library.
