### ISSUE TITLE
drawFloat with dp = 0 prints x.0 (1 decimal place)

### ISSUE THREAD

**Issue by ROSW6341** [Bodmer/TFT_eSPI#1639]
when dp = 0, drawFloat() places decimal point and a 0 following the number
  <number>.0

**Comment by Bodmer** [comment]
The expected dp parameter range  for drawFloat is 1 to 7. drawNumber is for integers.

I guess it might be useful to make 0 valid for dp so a float will then be rounded to the nearest integer so I will add to update list.

Thanks for the suggestion.
