### ISSUE TITLE
touch pointer not work properly with LVGL

### ISSUE THREAD

**Issue by jmcastillejo** [Bodmer/TFT_eSPI#1642]
Xpt2046 touch pointer does not work properly from version 2.4.0 onwards with:

lcd ILI9488 480x320
 lvgl/lvgl@7.11.0 or lvgl/lvgl@^8.1.0
esp32 with arduino framework 3.5.0

I use the example sketch included in the lvgl library in the corresponding version

Using version 2.3.89 downwards works correctly.

**Comment by Bodmer** [comment]
Do the TFT_eSPI examples work OK?

Note that the ILI9488 has an issue with the TFT SDO (MISO) pin because that pin does not go tristate. So DO NOT connect that pin.

**Comment by Bodmer** [comment]
Assumed resolved.
