### ISSUE TITLE
ESP32-CS pins

### ISSUE THREAD

**Issue by podaen** [Bodmer/TFT_eSPI#1644]
I did some tests to see what cs pins are available to make my own board. I have 5 pins work for a short time testing. Those are

GPIO21; GPIO22; GPIO25; GPIO26; GPIO32

I want to check if you see some issues on those pins and label them as cs pins. 

If you know GPIOS that not in the list, I want to know them and I will see if it works.

**Comment by Bodmer** [comment]
Check here, scroll down to the table of pins and functions.

TFT_eSPI managed the CS line so any output capable GPIO can be used. Note however tht some pins have dual functions and the state of some pins affect the boot more of the processor.
