### ISSUE TITLE
ESP32 TTGO T-Display black screen

### ISSUE THREAD

**Issue by Proton6476** [Bodmer/TFT_eSPI#1647]
Hi,
After upload any program on TTGO T-Display ESP32 I get a black screen,
upload passes ok but TTGO does not boot but only gives a black screen.

I made a change to the User_Setup_Select.h file  :
// #include <User_Setup.h>
#include <User_Setups/Setup25_TTGO_T_Display.h>

Any idea ? Every help is welcome

![Image 004](https://user-images.githubusercontent.com/99968465/154688560-71fd3bcd-185f-40af-9083-871355c94580.jpg)
.

**Comment by Proton6476** [comment]
Thanks for the engagement, the problem is solved, in the file User_Setup_Select.h another line was left unmarked by mistake, after the correction everything works OK.
Best regards

**Comment by ssr123631** [comment]
> Thanks for the engagement, the problem is solved, in the file User_Setup_Select.h another line was left unmarked by mistake, after the correction everything works OK. Best regards

can you tell me what you did? im getting the same issue

**Comment by Phando** [comment]
I have been using several TTGO Displays and each has gone dark after a few days of use. I doubt is it software related because some devices will work, till they don't. Is there an issue with powering them from a macbook pro (too much juice)?

**Comment by ahmdakd** [comment]
Hi i have a problem, what does this mean ? @Bodmer 
![image_2024-06-03_04-41-05](https://github.com/Bodmer/TFT_eSPI/assets/158393216/f57b15a5-3489-47d8-b623-05749f9f7946)
