### ISSUE TITLE
Method setFreeFont problem

### ISSUE THREAD

**Issue by rulon** [Bodmer/TFT_eSPI#1656]
I tryed custom fonts with extend range that generated by tool **fontconvert**.
I take file **consola.ttf** from win10 system fonts folder.

range 32-1279 (0x20-0x4FF)
./fontconvert consola.ttf 7 32 1279 > consola7_1279.h

But after call __tft.setFreeFont(&consola7pt8b);__ the program freezes. 
I am not getting any messages on the display and in the Serial Monitor.
Method loop() not called also.

I tried experimentally to find the threshold.
This range works as expected:
./fontconvert consola.ttf 7 32 287 > consola7_287.h

But this to a freeze, as I described above
./fontconvert consola.ttf 7 32 288 > consola7_288.h

```
#include "SPI.h"
#include "TFT_eSPI.h"

//#include "consola7_1279.h"
//#include "consola7_287.h"
//#include "consola7_288.h"

TFT_eSPI tft = TFT_eSPI();

void setup(void) {
  Serial.begin(115200);
  while (!Serial) {
  } 
  Serial.println("setup start");

  tft.begin();
  tft.setRotation(1);
  tft.setTextColor(TFT_WHITE, TFT_BLACK);  
  tft.fillScreen(TFT_BLACK);

  tft.setCursor(0, 20);

  Serial.println(__LINE__);
  tft.println("test1");

  tft.setFreeFont(&consola7pt8b);
  // starting from this line, nothing is displayed on the display and Serial Monitor
  // method loop() not called also
  // if included or consola7_288.h or consola7_1279.h

  Serial.println(__LINE__);
  tft.setCursor(0, 40);
  tft.println("test2");

```

Board info in Arduino IDE:
```
BN: Unknown board
VID: 10C4
PID: EA60
SN: Upload any sketch to obtain it
```

Other IDE Settings:
```
DOIT ESP32 DEVKIT V1
Speed: 921600
Freq: 80
```

lib info:
```
name=TFT_eSPI
version=2.4.32

#define TFT_MOSI 18
#define TFT_SCLK 23
#define TFT_CS   15  
#define TFT_DC    4  
#define TFT_RST   2  

```

I tested this on another similar esp32 board, the result is the same.
But I have M5Stack.
In this case everything works as expected on all fonts:
```
  M5.Lcd.println("\n\ntest2 cyrillic: ыёфжъэєїі");
```
[test_tft_espi01.zip](https://github.com/Bodmer/TFT_eSPI/files/8108552/test_tft_espi01.zip)

Attached my test fonts files.

Thanks! sorry for my english.

**Comment by Bodmer** [comment]
Thanks for reporting this, now fixed in the latest Github master.
