### ISSUE TITLE
drawWideLine(): Black gaps in connecting line edges

### ISSUE THREAD

**Issue by audreylim** [Bodmer/TFT_eSPI#1657]
Hello, when trying to connect anti-aliased lines with a thickness of 2,   `tft.drawWideLine(0, 40, 10, 45, 2, TFT_BLUE, TFT_BLACK);`, the connected edges are separated by a black gap:

![unnamed (3)](https://user-images.githubusercontent.com/4488777/154988169-f2df0d60-2539-4824-9974-a74e947e954e.jpg)

This problem does not appear when the background is set to TFT_BLUE, but then there is no anti-alias:
![unnamed (5)](https://user-images.githubusercontent.com/4488777/154988166-459ff83e-4e9d-49f0-9b01-f8cab00130dc.jpg)

and when the thickness is set to 1:
![unnamed (4)](https://user-images.githubusercontent.com/4488777/154988165-29cd0720-b92d-45cc-9715-2fb29e85f4e4.jpg)

Is there a way to use bold lines without the black gaps in the connecting edges?

**Comment by Bodmer** [comment]
The black joins are expected if the background colour is specified. The display then blends the colour with black.

Avoiding this is only possible with the TFT pixels can be read as then the function reads the screen pixel colour so it knows what to blend with. In that case do not specify the background colour.

The alternative is to use a sprite, as pixel colours in sprites can always be read.
