### ISSUE TITLE
SSD1963 5" 800x480 with STM32f405RGT6

### ISSUE THREAD

**Issue by hackeybabel** [Bodmer/TFT_eSPI#1667]
Hi Bodmer,  i am facing issues compiling ssd1963 for stm32 please take a look into this. I am getting following errors 
![error](https://user-images.githubusercontent.com/31416581/155836099-c0748ea9-0af8-4298-ba39-d2ac0f17f0fd.png)
i tried compiling for differrnt display and it works perfectly but as soon as i select ssd1963 it shows this error.

**Comment by Bodmer** [comment]
Should be fixed now in Github master.

Thanks for reporting this.
