### ISSUE TITLE
is end_tft_write() respect SPI internal mutex?

### ISSUE THREAD

**Issue by smarq8** [Bodmer/TFT_eSPI#1680]
I use display and accelerometer at the same SPI under ESP32, eccelerometer is driven by RTOS notification at around 1kHz. Additionally I use LVGL for some gui and it use only "pushColors()" to update screen content.
The problem is my accelerometer data is very often corrupted by screen update (example below). I tried to add additional mutex in SPI library at beginTransaction() and endTransaction() to ensure its not caused by SPI library without anny succes. Finally I found some place at TFT_eSPI library and its "SET_BUS_READ_MODE". As I move it before "spi.endTransaction()" then it solve all problems. As I'm not quite sure whats purpose of "SET_BUS_READ_MODE" then I just report it here.
I can also solve this by mutex around any functions that use SPI but it seems to be redundant assuming TFT_eSPI work properly.
So should I assume TFT_eSPI is thread safe (not sure how to name it) and its some bug or should I always use external mutex in situation of sharing SPI bus?

Corrupted raw data from accelerometer example
```
+5087 +429 -274911 +1766
+5109 +294 -275039 +1766
+0 +0 +1 +0
+0 +0 +1 +0
+5271 +178 -274639 +1765
+5338 +115 -274847 +1765
+5482 +172 -274863 +1765
+5514 +196 -274783 +1765
+5424 +1 -274671 +1765
+5264 +43 -274639 +1765
+5323 +184 -274895 +1765
+5390 +194 -275055 +1765
+5388 +214 -274879 +1765
+0 +0 +1 +0
+0 +0 +1 +0
+0 +0 +1 +0
+5481 +152 -274687 +1765
+5538 +209 -274719 +1765
+5589 +171 -274591 +1765
+5638 +150 -274543 +1765
+5641 +106 -274687 +1765
+5623 +40 -274767 +1765
+0 +0 +1 +0
+0 +0 +1 +0
+0 +0 +1 +0
+5455 -178 -274879 +1765
+5546 -83 -274927 +1765
```

```
inline void TFT_eSPI::end_tft_write(void){
  if(!inTransaction) {      // Flag to stop ending transaction during multiple graphics calls
    if (!locked) {          // Locked when beginTransaction has been called
      locked = true;        // Flag to show SPI access now locked
      SPI_BUSY_CHECK;       // Check send complete and clean out unused rx data
      CS_H;
#if defined (SPI_HAS_TRANSACTION) && defined (SUPPORT_TRANSACTIONS) && !defined(TFT_PARALLEL_8_BIT) && !defined(RP2040_PIO_INTERFACE)
      spi.endTransaction();
#endif
    }
    SET_BUS_READ_MODE;      // In case SPI has been configured for tx only <----- it seems to corrupt other SPI transactions
  }
}
```

**Comment by Bodmer** [comment]
Fixed. I have not needed or tested it to be thread safe is all circumstances, so proceed with caution!
