### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by harshcht** [Bodmer/TFT_eSPI#17]
I was trying to compile the library for esp32 dev kit but ,every time I try to compile the rainbow examples in eSPI library it gives an error , SPIMMOSI,SPIBUSY and many other variables are not defined. These are being used in TFT_eSPI.cpp but I cannot find where are they defined or innitialised.

**Comment by Bodmer** [comment]
I have added ESP32 support.
Define the pins you use in User_Setup.h
Only tested with an ILI9341 so far.

Let me know if you have problems.

**Comment by harshcht** [comment]
It is now working for esp-32 and st7735 , but red and blue color are getting exchanged.
i.e. it displays red in place of blue and vice versa.

**Comment by Bodmer** [comment]
The BLACKTAB and REDTAB have swapped colours compared to GREENTAB so try all the TAB options.

**Comment by Bodmer** [comment]
I've tried the ST7735 driver and it works OK. So can you check your setup and make sure the TFT really is a ST7735. As I cannot find a fault with the library I am closing this issue.
