### ISSUE TITLE
Touch not working with 2.8" TFT LCD Display Touch Panel SPI Serial 240*320 ILI9341 5V/3.3V STM32

### ISSUE THREAD

**Issue by jsdevel** [Bodmer/TFT_eSPI#171]
I purchased on of these [on ebay](https://www.ebay.com/itm/2-8-TFT-LCD-Display-Touch-Panel-SPI-Serial-240-320-ILI9341-5V-3-3V-STM32/201950756171?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649).

I believe I've followed the wiring correctly.  I _cannot_ get touch to work.  Here's what I have:

NoceMCU v1 (ESP-12N)

Wiring (TFT -> 8266):

* `VCC` -> `3.3v`
* `GND` -> `GND`
* `CS` -> `D8`
* `RESET` -> `D4`
* `D/C` -> `D3`
* `SDI/MOSI` -> `D7`
* `SCK` -> `D5`
* `LED` -> `3.3v`
* `SDO/MISO` -> `D6`
* `T_CS` -> `D2`

The TFT examples display fine, but touch is never captured.  I'll happily provide any more details as requested.

**Comment by Bodmer** [comment]
You need to wire up the touch controller SPI pins too:

T_DIN -> D7
T_DO -> D6
T_CLK -> D5

There is a touch controller diagnostic example that will test the touch screen works.

**Comment by jsdevel** [comment]
That was it!  Thank you so much!
