### ISSUE TITLE
issues with the version version=2.4.42 and ESP32-S2

### ISSUE THREAD

**Issue by homonto** [Bodmer/TFT_eSPI#1733]
just after upgrade  to version=2.4.42 there is an issue with ESP32-S2 and displays:

for #include <User_Setups/Setup18_ST7789.h> :
```
libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32.c:17:31: error: 'VSPI' was not declared in this scope
       SPIClass spi = SPIClass(VSPI);
                               ^~~~
```

for #include <User_Setups/Setup1_ILI9341.h> :
```
libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32.c:17:31: error: 'VSPI' was not declared in this scope
       SPIClass spi = SPIClass(VSPI);
                               ^~~~
```

**Comment by Bodmer** [comment]
2.4.43 has yesterdays update, it is only available direct from Github at the moment. I will release today, the it takes about 24hrs to show as an update in the IDE.
