### ISSUE TITLE
Bug? 32bit color used in TFT_eSprite::pushRotated

### ISSUE THREAD

**Issue by Bluebrain2000** [Bodmer/TFT_eSPI#1735]
in Sprite.cpp
`bool TFT_eSprite::pushRotated(int16_t angle, uint32_t transp)`
... uses 32 bit color and "tries" to swap bytes with:
`tpcolor = tpcolor>>8 | tpcolor<<8;`
especially this part messes it up.
e.g.:
0x1122>>8 = 0x1122
0x1122<<8 = 0x0011
with the -or- operator, it becomes:
0x112211 which does not make much sense, because the compare with a uint16_t color value further below:
`if (tpcolor == rp) {`
will never be true.

**Comment by Bodmer** [comment]
Should be fixed now in master.
