### ISSUE TITLE
Qestion using GFXFF Fonts

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#1741]
Hi,

if I want to use the gfxff fonts, is there a trick to include the specific header?
In your example you created a specifc "Font.h" file.

**Comment by Bodmer** [comment]
If the following in defined in your library setup file then a sketch will have access to the GFX free fonts:
#define LOAD_GFXFF

There are examples for using the fonts. Some examples include a header file that provides shorter reference names, but that is not necessary to reference a font by the full name.
https://github.com/Bodmer/TFT_eSPI/blob/master/examples/320%20x%20240/All_Free_Fonts_Demo/Free_Fonts.h
