### ISSUE TITLE
Blue is Red and Red is Blue !!! 

### ISSUE THREAD

**Issue by pbenaim** [Bodmer/TFT_eSPI#1750]
Blue and Red is swapped !!!

When I set font color Red I have blue, and when I set font blue, I have red one 🤔

When I call drawjpegfile colors are not good too, like blue and red are swapped 🤔

Any suggestions?

Thanks for your helps 😍

**Comment by Bodmer** [comment]
Suppliers connect the pixels to the controller either as RGB or BGR. There is a setup #define that works for the display controllers that library users have idenitifed as being sold with either colour order. Whether this sowrks depends on which controller you have.

[Example setup](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup15_HX8357D.h#L4-L9).
