### ISSUE TITLE
Original Adafruit 8 pixel font 

### ISSUE THREAD

**Issue by stef-ladefense** [Bodmer/TFT_eSPI#1759]
hi,
have you picture of this font ?
is this : https://cdn-learn.adafruit.com/assets/assets/000/103/682/medium800/graphic_lcds_gfx-cp437-bug.png?1627933765

if yes, how to use special characters outside 32-127?

thank for this excelente library

stephane

**Comment by Bodmer** [comment]
The library by default accepts UTF8 encoding of strings and many of the characters above 127 are not available.

It is possible to switch on/off UTF8 support. This will make the font characters available:

```
tft.setAttribute(UTF8_SWITCH, false); 
```
To turn back on and make use of the Unicode 16 bit glyphs change the false to true.
