### ISSUE TITLE
ILI9341_2_DRIVER option produces error: operator '||' has no right operand

### ISSUE THREAD

**Issue by SimGallery** [Bodmer/TFT_eSPI#1763]
Bodmer, I have been using a cheap Chinese alternative ILI9341 using the LI9341_2 driver.
I got error message `TFT_Drivers/ILI9341_Defines.h:4:49: error: operator '||' has no right operand`

TFT_eSPI-master/TFT_Drivers/ILI9341_Defines.h : 4 line , I have modified this as below.

#if defined (ILI9341_DRIVER) || ILI9341_2_DRIVER
to 
#if defined (ILI9341_DRIVER) || defined(ILI9341_2_DRIVER)

It's a shame I'm not familiar with github. This issue report is trivial, but I hope this report is helpful.

**Comment by Bodmer** [comment]
Thanks, I will correct that.  In the meantime, assingn a value, so this will work OK:

#define ILI9341_2_DRIVER 1
