### ISSUE TITLE
PlatformIO Registry: Broken manifest

### ISSUE THREAD

**Issue by ivankravets** [Bodmer/TFT_eSPI#1764]
Hi,

Could we ask you to fix https://github.com/Bodmer/TFT_eSPI/blob/master/library.json ?

https://registry.platformio.org/libraries/bodmer/TFT_eSPI

# Log

ManifestValidationError(
platformio.package.exception.ManifestValidationError: Invalid manifest fields: {'keywords': {5: ['Only [a-z0-9-+. ] chars are allowed'], 8: ['Only [a-z0-9-+. ] chars are allowed']}}. 
Please check specification -> https://docs.platformio.org/page/librarymanager/config.html

**Comment by Bodmer** [comment]
Sorted, thanks for pointing this out.

**Comment by ivankravets** [comment]
Sorry that disturb you, you can validate manifest with [pio pkg pack](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_pack.html) command. See

```
pio pkg pack -o /tmp/test.tar.gz ~/Downloads/TFT_eSPI-master.zip
Error: Invalid manifest fields: {'keywords': {5: ['Only [a-z0-9-+. ] chars are allowed']}}.
Please check specification -> https://docs.platformio.org/page/librarymanager/config.html
```

The `WT32_SC01` keyword uses not allowed underscore.
