### ISSUE TITLE
How to connect the 40 pins display?

### ISSUE THREAD

**Issue by simonovich** [Bodmer/TFT_eSPI#1768]
Hi, team

I have ESP-WROOM 32 and the display:
[https://ru.banggood.com/3_2-Inch-ILI9341-TFT-LCD-Display-Module-Touch-Panel](https://ru.banggood.com/3_2-Inch-ILI9341-TFT-LCD-Display-Module-Touch-Panel-Geekcreit-for-Arduino-products-that-work-with-official-Arduino-boards-p-918609.html?imageAb=1&rmmds=myorder&cur_warehouse=CN)

I tried connecting it like this:
[code]
TFT_eSPI ver = 2.4.44
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 23
MISO    = GPIO 19
SCK     = GPIO 18
TFT_DC   = GPIO 26
TFT_RST  = GPIO 27

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.00
[/code]

If I load any graphical example, then I see a white screen. The screen flickers sometimes. Nothing else happens.

**Comment by Bodmer** [comment]
Unfortunately that is a 16 bit display and is not supported. The library supports SPI and 8 bit parallel displays.
