### ISSUE TITLE
Many warnings during compilation of ili9341 in Arduino

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#178]
Hi,

I get many warnings due compilation in arduino for the esp8266 in Arduino.
Like:
`D:\Arduino\libraries\TFT_eSPI\Extensions/Sprite.cpp:528:37: warning: 'pixelColor' may be used uninitialized in this function [-Wmaybe-uninitialized]`

**Comment by Bodmer** [comment]
Yes, I will fix these on the next iteration. I leave the compiler warnings at the default setting so do not see them!

**Comment by hasenradball** [comment]
Hi, soundsgood! 😄 Can you give me a notice when it is available? Frank

**Comment by Bodmer** [comment]
Library has been updated, all the remaining warnings are likely to stay.
