### ISSUE TITLE
exit status 1 'class TFT_eSPI' has no member named 'initDMA'; did you mean 'init'?

### ISSUE THREAD

**Issue by iwordly** [Bodmer/TFT_eSPI#1784]
`#pragma GCC optimize("O3")
 
 
#include <Arduino.h>
 
#include <TFT_eSPI.h>
 
#include <Wire.h>
 
 
TFT_eSPI TFT = TFT_eSPI();
 
TFT_eSprite eSprite = TFT_eSprite(&TFT);
 
void setup() {
 
    TFT.init();
 
    TFT.setRotation(1);
 
    TFT.fillScreen(TFT_BLUE);
 
    TFT.initDMA();
 
    eSprite.setTextFont(1);
 
    eSprite.setTextColor(TFT_WHITE);
 
    eSprite.createSprite(240, 240);
 
}
 
 
void loop() {
 
    eSprite.setTextFont(1);
 
    eSprite.setCursor(20, 20);
 
    eSprite.println("Hello World\n");
 
   
 
    eSprite.setCursor(40, 40);
 
    eSprite.println("Hello World\n");
 
    eSprite.pushSprite(0, 0);
 
 
    delay(1000);
 
}`

output:
`exit status 1
'class TFT_eSPI' has no member named 'initDMA'; did you mean 'init'?`

**Comment by Bodmer** [comment]
Which processor and display interface are you using?
Write only DMA is supported on ESP32, STM32 and RP2040 with SPI interface. Parallel interface DMA is only supported on RP2040.

**Comment by iwordly** [comment]
ok think you



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 19, 2022 19:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Bodmer/TFT_eSPI] exit status 1 'class TFT_eSPI' has no membernamed 'initDMA'; did you mean 'init'? (Issue #1784)




 
Which processor and display interface are you using?
 Write only DMA is supported on ESP32, STM32 and RP2040 with SPI interface. Parallel interface DMA is only supported on RP2040.

**Comment by Bodmer** [comment]
I have updated the ReadMe to make this clear.
