### ISSUE TITLE
Compilation ERROR

### ISSUE THREAD

**Issue by moreauftheobald** [Bodmer/TFT_eSPI#1790]
Hello,

There is a mistake in the code of version 2.4.50.

In file /processors/TFT_eSPI_ESP32.c

At line 152 to 156 the function 

void TFT_eSPI::gpioMode(uint8_t gpio, uint8_t mode)
{
  pinMode(pin, mode);
  digitalWrite(pin, HIGH);
}

Should be

void TFT_eSPI::gpioMode(uint8_t gpio, uint8_t mode)
{
  pinMode(gpio, mode);
  digitalWrite(gpio, HIGH);
}

pin variable is not defined in this scope.

Regards/

**Comment by Bodmer** [comment]
Fixed thanks.
