### ISSUE TITLE
ESP-S3 Parallel support for ILI9488

### ISSUE THREAD

**Issue by DustinWatts** [Bodmer/TFT_eSPI#1797]
>To minimise effort to resolve issues the following should be provided as a minimum:
>1. ESP32-S3 parallel does not work
>2. Adruino IDE
>3. Latest from Guthub
>4. Board Package Arduino ESP32 Version 2.0.3-RC1
>5. ESP32 S3
>6. ILI9488
>7. Parallel

I tried the https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup16_ILI9488_Parallel.h setup but that had no affect. Check the wires, but noting.

**Comment by Bodmer** [comment]
I have not tested 8 bit parallel with the ESP32 S3. I thought it might work without modification but it seems that is not the case.

What I/O pins have you connected up? The ESP32 requires I/O pins for the data bus plus write pin to be in the range 0-31 so single register writes could be used. The same will apply to the S3.

Note that the Arduino board package is undergoing a lot of low level breaking changes at the moment and so I suspect trouble is ahead until things settle down. I will see if I can get it working with Version 2.0.3-RC1 but the next release may well break things!

**Comment by DustinWatts** [comment]
You are absolutely right, it works! Thanks!

**Comment by yesnoj** [comment]
Sorry for bring back this topic, but i'm using this display here : https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-ili9488.html 
But enabling the file Setup70d_ILI9488_S3_Parallel.h , doesn't works. 
The example from library, TFT_graphictest_one_lib.ino , is compiled without errors, on serial i can see stuff, but the screen is completly off.
Can someone help me? =)

**Comment by Gisbert12843** [comment]
> Sorry for bring back this topic, but i'm using this display here : [makerfabs.com/esp32-s3-parallel-tft-with-touch-ili9488.html](https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-ili9488.html) But enabling the file Setup70d_ILI9488_S3_Parallel.h , doesn't works. The example from library, TFT_graphictest_one_lib.ino , is compiled without errors, on serial i can see stuff, but the screen is completly off. Can someone help me? =)

dont forget to connect ground, background_power and VDD/VCC Pins!

**Comment by vishnumaiea** [comment]
> Sorry for bring back this topic, but i'm using this display here : https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-ili9488.html But enabling the file Setup70d_ILI9488_S3_Parallel.h , doesn't works. The example from library, TFT_graphictest_one_lib.ino , is compiled without errors, on serial i can see stuff, but the screen is completly off. Can someone help me? =)

I have the exact display you have. It uses 16-bit parallel interface with the ESP32-S3. Currently, the TFT_eSPI library only supports up to 8-bit parallel interface with ESP32-S3. So it's a library limitation.

**Comment by vishnumaiea** [comment]
@bjfhskj And is it working?

**Comment by bjfhskj** [comment]
> @bjfhskj And is it working?

No,It does'nt work.Can you help me?

**Comment by vishnumaiea** [comment]
> > @bjfhskj And is it working?
> 
> No,It does'nt work.Can you help me?

Please check my previous reply.
