### ISSUE TITLE
TFT_eSPI/examples/Sprite/Animated_dial - Still Working ?

### ISSUE THREAD

**Issue by bionicbone** [Bodmer/TFT_eSPI#1802]
First, thanks for this awesome library, I have worked through most of the examples and the capabilities with just a little code are amazing. 

I wonder if you can confirm the example examples/Sprite/Animated_dial/ still works with the current version. When I initially tried this with a older versions of libraries installed it worked well, since then I updated to the latest version of several drivers and now the font in the middle is corrupted.

If I do not load the font, then a standard small font is used and then it is fine.

![image](https://user-images.githubusercontent.com/7845867/165684511-7eab9d0a-b678-4ed5-95df-6b61e64c4901.png)

Arduino IDE v1.8.19
TFT_eSPI v1.2.1
ESP32 Boards Manager v2.0.2
ESP32 Wroover Module
Display ILI9341 v1.5.10 on SPI interface

**Comment by Bodmer** [comment]
Ah, a new rendering approach is used for smooth fonts that requires an additional parameter. The new approach reduces flicker dramatically.

```
// Adding a parameter "true" to the setTextColor() function fills character background
    // This extra parameter is only for smooth fonts!
    tft.setTextColor(TFT_GREEN, TFT_BLACK, true);
```
I will update the example.

**Comment by Bodmer** [comment]
I have updated the library github master example.

**Comment by bionicbone** [comment]
Unfortunately this still does not work for me.

I reinstalled the library, just in case and did an overwrite of the example to make sure I got the latest updated github version.

Looking at the updated example " examples/Sprite/Animated_dial/" there is a slight bug, bg_color needed to initiated as global since it is now used in both setup() & plotNeedle() 

However, for me the font is still corrupted in the middle of the dial even with the "spr.setTextColor(TFT_WHITE, bg_color, true);" changes.

I note that in the example "examples\Smooth Fonts\FLASH_Array\Font_Demo_1_Array" you have recently updated this code to remove the overlay of the rectangle and use the ",true" statement instead and this works successfully for me perfectly. 

However, this example is not using a sprite to display the text.

Question: What is the advantage of using a sprit for text ?

Sorry this is probably a discussion now, but I did not want to loose the thread above...

**Comment by bionicbone** [comment]
Just drilling in a bit using visual micro we can see as the sprite updates using breakpoints there is some corruption of the font.

![image](https://user-images.githubusercontent.com/7845867/165892304-85063b82-ca06-49bc-8332-17b2de6c454b.png)

![image](https://user-images.githubusercontent.com/7845867/165892530-6174bb00-efea-4193-940a-913b8c9dda02.png)

![image](https://user-images.githubusercontent.com/7845867/165892555-5972a6c5-f242-4217-83b1-fd8b51d5803f.png)

![image](https://user-images.githubusercontent.com/7845867/165892579-fb0c37d4-1b17-41fc-af6f-6e8b2d64de4c.png)

![image](https://user-images.githubusercontent.com/7845867/165892619-f76d3206-bfe7-4158-a37e-c73f1b585438.png)

**Comment by Bodmer** [comment]
I have updated the sprite.cpp file to fix this.

Thanks for reporting the problem.

**Comment by bionicbone** [comment]
Perfect, thank you for your trouble in resolving this.

Just so you know, because I think the example " examples/Sprite/Animated_dial/" is perfect to demonstrate flicker free needles on top of gauges.

There is a slight compile error, bg_color needs to be initialised in the header with the others because it is used in the setup() & plotNeedle() and for me I increase the spr_width using "777" the remove some artifects / white dots

```
uint16_t* tft_buffer;
bool      buffer_loaded = false;
uint16_t  spr_width = 0;
uint16_t**  bg_color = 0;
```
```
  bg_color = tft.readPixel(120, 120); // Get colour from dial centre
```
```
 spr_width = spr.textWidth("777");
```

Thank you again

**Comment by Bodmer** [comment]
Thanks. Have updated example.
