### ISSUE TITLE
coodinate of a text file

### ISSUE THREAD

**Issue by DaphneeVallieres** [Bodmer/TFT_eSPI#1805]
Let say my notepad.txt file has this

WWWWWTWWWWW

WWWWTTTWWWWW

WWWWWTWWWWW

How do find the coordinate of the 'T's The coordinates being in terms of (row,column)

**Comment by Bodmer** [comment]
Maybe this function does what you want:

https://github.com/Bodmer/OpenWeather/blob/master/examples/TFT_eSPI_OpenWeather_LittleFS/TFT_eSPI_OpenWeather_LittleFS.ino#L620
