### ISSUE TITLE
[FEATURE?] (undocumented?) The "`" character is replaced by "°" on screen by font

### ISSUE THREAD

**Issue by wilhelmzeuschner** [Bodmer/TFT_eSPI#181]
I have just discovered that I do not need to use `tft.drawCircle();` to resemble the "°" in °C.
Instead I can just use tft.print("Temp.:  " + String(temperature, 2) + "`C");
This is confirmed to be working with FONT4 (`tft.setTextFont(4);`).

(This character (ASCII Dec. 96) messes the markdown formatting on GitHub up, see the title)
https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

Please do not change this! But it would be nice to add a small hint, so that other users benefit from this!

**Comment by Bodmer** [comment]
Ah, I made the character mod many years ago and forgot about it.
One day I will get around to writing a user manual. I suspect there are other undocumented features waiting to be discovered :-)
