### ISSUE TITLE
Example for ESP-32

### ISSUE THREAD

**Issue by joseph-vedadi** [Bodmer/TFT_eSPI#1823]
I am very new to ESP-32 and I just  got a display : 
![image](https://user-images.githubusercontent.com/17168374/167745875-306249e0-2fe3-41c4-9632-51071a3104fa.png)
![image](https://user-images.githubusercontent.com/17168374/167745916-e051afc6-e162-46e3-ae2a-12b603a55e93.png)

How am I supposed to use your lib to display something on the display 
 thanks a lot

**Comment by Bodmer** [comment]
Simplest option is to use UNO format ESP32 board, make the changes [described here](https://github.com/Bodmer/TFT_eSPI#8-bit-parallel-support) and the setup file here:

https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup14_ILI9341_Parallel.h
