### ISSUE TITLE
two different lcd on one SPI ?

### ISSUE THREAD

**Issue by yuriy23** [Bodmer/TFT_eSPI#1829]
the actual question is whether it is possible to connect. how to assign two CS ?

**Comment by Bodmer** [comment]
You can put 2 displays on the same SPI bus if they are of identical type and manage the chip select in the sketch. See here:
https://www.youtube.com/watch?v=WL8Xs5D2VUA

Link from video....
https://github.com/kitecraft/Multiple_TFT_Displays
