### ISSUE TITLE
Want to discuss with Bodmer

### ISSUE THREAD

**Issue by jiangminghe** [Bodmer/TFT_eSPI#183]
@Bodmer Nice to meet you.
I am Chinese and i am very impressed to you when i work with your code.
I want to contribute to your code.
Can you give me any chance?
If you can, please let me know about that. 
Thanks a lot.
Best regards!

**Comment by Bodmer** [comment]
Hi, Thank you for your interest. Contributors tend to create a new "Branch" on Github, make and test the changes then submit a pull request.

Mostly I am interested in adding new display drivers (if the display is sold widely) and any bug fixes.

I have less interest in adding new features or functions.
