### ISSUE TITLE
HX8357-A01(T) with ESP32

### ISSUE THREAD

**Issue by m-menon** [Bodmer/TFT_eSPI#1836]
I have had quite a bit of trouble getting a 320 x 480 TFT display ( with "HX8357-A / A01(T)?") to work with ESP32. I have tried to hook it up in few different ways but prefer SPI ( either 3-wire or 4-wire ). I have tried [Adafruit HX8357](https://github.com/adafruit/Adafruit_HX8357_Library) and [Arduino_GFX](https://github.com/moononournation/Arduino_GFX) too but no luck. Would anyone have some idea or pointers on how to hook this display up correctly? I have tried a few different ways to connect as per some github, reddit, arduino forum discussions etc. I might be missing something simple here or perhaps that driver IC isn't supported. In any case does anyone provide me with some pointers on a preferred approach? Would like to run it on SPI but I can go with 8 bit parallel if that is the only solution. Thanks a ton. I have attached the datasheet as well for a quick glance. I am hardly an expert on tft/driver ICs so I am still trying to figure this one out.

[HX8357-A.pdf](https://github.com/Bodmer/TFT_eSPI/files/8737341/HX8357-A.pdf)

**Comment by Bodmer** [comment]
The HX8357A is not supported,  it needs a specific init sequence. A search via Google for an alternative library may find some options.
