### ISSUE TITLE
Cann't parse the png file fetched from some web

### ISSUE THREAD

**Issue by sonictl** [Bodmer/TFT_eSPI#1841]
Cann't parse the png file fetched from some web

I'm developing a static map app on ESP32 (arduino-core v2.0.1).
The `PNGDec` library can parse perfectly on some png fetched from some web url. 

**However**, there are some png fetched from some web url **CANNOT be parsed** by PNGDec. 
I received rc code == 6 when running "rc = png.open()" function in the example of [LittleFS_PNG](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/PNG%20Images/LittleFS_PNG) given in this repo.

In developer tool of Chrome web browser, if you look into the data obtained after GET, some differences can be found.

=== For your re-building this problem ===
The parse_OK png data can GET from [this url](http://api.map.baidu.com/staticimage?width=320&height=240&center=116.403874,39.914888&zoom=16&markers=116.403874,39.914888&markerStyles=l,)
The parse_fail png data can GET from [this url](http://restapi.amap.com/v3/staticmap?location=-60.403874,49.914888&zoom=4&traffic=1&size=320*240&markers=mid,,:-60.403874,49.914888&key=ee95e52bf08006f63fd29bcfbcf21df0)

The code I used for testing: 
 - for PNG fetching: [LittleFS_Web_Jpg](https://github.com/Bodmer/TJpg_Decoder/tree/master/examples/LittleFS/LittleFS_Web_Jpg) (modified for png instead of jpg)
 - for PNG parsing: https://github.com/Bodmer/TFT_eSPI/blob/master/examples/PNG%20Images/LittleFS_PNG/LittleFS_PNG.ino

The png fetched from url above (http://restapi.amap.com) is neccessary for me. 
Any suggestions and fixing method will be very appreciated! Thank you!!

**Comment by Bodmer** [comment]
Contact the PNGDec author. I expect Larry will help.
