### ISSUE TITLE
ILI9341 and Fonts

### ISSUE THREAD

**Issue by GurraE** [Bodmer/TFT_eSPI#1845]
Hello.
I am using the ILI9341 display with your TFT_eSPI library and a ESP32.

Everything is working fine, (I have been using your libraries för ESP8266, ESP32, ILI9341, ILI9488 etc. and everything is working just fine,
 but I want to use Font Sizes larger than the 24 point fonts in the Fonts/GFXFF folder.
In the Fonts/TrueType Folder there are a number of fonts larger than 24 points (Font64rle.c/Font64rlt.h) etc. but there is also a file in that folder saying “Not yet supported”. Thats a bit confusing. Can i use them and if so, how ??

I have also created a font using the https://oleddisplay.squix.ch/ font creator for the ili9341, but where do i put them, and how do i access them in my sketch ??

**Comment by Bodmer** [comment]
This may be of interest. There is a library here:
https://github.com/takkaO/OpenFontRender
That supports rendering of TrueType fonts. Due to the complexity of the code required to convert the font format to a pixel may this is quite slow to render but may be of interest for static text.
