### ISSUE TITLE
User_setup not being read

### ISSUE THREAD

**Issue by smiffycom** [Bodmer/TFT_eSPI#1860]
I just installed a virgin copy of Arduino IDE and TFT_Espi on a new PC, but having issues with TFT_Espi not reading the User_setup file. If I use the read_user_file tool it gives me completely wrong pinouts. I have 4 ESP32 boards all with the same setup and no issues, any idea why a new install cant read the (by me) defined User_setup file?

stumped

smiffy

**Comment by Bodmer** [comment]
Check the User_Setup_Select.h file is correctly loading it and no other setup file.

Examine User_Setup.h and pins are only defined once.

**Comment by Bodmer** [comment]
Assumed resolved.
