### ISSUE TITLE
ESP8266-12E + ST7789 Backlight Only

### ISSUE THREAD

**Issue by CC-4477** [Bodmer/TFT_eSPI#1870]
I've set up my ESP-8266-12E NodeMCU board with a [DFR0649 LCD module](https://www.dfrobot.com/product-2072.html) (uses the ST7789 driver as per [this datasheet](https://wiki.dfrobot.com/1.54%20Inches%20240_240_IPS_TFT_LCD_Display_with_MicroSD_Card_Breakout_SKU_DFR0649#target_5)). However, it seems that I can't get any graphical output on the LCD, and all I see is the backlight (which turns off, as expected, when connected to GND). 

I'm using TFT+eSPI v2.4.61, with the Arduino IDE. My board package version is 3.0.2. The TFT driver I have is ST7789, and I'm interfacing it using SPI.

Here are some images of my setup: 
**LCD**  **ESP**
VCC         3.3V
GND       GND
CS           D8
MOSI      D7
MISO      D6
SCLK       D5
RES         D4
DC          D3

![image](https://user-images.githubusercontent.com/22755244/172113053-ce2f6c96-535e-48bc-9315-25117a36829d.png)
![image](https://user-images.githubusercontent.com/22755244/172113413-86ad5b83-6281-49ef-bc92-67372d588bf8.png)
![image](https://user-images.githubusercontent.com/22755244/172113431-792ea8e6-444f-4b97-993f-1278e1fec95e.png)

Here's my User_Setup.h:
[User_Setup.zip](https://github.com/Bodmer/TFT_eSPI/files/8842522/User_Setup.zip)

Here's the sketch I'm trying to run: https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Generic/Gradient_Fill/Gradient_Fill.ino

edit: here's my Read_User_Setup.ino serial output:
```[code]
TFT_eSPI ver = 2.4.61
Processor    = ESP8266
Frequency    = 80MHz
Voltage      = 3.38V
Transactions = No
Interface    = SPI
SPI overlap  = No

Display driver = 7789
Display width  = 240
Display height = 240

TFT_CS   = PIN_D8
TFT_DC   = PIN_D3
TFT_RST  = PIN_D4

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 80.00
[/code]
```

**Comment by Bodmer** [comment]
Looks OK apart from the SPI clock speed, drop that to 10MHz. The display board has a logic level shifter so it is unlikely to work at high clock speeds.

Also adapt and run the examples provided in the display Wiki and make sure all solder connections are good.

**Comment by CC-4477** [comment]
> Looks OK apart from the SPI clock speed, drop that to 10MHz. The display board has a logic level shifter so it is unlikely to work at high clock speeds.
> 
> Also adapt and run the examples provided in the display Wiki and make sure all solder connections are good.

I'm travelling currently, I'll be able to test this around a week from now. I think it may be the soldering, so I'll disconnect all the pins, clean up the solder, and redo the process. where can I find the examples?

**Comment by Bodmer** [comment]
The examples are in the product Wiki.

**Comment by CC-4477** [comment]
> Looks OK apart from the SPI clock speed, drop that to 10MHz. The display board has a logic level shifter so it is unlikely to work at high clock speeds.
> 
> Also adapt and run the examples provided in the display Wiki and make sure all solder connections are good.

changed this and still nothing but the backlight. I've added `#define TFT_SPI_MODE SPI_MODE3` after creating the TFT object, but nothing's changed.
