### ISSUE TITLE
ESP32 Heltec Dev Board - analogRead(37) returns 4095

### ISSUE THREAD

**Issue by HarroldMonroe** [Bodmer/TFT_eSPI#1888]
I'm using a ESP32 by Heltec with the TFT_eSPI library . Analog pin 37 (adc1_1)  is the battery voltage pin. 
The code analogRead(37) returns 4095.  Which is the adc 12 bit max.
I get appropriate readings in sketches that don't use the TFT eSPI library. 
Is this pin used/blocked in the library somewhere?

**Comment by Bodmer** [comment]
The library only uses GPIO specified in the setup file.
See also here:
https://github.com/espressif/arduino-esp32/issues/2422
