### ISSUE TITLE
max function apparently doesn't work on ESP32 and eSPI

### ISSUE THREAD

**Issue by jlgoasis** [Bodmer/TFT_eSPI#189]
When compile appear " max was not declared in this scope" error. Please can you check it?
Please find below simple example:

#include <SPI.h>
#include <TFT_eSPI.h> 

TFT_eSPI tft = TFT_eSPI();

void setup() {
  tft.init();
  tft.setRotation(0);
}

void loop() {
uint8_t value = max(0,  10);
}

**Comment by pipi61** [comment]
max declared in ......\hardware\espressif\esp32\cores\esp32\Arduino.h
try insert:
#include <Arduino.h>

**Comment by Bodmer** [comment]
See [this issue.](https://github.com/espressif/arduino-esp32/issues/1734)

**Comment by Bodmer** [comment]
This is error not caused by the TFT_eSPI library. I see I added this to TFT_eSPI.h to circumvent the problem with min():

#ifndef min
  #define min(a,b) (((a) < (b)) ? (a) : (b))
#endif

So you could add this in your sketch:

#ifndef max
  #define max(a,b) (((a) > (b)) ? (a) : (b))
#endif

**Comment by jlgoasis** [comment]
Thank you Istvan

I'll try it.

All the best

Jacinto

2018-08-14 1:39 GMT+02:00 Istvan Puzsar <notifications@github.com>:
