### ISSUE TITLE
Setup file for ESP32 S3 with SPI ST7789?

### ISSUE THREAD

**Issue by huigang39** [Bodmer/TFT_eSPI#1895]
Is it possible to drive ST7789 with ESP32 S3?

**Comment by H4nky84** [comment]
Yes it is, it works really well. For some S3 boards you need to ensure you are using SPI_MODE_0 though. I had an issue with this but it was closed a couple of weeks ago in case you need to see the details.

**Comment by mysteriousTreasure** [comment]
I USE ESP32-S3 (N8R8), i want to use SPI2/3,but it  con`t work,

**Comment by H4nky84** [comment]
The two SPI ports I have got working were the 9-14 and the 35-38 set. Which ones are you trying to get it working on?

**Comment by mysteriousTreasure** [comment]
9-14 connect  tft，35-38 connect psram，how to set ？

**Comment by H4nky84** [comment]
Yep, that was what I needed to do as well. If you are using a dev module with the ESP32-S3 WROOM-1 module then the 35-38 should still be available. Only the WROOM2 modules use that for PSRAM.

Since it seems you have got it working please close the issue.

cheers

**Comment by huigang39** [comment]
I don't know how to wire from my ESP32 S3 DevkitC-1 to the tft_espi display

**Comment by Bodmer** [comment]
@H4nky84 Thanks for answering.

@huigang39 An example setup is here:
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup70b_ESP32_S3_ILI9341.h

Clearly you also have to connect power (3V3 and GND assuming the display does not have a 5V regulator)
