### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MarcFinns** [Bodmer/TFT_eSPI#19]
Hi Bodmer, back again and just saw the ESP32 compatibility - great!!
A quick question. I am looking for fonts on various sizes. I like the ones you embedded in your porting of the weather station but only two sizes are available.
Is your lib compatible with Paul Stoffregen collection here on Github, and derived? (e.g. https://github.com/sumotoy/commonFonts).
thanks once more. m

**Comment by Bodmer** [comment]
No the library is not compatible with Paul's fonts.

You can generate fonts in the correct format using the online utility here:
[http://oleddisplay.squix.ch/#/home](http://oleddisplay.squix.ch/#/home)

and then use them as custom fonts.

**Comment by pipi61** [comment]
Yes, use squix converter, but large font this converter not generate,
or use in https://github.com/adafruit/Adafruit-GFX-Library  ->fontconvert utility (first make executable fontconvert). This utility convert any windows ttf font.

**Comment by Bodmer** [comment]
True, the Squix utility only generates fonts up to size 100 (height in pixels)..

**Comment by beegee-tokyo** [comment]
Sorry to comment on a closed issue, but [http://oleddisplay.squix.ch/#/home](http://oleddisplay.squix.ch/#/home) is down. I tried to compile [https://github.com/adafruit/Adafruit-GFX-Library ->fontconvert](https://github.com/adafruit/Adafruit-GFX-Library), but doesn't get it to work.

Is anybody aware of another online or Windows tool to create fonts for this lib?

**Comment by Bodmer** [comment]
The font generator website does go down sometimes. Try leaving a message on Dani's [suport forum.](https://blog.squix.org/2017/07/finally-support-forum.html)

**Comment by pipi61** [comment]
try adafruit fontconvert, upload binary:
http://puzsar.hu/adafruitfontconvert.rar

**Comment by beegee-tokyo** [comment]
@pipi61 thank you I will give it a try.
