### ISSUE TITLE
ESP32 UNO with TFT SHIELD ILI9486 PARALLEL

### ISSUE THREAD

**Issue by kwittek** [Bodmer/TFT_eSPI#1902]
DELETED (My display is broken)

**Comment by Bodmer** [comment]
Have you added the wire links described here:
https://github.com/Bodmer/TFT_eSPI#8-bit-parallel-support

**Comment by kwittek** [comment]
> Have you added the wire links described here: https://github.com/Bodmer/TFT_eSPI#8-bit-parallel-support

Thanks for replay, my display was broken. I change it to another and it works. Thanks for replay anyway. Please delete this issue, it will not help anyone
