### ISSUE TITLE
ESP32 v2.0.1 and later error on init()

### ISSUE THREAD

**Issue by JimDrewGH** [Bodmer/TFT_eSPI#1908]
I upgraded from v1.0.6 of the ESP32 framework to v2.0.4.  When I power up after flashing, I get this error message in the serial monitor:

E (139) gpio: gpio_set_level(226): GPIO output gpio_num error

I traced this down literally to just having:

tft.init(); 

Just having this enabled generates this error.  I do have a custom config file (shown at the end of this text).  Everything seems to work fine, but this message popping up in the serial monitor every time I boot is a bit alarming.

I am using Arduino IDE 1.8.19.

I am using the latest TFT_eSPI (v2.4.61 as installed by the library manager).

I tested this with v2.0.1 and later ESP32 framework.  I did not test v2.0.0, but v1.0.6 and earlier does not generate the message.

This is being tested on a ESP32 WROOM module using the DOIT ESP32 DEVKIT1 board type.

This is a ST7735, 1.8" TFT (160x128) display.  Using the SPI bus.

This is the entire sketch that I am testing with:

//-------------------------------------------------------------------------------`
#include <SPI.h>
#include <TFT_eSPI.h>                         // Hardware-specific library

// SETUP

TFT_eSPI tft = TFT_eSPI();                    // Invoke custom library

void setup() {
  Serial.begin(115200);
  Serial.println("Starting up!");
  tft.init();                                    // <<----- here is the line to init the display that generates the error
  Serial.println("Done!");
}

void loop() {
}
//-------------------------------------------------------------------------------`

The error message appears between the "Starting Up!" and "Done" output to the serial monitor.

Attached is the custom user config file.
[RetroRepairStation.zip](https://github.com/Bodmer/TFT_eSPI/files/9089085/RetroRepairStation.zip)

**Comment by Bodmer** [comment]
This is because the latest IDF throws an error if a pin number -1 is used. The message can be ignored.

Read about the problem with the IDF here:
https://github.com/espressif/arduino-esp32/issues/6737

**Comment by JimDrewGH** [comment]
I can't simply ignore the message because I can't have *any* unwanted serial data going out on the serial port - that is restricted to actual packet data.  Is possible that you change the library so that when something is not defined that it is equal to -1?

**Comment by Bodmer** [comment]
In that case simply comment out the setup lines thus:
```
//#define TFT_RST  -1
//#define TOUCH_CS -1
```

**Comment by JimDrewGH** [comment]
Perfect!  Thanks!

**Comment by openstep** [comment]
HI, 

I am new to arduino and ESP32. I have the same error message when the code tries to set the level on a GPIO port.
Result here is that the relay will not get turned on part of an irrigation system.
This is connected to an 8 channel relay board and it goes in a loop switching realys 0-1-2-3. The first iteration is ok, but the 2nd one I got the error: `E (116335) gpio: gpio_set_level(226): GPIO output gpio_num error`

**Comment by TXyy2023** [comment]
I use a simple to solve this problem，we have already know that E (116335) gpio: gpio_set_level(226): GPIO output gpio_num error is usb wrong GPIO，because in propertie it has initialize CS as -1，So I delete all about cs，then it works perfect
