### ISSUE TITLE
Arduino Library Load vs GitHub Desktop

### ISSUE THREAD

**Issue by LongmontRobotics** [Bodmer/TFT_eSPI#191]
Over the past week I have been trouble shooting a problem I thought I had created.

Compiling and loading the UTFT_Demo_480x320.ino program seemed to work two weeks ago.
I had used the internal library manager in the Arduino 1.8.5 IDE.

Last weekend I thought I'd try the GitHub Desktop.
I moved my TFT_eSPI directory to a backup place and loaded the same TFT_eSPI repo.
Nothing worked.
I had thought I had done something wrong I set out to trouble shoot what I thought was just a type on my part.

Today I finally moved my entire library directory to a safe place and only had one directory in Libraries.
I cloned TFT_eSPI repo into that directory, make the changes I needed for my hardware and nothing.
I deleted that directory and used the Arduino Library manager.
Again made those same changes for my hardware and all works well.

I must have missed something in the documentation about how to properly clone a repo via GitHub Desktop.
I hope someone here has seen this quirk and can point me to a solution/fix.

I also hope I was clear about the problem I am having.
Thanks,
Don

**Comment by Bodmer** [comment]
I have not been able to reproduce the problem. I keep a copy of the repo in my library folder and all master copies are in another location.

TFT_eSPI is now in the Arduino IDE library manager so that is another route for download.
