### ISSUE TITLE
Using tft.setTextFont(4) and tft.textWidth() with extended ASCII text

### ISSUE THREAD

**Issue by Frank-Bemelman** [Bodmer/TFT_eSPI#1913]
I encountered a small misbehavour when writing some code for horizontal scrolling text. I did not follow the example that fills a bitmap with text because the text lengths I am using have different lengths and wanted them to scoll around neatly without any blank space when the buffer is allocated too large. 

So I do a lot of mad calculations to achieve that, all to decide where to start in my string for a new horizontal scroll position. Works well with characters are < 128. When scrolling text with extended ascii, I get horizontal jitter. 

The tft.textWidth() calculates for every illegal character (é, á, ë, ñ etc) a width of 5 (space width). That is sort of ok, but when it comes to printing the actual text with illegal characters, these are just not printed and don't consume any space at all. So there is a discrepancy between the reported textWidth and the actual lenght when it gets printed.

My guess is that it is better to calculate a zero width for illegal characters, since they are not going to be printed.

Another approach might be to print a ~ as a replacement for such illegal character, and use the character width for a ~. That would also give you a visible clue that something is wrong. Or add a tofu character to the font, and use that. If I understood how the characters are actually bitmapped in Font32rle.c I might have given that a try - alas my brain could not figure that out.  

TFT_eSPI.ccp, line 2924:
      else str_width += pgm_read_byte( widthtable + 32); // Set illegal character = space width
TFT_eSPI.ccp, line 4500:
      if (uniCode > 127) return 1;

Anyway, many workarounds to circumvent this behaviour. If I pre/test/modify/fix my text and replace everything above 127 with a '~' I'm also good. So I will use that fix for now.

A full blown extended ASCII font 4 would be nice too ;-) 

Thank you for this magnificent library!
Cheers, Frank

**Comment by Bodmer** [comment]
Yes, font 4 is only provides characters in the range 32-127. The library supports 4 other font formats if extended character sets are needed so there are no plans to extend font 4.
The basic GLCD 5x7 font does have extended characters but maybe not the glyphs you want so the width calculation is correct for that font. Note to access all the extended characters in the range you will need to switch off UTF8 decoding, see #1759.
You have a good work-around for you use case.
