### ISSUE TITLE
Example code DMA Test/Bouncy_Circles breaks on ILI0341 with Color Depth set to 8 

### ISSUE THREAD

**Issue by Smaraguel** [Bodmer/TFT_eSPI#1951]
Hi, i get weird artifacts on my screen when using Color Depth set to 8 and DMA transfers:

![IlI9341_2](https://user-images.githubusercontent.com/108471097/182968319-726ac0c4-c6c5-4e9a-8902-950be9fa6b08.jpg)

Is this supposed to work with my hardware setup:

Arduino IDE
ESP32 (Board package version 1.0.6) 
ILI9341 (4 cable spi)
Using latest Version of library

examples/DMA test/Bouncy_Circles

Added in line 64:

```
  spr[0].setColorDepth(8);
  spr[1].setColorDepth(8);
```

Greetings Smaraguel

**Comment by Bodmer** [comment]
DMA will only work with 16 bit sprites.
