### ISSUE TITLE
How use touch with: esp32 + 320x480 ILI9488 ?

### ISSUE THREAD

**Issue by PospelovDaniil** [Bodmer/TFT_eSPI#1952]
1. How use 320x480 ILI9488 parallel with touch ?
2. Arduino IDE 
3. TFT_eSPI library version - 2.4.72
4. Board package version - 2.0.4
5. ESP32
6. TFT driver - ILI9488
7. Interface type - parallel

<img width="196" alt="display" src="https://user-images.githubusercontent.com/36377393/183266475-09474da5-105b-453d-9c3f-fa7870f05450.png">

Hi Bodmer, I bought a display like the one in the picture.  If I just use the parallel interface (setup 16) the display works, but I don't understand how to use this display together with the touch ? Can you tell me which setup to use, how to connect the display ?

**Comment by Bodmer** [comment]
The screen has an analogue touch interface which requires another library and additional connections:
https://github.com/s60sc/Adafruit_TouchScreen
