### ISSUE TITLE
Add support for 4bits pushToSprite, pushRotated

### ISSUE THREAD

**Issue by sduponch** [Bodmer/TFT_eSPI#1953]
Hi,

When using 4bits colorDepth on eTFT_Sprite, the pushToSprite and pushRotate(&sprite,..) are not working.

I spent one night figuring why it was working in 8bits/16bits and not in 4bits. 
- It seems that the 4bits has been disabled in code.
- Investigation leads me to an issue with the "pushImage" code in 4bits mode (https://github.com/Bodmer/TFT_eSPI/blob/cc9787deaf739f22014b8319e54555da2a5cf761/Extensions/Sprite.cpp#L1110).
- The pushed sprites has color corruptions, only the transparency color is correctly handled.
- The color picking does not look to work, returning always the same color in code display the sprite but with some corruption.

on Arduino IDE with latest library on a DOIT ESP32 Devboard and the 2" 320x240 ST7789 SPI TFT.
[bitmap.zip](https://github.com/Bodmer/TFT_eSPI/files/9281053/bitmap.zip)
```
#include <TFT_eSPI.h>
TFT_eSPI tft = TFT_eSPI();

#include "background_swipe4bits.h";
TFT_eSprite bg = TFT_eSprite(&tft);
#include "swipe4bits.h";
TFT_eSprite swipeCard = TFT_eSprite(&tft);

int angle = 0;
void drawBackground() {
  bg.setColorDepth(4);
  bg.createSprite(320, 240);
  bg.createPalette(palette, 16);
  //bg.fillSprite(4);
  bg.pushImage(0, 0, 320, 240, (uint16_t *)background);
  
  swipeCard.setColorDepth(4);
  swipeCard.createSprite(140, 70);
  swipeCard.createPalette(palette, 16);

  //swipeCard.fillSprite(5);
  swipeCard.pushImage(0, 0, 140, 70, (uint16_t *)swipe_card);
  swipeCard.setPivot(0, 35);
 
  //swipeCard.pushToSprite(&bg, 10, 10, 5);
  bg.setPivot(170,240);
  swipeCard.pushRotated(&bg, angle, 5); // 5 is transparency color in palette
  
  bg.pushSprite(0,0);
  bg.deleteSprite();
  swipeCard.deleteSprite();
}
```

**Comment by Bodmer** [comment]
pushToSprite already handles copying a 4 bit sprite into another sprite. So this should work:
```
  bg.setColorDepth(4);
  bg.createSprite(320, 240);
  bg.createPalette(palette, 16);
  bg.pushImage(0, 0, 320, 240, (uint16_t *)background);

  swipeCard.setColorDepth(4);
  swipeCard.createSprite(140, 70);
  swipeCard.createPalette(palette, 16);
  swipeCard.pushImage(0, 0, 140, 70, (uint16_t *)swipe_card);

  swipeCard.pushToSprite(&bg, 70, 35);

  bg.pushSprite(0, 0);

  while(1) delay(1000);
```

pushRotated only handles 8 bit and 16 bit sprite to sprite copying. I will add to the todo list but I have little time at the moemnt to work on additions.
