### ISSUE TITLE
Centre Text

### ISSUE THREAD

**Issue by leetut** [Bodmer/TFT_eSPI#1977]
How can i print a word in the centre of my display?
using the ST7735 library I use  tft.setCursor(tft.width() / 2, 15, true);
that prints any length word in the top centre of my display
but the eSPI library starts the word in the centre

ive tried using the string align example but still cant figure it out

**Comment by zuhairmst** [comment]
Use the function setTextDATUM() with MC_DATUM which means middle centre.

**Comment by leetut** [comment]
How do I print something Top Centre and 15px from top?

**Comment by zuhairmst** [comment]
tft.setTextDatum(TC_DATUM);
tft.setCursor(width/2,15);

**Comment by Bodmer** [comment]
The print stream cannot be used with text formatting for technical reasons. Use drawString():
```
tft.setTextDatum(MC_DATUM);
tft.drawString("Hello", tft.width() / 2, 15);
```
