### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by abdollahpour** [Bodmer/TFT_eSPI#199]
Is it possible to have the horizontal scrolling? I did not find anything about it in the library

**Comment by Bodmer** [comment]
I assume you know that screens natively support vertical scrolling in portrait orientation. This is used in the [example here](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/320%20x%20240/TFT_Terminal).

Scrolling in Sprites, horizontally, vertically and diagonally is supported as in the appropriately names [examples here](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Sprite).

**Comment by abdollahpour** [comment]
Thanks for the answer. I assumed hardware scrolling using without spirit would be faster and does not need extra memory. My device uses the LCD in portrait mode.
