### ISSUE TITLE
Add SPIClass object parameter for <init> function

### ISSUE THREAD

**Issue by StarsRiver-der** [Bodmer/TFT_eSPI#1991]
A **hal Error**  happens when I sharing one spi_bus(VSPI) with multi devices (in my case is `microSD` and `GC9A01A`), the reason is,  `TFT_eSPI::begin_tft_write` and `end_write` function only use `spi.beginTransaction()` and `spi.endTransaction()` to control the data stream, but not remove the apbChangeCallback (by using `spi.end()`). 
1. Procesor: ESP32-WROVER
2. IDE PlatformIO
3. Interface type: SPI
4. TFT driver: GC9A01A
5. IOSET: MISO--27 MOSI--25 CLK--26 CS--32

The Error message is: `[esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x*** arg=0x***`
Execution backtrace is: 
```
// SPI_1 start
  SPIClass SPI_instance1(VSPI)
  -> SPI_instance1.begin(**) 
  --> spiStartBus(spi_num)      // Here I use VSPI (3), so spi_num is 3
  ---> addApbChangeCallback(&_spi_bus_array[spi_num])

// SPI_2 start
  SPIClass SPI_instance2(VSPI) 
  -> SPI_instance2.begin(**) 
  --> spiStartBus(spi_num)     // spi_num = VSPI = 3
  ---> addApbChangeCallback(&_spi_bus_array[spi_num])  // Here we will get a <duplicate> error
```

If  we add `SPI_instance1.end()` before SPI_2 start, problem solved. So my first temporary solution is: 
```
inline void TFT_eSPI::begin_tft_write(void){
  spi.begin(**);
  // do something
}

inline void TFT_eSPI::end_tft_write(void){
  // do something
  spi.end();
}
```

The temporary solution is not a good idea, as `spi.begin` and `spi.end` cost about 200~300 microsecond in ESP32，I think add more parameters for `init()` could be better, like this `tft.init(CS, SPI_obj, Freq)`. So that I can control SPI bus begin or end manually, then the code would be like this:
```
SPIClass SPI_obj= SPIClass(VSPI); // Create a SPI instance

tft.init(TFT_CS, SPI_obj, Freq);  // Init TFT_eSPI
microSD.init(SD_CS, SPI_obj, Freq); // Init SD card

// Run TFT functions
SPI_obj.begin(CLK, MISO, MOSI, TFT_CS);
tft.do_something_1();
tft.do_something_2();
tft.do_something_3();
SPI_obj.end();

// Run SD functions
SPI_obj.begin(CLK, MISO, MOSI, SD_CS);
microSD.do_something();
SPI_obj.end();
```

**Comment by Bodmer** [comment]
You can get the SPI class instance by using the library function:
```
static   SPIClass& getSPIinstance(void);
```
Then control begin/end in the sketch.

**Comment by StarsRiver-der** [comment]
> You can get the SPI class instance by using the library function:
> 
> ```
> static   SPIClass& getSPIinstance(void);
> ```
> 
> Then control begin/end in the sketch or pass instance to microSD library.

ok, that is enough.

**Comment by baloyou** [comment]
> 

hello, I have the same question as you, can you share your code? Thank you very much!!

**Comment by StarsRiver-der** [comment]
> > 
> 
> hello, I have the same question as you, can you share your code? Thank you very much!!

I code a common class as template for fully comply with different devices.
A `IO_SPI.cpp` is parent class that 'my_device.cpp' needs to extend.
you can see it in my gitlab, please refer to.
[IO_SPI.cpp](http://git.starsriver.net:8110/starsriver/circuits-design/-/blob/master/Module/ESP32_WROVER_EVB/firmware/SmartKnob/src/module/IO_SPI.cpp)
[display class](http://git.starsriver.net:8110/starsriver/circuits-design/-/blob/master/Module/ESP32_WROVER_EVB/firmware/SmartKnob/src/module/dev/display/GC9A01A.cpp)

in `display class`, two methods below are used to control spi. Where `Device` is announced by `TFT_eSPI Device = TFT_eSPI();`
```
void begin_spi() { Device.getSPIinstance().begin(CLK, MISO, MOSI, CS); }
void end_spi() { Device.getSPIinstance().end(); }
```

**Comment by baloyou** [comment]
> > hello, I have the same question as you, can you share your code? Thank you very much!!
> 
> I code a common class as template for fully comply with different devices. A `IO_SPI.cpp` is parent class that 'my_device.cpp' needs to extend. you can see it in my gitlab, please refer to. [IO_SPI.cpp](http://git.starsriver.net:8110/starsriver/circuits-design/-/blob/master/Module/ESP32_WROVER_EVB/firmware/SmartKnob/src/module/IO_SPI.cpp) [display class](http://git.starsriver.net:8110/starsriver/circuits-design/-/blob/master/Module/ESP32_WROVER_EVB/firmware/SmartKnob/src/module/dev/display/GC9A01A.cpp)
> 
> in `display class`, two methods below are used to control spi. Where `Device` is announced by `TFT_eSPI Device = TFT_eSPI();`
> 
> ```
> void begin_spi() { Device.getSPIinstance().begin(CLK, MISO, MOSI, CS); }
> void end_spi() { Device.getSPIinstance().end(); }
> ```

Okay, I'll try, thanks. :)
