### ISSUE TITLE
TFT display with long wire

### ISSUE THREAD

**Issue by RoboticsAayush** [Bodmer/TFT_eSPI#1999]
Hi, I was working with a 3.5' TFT display Driver: ILI9486(Parallel 8bit) and ESP32, and thanks to the library I was able to fully control the display.
I was able to get my circuit function on a breadboard but as soon as I soldered everything the display seems to be creating colorful dots and turning white(attached a video).
the only change I did was to use longer wires(1.5 m), can this cause this issue? if yes how can I resolve it without moving the esp32 closer to the display?

Thanks 
Aayush

https://user-images.githubusercontent.com/84365147/188565379-b9e65651-733b-43b5-b9eb-f37a4a57a396.mp4

**Comment by Bodmer** [comment]
The parallel bus requires short wires. I doubt you will be able to get it working with such long wires.

Using a GND wire between every signal line in the ribbon cable may  help with ground bounce and adding 22 Ohm series resistors in every signal pin line at the processor to suppress reflections might work. Really the lines need to be about 100mm maximum!
