### ISSUE TITLE
Issues with setRotation()

### ISSUE THREAD

**Issue by harshcht** [Bodmer/TFT_eSPI#20]
the tft works fine normally but whenever I use the setRotation() function it behaves aierdly.
For instance , 

     `#include <TFT_eSPI.h> // Graphics and font library for ST7735 driver chip
     #include <SPI.h>

    TFT_eSPI tft = TFT_eSPI(); 

     void setup() {
    // put your setup code here, to run once:
     Serial.begin(115200);
    tft.init();
    //tft.setRotation(1);
     tft.fillScreen(ST7735_GREEN);

    Serial.println(tft.width());
    Serial.println(tft.height());
    tft.fillRect(0,0,tft.width()/4,tft.height()/4,ST7735_RED);
    }

    void loop() {
    }` 

This code works perfectly fine but if I uncomment the line
       `tft.setRotation(1)`
the display suddenly stops i.e nothing is displayed, the tft goes entirely white.

Now when I exchange red and green (keeping setRotation() uncommented) this is what is displayed : 

![img_20170526_102206](https://cloud.githubusercontent.com/assets/28594884/26481380/3e80037e-41fe-11e7-8194-90bd4a2793dd.jpg)

**Comment by Bodmer** [comment]
I don't have a similar setup I can test at the moment but try adding a 20ms delay before and after the setRotation() call.  Some TFT drivers need a delay after some commands so maybe this is the problem. I will check the ST7735 datasheet.

**Comment by harshcht** [comment]
Thanks @Bodmer . Adding the delays partially solves the problem, but it inverts the blue and red color again.

**Comment by Bodmer** [comment]
I have tried my ST7735 display and it works fine so I am unable to help you at the moment.  can only assume that the display you have is not an ST7735. Does it work normally with the Adafruit libraries and a standard UNO?

**Comment by harshcht** [comment]
I checked it on arduino mega. On that it works fine.

**Comment by Bodmer** [comment]
Can you describe your hardware setup in more detail. Can you provide a web link to the display vendors page.

**Comment by Bodmer** [comment]
Also try the latest version of the library.
