### ISSUE TITLE
Support for building images in external memory.

### ISSUE THREAD

**Issue by JamesNewton** [Bodmer/TFT_eSPI#200]
Lovely ePaper display with onboard SRAM for display frames, and their library supports building a frame in /that/ memory then pushing it to the display. Would be perfect if it supported overlap mode on the ESP. 
https://www.adafruit.com/product/3625
Happy to send you one if you would like. 

Or perhaps there is a more general solution: Support for building the image in a SPIFFS file which is then shoved out to the display? That would allow supporting very large displays, but I assume it would be rather slower? However, ePaper isn't fast anyway so the SPIFFS time would be a fraction of the update speed anyway.

**Comment by Bodmer** [comment]
The board is good for AVR processors that do not have much RAM spare, pity it is only 8kbytes. The need for two chip selects precludes use in Overlap mode, as that only supports 1 chip select.  SPIFFS is FLASH memory thus is prone to wear-out if used as a dynamic graphics buffer.

For Espressif processors a better solution is PSRAM as that makes Megabytes svailable and I see Arduino support for this is being added for the ESP32. This makes screen buffers for higher pixel count displays possible.
