### ISSUE TITLE
add 565 bitmap utility

### ISSUE THREAD

**Issue by tbillion** [Bodmer/TFT_eSPI#2003]
i havent found a method for drawing color bitmaps but i may just be over looking something it would be nice if you would add this utility to the main library or a version that would be faster.

```void draw565Bitmap(int16_t x, int16_t y, const uint16_t *bitmap, uint8_t w, uint8_t h) {

  uint16_t offset = 0;

  int j, i;

  for (i = 0; i < h; i++) {
    for (j = 0; j < w; j++) {
      tft.drawPixel(j + x, i + y, bitmap[offset]);
      offset++;
    }
  }

}
```

**Comment by Bodmer** [comment]
The example TFT_Flash_Bitmap draws 16 bit 565 colour bitmaps.
