### ISSUE TITLE
Program problems of ESPI Library in stm32f103c8t6

### ISSUE THREAD

**Issue by CJT1111** [Bodmer/TFT_eSPI#2011]
Hello, friend
My problem is that the ESPI library is applied to STM32 Series MCU. First, I did an experiment (Application of ESPI on esp32). This experiment perfectly displayed the content. But ask
The question appeared in the ESPI library and STM32. I modified the user_ Setup。 The pin definition of the. H file (other definitions I tested in esp32 are normal), as shown in the figure:
![image](https://user-images.githubusercontent.com/111559992/189541070-fce51b05-977b-4c7a-b796-3d860031e337.png)
But de reported this fault. As shown in the figure:
![image](https://user-images.githubusercontent.com/111559992/189541118-6c94076d-912e-4d64-a09c-427c31834ae1.png)
The above is only one of the questions. When I continue to experiment, I find that esp32 does not have port multiplexing function? However, when I repeatedly define data and clock on the SPI port used by the SD card
The display will not be available. However, this problem does not matter, because I can solve the problem by avoiding several ports used by the SD card. I look forward to the answer from the great God.

**Comment by Bodmer** [comment]
I do not get the same errors. Make sure you have the correct board package loaded into the Arduino IDE and not an old deprecated version. I have version 2.3.0:

![image](https://user-images.githubusercontent.com/15824805/189547433-981047b8-bc33-4c49-9733-ff2ef4058100.png)
