### ISSUE TITLE
tft.setTextColor(_,_,true) will not clean the ten or hundred's place ,when I use drawNumber ,or drawFloat

### ISSUE THREAD

**Issue by yukiloh** [Bodmer/TFT_eSPI#2017]
Even the ten/hundred change to 0,last value will still living in the screen ,I hope it shoukd be disappeared.

Device: Esp32
IDE: Arduino IDE 2.0
lib: TFT_ESPI_VERSION "2.4.72"
Screen: GMT130 240*240pi ST7789

Code:
```
spd = 0; //init
rpm = 0;

void setup() {
  Serial.begin(115200);
  tft.init();
  tft.fillScreen(SCREEN_COLOR);
  tft.setRotation(0);
}

void loop() {
  spd = spd + 1.1;
  rpm += 10;

  if (spd > 19.9) {
    spd = 0;
  }

  if (rpm > 100) {
    rpm = 0;
  }

  refresh_spd_screen();  //to print number
  refresh_rpm_screen();

  vTaskDelay(100);
}

void refresh_spd_screen() {
  tft.setTextDatum(TR_DATUM); 
  tft.setTextColor(VAL_COLOR, SCREEN_COLOR, true);
  tft.drawFloat(spd, 1, spd_x, spd_y, FONT_SIZE);
}

void refresh_rpm_screen() {
//the same code,pass...
}
```

The screen: ten/hundred never return to blank(always keep 1)
[![vvanxg.jpg](https://s1.ax1x.com/2022/09/14/vvanxg.jpg)](https://imgse.com/i/vvanxg)

**Comment by Bodmer** [comment]
Use  setTextPadding, see example:
https://github.com/Bodmer/TFT_eSPI/blob/master/examples/480%20x%20320/TFT_Padding_demo/TFT_Padding_demo.ino
