### ISSUE TITLE
Suggestion: animated GIF support

### ISSUE THREAD

**Issue by MarcFinns** [Bodmer/TFT_eSPI#203]
Hello Bodmer, a number of weather services provide animated GIFs with moving weather.
Do you think this is beyond the limits of esp8266/esp32?  would it be an interesting option to support it?
thanks.

**Comment by Bodmer** [comment]
Have you tried[ this library](https://github.com/prenticedavid/AnimatedGIFs_SD)?

**Comment by MarcFinns** [comment]
Well, i searched and missed this one... thanks!
Let’s see if it works. Need first to solve the out of memory as these services sadly all use https which crashes my device for now.
Thanks again!

On 7 Sep 2018, at 00:53, Bodmer <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried this library<https://github.com/prenticedavid/AnimatedGIFs_SD>?

**Comment by nikthefix** [comment]
Also this one:

https://github.com/bitbank2/AnimatedGIF

He has a TFT_eSPI example which works really well and can play back from PROGMEM.
