### ISSUE TITLE
Arduino 2.0 compile error 'class TFT_eSPI' has no member named 'getTouch'

### ISSUE THREAD

**Issue by Skyboy68** [Bodmer/TFT_eSPI#2041]
I am writing a program using getTouch and the TFT_eSPI library. I recently downloaded the new Auduino IDE 2.0 and it wouldn't compile my code. I got the error;

error: 'class TFT_eSPI' has no member named 'getTouch'

So I deleted 2.0 and went back to 1.8.19 and it worked fine. Then I tried 2.0 again a few days later and now 1.8.19 does the same thing as 2.0, no member named getTouch. I tried a fresh install of 1.8.19 too. Nothing.

I even tried changing the #define CS pin in usersetup.h as recommended elsewhere but it did not work, but after I did that, the tft will now no longer work at all. I tried different example code, but nothing, the tft is blank. Code does seem to run on the EPS32 however, but screen stopped working completely. It compiles if I removed any reference to getTouch.

Everything worked fine before I installed v2,.0 :-(

Any suggestions fellow coders???

David

----------------------------ADDITIONAL DATA IN ERROR---------------------------

Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Disabled, No OTA (2MB APP/2MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

    tft.getTouch(&touch_x, &touch_y);

        ^

Multiple libraries were found for "Adafruit_SHT31.h"

 Used: C:\Users\Davey\Documents\Arduino\libraries\Adafruit_SHT31_Library

 Not used: C:\Program Files (x86)\Arduino\libraries\Adafruit_SHT31_Library

Multiple libraries were found for "Adafruit_I2CDevice.h"

 Used: C:\Users\Davey\Documents\Arduino\libraries\Adafruit_BusIO

 Not used: C:\Program Files (x86)\Arduino\libraries\Adafruit_BusIO

exit status 1

'class TFT_eSPI' has no member named 'getTouch'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Bodmer** [comment]
A GPIO pin X must be defined in the setup:

#define TOUCH_CS X
