### ISSUE TITLE
DMA support for ILI9488/ILI9486

### ISSUE THREAD

**Issue by andrey-belokon** [Bodmer/TFT_eSPI#2048]
Hi,

In readme you note that 

> ILI9486 (DMA not supported with SPI)
> ILI9488 (DMA not supported with SPI)

I found old issues https://github.com/Bodmer/TFT_eSPI/issues/963 with same question. As solution you give a beta branch

> I have uploaded a[ Beta test branch](https://github.com/Bodmer/TFT_eSPI/tree/2.4.0-Beta).

But now this branch is not available - error 404. May be you add support for DMA with ILI9486/9488 SPI to master? Or DMA still unsupported? Please explain this.

PS I ask because now need make choice between 9341 and 9486/88. Wide display is more preferable for my project, but DMA required.

**Comment by Bodmer** [comment]
DMA is not supported for those 18 bit colour SPI displays. The beta branch added other performance improvements for 18 bit displays.

DMA for 18 bit displays will not be supported in the future except maybe for the RP2040 processor.
