### ISSUE TITLE
Can I use just low 4 bits for an 8-bit 8080 MCU?

### ISSUE THREAD

**Issue by BrandonStudio** [Bodmer/TFT_eSPI#2067]
I'm using ESP32 but short of pins, can I just use 4 or 6 data pins of 8 total (i.e. TFT_D0~TFT_D5)?

Besides, is there any control pin that does not need to connect to ESP32 (RST, DC, WR, RD)?

**Comment by Bodmer** [comment]
No, 8 bit data plus WR and DC is minimum. Then CS tied low, RD tied high, RST eithet tied high or to power on reset signal.
