### ISSUE TITLE
Display wrong image color

### ISSUE THREAD

**Issue by camdiep2** [Bodmer/TFT_eSPI#2077]
Hi all,

I use this library with my nodemcu but image is displayed in wrong color, what should I check to resolve the issue ?

![image1](https://user-images.githubusercontent.com/80382054/195501490-fa9f248e-a135-4d48-b682-e4e015bb2a42.jpg)

Original image
![icon3](https://user-images.githubusercontent.com/80382054/195501460-7d2e7e1c-1ca4-4348-825c-877b7d116cbb.jpg)
![icon1](https://user-images.githubusercontent.com/80382054/195501428-63bfe61c-ffa6-47ef-af07-a3302834abcd.jpg)

I use http://www.rinkydinkelectronics.com/t_imageconverter565.php to convert original images to *.h file and use it in my codes

#define TFT_ESPI_VERSION "2.4.76"
tft.init();
tft.fillScreen(TFT_BLACK);
tft.setSwapBytes(true);
tft.pushImage(30, 199, 112  , 112, icon1);

but icon is displayed in wrong color, so what should I check now ? Thank you.

**Comment by Bodmer** [comment]
Try setting swap bytes to false. 

tft.setSwapBytes(false);
