### ISSUE TITLE
HX8357B pinouts

### ISSUE THREAD

**Issue by kuzmanzs** [Bodmer/TFT_eSPI#209]
Hi,

I have a TFT board above. 
It looks like similar to http://www.ekt2.com/pdf/412_ARDUINO_SHIELD_LCD_TOUCH_3.2inch_320x480.pdf
On the plastic bag I have a label with following:
3.2" Arduino module
Driver:HX8357B  BUS:16bit
Dots: 480x320  Tocuh: NO

First I want to use it with Wemos board. You have recommended to use this library for it. I do not find pins in the document above for SPI mode (only pins for SD card). Have you ever seen such board?
I think it can be working with ESP32 mobule in 16bit configuration. What do you think?

**Comment by Bodmer** [comment]
You have a 16 bit parallel display, the ESP32 and ESP8266 do not have enough pins to drive the bus.

The board coud proably be driven with a Mega or Due and suitable library.
