### ISSUE TITLE
Issue ESP32 and uncommon pin for CS

### ISSUE THREAD

**Issue by everyb313** [Bodmer/TFT_eSPI#21]
Hi,
I used ESP32 with ILI9341 and the freefont_demo.
I think the initialization fails if an uncommon io pin for CS is selected.
with "#define TFT_CS   5"  the LCD runs fine, but with "#define TFT_CS   15" I cannot see an image.

![image](https://user-images.githubusercontent.com/4741156/27029856-59df2b62-4f6a-11e7-8b94-f43dfdd9af2d.png)
figure above: IO5 used (ok)

![image](https://user-images.githubusercontent.com/4741156/27029904-896c897e-4f6a-11e7-9f73-eeafec6c0369.png)
figure above: IO15 used (fails)

ILI9341_Init.h:

// This is the command sequence that initialises the ILI9341 driver
// This setup information uses simple 8 bit SPI writecommand() and writedata() functions
// See ST7735_Setup.h file for an alternative format
{
  writecommand(0xEF);
  writedata(0x03);
  writedata(0x80);
  writedata(0x02);
(...) 

It seems that the CS is not drawn to LOW at the 1st initialization byte after switching the SPI clock on.
(SPI clock rate 1MHz, logic analyzer sampling rate = 16 MHz)

Any hints ?

**Comment by Bodmer** [comment]
Thanks for reporting this. Post back if the fix does not work for you.
