### ISSUE TITLE
Using this library with an Arduino Uno to use a 3.5" RPi LCD (A)

### ISSUE THREAD

**Issue by Fortunate-MAN** [Bodmer/TFT_eSPI#210]
I currently have a 3.5" RPi LCD (A), by Waveshare, as described in the README, and imaged over [here](https://github.com/Bodmer/TFT_eSPI/blob/master/Tools/RPi_TFT_Connections.png). I'm trying to use this with an Arduino Uno.

This was one of the few libraries which I found which explicitly stated supporting this LCD, but sadly, this library has been designed for the ESP8266 and the ESP32. I failed in using the LCD with other libraries which specifically support the Uno.

Is it possible for me to use this library with an Arduino Uno? If so, how?

**Comment by Bodmer** [comment]
The library is optimised and setup for the Espressif processors and will not work on an UNO without very extensive changes. Your best option is to get a display that is supported by an existing compatible libray.

**Comment by indraneelpatil** [comment]
@fortunate-man  Did you figure out a way to use the Rpi LCD with arduino UNO using SPI?
