### ISSUE TITLE
TL_DATUM not working?

### ISSUE THREAD

**Issue by MarcFinns** [Bodmer/TFT_eSPI#212]
Hello Bodmer,
Onn a ILI9341 i have the feeling the TL_DATUM is not working correctly.
At the same coordinates, BL prints correctly aligned to the right limit of the screen, while TL does not print anything...

**Comment by pipi61** [comment]
example?

**Comment by pipi61** [comment]
minimal source?

**Comment by Bodmer** [comment]
I ran some tests but found no issues with TL_DATUM.  Please check your sketch for x,y position errors.
