### ISSUE TITLE
Problems with colors inverted

### ISSUE THREAD

**Issue by sorriso93** [Bodmer/TFT_eSPI#213]
I have a problema with colors, is it possibly due to the wrong TFT type (red, green and so on) on user_setup.h?

I'm using ST7735 driver and choosed #define ST7735_REDTAB... On three displays, should be same type hardware, I obtain different colors on RED (I get blue) for examples with the same code...

Thanks

**Comment by Bodmer** [comment]
Try the ST7735_BLACKTAB option.

**Comment by Bodmer** [comment]
Closing but will re-open if you have a problem with your other displays.
