### ISSUE TITLE
Compilation Error with ESP8266 and Stino

### ISSUE THREAD

**Issue by moelfus** [Bodmer/TFT_eSPI#214]
Hi, 

first of all thanks for this great library. I'm using a WeMos D1 mini (ESP8266) and a cheap 1.8" ST7735 (KMR-1.8). With the Arduino IDE (Windows) and the newest tool chain (espressif 2.4.2) the demos can be compiled and run fine. However, usually I use Sublime as IDE with the Stino plugin (https://github.com/Robot-Will/Stino). When using Sublime with the same tool chain I'm facing a compilation error:

[Build]
 C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/examples/160 x 128/TFT_Clock_Digital...
[Step 1] Check Toolchain.
[Step 2] Find all source files.
[Step 3] Start building.
[1.4%] Compiling TFT_Clock_Digital.ino.cpp...
[2.8%] Compiling TFT_eSPI.cpp...
[4.2%] Compiling SPI.cpp...
[5.6%] Compiling Font16.c...
[6.9%] Compiling Font32rle.c...
[8.3%] Compiling Font64rle.c...
[9.7%] Compiling Font72rle.c...
[11.1%] Compiling Font72x53rle.c...
[12.5%] Compiling Font7srle.c...
[13.9%] Compiling glcdfont.c...
[15.3%] Compiling Button.cpp...
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:5:1: error: 'TFT_eSPI_Button' does not name a type
 TFT_eSPI_Button::TFT_eSPI_Button(void) {
 ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:10:6: error: 'TFT_eSPI_Button' has not been declared
 void TFT_eSPI_Button::initButton(
      ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:2: error: variable or field 'initButton' declared void
  TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h,
  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:2: error: 'TFT_eSPI' was not declared in this scope
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:12: error: 'gfx' was not declared in this scope
  TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h,
            ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:17: error: 'int16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h,
                 ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:28: error: 'int16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h,
                            ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:39: error: 'uint16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h,
                                       ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:11:51: error: 'uint16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x, int16_t y, uint16_t w, uint16_t h,
                                                   ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:12:2: error: 'uint16_t' was not declared in this scope
  uint16_t outline, uint16_t fill, uint16_t textcolor,
  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:12:20: error: 'uint16_t' was not declared in this scope
  uint16_t outline, uint16_t fill, uint16_t textcolor,
                    ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:12:35: error: 'uint16_t' was not declared in this scope
  uint16_t outline, uint16_t fill, uint16_t textcolor,
                                   ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:13:2: error: expected primary-expression before 'char'
  char *label, uint8_t textsize)
  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:13:15: error: 'uint8_t' was not declared in this scope
  char *label, uint8_t textsize)
               ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:21:6: error: 'TFT_eSPI_Button' has not been declared
 void TFT_eSPI_Button::initButtonUL(
      ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:2: error: variable or field 'initButtonUL' declared void
  TFT_eSPI *gfx, int16_t x1, int16_t y1, uint16_t w, uint16_t h,
  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:2: error: 'TFT_eSPI' was not declared in this scope
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:12: error: 'gfx' was not declared in this scope
  TFT_eSPI *gfx, int16_t x1, int16_t y1, uint16_t w, uint16_t h,
            ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:17: error: 'int16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x1, int16_t y1, uint16_t w, uint16_t h,
                 ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:29: error: 'int16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x1, int16_t y1, uint16_t w, uint16_t h,
                             ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:41: error: 'uint16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x1, int16_t y1, uint16_t w, uint16_t h,
                                         ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:22:53: error: 'uint16_t' was not declared in this scope
  TFT_eSPI *gfx, int16_t x1, int16_t y1, uint16_t w, uint16_t h,
                                                     ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:23:2: error: 'uint16_t' was not declared in this scope
  uint16_t outline, uint16_t fill, uint16_t textcolor,
  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:23:20: error: 'uint16_t' was not declared in this scope
  uint16_t outline, uint16_t fill, uint16_t textcolor,
                    ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:23:35: error: 'uint16_t' was not declared in this scope
  uint16_t outline, uint16_t fill, uint16_t textcolor,
                                   ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:24:2: error: expected primary-expression before 'char'
  char *label, uint8_t textsize)
  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:24:15: error: 'uint8_t' was not declared in this scope
  char *label, uint8_t textsize)
               ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:38:6: error: 'TFT_eSPI_Button' has not been declared
 void TFT_eSPI_Button::drawButton(boolean inverted) {
      ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:38:34: error: variable or field 'drawButton' declared void
 void TFT_eSPI_Button::drawButton(boolean inverted) {
                                  ^
C:/Users/User/Documents/Arduino/libraries/TFT_eSPI/Extensions/Button.cpp:38:34: error: 'boolean' was not declared in this scope
[Build] Error occurred.

p.s.: the pin notation on the KMR-1.8 SPI display is a bit misleading. SCL = D5 (instead SCK); SDA = D7 (instead of MOSI)

**Comment by Bodmer** [comment]
I do not use Sublime or Stino so am unable to help. It sounds like an issue with Stino as the library compiles OK under the Arduino IDE and PlatformIO IDE.

Perhaps raise an issue on the Stino Github page, but it looks like development on that plugin has ceased.
