### ISSUE TITLE
printf error

### ISSUE THREAD

**Issue by johnerb44** [Bodmer/TFT_eSPI#2172]
In file included from C:\Users\*****\AppData\Local\Temp\.arduinoIDE-unsaved20221013-20924-v86r6q.9ml88\Flash_PNG\Flash_PNG.ino:18:0:
C:\Users\*****\AppData\Local\Temp\.arduinoIDE-unsaved20221013-20924-v86r6q.9ml88\Flash_PNG\Flash_PNG.ino: In function 'void loop()':
c:\Users\*****\Documents\Arduino\libraries\LibPrintf\src/LibPrintf.h:20:20: error: 'class arduino::UART' has no member named 'printf_'; did you mean 'print'?
 # define printf    printf_
                    ^
C:\Users\*****\AppData\Local\Temp\.arduinoIDE-unsaved20221013-20924-v86r6q.9ml88\Flash_PNG\Flash_PNG.ino:55:12: note: in expansion of macro 'printf'
     Serial.printf("image specs: (%d x %d), %d bpp, pixel type: %d\n", png.getWidth(), png.getHeight(), png.getBpp(), png.getPixelType());

using rp2040
mbed rp2040 package

flash_png.ino

Example output:
](error: 'class arduino::UART' has no member named 'printf_'; did you mean 'print'?)

**Comment by Bodmer** [comment]
The error seems to be reported by another library called LibPrintf. I am not sure why such a library is needed as many supported processors have printf built into the board package. Maybe you can delete that library as it does not seem to provide the full functionality expected for printf.

Which processor are you using?

**Comment by johnerb44** [comment]
I am using a Raspberry Pi Pico RP2040.
Thanks for the quick reply. Sorry to waste your time. I have used your library with Esp32 and esp8266 before and really liked it. Never had a problem.
I should have investigated the LibPrintf library more. To get it to compile I needed to add printf_init(Serial); to setup()

void setup()
{
  printf_init(Serial);
  Serial.begin(115200);
  Serial.println("\n\n Using the PNGdec library");

  // Initialise the TFT
  tft.begin();
  tft.fillScreen(TFT_BLACK);

  Serial.println("\r\nInitialisation done.");
} 
Also changed Serial.printf() statement to just printf().

Without adding the LibPrintf library (there are others I could have tried) it didn't look like the mbed rp2040 package supported printf().

**Comment by johnerb44** [comment]
See previous comment. Raspberry Pi Pico Also my first instinct was to use the https://github.com/earlephilhower/arduino-pico board rp2040 package but in the Arduino IDE it seems to have said it was deprecated and to use the mbed package.   I now notice that the earlephilhower package specifically says it supports printf. I think I will try it and see if your library compiles without having to use LibPrintf. Thanks again. I will close the issue. Sent from Mail for Windows From: BodmerSent: Monday, November 14, 2022 5:33 PMTo: Bodmer/TFT_eSPICc: John; AuthorSubject: Re: [Bodmer/TFT_eSPI] printf error (Issue #2172) The error seems to be reported by another library called LibPrintf. I am not sure why such a library is needed as many supported processors have printf built into the board package. Maybe you can delete that library as it does not seem to provide the full functionality expected for printf.Which processor are you using?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
