### ISSUE TITLE
[Question] Pins to not connect ?

### ISSUE THREAD

**Issue by YordanYanakiev** [Bodmer/TFT_eSPI#218]
![ili works](https://user-images.githubusercontent.com/6534199/46772085-fb9e1180-ccfe-11e8-8b71-14c18fea9838.jpg)
Hello.
It turns out my display is actually ILI9488
(using this setup #include <User_Setups/Setup16_ILI9488_Parallel.h> works like a charm).
Anyway I am trying to save pins for my other devices, and I am about to remove them permanently, so I wonder if the pins which I surrounded with red paint is actually needed to work the display or not ?
( I am not planing to use the SD card on the display module ).

**Comment by Bodmer** [comment]
Yes, in addition you can disconnect LCD_RD and pull the LCD line high if you do not read from the LCD. You can also disconnect TFT_CS and pull that LCD line low.

**Comment by YordanYanakiev** [comment]
Thank You very much Bodmer!

**Comment by hamzamahmood-lm** [comment]
Hello @YordanYanakiev , which controller were you using if you remember ? 🤞

**Comment by Bodmer** [comment]
Setup 16 is for an ESP32.

**Comment by YordanYanakiev** [comment]
> Hello @YordanYanakiev , which controller were you using if you remember ? 🤞

The microcontroller was ESP32
