### ISSUE TITLE
Generic->Sketch_with_tft_setup  not found

### ISSUE THREAD

**Issue by griffinmt** [Bodmer/TFT_eSPI#2184]
I currently have the most recent copy of your library (2.4.79) installed with Arduino IDE, but cannot find the mentioned sketch. Like many folks, I really want to do this. Can you help?

**Comment by Bodmer** [comment]
It is here:
https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Generic/Sketch_with_tft_setup
 this only works on ESP32 and may cause problems with other libraries.
