### ISSUE TITLE
ILI9488 touch pins

### ISSUE THREAD

**Issue by kuzmanzs** [Bodmer/TFT_eSPI#220]
Hi,
I have ILI9488 with touch sensor.

Where should I connect touch related pins?
T_IRQ ?
T_DO  MISO?  
T_DIN  MOSI?
T_CS - > D1

I have selected "Setup20_ILI9488.h" for ESP8266

https://www.dropbox.com/s/fvcl14v6we3v3yg/IMG_20181015_175350.jpg?dl=0

**Comment by kuzmanzs** [comment]
I have connected so.

Something is wrong with the calibration. The corner test comes up, but it is so fast I can't touch the screen and the touching does not work(Keypad 480x320.ino).

**Comment by Bodmer** [comment]
The ILI9488 is unusual as it does not tristate SDO, connecting it to MISO via a 1K resistor may work it you need to read from the TFT.
