### ISSUE TITLE
ESP32 S3 ili9488 SPI 480x320 extension

### ISSUE THREAD

**Issue by MYCHMA** [Bodmer/TFT_eSPI#2210]
1. Any plans to do it
2. IDE Arduino 
3. TFT_eSPI library version (try the latest, the problem may have been resolved!) from the Manage Libraries... menu
4. Board package version 2.0.4
5. ESP32 S3 
6. ili9488
7. SPI

**Comment by Bodmer** [comment]
It is already supported.
Example setup here, just change the driver at line 5!
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup70b_ESP32_S3_ILI9341.h

**Comment by MYCHMA** [comment]
Thanks it works awesome:-)
