### ISSUE TITLE
Parallel interface use touchscreen 

### ISSUE THREAD

**Issue by Andrisetianabrata** [Bodmer/TFT_eSPI#2278]
Is it possible to use a touchscreen with the ili9486 parallel interface? I've looked it up on various sites and YouTube and I've tried various touchscreen libraries beyond TFT_eSPI. But nothing can solve my problem

**Comment by Bodmer** [comment]
No.

If you have a resistance analogue type screen you can use the library mentioned here:
https://github.com/s60sc/Adafruit_TouchScreen

If it has a SPI interface then a third party library is needed.
