### ISSUE TITLE
RP2040 in 8 bit parallel mode does not work with SSD1963 display

### ISSUE THREAD

**Issue by Bodmer** [Bodmer/TFT_eSPI#2297]
### Discussed in https://github.com/Bodmer/TFT_eSPI/discussions/2283

<div type='discussions-op-text'>

<sup>Originally posted by **Technikfreak2002** December 30, 2022</sup>
Hello! 
First of all, thank your awesome library!
I have some trouble with a SSD1963 Display. It works fine with an ESP32, 8 bit mode, SSD1963_DIVERALT, and RGB order.
But if i use another MCU, in this case a Pi Pico, i get only wired colors and pixel garbage on the screen.
I also tried some STM32 boards, with no luck. STM32F103, STM32F411 (Blue and Black Pill) Nucleo64 L476RG and Nucleo144 H743ZI2. 
for every test i made a user setup to set the correct pins. but no luck.
Other display drivers, like the ILI9486, work with the pico and at with the nucleo64.

Can some give me a hint? am i missing a bit?

Thank you very much and a happy new year! :D
</div>

**Comment by Technikfreak2002** [comment]
I tested the new define but it doesn't work.

I use Arduino IDE 1.8.19, under Linux Mint 21.
Earle's package at 2.6.5

Setup ist 103, but RST on 27, #define SSD1963_800ALT_DRIVER  added, #define TFT_RGB_ORDER TFT_RGB added and #define RP2040_PIO_CLK_DIV 3 added

Display is a 7 inch from Amazon. Conected via 10cm Jumper wires to a Pico Breadboard Demo board.

Sketch is the UTFT_DEMO_480x320

Thank you for your time and feedback! :D

**Comment by Technikfreak2002** [comment]
![20230115_163021.jpg](https://user-images.githubusercontent.com/38852340/212550286-b520d0e2-9991-439c-9b9e-841ed6eb9f68.jpg)

Here is the setup.

**Comment by Bodmer** [comment]
How have you wired the TFT_CS and TFT_RD pins?

**Comment by Technikfreak2002** [comment]
CS to GND
RD to 3.3V

**Comment by Bodmer** [comment]
Fixed in master library.

Display should work with #define RP2040_PIO_CLK_DIV 1

The DIV value may need to be increased if you overclock the RP2040 but mine works up to 200MHz with DIV set to 1!

**Comment by Technikfreak2002** [comment]
I tested the new version. And it works! Thank you so much!
