### ISSUE TITLE
How to tell if library successfully initialised

### ISSUE THREAD

**Issue by euphy** [Bodmer/TFT_eSPI#231]
Hi Bodmer, this is a brilliant library and I'm using it in my Polargraph machines. Thank you very much for making it so good. 
I'd like to be able to sense if the ESP32 is running without an LCD/Touchscreen connected (on the test-bed essentially), or with a real display attached. Is there a way to sense whether the library is interacting with a real SPI device? If there's not a built-in way, perhaps you could give me a pointer. I don't know much about how SPI works but I might be able to figure it out.
Thanks!

**Comment by Bodmer** [comment]
If you need more help then do post an update.
