### ISSUE TITLE
There is something wrong with the DMA on ESP32C3

### ISSUE THREAD

**Issue by 0x0fe** [Bodmer/TFT_eSPI#2311]
So, i enabled the DMA and i get an error related to DMA channel, telling in SPI mode the DMA cannot be selected on the C3, it has to be set to SPI_DMA_CH_AUTO.
I tried to change the init to SPI_DMA_CH_AUTO in TFT_eSPI_ESP32_C3.c line 836, but it did not fixed the problem : there is no more loop reboot but now the display is just filled with random data (same as an uninitialized buffer).

**Comment by Bodmer** [comment]
For the ESP32-S2, ESP32-S3 and ESP32-C3 DMA is not supported at the moment (ReadMe new item 6).  This is on the TODO list.
