### ISSUE TITLE
ESP32-WROVER-KIT V3 with ST7789 TFT Driver (240x320) - inverted colours and other problems

### ISSUE THREAD

**Issue by Les-A** [Bodmer/TFT_eSPI#232]
I've looked back over past issues for this TFT and noted earlier comments about the Adafruit library and wrong colours.  I have a couple of problems ...

1.  The display is defaulting to 240 x 240 and I'm not clear on how to amend it.  I tried setting TFT_WIDTH and TFT_HEIGHT in my User_Setup.h file but it doesn't seem to do anything.

2.  On the Print_Test script,  I'm getting inverted colours - Black on White is showing as White on Black, Yellow is Blue, Green is Magenta, Blue is Yellow.  This occurs on all rotation values.

On rotation(0) the text fits the screen ok, though the grey background stops short.
On rotation(2) the text starts part way down the screen and the "Binary" and "Hexadecimal" lines are lost.

I'm guessing that the screen size is hard-coded in the driver.  Can this be parametrised please, as per the ST7735?

Is there any option I can set to get the right colours - Inversion option or something?

Finally, does setting the Touch Screen pin value always switch on support regardless of the driver or does it have to be specifically coded?  I believe the ST7789 supports touch screen but I'm not sure if it is implemented in this development kit.

Details from the library Read_User_Setup are:
`
[code]
Processor    = ESP32
Frequency    = 240 MHz
Transactions = Yes 
Interface    = SPI 
Display driver = 7789
Display width  = 240 
Display height = 240 

MOSI    = D23 (GPIO 23)
MISO    = D25 (GPIO 25)
SCK     = D19 (GPIO 19)
TFT_CS   = D22 (GPIO 22)
TFT_DC   = D21 (GPIO 21)
TFT_RST  = D18 (GPIO 18)

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.0 MHz 
[/code]
`

Many thanks - excellent library.

**Comment by Bodmer** [comment]
I have just merged a pull request by amakukha for the ST7789.

I do not have one of these 240x320 displays so can you test it for me?

Thanks.

**Comment by Bodmer** [comment]
The inverted colors may disappear if you do not use setRotation() as it looks like the merged pull request uses the opposite RGB<>BRG color order, if this is the case then let me know as I need to swap the control bit in the rotation code to match.

**Comment by Bodmer** [comment]
Defineing the touch pin switches on support for the XPT2046 resisitive touch screen controller. No other touch controllers are supported.

**Comment by Les-A** [comment]
OK, so I amended the TFT_WIDTH and TFT_HEIGHT values in ST7789_Defines.h and reran the Print_Test script.

In rotation(0) its ok.
In rotation(1) its ok except the bottom half of "Hexadecimal" appears at the 'top' of the screen (wrap-around?).
In rotation(2) it operates as 240 x 240 and starts part way up from the physical bottom of the screen.
In rotation(3) its a combination of r(1) and r(2) problems.

Wrap-around text is displayed as you would expect so I take this to mean that the screen size change is being respected.

This is probably what you'd expect but it may be helpful.

**Comment by Les-A** [comment]
One further note.  I amended the Test_Print script and printed the values of tft.height() and tft.width() for the 4 rotations and they are (320, 240), (240,320), (320,240), (240,320) respectively.

**Comment by Les-A** [comment]
I've just seen your response re pull request.  I'll see what I can do.

**Comment by Les-A** [comment]
I've just seen your response re pull request.  I'll see what I can do.

**Comment by Les-A** [comment]
So based on my earlier post ...
screen is now 320 x 240.
TFT_Clock looks correct except for the second hand which is Blue - with and without setRotation(0).
Print_Text still has the same problems except that "Groop ..." is now correctly Green on Black, but "Float ..." is now Red and "1234.56" is now Pale Blue.  I tested with and without setRotation() - same results.
I'll try a couple more tests on colour.

**Comment by moononournation** [comment]
@Les-A you may try add "tft.invertDisplay(false);" after "tft.init();" or you may try this branch:
https://github.com/moononournation/TFT_eSPI

**Comment by Les-A** [comment]
Interesting.  Used 'true' - red now goes to yellow instead of blue; white & black are reversed; green goes to magenta.  Option 'false' gives me exactly what I had before (as you'd expect).  

Last night I looked through the spec and there are a couple of pages on 4-wire SPI  (pp 103 & 104) that describe RGB (6-6-6) 262k colours 3Ah = "06h" - but as I've no idea what other displays use, it didn't really help me a lot.  I imagine this makes much more sense to you.  The description says 
msb = Rx5, Gx5, Bx5
lsb = Rx0, Gx0, Bx0
and the signal diagram shows
rrrrrr--gggggg--bbbbbb--
as the bit transmission.

**Comment by Les-A** [comment]
I've looked at the example supplied in the ESP IDE and they use 16-bit, 65k colours.  From memory I believe the colours worked ok.

msb bit 4, lsb bit 0
RGB (5-6-5) format, 3ah = "05h"
rrrrrggggggrrrr  etc.

**Comment by Bodmer** [comment]
Ah, went brain dead there! Invert turns black to white etc and does not change the colour order!

I have created a branch for you to try, see links above to see what to modify or download a copy of the branch (use branch button on main TFT_eSPI page).

**Comment by Bodmer** [comment]
I have added another change to the branch to remove the offset that is needed for 240 x 240 displays (see link above for the change) so that should fix everything for you.

I will need to add some switches for the different screen sizes and RGB order varieties of the display... but at least this should get you going in the meantime.

**Comment by Les-A** [comment]
I downloaded the branch and tried it on the clock and print_test scripts.  All problems appear to be resolved ... colours are correct and screen size is correct in all rotations.
A couple of further questions:
1. Is it normal for text beyond the bottom of the display to wrap around to the top and overwrite what's already there? It does this on the test_print script in rot(1) and rot(3).
2. Will I need to continue to add a line of code to turn on the backlight or will that be fixed under the other issue?
3. Do you know how long it will take for this update to appear officially in the Arduino IDE?

I'd like also to say thank you for fixing these problems for me so quickly.  I only wish I could have done it myself (that is, had the skills!).

**Comment by Bodmer** [comment]
Glad to hear it is working. 
1. Text wrap can be switched on/off, which example are you using? You can turn off the wrap in the x and y directions with:
tft.setTextWrap(wrapX, wrapY);  // Where wrapX and wrapY are true, or false

2. Yes, the line of code has to be in your sketch at the moment until I add an extra control switch.

3. I need to add the switch first as it will break compatibility with some displays. Probably do that within 7 days.

RE. help. No problem, I happen to be tinkering with the library at the moment anyway!

**Comment by Bodmer** [comment]
I have added WROVER ST7789 support to the master branch and issued a release for the Arduino IDE library manager.  It can take a while (~24 hours) for the library manager to pick up new releases.

**Comment by Les-A** [comment]
Hi, sorry to bother you again but I lost the library I was testing with and downloaded the one here on github just now.  Unfortunately the changes you made don't seem to be in it - is there something I need to do?  I've got the wrong colours and the screen is 240 x 240 again.  Best regards.

**Comment by Bodmer** [comment]
The changes are in there, to support the different screen sizes [you must specify the width and height](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h#L32) in portrait mode in the setup file.

**Comment by Les-A** [comment]
Thanks.  Sorry, I had the width & height the wrong way round from an earlier test.  My fault.  However, I still have blue instead of red but I can see your changes and tests in the code in my copy of the library.  Library manager says I have 1.1.3 installed.  I've used both .zip and git clone to get the library.  Not sure what's gone wrong.

**Comment by Bodmer** [comment]
Ok, I can see the problem, setRotation is setting the wrong colour order. I will fix withkn 24 hrs.

**Comment by Les-A** [comment]
Thanks.  I've altered my copy so no pressure.

**Comment by Bodmer** [comment]
I have made the changes needed. Can you test the updates for me as I do not have one of those displays.
