### ISSUE TITLE
Problem with ESP32 and ili9488 capacitive-GT911 touch screen 

### ISSUE THREAD

**Issue by RSanchez888** [Bodmer/TFT_eSPI#2346]
Dear Bodmer,
I am not very experience with these boards and programming, but I am trying to control this ili9488 capacitive screen (https://es.aliexpress.com/item/1005004083478309.html?spm=a2g0o.cart.0.0.413f7a9dT3jQJE&mp=1&gatewayAdapt=glo2esp)
with this ESP32 board (https://es.aliexpress.com/item/1005004337178335.htmlspm=a2g0o.cart.0.0.413f7a9dT3jQJE&mp=1&gatewayAdapt=glo2esp)

For the moment, I managed to make the screen and SD work, but I had no success with the touch control. I´ve tried different wiring diagrams but no way. Could you please share the complete and correct TFT, SD and touch wiring I should use, according to my TFT screen and ESP32 board.
I would appreciate if you can suggest a code for testing the correct functioning.
Thanks in advance.

**Comment by Bodmer** [comment]
The TFT_eSPI library does not support that touch controller so you will need to find an independant library. A quick Google came up with this video:
https://www.youtube.com/watch?v=WyyrxYFd2C4

Although that is without a screen the principles are the same. And this further link from the video which has test sketches and a good explanation of how to connect up and get it working:
http://www.digitaltown.co.uk/components14ESP32GT911Screen.php
