### ISSUE TITLE
Problem with tft.readPixel on MCU ESP32S2 and driver ST7735S 

### ISSUE THREAD

**Issue by UkiTenzai** [Bodmer/TFT_eSPI#2363]
## Description
Hello, I drew a picture on the screen and wanted to take a screenshot with tft.readPixel. 
Here is my code

```
  // draw
  tft.fillScreen(TFT_BLACK);
  tft.fillCircle(20,20,4,TFT_WHITE);
  tft.fillCircle(108,108,4,TFT_GREEN);
  tft.fillRect(64,64,16,16,TFT_RED);
  ...
  //generate picture and send it to PC
  for (int y=0; y<128; y++){
    udp.beginPacket(udpAddress,udpPort);
    for (int x=0; x<128; x++){
      uint16_t pixel = tft.readPixel(x,y);
      udp.printf("%d,", pixel);
    }        
    udp.endPacket();
    delay(10);
  }
```
Here are the **photo of the screen** and **the generated picture**
![IMG_20230129_112352_edit_1041639881605116](https://user-images.githubusercontent.com/75011154/215303840-0f0f83e0-21bc-469e-a44d-1133ce5ed338.jpg)

![4](https://user-images.githubusercontent.com/75011154/215303854-f21dff29-6b48-4741-807a-d4ad6e1f47ce.png)

The circles' shape and location are right but the colors are wrong. And it doesn't show the rectangle. So I think there may be some bugs about the decode of  RGB. Perhaps in your code `Arduino\libraries\TFT_eSPI\TFT_eSPI.cpp`, lines 1184 ~ 1191
```
  #else
    // Read the 3 RGB bytes, colour is actually only in the top 6 bits of each byte
    // as the TFT stores colours as 18 bits
    uint8_t r = tft_Read_8();
    uint8_t g = tft_Read_8();
    uint8_t b = tft_Read_8();
    color = color565(r, g, b);
  #endif
```
## Configuration

-  IDE:       Arduino 2.0.3
-  MCU:    ESP32-S2-MINI-1
-  screen:  TFT LCD (driver st7735s)

## Testing
I read issue #2327 and then run `TFT_ReadWrite_Test`, it failed as well.
![image](https://user-images.githubusercontent.com/75011154/215304525-2ca2b13c-280d-432e-86b6-a33f871eb887.png)
So I convince that there is something wrong with the color.

## Debugging attempts
I changed SPI_READ_FREQUENCY, but it have no effect.

## Other
I have read the doc of  ST7735S and I will try to write a driver to read a pixel by micropython.  
I am a beginner of this field. Any help would mean a lot.

**Comment by Bodmer** [comment]
Post your setup file so I can see how you have connected the S2 to the display.

**Comment by Bodmer** [comment]
That is interesting. The display does not have a MISO pin. The S2 must be automatically switching the SPI bus to half duplex for it to work at all. The read frequency is too high, try reducing the SPI read frequency to 6MHz..

**Comment by UkiTenzai** [comment]
I found that if SPI_READ_FREQUENCY < 10MHz or > 25MHz, tft.readPixel always return 0. 
But if 10MHz < SPI_READ_FREQUENCY < 25MHz, it return a wrong number, but not 0.

**Comment by UkiTenzai** [comment]
I have no idea why SPI_READ_FREQUENCY is low enough, it also always returns 0.

**Comment by Bodmer** [comment]
I think half duplex SPI with a bidirectional SDA signal is not going to work. I suggest you use a sprite instead as the screen is only 128x128 you can create a sprite of that size, draw graphcs in it and push to the screen. The pixel values can be read from the sprite, e.g. spr.readPixel(...).

**Comment by UkiTenzai** [comment]
Yes, I have thought about using a buffer to store the data but I didn't know it is called sprite. I will try it later.

**Comment by UkiTenzai** [comment]
It really works. Thanks.
![20230131-103342](https://user-images.githubusercontent.com/75011154/215650900-7b02bb9b-acb4-41c3-8300-fe406f855b17.png)

**Comment by Bodmer** [comment]
I have updated the library so that displays with a bidirectional SDA pin can be read without bus conflicts. The ST7735 pixel read code has been updated to correct the colour conversion (remove leading dummy bit).
I have tested with an ST7735 display. The setup file needs the following line to be included when using a display with a single bidirectional SDA pin.:
```
#define TFT_SDA_READ
```
