### ISSUE TITLE
Touchscreen support for parallel displays while using Wifi

### ISSUE THREAD

**Issue by s60sc** [Bodmer/TFT_eSPI#237]
I have been using your library on ESP32 UNO style boards and the cheap red MCU Friend displays with the parallel interface. The touchscreen stops working if WiFi is enabled because the latter reserves the ADC2 channel. I've forked the [Adafruit Touchscreen](https://github.com/s60sc/Adafruit_TouchScreen) library to handle this.

**Comment by Bodmer** [comment]
Thanks, very clear explanation. I will add a link to the ReadMe soon.

**Comment by Bodmer** [comment]
Added link to your fork. Thanks.
