### ISSUE TITLE
Arduino IDE 2.0.3

### ISSUE THREAD

**Issue by fruktiz32** [Bodmer/TFT_eSPI#2378]
Hello, I have noticed that my program uploaded with Arduino IDE 2.0.3 does not work, device goes restart loop and screen is blank white.
And if I compile and upload with Arduino IDE 1.8.19, everything works well as before. Any ideas?

**Comment by Bodmer** [comment]
It works for me!

Maybe the board support package you are using for your processor is not compatible with the latest IDE.

Provide more information on your software and hardware environment.

**Comment by Bodmer** [comment]
If you have upgraded TFT_eSPI make sure the setup has been updated correctly.

**Comment by fruktiz32** [comment]
All good. I have updated it from v2.4.72 to v2.4.79 and now it works. Thanks!
