### ISSUE TITLE
Display only flickering

### ISSUE THREAD

**Issue by SunkenHero** [Bodmer/TFT_eSPI#2404]
1. My Display is only flickering every time i draw something on it. It happens not only with my code, i tried other examples and got the same result. It seems like the flickers comes from updating the screen and its only drawing White
2. Arduino IDE
3. TFT_eSPI library version 2.5.0
4. 2.0.6
5. ESP32
6. TFT driver ILI9341 https://www.reichelt.de/de/en/arduino-shield-8211-2-8-inch-display-touch-320-x-240-pixels-ard-shd-2-8td-p282497.html?&trstct=pol_18&nbc=1
7. 8 bit parallel

```
#include <SPI.h>
#include <TFT_eSPI.h>

TFT_eSPI tft = TFT_eSPI();

TaskHandle_t Task0;
TaskHandle_t Task1;

void setup() {
  Serial.begin(115200);

  xTaskCreatePinnedToCore(Main0, "Task0", 10000, NULL, 1, &Task0, 0);
  xTaskCreatePinnedToCore(Main1, "Task1", 10000, NULL, 1, &Task1, 1);
}

void Main0(void * Parameters){
  //Setup
  tft.init();
  tft.setRotation(1);
  Serial.println("Initilized TFT");
  for(;;){
    //Loop
    tft.fillScreen(TFT_BLACK);
    Serial.println("Filled Screen");
    delay(500);
  }
}

void Main1(void * Parameters){
  //Setup
  
  for(;;){
    //Loop
    
  }
}

void loop() {

}
```

```
Initilized TFT
Filled Screen
Filled Screen
Filled Screen
…
```

**Comment by SunkenHero** [comment]
Just a wiring issue. :D

**Comment by voxain** [comment]
Can you elaborate on what your wiring issue ultimately was? I think I might be having a similar problem but I can't pin it down.
