### ISSUE TITLE
GLCD Font does not display entire character set and crashes on ESP32

### ISSUE THREAD

**Issue by goodmandj** [Bodmer/TFT_eSPI#2409]
Hi Bodmer.
Firstly, thanks for an amazing library.
I was porting an application for the round GC9A01 TFT from AdaFruit to TFT_eSPI when it kept crashing with a small code example.
Having traced through the library I found that if you dont disable the UTF8_SWITCH the processor keeps crashing and restarting.

I was also concerned because your library excluded the first 32 chars of the GLCD font which contain useful glyphs.

I have modified the code which I would recommend making its way into your next release if you agree.

TFT_eSPI.cpp -> line 5004 area
  if (uniCode == '\n') uniCode+=22; // Make it a valid space character to stop errors
  else if **(uniCode < 32 && textfont!=1)** return 1;

TFT_eSPI.cpp -> line 3131 area
void TFT_eSPI::drawChar(int32_t x, int32_t y, uint16_t c, uint32_t color, uint32_t bg, uint8_t size)
{
  if (_vpOoB) return;

  if **(c < 32 && textfont != 1)** return;

-----------------------------------------------------------------------------------------------------------------------
Sample program to test the issue. 
With tft.setAttribute(UTF8_SWITCH, true) which for others reading this, is the default state, the application crashes.
-----------------------------------------------------------------------------------------------------------------------
#include <TFT_eSPI.h>
#include "Free_Fonts.h"

TFT_eSPI tft = TFT_eSPI(240,240);

void DrawCharacterSet()
{
tft.setTextColor(TFT_GREEN);
for (int x = 0; x < 16; x++)
  {
  tft.setCursor(60 + x * 8, 25);
  tft.print(x, 16);
  }

tft.setTextColor(TFT_BLUE);
for (int y = 0; y < 16; y++)
  {
  tft.setCursor(40, 40 + y * 10);
  tft.print(y, 16);
  }

char c = 0;
tft.setTextColor(TFT_WHITE);
for (int y = 0; y < 16; y++)
  {
  for (int x = 0; x < 16; x++)
    {
      tft.setCursor(60 + x * 8, 40 + y * 10);
      tft.print(c++);
    }
  }  
}

void setup() {
  tft.init();
  tft.setAttribute(UTF8_SWITCH, false);
  tft.setRotation(0);
  tft.fillScreen(TFT_BLACK);
  tft.setTextFont(GLCD);
  tft.setTextSize(1);
  
  DrawCharacterSet();
}

void loop() {
 }
----------------------------------------------------

David
**The crashing is the display just before it reboots**
![crashing](https://user-images.githubusercontent.com/35844622/218871544-532beee6-ca2a-4e36-8aa2-973e1bc45b1a.jpg)

**Part working is without the fix for the first 32 characters**
![part_working](https://user-images.githubusercontent.com/35844622/218871538-b21d0a77-89f5-4d0e-bdf4-077c92a17603.JPG)

**Full working is happiness**
![full_working](https://user-images.githubusercontent.com/35844622/218871542-17e73549-16df-4d2c-a5f9-291cd283a8e1.JPG)

**Comment by Bodmer** [comment]
Thanks for reporting this and identifying the root casue. I have updated the library.
