### ISSUE TITLE
No Serial1 PI PICO then using TFT_eSPI with GC9A01 round display 

### ISSUE THREAD

**Issue by chester2400** [Bodmer/TFT_eSPI#2419]
1. No Serial1 PI PICO when using TFT_eSPI with GC9A01 round display 
2. IDE
3. 2.5.0
4. Pi pico philhover 2.7.2
5. RP 2040
6. GC9A01
7. SPI
8. prototyping
9. The serial1 TX pin and Serial2 TX pin are pulled HIGH.

[Serial1_not_working.zip](https://github.com/Bodmer/TFT_eSPI/files/10772207/Serial1_not_working.zip)

[Setup61_RP2040_GC9A01.zip](https://github.com/Bodmer/TFT_eSPI/files/10772186/Setup61_RP2040_GC9A01.zip)

![IMG_4346](https://user-images.githubusercontent.com/90867475/219814580-3706c59b-ee33-4ff8-bf87-a20a4317b9b4.jpg)

**Comment by Bodmer** [comment]
Which GPIO pin are you expecting to see the Serial1 dat output on?

**Comment by chester2400** [comment]
Pin 0

**Comment by Bodmer** [comment]
The setup file allocates pin 0 to the TFT_RST and TFT_MISO signal. The pin cannot be used for both Serial1 output and the TFT signals. Change the pin in the setup and change the wiring to the TFT accordingly.
