### ISSUE TITLE
Parallel fix addes S2 twice to Kconfig, should it be S3 instead like commit message?

### ISSUE THREAD

**Issue by tyeth** [Bodmer/TFT_eSPI#2435]
Was just checking latest release notes before upgrading and saw the parallel fix commit.  #2430 
Noticed the changes said for the s3 but were done with s2 label, assuming a typo and all should be S3?
https://github.com/Bodmer/TFT_eSPI/pull/2430/commits/ad7a8aea9728aa7de0ed69037e7f7656ab85ac68#diff-7c9693e9c5e61a1d80e09769377d47bb415ec39ca5aeaa85d13581b0105d6359R239

**Comment by dracir9** [comment]
You are right, it should be S3. Sorry 😅
