### ISSUE TITLE
TFT_eSPI with WT32-SC01

### ISSUE THREAD

**Issue by leofouhy** [Bodmer/TFT_eSPI#2467]
I'm working with the WT32-SC01 board that uses the ST7796 display driver.
I have made what I believe are the correct changes to the eSPI files to get it to use Setup201_WR32_SC01.h
When I run your "Read_User_Setup.ino" program, it  shows the 9341 display driver is being used.
See attached file:
![eSPI](https://user-images.githubusercontent.com/8432624/222858539-adcc192f-6a27-4879-97b7-3490bd212293.gif)
Can you explain what files I need to edit to make this work?

Thanks for your help.

**Comment by Bodmer** [comment]
Comment out or delete this line:
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L30

Remove // at start of this line:
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L123

**Comment by leofouhy** [comment]
Fantastic. That worked. All because I hadn't commented out the line:
https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L30

Thanks for your help.
