### ISSUE TITLE
XPT2046(ILI9341) compatibility with Audio-Kit(ESP32-A1S)

### ISSUE THREAD

**Issue by KazanskiyMaks** [Bodmer/TFT_eSPI#2468]
1. Can't interact with XPT2046(ILI9341) using Audio-Kit based on ESP32-A1S. I had tried various variant of connection using described SPI pins in [this document](https://docs.ai-thinker.com/_media/esp32-a1s_specification.pdf) and the connection with script described in [this discussion](https://github.com/Bodmer/TFT_eSPI/discussions/895). In output, I'm getting only zeros (or max pressure if using XPT2046_Touchscreen). Same sketches works with ESP32 DEVKITV1(ESP32-WROOM-32).
2. Any IDE (Arduino and PlatformIO)
3. TFT_eSPI library version: 2.5.22
4. Board package version: 2.0.7
5. Processor: ESP32-A1S
6. TFT driver: ILI9341, like [this](https://www.aliexpress.com/item/1005003732763639.html)
7. Interface type: SPI

Plus further information as appropriate to the problem:
1. TFT to processor connections used: 19 (MISO->T_DO), 23 (MOSI->T_DIN), 18 (SCK->T_CLK), 22 (CS_PIN->T_CS)
2. A zip file containing my setup file: [User_Setup.zip](https://github.com/Bodmer/TFT_eSPI/files/10887887/User_Setup.zip)
3. Example sketch [(Test_Touch_Controller)](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Test%20and%20diagnostics/Test_Touch_Controller/Test_Touch_Controller.ino).
4. Screen shot pictures showing the problem: ![image](https://user-images.githubusercontent.com/45522412/222884477-6da85986-63a0-40c4-809f-1f056df910c7.png)

**Comment by Bodmer** [comment]
I assume the TFT is working and it is just the touch that is not working?

Since it works with a standard ESP32 then the library is working. This means the problem is at the hardware level  so check that against your schematic and look at the signal lines with an oscilloscope by comparing with the working setup.
