### ISSUE TITLE
drawSmoothArc does not draw over 360° on GC9A01

### ISSUE THREAD

**Issue by hansaplasst** [Bodmer/TFT_eSPI#2487]
Hi,

The drawSmoothArc function does not display the arc above 360°. 
```
tft.drawSmoothArc(120, 120, 110, 90, 330, 390, 0xFFFF, 0x0000, true);
```
![image](https://user-images.githubusercontent.com/27355296/224076739-48d30676-842e-4bef-9373-dc66da093b0b.png)

Going negative, also has some unexpected behavior.
```
tft.drawSmoothArc(120, 120, 110, 90, -30, 30, 0xFFFF, 0x0000, true);
```
![image](https://user-images.githubusercontent.com/27355296/224078537-f6d74997-5007-4b97-ac60-87ee4b56cb87.png)

Thank you for your work!

**Comment by Bodmer** [comment]
See comments here:
https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.cpp#L3968

Use drawArc or drawSmoothCirle for 360 circles.

**Comment by Bodmer** [comment]
I checked the examples and this is included in the comments already.
