### ISSUE TITLE
T-Watch V2 and readRectRGB

### ISSUE THREAD

**Issue by NDC-SC** [Bodmer/TFT_eSPI#2492]
With the TTGO T-Watch V2, the readRectRGB instruction returns values of 255 rather than the RGB values for each pixel.
The same result with a variety of screen colours.
As a check, the uint16_t val = tft->readPixel(px, py) instruction returns 65535 (which is consistent with 2^16 for 565 colour format)

The readRectRGB instruction works well with the M5Stack Core2 ESP32, to enable screen capture.

Is there a workaround for the T-Watch V2 ESP32, please ?
Thanks

**Comment by Bodmer** [comment]
It looks like the MISO pin is not connected.

The display may be configured for a half duplex  interface. Ask the vendor.

If the display is configured for half duplex then adding the following line to the setup file may work:

#define TFT_SDA_READ

**Comment by NDC-SC** [comment]
Inclusion of #define TFT_SDA_READ in the twatch2020_v2 setup file did not resolve the issue.

I built the screen image as a 240x240 Sprite and pushed the Sprite to the T-Watch screen.
With the Sprite, the readPixel instruction returned the correct 565 colour value.
However, the readRectRGB instruction still returns values of 255, irrespective of the pixel colours.

Do you know why readPixel obtains a value, while readRectRGB does not ?

**Comment by Bodmer** [comment]
In that case screen CGRAM reads are not supported by the hardware.

readRectRGB is for reading screen CGRAM, not sprites.

**Comment by NDC-SC** [comment]
Splitting the 565 value of a Sprite pixel, obtained with the readPixel instruction, into the RGB components, which are then written to the SD card, enables capture of the T-Watch V2 screen.

The TFT-eSPI library is a great asset. Thank you.
