### ISSUE TITLE
Wish List :   Example for rending PNG image to TFT Screen.

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eSPI#254]
Sometime picture from internet received by png format.
If there is an example for rending png image,
it's helpful for many usage.

Thank you.

**Comment by Bodmer** [comment]
Yes, it is on my to do list.  Decoding a png needs a lot of RAM to hold the image as it is decoded, so an ESP32 with PSRAM will be needed, this is the main reason why an Arduino library is not availabe yet.

**Comment by Andy1968T** [comment]
Now that TFT_eSPI has taken a good foot hold in LILYGO devices with LCD screens. It would be very useful to be able to render .png files. Else the driver is running the development of useful esp32 LCD based apps to be developed, down a dead end. Anyone achieved this yet? Or found a driver that can that works with an ST7789V  with .png's.This is way beyond my programming skills.

**Comment by Bodmer** [comment]
There are two working Arduino sketch examples here:
https://github.com/Bodmer/PNG_TEST_ONLY

The png decoder is part of the sketch, but I plan to create a png decoder library.

**Comment by VioletGiraffe** [comment]
Thank you for providing the example! Just want to bump this discussion - would be awesome to have it as a ready-to-use library. ESP32 is a pretty powerful SoC, often used for doing Internet stuff, and in my case I need to download and display small icons (50x50) in PNG format.

**Comment by Bodmer** [comment]
Fair enough! I have been distracted with other things. Thanks for the bump!

**Comment by JHershey69** [comment]
This is really needed right now... displaying png files from the web on the T-watch, LilyGo T-Display, et all. Just sayin' :)

**Comment by simkard69** [comment]
Hello,

Just to know if there is any update on drawing PNG files directly from files (SPIFFS and/or SD card) ?

BTW, Big thanks for the hard work already provided.

**Comment by Koxx3** [comment]
> Hello,
> 
> Just to know if there is any update on drawing PNG files directly from files (SPIFFS and/or SD card) ?
> 
> BTW, Big thanks for the hard work already provided.

+1

**Comment by Bodmer** [comment]
Examples added here:
https://github.com/Bodmer/TFT_eSPI/tree/master/examples/PNG%20Images

**Comment by Koxx3** [comment]
> Examples added here: https://github.com/Bodmer/TFT_eSPI/tree/master/examples/PNG%20Images

thanks a lot !
forgot png needed some much ram 😅
40-45K to decode.

**Comment by Bodmer** [comment]
The pngle tool is a bit more economical on memory for PNG files, but a bit slower.  I created [some sketches here](https://github.com/Bodmer/PNG_TEST_ONLY) that use it.

**Comment by Koxx3** [comment]
yes. i tested your sketches already. i am short in ram, i'll stick with gif 😅

**Comment by ruebarb** [comment]
How do you use transparency with the png? For me that is the advantage of using png vs jpg for graphics.

Thanks

I'm working with Flash_PNG

How do I use your function, where do I get the **uint16_t transparent** value?

**TFT_eSPI.h**
void     pushImage(int32_t x, int32_t y, int32_t w, int32_t h, const uint16_t *data, **uint16_t transparent**);

**PNGDec.cpp**
uint8_t PNG::getAlphaMask(PNGDRAW *pDraw, **uint8_t *pMask**, uint8_t ucThreshold)

In the png_transparency example

uint8_t ucMask[40];
png.getAlphaMask(pDraw, ucMask, 255)

**Comment by juper** [comment]
co to z apng jak nie ma przexroczystości

**Comment by Bodmer** [comment]
See example here:
https://github.com/Bodmer/TFT_eSPI/tree/master/examples/PNG%20Images/Flash_transparent_PNG

**Comment by tnetwork96** [comment]
> There are two working Arduino sketch examples here: https://github.com/Bodmer/PNG_TEST_ONLY
> 
> The png decoder is part of the sketch, but I plan to create a png decoder library.

I have tried running TFT 80x160 using your examples, but I have failed
