### ISSUE TITLE
Draw a smooth arc from 12 'o clock

### ISSUE THREAD

**Issue by bbuster2** [Bodmer/TFT_eSPI#2544]
Is there a way to draw a smooth arc from the top?

Since it starts from the bottom and can only range from 0 to 360 i have to start at 180 till 360 and after that create a new arc from 0 till 180.

With the anti-aliasing it shows a "border" at the bottom.
Is it possible to rotate just the arc by 180 degrees?

**Comment by Bodmer** [comment]
Start at 180 and end at any angle in range 0-360. 180 to 179 will be the largest arc angle. For the circle case draw 0 to 360.
