### ISSUE TITLE
Anti-aliased Clock Example is not working with Clock radius 230px

### ISSUE THREAD

**Issue by ranacse05** [Bodmer/TFT_eSPI#2548]
Hey Bodmer,

First of all, thanks a lot for TFT_eSPI library. I was trying Anti-aliased Clock example of Smooth-Graphics and I noticed if I set the clock radius  to 230px it does not work. Image attached.

To minimise effort to resolve issues the following should be provided as a minimum:
1. IDE : Arduino 
3. TFT_eSPI library version 2.5.0
4. Board package version 3.0.1
5. Procesor, ESP8266 D1 Mini
6. TFT driver ST7899 1.54" 
7. Interface type SPI

```
 #define CLOCK_R       230.0f / 2.0f // Clock face radius (float type) (Line 31)
```
![WhatsApp Image 2023-03-31 at 1 58 04 AM](https://user-images.githubusercontent.com/463825/228950915-ff9fa187-1a75-4984-a757-ce54e5b79a8a.jpeg)

```
#define CLOCK_R       130.0f / 2.0f // Clock face radius (float type) (Line 31)
```
![WhatsApp Image 2023-03-31 at 2 00 23 AM](https://user-images.githubusercontent.com/463825/228950998-77046d1e-e76d-4e14-805d-2c30a62ae1bc.jpeg)

**Comment by Bodmer** [comment]
I suspect the sprite is not created because there is insufficient RAM space available. Try a smaller size.
