### ISSUE TITLE
Add Scrolling for 1-bit sprites

### ISSUE THREAD

**Issue by Redstoned** [Bodmer/TFT_eSPI#255]
Hi,
I just wanted to scroll an 1-bit sprite but as it seem the library doesn't support it. Could You please implement it?

**Comment by Bodmer** [comment]
Adding scrolling for 1 bit Sprites is trickier than for 8 or 16 bit Sprites because in those cases memcpy could be used.

Which direction d you wish to scroll in?

**Comment by Redstoned** [comment]
All directions would be best. Are some directions easier than other to implement?

**Comment by Bodmer** [comment]
I had a look and scrolling was easy if I use pixel be pixel copying. So I have added scrolling for 1bpp Sprites and added a new example: Sprite_scroll_1bit.

1bpp Sprites are unique in that the coordinate frame can be rotated, so the example shows how this is done too.
