### ISSUE TITLE
TL_DATUM does not work correctly. 

### ISSUE THREAD

**Issue by avkv76** [Bodmer/TFT_eSPI#2583]
TL_DATUM does not work correctly. The start coordinates should be at the top left of the text. But that's not how it works. In reality, the starting coordinates are from the bottom left of the text, like BL_DATUM

tft.setTextDatum(0);

**Comment by Bodmer** [comment]
I have not seen that behaviour. Note that independant supporting font libraries like OpenFontRender or U8g2_for_TFT_eSPI etc have their own glyph rendering functions which TFT_eSPI cannot override.

Provide an example that demonstrates the problem and describe the software environment with versions.

**Comment by Bodmer** [comment]
Assumed to be resolved.
