### ISSUE TITLE
Wemos D1 R32 with 3.5" TFT LCD Shield 

### ISSUE THREAD

**Issue by vgomasjaya** [Bodmer/TFT_eSPI#2585]
I have wemos d1 r32 and 3.5" TFT LCD Shield (ILI9486)... 
After I run Read_User_Setup, I got this

```
[code]
TFT_eSPI ver = 2.5.0
Processor    = ESP32
Frequency    = 240MHz
Transactions = Yes
Interface    = Parallel
Display driver = 9341
Display width  = 240
Display height = 320

TFT_CS   = GPIO 33
TFT_DC   = GPIO 15
TFT_RST  = GPIO 32
TFT_WR   = GPIO 4
TFT_RD   = GPIO 2

TFT_D0   = GPIO 12
TFT_D1   = GPIO 13
TFT_D2   = GPIO 26
TFT_D3   = GPIO 25
TFT_D4   = GPIO 17
TFT_D5   = GPIO 16
TFT_D6   = GPIO 27
TFT_D7   = GPIO 14

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled
```

I think my LCD Driver is ILI9486, but why it's written 9341? 

I already wiring my Wemos D1 R32
- IO15 wired to IO35
- IO33 wired to IO34
- IO32 wired to IO36
- IO4 wired to IO39 (for touchscreen)

And in User_Setup_Select.h I already try to uncomment one by one
- #include <User_Setups/Setup14_ILI9341_Parallel.h>  // Setup file for the ESP32 with parallel bus TFT
- #include <User_Setups/Setup13_ILI9481_Parallel.h>  // Setup file for the ESP32 with parallel bus TFT
- #include <User_Setups/Setup11_RPi_touch_ILI9486.h> // Setup file configured for ESP32 and RPi TFT with touch

But my LCD just get white screen and nothing happen

My shield like this
![image](https://user-images.githubusercontent.com/92163440/232187046-fbc92250-a29e-4f90-88ae-5b6f57b645b5.png)

After I run TFT_ReadWrite_Test with uncomment 
`#include <User_Setups/Setup14_ILI9341_Parallel.h>  // Setup file for the ESP32 with parallel bus TFT`

The result is
```
 Pixel value written = 10
 Pixel value read    = 80
 ERROR                 ^^^^
 Pixel value written = 20
 Pixel value read    = 100
 ERROR                 ^^^^
 Pixel value written = 40
 Pixel value read    = 200
 ERROR                 ^^^^
 Pixel value written = 80
 Pixel value read    = 400
 ERROR                 ^^^^
 Pixel value written = 100
 Pixel value read    = 0
 ERROR                 ^^^^
 Pixel value written = 200
 Pixel value read    = 0
 ERROR                 ^^^^
 Pixel value written = 400
 Pixel value read    = 0
 ERROR                 ^^^^
 Pixel value written = 800
 Pixel value read    = 801
 ERROR                 ^^^^
 Pixel value written = 1000
 Pixel value read    = 1002
 ERROR                 ^^^^
 Pixel value written = 2000
 Pixel value read    = 2004
 ERROR                 ^^^^
 Pixel value written = 4000
 Pixel value read    = 4008
 ERROR                 ^^^^
 Pixel value written = 8000
 Pixel value read    = 8010
 ERROR                 ^^^^
```

But the LCD just white screen

Please help me and thank you before

**Comment by Bodmer** [comment]
It looks like you have not commented out [this line 30](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L30).

As noted in line 28: "Only ONE line below should be uncommented"

**Comment by vgomasjaya** [comment]
I've uncommented it and still get white screen... but when I use mcufriend_kbv, it works without any mod... but now the problem is the touchscreen doesn't work properly

**Comment by Bodmer** [comment]
I asked toI comment out [this line 30](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L30).

NOT uncomment it!

It should look like this:
//#include <User_Setup.h>           // Default setup is root library folder

To be clear on what you have done, post your complete User_Setup_Select.h file and the setup file you want to use as ZIP files. (Drag and drop).

**Comment by Bodmer** [comment]
Assumed resolved.
