### ISSUE TITLE
DMA is not supported in parallel mode

### ISSUE THREAD

**Issue by ea7kir** [Bodmer/TFT_eSPI#2606]
Having coded a what I think is a beautiful GUI for an audio PPM meter.

![IMG_0082](https://user-images.githubusercontent.com/84274919/234002367-2ced0584-bd18-4b19-90d9-d793bb5c4eea.jpeg)

But it is now unclear to me if it is possible to use I2S with a Lily ESP32 T-Display S3.

I have edited `User_Setup_Select.h` as follows:
```
.
.
.
//#include <User_Setup.h>           // Default setup is root library folder
.
.
.
#include <User_Setups/Setup206_LilyGo_T_Display_S3.h>
.
.
.
```
My code compiles, but with the following warnings:

```
In file included from .pio/libdeps/lilygo-t-display-s3/TFT_eSPI/TFT_eSPI.h:96,
                 from .pio/libdeps/lilygo-t-display-s3/TFT_eSPI/TFT_eSPI.cpp:16:
.pio/libdeps/lilygo-t-display-s3/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:110:3: warning: #warning >>>>------>> DMA is not supported in parallel mode [-Wcpp]
  #warning >>>>------>> DMA is not supported in parallel mode
   ^~~~~~~
.
.
.
In file included from .pio/libdeps/lilygo-t-display-s3/TFT_eSPI/TFT_eSPI.cpp:16:
.pio/libdeps/lilygo-t-display-s3/TFT_eSPI/TFT_eSPI.h:970:8: warning: #warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available! [-Wcpp]
       #warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available!
        ^~~~~~~
```
I'm not bothered about Touch, but my hope is to acquire audio from an external I2S ADC and I believe the `<driver/i2s.h>` uses DMA.

1) Am I editing `User_Setup_Select.h` correctly?
2) Is it possible to use I2S with a parallel screen?
3) If (1 && 2) where can I find an example?

**Comment by Bodmer** [comment]
The warning simply means that pixel data cannot be sent to the TFT screen using DMA. You can still use DMA for other processor interfaces.

That screen does not have touch capability, your setup file is OK since graphics display is working.
