### ISSUE TITLE
Replace hardcoded SPI pin numbers by variable/parameter?

### ISSUE THREAD

**Issue by martybillingsley** [Bodmer/TFT_eSPI#2610]
At runtime, I'd like to be able to choose which SPI pins the TFT display is plugged into. Particularly TFT_CS and TFT_DC, but flexibility on some of the other pins would also be nice. Currently these are defined in User_Setup.h and seem to be immutable after compilation.

Is there a way to use a variable or parameter instead of #define for each pin so that I can select the pins at runtime, when a new instance of TFT_eSPI is created?

**Comment by Bodmer** [comment]
The library does not support that capability and adding it is not planned.
