### ISSUE TITLE
Random block on text

### ISSUE THREAD

**Issue by Keaster20** [Bodmer/TFT_eSPI#2618]
Using a 4.0" tft with ILI9488 chip I get this random block on the last letter that is written to the screen. Does not matter is I use print or drawstring. I have never had this problem with other displays such as ili9341. If I display more text the block moves to the last character displayed.
![20230429_161814](https://user-images.githubusercontent.com/95320113/235329599-1d18cb82-1ba0-4efb-a1c7-a21187d0ce84.jpg)

**Comment by Bodmer** [comment]
Provide an exampel sketch that demonstrates the problem. Other information that is helpful to track down the reason is listed here:
https://github.com/Bodmer/TFT_eSPI/blob/master/.github/ISSUE_TEMPLATE/issue-template.md

**Comment by Bodmer** [comment]
Has this been solved?

**Comment by Bodmer** [comment]
Assumed resolved.
