### ISSUE TITLE
Code assumes Serial is always present

### ISSUE THREAD

**Issue by git2212** [Bodmer/TFT_eSPI#2645]
I have a build/configuration setup which leaves the Serial object undefined and results in link time errors for an unresolved reference to Serial. I am able to recreate the situ using VS+PlatformIO and the latest version from GIT as soon as I compile with the build flags `-D PIO_FRAMEWORK_ARDUINO_NO_USB` and `-D RP2040_PIO_SPI=1`.

The solution was to modify line 148 in TFT_eSPI_RP2040.c from

```
Serial.println("No room for PIO program!");
```
to

```
#ifdef Serial
Serial.println("No room for PIO program!");
#endif

```
Using Serial out for debug and error notifications is common, however, with the RP2040 platform in particular, one core can be used for debugging but one has to give up the USB based Serial IO as a tradeoff... about the only way to debug code specifically on some of the smaller boards which don't break out all the pins for attaching an external debugger.

Perhaps these changes could be merged into the next release?

**Comment by Bodmer** [comment]
Thanks for reporting this. That line was for development  debug and should be commented out.

I will implement optional debug messages at a future date.
