### ISSUE TITLE
Compilatino error for IFI9488

### ISSUE THREAD

**Issue by wvmarle** [Bodmer/TFT_eSPI#267]
Hi,

Just playing with your library.
It seems to work fine for my ILI9341 (compiles; ran the ellipse example), but when I wanted to try my ILI9488 it failed to compile, with this error:

Arduino: 1.8.7 (Linux), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

/home/wouter/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:4798:58: error: no 'void TFT_eSPI::writeBlock(uint16_t, uint32_t)' member function declared in class 'TFT_eSPI'
 void TFT_eSPI::writeBlock(uint16_t color, uint32_t repeat)
                                                          ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by Bodmer** [comment]
Hi,

I have fixed the problem, so if you download the latest off Github all should be OK.

Thanks for reporting this.
