### ISSUE TITLE
ST7735 wrong color

### ISSUE THREAD

**Issue by demenkovms** [Bodmer/TFT_eSPI#2718]
Hello. I use TFT_eSPI with my ESP32 in Arduino IDE, I tried display bmp but get not bright colors.

on display:
![изображение](https://github.com/Bodmer/TFT_eSPI/assets/89016279/8f41a71d-9ee0-43ef-b29e-65c74fa7808e)

in original:
![OK](https://github.com/Bodmer/TFT_eSPI/assets/89016279/33a7fdcc-7ecd-4782-ab80-9e8a399f5185)
![ERR](https://github.com/Bodmer/TFT_eSPI/assets/89016279/a1b4156c-b117-4210-81f0-e2b065a23038)

I thought that trouble was in img convert, but I try jpg from example and get the same result:

![изображение](https://github.com/Bodmer/TFT_eSPI/assets/89016279/dc5b5fec-31e2-49e2-b9ff-5a95549ad8ca)

I use ST7735 display [(https://www.aliexpress.com/item/1005004565692996.html?spm=a2g0o.order_list.order_list_main.162.6e921802MyEB6N)](https://www.aliexpress.com/item/1005004565692996.html?spm=a2g0o.order_list.order_list_main.162.6e921802MyEB6N)

![изображение](https://github.com/Bodmer/TFT_eSPI/assets/89016279/7ee2c05a-4853-4530-b0ce-9e821e234630)

and my Setup.h:
```
#define ST7735_DRIVER

#define ST7735_REDTAB

#define TFT_WIDTH  320
#define TFT_HEIGHT 240

#define TFT_RGB_ORDER TFT_RGB


#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   15  // Chip select control pin
#define TFT_DC    2  // Data Command control pin
#define TFT_RST   4  // Reset pin (could connect to RST pin)


#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

#define SMOOTH_FONT


#define SPI_FREQUENCY  40000000
```

Can you help what is wrong? Thanks!

**Comment by Bodmer** [comment]
That display is not an ST7735 type. The vendors page title is only correct for one of the listed display options. It looks like you have selected and bought the ILI9341 display, check which one you bought, try the ILI9341 driver.

**Comment by Bodmer** [comment]
Also try ST7789 driver.

**Comment by Bodmer** [comment]
Assumed resolved.
