### ISSUE TITLE
Bug with DMA writes on ESP32-S3 for large transactions: `setSwapBytes()` ignored during part of the transfer. 

### ISSUE THREAD

**Issue by vindar** [Bodmer/TFT_eSPI#2725]
Hi, 

I think I have found a bug when the driver performs large DMA updates on an ESP32-S3. When the transfer is larger than (around) 32768 bytes, the `setSwapBytes()` command is ignored for during part of the transfer. I guess that large transfers are broken into chunks and for some reason, the 'swap byte' flag does apply to all the chunks... 

My setup:

- Arduino 2.1.1
- TFT_eSPI 2.5.30
- ESP32-S3 
- (red) ILI9341 display with MOSI(35), SCK(36),  MISO(37), CS(8), DC(15),  RST(14)

The following sketch illustrates the issue: 

```
#include <TFT_eSPI.h>

TFT_eSPI tft = TFT_eSPI();

#define SLX 200  // the bug does not occurs if SLX*SLY < 326768 ? 
#define SLY 200  // for instance 160x100 is ok...

uint16_t sprite[SLX*SLY]; // sprite of size SLY*SLY

void setup()
  {
  // initialize the screen driver
  tft.init();
  tft.setRotation(0);
  tft.setSwapBytes(true);
  tft.fillScreen(TFT_BLACK);
  tft.initDMA();

  // the sprite is set completely blue
  for(int i=0; i< SLX*SLY; i++) sprite[i] = 31; // 31 = blue 

  // draw the sprite using DMA
  tft.startWrite();
  tft.pushImageDMA(0, 0, SLX, SLY, sprite);
  tft.dmaWait(); 
  }


void loop()
  { // nothing
  }
```

One expects a blue rectangle drawn to be drawn on the screen but half of it is green as shown in the picture below: 

![bug](https://github.com/Bodmer/TFT_eSPI/assets/12938966/25dae530-d5d8-4477-9822-434ccfb57fd6)

The problem disappears if `setSwapBytes()` is set to false or if the buffer size is small enough...

**Comment by Bodmer** [comment]
Thanks for reporting this, I will investigate.
