### ISSUE TITLE
Text not refreshing between loops and overprints itself

### ISSUE THREAD

**Issue by tmargot** [Bodmer/TFT_eSPI#2728]
Hi,
I have tried using tft.println() and tft.drawString() and both seem to overprint each loop. It basically print 0,1,2 and then all the 7 segment font shows as a solid 8. (see screenshots). If the whole screen is refreshed (tft.fillScreen(mainBgColor)) then this does not happen. Any ideas? I have new wiring and all seems to be in order. 

![2023-07-03_22-58-35](https://github.com/Bodmer/TFT_eSPI/assets/5753762/482bb681-621a-456a-94ad-5b3ea5050f19)

2. IDE: PlatformIO
3. TFT_eSPI library version: 2.5.31
5. Procesor: ESP32 WROOM (ESP32 Dev board - https://www.aliexpress.com/item/1005004511592758.html)
6. TFT driver: ILI9488 (https://www.aliexpress.com/item/1005003033841623.html)
7. Interface type: SPI

My very basic script:
```#include <Arduino.h>
#include <SPI.h>
#include <TFT_eSPI.h> // Hardware-specific library

TFT_eSPI tft = TFT_eSPI();       // Invoke custom library
int16_t mainBgColor = TFT_BLACK;
int16_t incr;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  tft.setRotation(1);
  tft.init();
  tft.fillScreen(mainBgColor);
}

void loop() {

  tft.setCursor(0, 0, 2); 
  tft.setTextColor(TFT_WHITE,TFT_BLACK);  tft.setTextSize(1);
  tft.println("Hello World!");
  tft.setTextColor(TFT_YELLOW); //tft.setTextFont(7);
  tft.drawString(String(incr),0,20,7);
  incr++;

  delay(500);
}
```

My Platformio.ini file:
```[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = bodmer/TFT_eSPI@^2.5.31
monitor_speed=115200

build_flags =
  -Os
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DUSER_SETUP_LOADED=1
  
  ; Define the TFT driver, pins etc here:
  -DILI9488_DRIVER=1
  -DTFT_WIDTH=320
  -DTFT_HEIGHT=480
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=16
  -DTFT_RST=4
  -DTFT_BL=27
  -DTFT_BACKLIGHT_ON=HIGH
  ;-DTOUCH_CS=22
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_FONT6=1
  -DLOAD_FONT7=1
  -DLOAD_FONT8=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1
  -DSPI_FREQUENCY=27000000
```

**Comment by Bodmer** [comment]
The behaviour is  correct when a background colour is not specified, try:
```
tft.setTextColor(TFT_YELLOW, TFT_BLACK);
tft.drawString(String(incr),0,20,7);
```
