### ISSUE TITLE
25% offset on tft clock

### ISSUE THREAD

**Issue by jmartens2** [Bodmer/TFT_eSPI#273]
hi i always loved your work. im trying to get the tft_clock to move over 25% of the screen. 
ive been editing to get my st7789 to get set up but i cant figure out how to offset.
i see the clock on 75% of the screen the other 25 is pixelated dots

**Comment by Bodmer** [comment]
Invert the colours has two possible meanings to me..

To swap blue and red use the [setup file options](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h#L38).

To invert all colour bits use:
tft.invertDisplay(true);  // or false for no inversion

**Comment by jmartens2** [comment]
Thank you. I’ve always enjoyed your work! Thank you for all your hard work and time. I’d like to buy you a beer someday!

**Comment by Bodmer** [comment]
Thanks for the feedback. If you have any more questions then I will try to help.
