### ISSUE TITLE
error value computed is not used *ptr++; while compiling 

### ISSUE THREAD

**Issue by atc1441** [Bodmer/TFT_eSPI#276]
Hi, i am on android 1.8.7 and get the error value computed is not used for 

TFT_eSPI.cpp:1395:15: *ptr++; and

TFT_eSPI.cpp:1246:15: *ptr++;

when i remove the star it compiles without error. 

what could be the reason for it? i try using an st7789 display

**Comment by Bodmer** [comment]
Thanks for reporting. It is fixed now.
