### ISSUE TITLE
ili9486 color error.

### ISSUE THREAD

**Issue by acer1204** [Bodmer/TFT_eSPI#2773]
i use user_setup.h to config ili9486 in this tft lcd.
http://www.lcdwiki.com/4.0inch_SPI_Module_ILI9486
the color has some problem.
how to fix it?
It looks like 16bit 18bit problem?
but when i define RPI_DISPLAY_TYPE, the tftlcde will show a white screen.
my board is esp32u.
![IMG_20230730_222928](https://github.com/Bodmer/TFT_eSPI/assets/6522774/88a4a6ca-2caf-4aec-b9e6-f64177372b76)

**Comment by Bodmer** [comment]
Do not use RPI_DISPLAY_TYPE, it will not work.

Run the colour test example to see if red and blue are swapped.

**Comment by acer1204** [comment]
> Do not use RPI_DISPLAY_TYPE, it will not work.
> 
> Run the colour test example to see if red and blue are swapped.

Which example is the color test?

**Comment by Bodmer** [comment]
It is an example, see [here](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Test%20and%20diagnostics/Colour_Test).

**Comment by Bodmer** [comment]
Assumed resolved.
