### ISSUE TITLE
Hii iam try to pair esp32 to ILI9486 8bit parallel display with touch but iam facing this error =    Touch functions not supported in 8/16 bit parallel mode or with RP2040 PIO.        #error >>>>------>> Touch functions not supported in 8/16 bit parallel mode or with RP2040 PIO

### ISSUE THREAD

**Issue by DhirajDSD** [Bodmer/TFT_eSPI#2775]
Hii iam try to pair esp32 to ILI9486 8bit parallel display with touch but iam facing this error = Touch functions not supported in 8/16 bit parallel mode or with RP2040 PIO. #error >>>>------>> Touch functions not supported in 8/16 bit parallel mode or with RP2040 PIO

**Comment by Bodmer** [comment]
The library does not support touch functions in parallel mode.

If you have a SPI, I2C or resistance based touch screen then another library will be required. The touch library selected must support the touch controller fitted and the touch controller interface (SPI, I2C or resistance measurement).

**Comment by DhirajDSD** [comment]
How can we include seperate library for 8-bit parallel

**Comment by Bodmer** [comment]
Yes, use a separate library. You are likely to find an Arduino library for your touch controller with a Google search.

**Comment by LazaroFilm** [comment]
How do we make the external library communicate with TFT_eSPI? is are there certain function calls or expected returns necessary?

**Comment by Bodmer** [comment]
No library linking is required.  Checking for touch and the drawing the graphics are all done in the sketch.

**Comment by DhirajDSD** [comment]
hii bodmer how to link <TouchScreen.h> to <TFT_eSPI.h> if any example code available please share me

**Comment by LazaroFilm** [comment]
I realized that tft_eSPI actually doesn't need any touchpad input. You would write that in your code and update your display accordingly. If you want your GUI to be reactive Yoo can try LVGL. It creates widgets you can use and apply. LVGL does have a function it ads you it's boilerplate to read your touchscreen inputs.

**Comment by DhirajDSD** [comment]
> No library linking is required. Checking for touch and the drawing the graphics are all done in the sketch.

Thanks Bodmer, I have successfully linked together "Touch Screen.h" and <TFT_eSPI.h> and Touch is working properly

**Comment by DhirajDSD** [comment]
but it is possible to work touch on squareline studio using  "Touch Screen.h" and <TFT_eSPI.h>

**Comment by Bodmer** [comment]
I am not familiar with squareline studio so am unable to help.

**Comment by morsteevo** [comment]
can you share your code with how you got this working? please
