### ISSUE TITLE
Sprite drawChar causes excessively eager clipping when characters are drawn near the bottom of a sprite.

### ISSUE THREAD

**Issue by Nullaccount** [Bodmer/TFT_eSPI#2793]
The Y clipping logic in the sprite drawChar causes premature clipping. As soon as any freefont is drawn to a sprite where the bottom extent of the character could be below the bottom of the sprite, then the whole character is clipped (but the background is still drawn).

Does not affect classic built-in fonts.

Was working on a sprite tiling setup and didn't have any issues with clipping at `Y<0`, but **any** `Y` that puts any portion of a freefont below the `vpH-ydatum` will instantly clip the full character, effectively causing the whole string to disappear.

So far just removing the early Y check linked below below resolved the issue. I've confirmed that removing the check linked below has resolved my issue.
https://github.com/Bodmer/TFT_eSPI/blob/5c1f163b05a85d747fcb0088863ace6b816fa456/Extensions/Sprite.cpp#L1989

Reproduction: Print any freefont string/character near the "bottom" of a sprite. As long as the character has any overlap with the max Y then the whole character will clip. drawString functions pre-draw the background before the drawChar early return, so the block of BG still appears without any characters.

```
sprite.createSprite(100,100);
sprite.setFreeFont(ANY_FREE_FONT);
sprite.drawString("string", 10, 97);
sprite.pushSprite(0, 0);
```

**Comment by Bodmer** [comment]
Thanks for raising this and finding the problem, it is now fixed in the master.

The problem occured because the character datum for GFX free fonts is normally bottom left. whereas for other character fonts it is top left.
