### ISSUE TITLE
Seeed XIAO RP2040 & ILI9341 Touch not working

### ISSUE THREAD

**Issue by dslocum** [Bodmer/TFT_eSPI#2803]
I have a Seeed XIAO RP2040 with the these connections.  
---
T_DO  -> MISO pin (e.g. TFT_MISO)
T_DIN -> MOSI pin (e.g. TFT_MOSI)
T_CS  -> pin of you choice specified in setup file as TOUCH_CS
T_CLK -> SCLK pin (e,g, TFT_SCLK)
T_IRQ -> not connected
---
The display works fine with any of the demos I've tried, but I can't get any touch examples to run.

I'm currently using Test_Touch_Controller.ino and the Serial monitor shows all 3 parameters = "0".  On a o'scope there are reasonable signals on the pins and I even get outputs on the MISO line that appear to have data changing as I move my finger / stylus.
![Screenshot 2023-08-19 131823](https://github.com/Bodmer/TFT_eSPI/assets/16817473/db4359b5-e3cf-4af2-87dd-091bb9f01f69)

Anything else I could look for?

_Originally posted by @dslocum in https://github.com/Bodmer/TFT_eSPI/discussions/2230#discussioncomment-6769564_

**Comment by Bodmer** [comment]
I am guessing you are trying to use the PIO based SPI interface which does not support SPI reads. See here:

https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup61_RP2040_ILI9341_PIO_SPI.h#L7-L11

Make sure line 11 is commented out.

**Comment by Bodmer** [comment]
Asumed resolved.
