### ISSUE TITLE
Sprite Creation

### ISSUE THREAD

**Issue by chrisgwgreen** [Bodmer/TFT_eSPI#2805]
1. A description of the problem and the conditions that cause it to occur
- When Creating a sprite, adding a 4th `createSprite` breaks and renders a black screen.
2. IDE (e.g. Arduino or PlatformIO)
- PlatformIO
3. TFT_eSPI library version 
- 2.5.31
4. Board package version (e.g. 2.0.3) available from the Boards Manager
- ESP32 WROOM 32
5. Procesor, e.g RP2040, ESP32 S3 etc
- ESP32
6. TFT driver (e.g. ILI9341), a link to the vendors product web page is useful too.
- GC9A01_DRIVER
7. Interface type (SPI or parallel)
- SPI

Everything works great (and thanks for a great lib) but if I add a 4th sprite (i.e. uncomment `// z.createSprite(120, 240); <----`) it just renders a black screen. I've dug around in the docs but feel this could be a bug or at least not obvious to resolve.

Code:

```
#define SCREEN_ONE 18
#define SCREEN_TWO 21

#include "Display.h"

TFT_eSPI tft = TFT_eSPI();
TFT_eSprite x = TFT_eSprite(&tft);
TFT_eSprite y = TFT_eSprite(&tft);
TFT_eSprite z = TFT_eSprite(&tft);
TFT_eSprite bg = TFT_eSprite(&tft);

int i = 0;

int rotation = 0;

void displaySetup()
{
  Serial.println("Display SETUP");

  pinMode(SCREEN_ONE, OUTPUT);
  pinMode(SCREEN_TWO, OUTPUT);

  digitalWrite(SCREEN_ONE, LOW);
  digitalWrite(SCREEN_TWO, LOW);

  tft.init();
  tft.setSwapBytes(true);
  tft.fillScreen(TFT_BLACK);
  tft.setPivot(120, 120);

  x.setAttribute(PSRAM_ENABLE, false);
  y.setAttribute(PSRAM_ENABLE, false);
  z.setAttribute(PSRAM_ENABLE, false);

  x.createSprite(120, 240);
  y.createSprite(120, 240);
  // z.createSprite(120, 240); <----
  bg.createSprite(238, 238);

  x.setPivot(120, 120);
  y.setPivot(120, 120);
  // z.setPivot(120, 120);

  x.fillSprite(TFT_BLACK);
  y.fillSprite(TFT_PINK);
  // z.fillSprite(TFT_WHITE);

  digitalWrite(SCREEN_ONE, HIGH);
  digitalWrite(SCREEN_TWO, HIGH);
}

void eyesLoop()
{
  digitalWrite(SCREEN_ONE, LOW);

  bg.fillSprite(TFT_GREEN);

  x.pushRotated(&bg, rotation + 10);
  y.pushRotated(&bg, -rotation);

  bg.pushSprite(1, 1);

  rotation++;

  if (rotation == 360)
    rotation = 0;

  digitalWrite(SCREEN_ONE, HIGH);
}
```

**Comment by Bodmer** [comment]
You are not using PSRAM for sprites x,y,z so the ESP32 has run out of memory during sprite creation.

Use lines:
 x.setAttribute(PSRAM_ENABLE, true);

etc.
