### ISSUE TITLE
1.8' ST7735S TFT always shows the white screen with STM32Duino

### ISSUE THREAD

**Issue by ericzhang-debug** [Bodmer/TFT_eSPI#2818]
Hello,
I tried to run all of the examples provided but none of them could run successfully ,which always showed a white screen.
I think the TFT hardware is ok because it was bought newly .
I want to knwo how to solve it.
Also I want to knwo whether the TFT should be connected to the board using the hardware SPI strictly? Can I use any other pin (Software SPI) just to modify the UserScript.h in stm32duino?

![image](https://github.com/Bodmer/TFT_eSPI/assets/71204348/969173af-0efb-4855-80ed-0a52fdbb381a)
My TFT is 1.8' (128*160) with ST7735S. 
![image](https://github.com/Bodmer/TFT_eSPI/assets/71204348/d407eaad-2f82-4801-8e5b-47fe4177583e)
![image](https://github.com/Bodmer/TFT_eSPI/assets/71204348/ad177795-1c61-4555-832e-b2c8fa0df33d)
My platform is Arduino IDE2.1.1, STM32Duino 2.4.0, TFT_eSPI 2.5.0.
My chip is STM32F103C8T6 (BluePill). 

Connection:
| STM32 | TFT |
| --- | --- |
| PB5 | SDA |
| PA4 | SCL |
| PA6 | DC |
| PA4 | CS |
| PA3 | RST |
| PA2 | BLK |
| 3V3 | VDD |
| G | GND |

chip:
![image](https://github.com/Bodmer/TFT_eSPI/assets/71204348/281d46ce-5979-4a26-a492-40dc5db66ac3)

UserScript.h:
```cpp
#define USER_SETUP_INFO "User_Setup"
#define ST7735_DRIVER
#define TFT_WIDTH  128
#define TFT_HEIGHT 160
#define ST7735_REDTAB
#define TFT_MOSI    PB5     //SDA
#define TFT_SCLK    PB3
#define TFT_CS      PA4
#define TFT_DC      PA6
#define TFT_RST     PA3
#define TFT_BL      PA2
#define LOAD_GLCD   
#define LOAD_FONT2  
#define LOAD_FONT4  
#define LOAD_FONT6  
#define LOAD_FONT7  
#define LOAD_FONT8  
#define LOAD_GFXFF  
#define SMOOTH_FONT
#define SPI_FREQUENCY  27000000
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY  2500000
```
Thank you very much!

**Comment by thuvasooriya** [comment]
Hi would you care to tell me what did you do?, I'm facing the same issue. I couldn't get the display working. just white screen.
