### ISSUE TITLE
'class TFT_eSPI' has no member named 'getTouch'

### ISSUE THREAD

**Issue by yoroboticscolombia** [Bodmer/TFT_eSPI#2824]
Hi, Im using the library in arduino ide, however I get the error> 
'class TFT_eSPI' has no member named 'getTouch'
I uncommented the line #define TOUCH_CS 21 , in usersetup.h, any ideas why it keeps happening, 

board esp32.
driver ili9341.
display 2.8inch
I tried evertything, with no success. appreciate your help.

**Comment by Bodmer** [comment]
Run the Read_User_Setup sketch and look at the serial output to verify the touch pin is listed.

**Comment by yoroboticscolombia** [comment]
Hi, thanks, the touch pin is not listed, see: 

![image](https://github.com/Bodmer/TFT_eSPI/assets/62781222/59890db5-f0a0-4117-97ff-b55eee71c03a)

**Comment by Bodmer** [comment]
Check User_Setup_Select.h is only calling up one setup file and it is the correct one.

**Comment by yoroboticscolombia** [comment]
well, I was able to compile, by adding #define TOUCH_CS 21, inside every driver setup, and it worked, maybe you should update the library.  also, do you know if st7735 has lower resolution than ili9341?

I get it in the display, since ili9341, is cut, but i tried setting rotation and did not work, thanks.

![image](https://github.com/Bodmer/TFT_eSPI/assets/62781222/75432f3e-4f41-408f-97c8-cbf0a0f5ea93)

**Comment by Bodmer** [comment]
There is a problem somewhere in your setup path.

Adding #define TOUCH_CS 21 inside every driver setup is not needed or desirable normally.

Check User_Setup_Select.h is only calling up ONE setup file and it is the correct one.

Since you have it working I will close.
