### ISSUE TITLE
White square graphics artifacts where the pointer moved in the animated dial example on GC9A01 with an ESP32 DOIT board. 

### ISSUE THREAD

**Issue by 01GOD** [Bodmer/TFT_eSPI#2840]
-Using User_setup 46 (the ESP32 SPI config for GC9A01) there were White square graphics artifact trails on the pointer in the animated dial example on GC9A01 with an ESP32 DOIT board. 
-IDE: Arduino 
-TFT_eSPI library version: 2.5.0
-ESP32 WROOM 32
-GC9A01
-SPI

**Comment by Bodmer** [comment]
The sketch requires a display that permits pixel reads. The GC9A01 cannot be read.
