### ISSUE TITLE
How to convert the Matrix example to horizontal display?

### ISSUE THREAD

**Issue by VictorTagayun** [Bodmer/TFT_eSPI#285]
Hello, I am quite noob on programming.
How to convert the Matrix example to horizontal display?
Rotation alone does not make it same between vertical and horizontal.

**Comment by Bodmer** [comment]
The matrix example makes use of a hardware scrolling feature built into the display, this feature only works in portrait orientation.

**Comment by VictorTagayun** [comment]
Thanks for the info.
