### ISSUE TITLE
Image incomplete and pixelation when using TFT_eSPI with ST7796 SD ESP32

### ISSUE THREAD

**Issue by Jc096** [Bodmer/TFT_eSPI#2864]
Using the SPI TFT ST7796 screen and the TFT_eSPI library to project an image with the SD card, the image comes out incomplete and pixelated, the diode that generates the fault in that screen model has already been removed but the fault continues the same, I add photos and evidence of the error, I would greatly appreciate your help.
the configuration of the connection pins is the following:

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS 22 // Chip select control pin
#define TFT_DC 4 // Data Command control pin
#define TFT_RST 17 // Reset pin (could connect to RST pin)

Author suggested setting:
 tft.init()
if(!SD.begin(22, tft.getSPIinstance())){
    Serial.println("Card Mount Failed");
    return;
}

https://github.com/Bodmer/TFT_eSPI/assets/143748869/c410e7dd-2e62-4401-917f-9a7cd4e3cee6

![falla 3](https://github.com/Bodmer/TFT_eSPI/assets/143748869/c3435f55-d56b-4e21-805e-d6c3fee4bc8b)

https://github.com/Bodmer/TFT_eSPI/assets/143748869/160c4fa1-3bf2-4de7-b8a7-fa0ea21845b2

https://github.com/Bodmer/TFT_eSPI/assets/143748869/a0049097-3a91-4a99-ad8e-5d78089f66c9

[PROYECTO.zip](https://github.com/Bodmer/TFT_eSPI/files/12731611/PROYECTO.zip)

but this did not solve the error, I attach evidence

**Comment by Bodmer** [comment]
I have run the sketch with the image files provided, these were loaded on a 8GB SDHC card. The only chagne I mage to the sketch was to make the SD card CS GPIO 26 as that is how my PCB is wired.

All images loaded without error.

I set the sketch to loop continuously with those 3 images used in the sketch and no problems have been seen.

Suggestions:
1. Shorten the SPI lines to the SD interface
2. Check the back of th display for series resistors in the SD signal lines, these should be no more than 1K Ohm
3. Try another SD card, some cards do not like the series resistors (which are there to drop 5V logic levels only)
4. Run som SD linbrary examples to verify you have a reliable high rate interface to the SD card
5. Try dropping the SPI speed to the SD card to 1MHz:
       SD.begin(26, tft.getSPIinstance(), 1000000);

Unfortunately there is little more I can do as it works fine for me. 

My setup:

- Arduino IDE
- ESP32 board package 2.0.13
- ILI9488 display with onboard SD card slot (1K series resistors)
- 8GB SDHC card
- Default 4MHz SD card interface speed

Connections used:
```
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   15  // Chip select control pin
#define TFT_DC    2  // Data Command control pin
#define TFT_RST   4  // Reset pin (could connect to RST pin)

#define TOUCH_CS 21     // Chip select pin (T_CS) of touch screen

and SD CS on GPIO 26
```

Example serial output:
```
SD Card Type: SDHC
SD Card Size: 7600MB
initialisation done.
===========================
Drawing file: /tropical.jpg
===========================
JPEG image info
===============
Width      :480
Height     :320
Components :1
MCU / row  :30
MCU / col  :20
Scan type  :4
MCU width  :16
MCU height :16
===============

 JPEG drawn in 686 ms 
===========================
Drawing file: /Baboon40.jpg
===========================
JPEG image info
===============
Width      :320
Height     :480
Components :1
MCU / row  :20
MCU / col  :30
Scan type  :4
MCU width  :16
MCU height :16
===============

 JPEG drawn in 749 ms 
===========================
Drawing file: /lena20k.jpg
===========================
JPEG image info
===============
Width      :320
Height     :480
Components :1
MCU / row  :20
MCU / col  :30
Scan type  :4
MCU width  :16
MCU height :16
===============

 JPEG drawn in 717 ms 

```
