### ISSUE TITLE
textWidth() with linebreak

### ISSUE THREAD

**Issue by bbuster2** [Bodmer/TFT_eSPI#2878]
I am using the "textWidth()" function to check the width of the text I want to show on the display so I can calculate the center of the text.

This works good but I noticed that when I use \n in the text (linebreak), the textWidth() function doesn't calculate this but the text is printed in multiple line.

Example output:

```
  Serial.begin(115200);
  tft.init();
  int width = tft.textWidth("test\ntext");
```

Is this normal behaviour or a bug?

**Comment by Bodmer** [comment]
This is expected behaviour. The function ignores control characters.

There are no plans to change this behaviour at the moment, so this will need to be handled in the sketch.
