### ISSUE TITLE
drawJpeg() in Sprite draws white vertical lines instead full image data

### ISSUE THREAD

**Issue by JavierPascual** [Bodmer/TFT_eSPI#289]
If I draw a JPEG image directly in the display all is OK (red heart):

`this->lcd.drawJpeg("/heart.jpg", 0, 0);`

But when I draw to a Sprite, and after I push the sprite to lcd, the result its terrible (red heart with white vertical lines):

```
this->lcd.drawJpeg("/heart.jpg", 0, 0, sprite);
sprite.pushSprite(0, 0);
```

The color depth is 8: setColorDepth(8) and the size is 320x240;

Display driver is ILI9341, and all drawing functions its going OK.

**Comment by JavierPascual** [comment]
![img_2745](https://user-images.githubusercontent.com/207247/51432553-d5f7a100-1c39-11e9-9798-ed8804029972.jpeg)
![img_2746](https://user-images.githubusercontent.com/207247/51432554-d5f7a100-1c39-11e9-9a37-00e7e10cbe23.jpeg)

**Comment by Bodmer** [comment]
Thanks for reporting this. I am not able to investigate this for a few days but will soon.

Does the Rotated_Sprite_3 example work for you? That example also plots a jpeg in a Sprite.

**Comment by JavierPascual** [comment]
Yes, your sample runs good for me!!

Then, when I try with next sprite size all is ok:

`this->buffer->createSprite(237, 240);`

But with 1 pixel more, sprite is not drawed in screen:

`this->buffer->createSprite(238, 240);`

And, with big sizes, the sprite is drawed with vertical white lines:

`this->buffer->createSprite(320, 240);`

**Comment by Bodmer** [comment]
You may be running out of memory (RAM) as decoding a jpeg into a 240x240 Sprite will require around 60kbytes.
I am guessing you are using an ESP32, since the heart symbol image is smaller than the screen you could crop it to the minimum bounding box using a program like MS Paint, then a smaller Sprite can be used.

I will investigate further when I can in the next few days.

**Comment by JavierPascual** [comment]
Thank you very much, Bodmer!! Your work is incredible! 🥇

**Comment by Bodmer** [comment]
I found a bug and have corrected it.

Thanks for reporting this problem.

**Comment by JavierPascual** [comment]
Hi @Bodmer!!

I've doing more tests and with some little JPEG files, I'm seeing new artifacts in screen on the right side of the images. I'm loading and painting it with:

`lcd_fx.drawJpeg("/heart.jpg", x, v, _buffer_sprite);`

Some real examples here, in a ILI9341 320x240 display:

![IMG_3479](https://user-images.githubusercontent.com/207247/57439932-5a048180-7247-11e9-9c6c-5b6de8b3e482.jpeg)
![heart_failed](https://user-images.githubusercontent.com/207247/57440158-c67f8080-7247-11e9-8ca0-770833ef3b09.jpg)
![logo_failed](https://user-images.githubusercontent.com/207247/57440159-c67f8080-7247-11e9-8516-5db7223e3427.jpg)

**Comment by JavierPascual** [comment]
And thanks a lot!!! :-) :-) :-)
