### ISSUE TITLE
gc9503v display driver compatibility?

### ISSUE THREAD

**Issue by tomayr** [Bodmer/TFT_eSPI#2891]
Good day,
Is there any home in the future on gc9503v compatibility?
It's compatible with the Arduino_GFX library but would love to see this compatible here so it can be used with ESPHome_LVGL or the like.

**Comment by Bodmer** [comment]
I think that display required realtime updates of the screen continuously via parallel port DMA.  The ESP32 S3 could do that but there are no plans to add that capability to this library.  You should find alternative screens that could be used.
