### ISSUE TITLE
Tearing Effect GC9A01

### ISSUE THREAD

**Issue by yunusemreucan** [Bodmer/TFT_eSPI#2906]
Hello

I have GC9A01 round 1.28 parallel LCD and ESP32-16MB Wrover module.
All connections are true and healthly.
But ı changes images fast and i see tearing effect.
How use TE pin signal for TFT_eSPI library 
Thanks.

**Comment by yunusemreucan** [comment]
I think this function to be "inline void TFT_eSPI::begin_tft_write(void)" 
Is it true ?

**Comment by Bodmer** [comment]
The library does not support the TE line.

Check you code is not causing the problem, i.e repeated screen clearing before updates making it appear to tear.

Use sprites as a screen buffer if updates are complex.
