### ISSUE TITLE
SSD1963 JPG IMAGE PROBLEM

### ISSUE THREAD

**Issue by nodoubtman** [Bodmer/TFT_eSPI#2922]
Hello. I have got a new display to play with it is the SSD1963.
I tried the example JPEGDecoder library LittleFS From the web.
And the sd card example from TJpg_Decoder.

Same effect, the jpg is in very low resolution, comparing if i take the ili9488 smaller screen.

Is it normal?
What can i do to normalize the resolution of the jpg ?

Thank You.
Marc.

**Comment by Bodmer** [comment]
The libraries do not limit the jpg image x,y pixel size. You can create jpeg files that have the resolution you want using programs like GIMP or MS Paint etc.

The examples just include jpegs for common screen sizes.
