### ISSUE TITLE
Board Manager esp8266 version above 2.4.1 & issues with unicode/utf-8

### ISSUE THREAD

**Issue by ismaelit** [Bodmer/TFT_eSPI#293]
When I use a boards manager version of the Arduino IDE for esp8266 higher than 2.4.1, I have problems with the use of unicode / utf-8 characters, they simply are not printed on the screen, and no characters are printed after the special character.

Does the TFT_eSPI library suggest the use of version 2.4.1 even, or can this be a local problem of mine? I tried on two different computers, and so it did.

Using board Wemos D1 Mini. 

![screen shot 2019-01-21 at 15 10 11](https://user-images.githubusercontent.com/6721120/51489324-1288e100-1d8f-11e9-85a9-074024cbf1c5.png)

**Comment by Bodmer** [comment]
I am using 2.4.2 and it is working OK.

There is a bug in some versions of the Arduino IDE which fails to compile the correct Unicode values unless the sketch is saved first. One way to ensure this happens automatically is to tick the "Preferences" box "Save when verifying and uploading".

Run the Unicode_Test sketch, make sure the fonts have been uploaded to SPIFFS, with this example you can check the Serial Monitor output reports font files are found.

If your own sketch does not work post the entire sketch and font file so I can test and debug for you.

**Comment by Bodmer** [comment]
I have just run the sketch and I see lines 135 and 138 do not print to screen.

I will investigate.

Thanks for reporting this.

**Comment by Bodmer** [comment]
You are right, there is a bug in the ESP8266 board package 2.4.2 and later which fails to build Unicode values into a string.

I cannot fix this in the library so please use **ESP8266 board core version 2.4.1** until the core developers have fixed the issue.  I will report it.

Thanks for pointing out this issue.

**Comment by Bodmer** [comment]
OK, I have tracked this down to the TFT_eSPI library, the way the print stream is handled has changed.

It is now fixed. Thanks for reporting this.
