### ISSUE TITLE
Compile error @readAddrWindow for ESP32

### ISSUE THREAD

**Issue by LaKoBlue** [Bodmer/TFT_eSPI#295]
Hi I'm getting a compile error on using the lib for ESP32.
Seems that there must be a change on readAddrWindow in the ESP32 variant similar to the ESP8266.

I changed lines 2995++ to 
#ifdef CGRAM_OFFSET
  x**s**+=colstart;
  x**e**+=colstart;
  y**s**+=rowstart;
  y**e**+=rowstart;
#endif

and everything worked

**Comment by Bodmer** [comment]
Thanks you for pointing out the problem and the fix, it is very helpful.

I have corrected the code.
