### ISSUE TITLE
esp32-s3 crash with 1.9" but not crash with 2.8" when use xTaskCreatePinnedToCore

### ISSUE THREAD

**Issue by taoloo897** [Bodmer/TFT_eSPI#2961]
Hi again
Two esp32_s3 boards with the same ino (ony user_setup is modified for lcd-s)
1 is 1.9lcd https://www.aliexpress.com/item/1005005951347460.html?spm=a2g0o.order_list.order_list_main.13.21ef1802v1yiy9
2 is 2.8" https://www.aliexpress.com/item/1005005187357655.html?spm=a2g0o.order_list.order_list_main.24.6c2e1802lMZOyc

With first one 1.9 lcd i have a crash (the board reboot) if i put in xTaskCreatePinnedToCore task something to display on lcd.
This is error (i think the task is not terminated and in loop i display something on tft)

assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())

Backtrace: 0x4037792a:0x3fcee850 0x4037b0b1:0x3fcee870 0x4038085d:0x3fcee890 0x4037b8df:0x3fcee9c0 0x4201cfbd:0x3fceea00 0x4200a921:0x3fceea20 0x42006b15:0x3fceea40 0x42008526:0x3fceea80 0x420024a3:0x3fceeab0 0x420024d9:0x3fceeaf0

If i comment drawString from lTask function, not crash. I tried to display in a sprite in lTask function, nothing , the same.
I think is a problem from 1.9 lcd, but i think they are both 1.9 and 2,.8 8bit parallel.
For 1.8 i made a new user setup definition like i wrote in discussion 2938
https://github.com/Bodmer/TFT_eSPI/discussions/2939

Can somebody help?

this is the definition in 
void setup()
{ 
  ..... here is some initialisation of lcd....
  xTaskCreatePinnedToCore(lTask, "lTask", 4096, NULL, 6, NULL, 1);
}

void loop()
{
   tft.drawString("welocme lcd" , 100 , 100);
}

static void lTask(void *param)
{
    while (1) 
    {
        if (errorss == true)        
           { tft.drawString("have errors" , 2 , 0);}
    }
    vTaskDelete(NULL);
}

**Comment by Bodmer** [comment]
The library is not thread safe so it will be a lottery whether it works or crashes. All TFT_eSPI operations are best kept in the main code and not within time-sliced scheduled tasks.
