### ISSUE TITLE
TFT ILI9341 stuck a boot (white screen) if TFT LED PIN hook to GPIO (ESP32)

### ISSUE THREAD

**Issue by sbarabe** [Bodmer/TFT_eSPI#2981]
Hello !

I've set up the TFT screen and it works great if I hook the LED pin to 3v3 Power supply. But if I hook-up the TFT LED pin to a ESP32 GPIO, correctly identified in the tft_eSPI user setup, then I got a white screen at boot, or if it boot correctly, a jam display when I hit reset. Nothing after that is owrking on the display, I must power everything down again. Program seems to be running normally since I have serial output...

If I unhook the GPIO at boot, then put it back after boot, every thing just work fine, and I can also turn the screen on/off using the LED pin.

How can I fix this issue at boot when using the GPIO? I would like to turn on/off the screen, but if it's jam at boot, it's useless...

Regards !

Samuel

**Comment by Bodmer** [comment]
Some GPIO have alternative functions at boot and the LED signal bias can affect the boot state. This is not due to the library. Choose a different GPIO for LED control. See here:
https://randomnerdtutorials.com/esp32-pinout-reference-gpios/
