### ISSUE TITLE
drawRoundRect/fillRoundRect radius issue

### ISSUE THREAD

**Issue by karlheinz2000** [Bodmer/TFT_eSPI#2997]
I tried to update old project with new lib. Unfortunately _drawRoundRect_ and/or _fillRoundRect_ behaves different then before.
Radius seems to be not same. I assume problem is _fillRoundRect_ .
Code is simple. Just print round, filled rect and add a frame. I can see it everywhere.
```
tft.fillRoundRect(5, 20, 310, 35, 15, TFT_WHITE);          
tft.drawRoundRect(5, 20, 310, 35, 15, TFT_BLACK);    
```  
Lib until 2.3.61 is fine. All later versions have this issue.

Arduino, STM32, ILI9341

![Screenshot_20231122-201235](https://github.com/Bodmer/TFT_eSPI/assets/11009766/c8d643e2-ae10-451e-85b7-fc8ee7074db0)
![Screenshot_20231122-201301](https://github.com/Bodmer/TFT_eSPI/assets/11009766/904e5239-3a40-4598-b192-e70a2a2c02c0)

**Comment by Bodmer** [comment]
Thanks for reporting this, it is now fixed in the Github master.
