### ISSUE TITLE
problems with examples

### ISSUE THREAD

**Issue by Tepo202** [Bodmer/TFT_eSPI#3006]
Hello, I have a problem with the examples of the TFT_eSPI.h library, to be more specific with the examples of "PNG images" none of them compile in the scketch and I get the error 
"c:/users/user/appdata/ local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../ ../../../xtensa-lx106-elf/bin/ld.exe: address 0x3fffdb90 of C:\Users\Usuario\AppData\Local\Temp\arduino_build_219796/LittleFS_PNG.ino.elf section `.bss' is not within region `dram0_0_sec'
c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106- elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: address 0x3fffdb90 of C:\Users\Usuario\AppData\Local\Temp\arduino_build_219796/LittleFS_PNG. ino.elf section `.bss' is not within region `dram0_0_seg'
collect2.exe: error: ld returned 1 exit status
"
and
"exit status 1
Error compiling for board Generic ESP8266 Module."

I am using an ILI9341 240x320 tft screen and ESP8266 development board

I've been looking for the solution for a while but I can't find it. I would really appreciate if you could help me.

**Comment by Bodmer** [comment]
The ESP8266 does not have enough RAM to run the PNGDEC library.
