### ISSUE TITLE
Compile error on ESP32 in conjunction with no MISO

### ISSUE THREAD

**Issue by martin5233** [Bodmer/TFT_eSPI#301]
I am using an ESP32 in conjunction with a Waveshared 1,7 inch display, i.e. with the ST7735 driver and your great library, version 1.4.1. I don't need the read support for the display, therefore I commented out the MISO definition in User_Setup.h. In this case the library issues a compile error from line 286 in TFT_eSPI.cpp. It is easy to fix by simply passing a -1 to spi.begin(), instead of the MISO pin number.

**Comment by Bodmer** [comment]
Thanks for reporting this. It is not fixed, but I have not raised the issue yet as I have some other enhancements to add within the next 24 hours.
