### ISSUE TITLE
Example compile error

### ISSUE THREAD

**Issue by Vperepelov** [Bodmer/TFT_eSPI#3024]
Hello,
I tried to compile example sketch "LittleFS_PNG"
I am getting compile-time error "...LittleFS_PNG.ino.elf section `.bss' is not within region `dram0_0_seg'
No changes to sketch done, just decreased MAX_IMAGE_WIDTH down to 50

What can be wrong ?
I had the same issue with Flash_PNG example, though PNG image was small enough (48*48 pixels * 16 bits) =~4.5K only
Strange, but Font_Demo_2_Array example compiles and works fine, though PROGMEM fonts there are much-much bigger...
Quite strange befaviour...

Win11, Arduino IDE 2.2.1, TFT_eSPI version is 2.5.31, NodeMCU v1 (ESP-12E Module)

Thank you for any hints.

Valery

**Comment by Bodmer** [comment]
Unfortunately the ESP8266 does not have enough RAM to run the PNGDEC library. I have added a comment to the examples to highlight this.
