### ISSUE TITLE
Printing ASCII Characters in a Sprite with a ordinal number less than 32

### ISSUE THREAD

**Issue by DGhost001** [Bodmer/TFT_eSPI#3035]
Hi,

I use the library with a full 256 Character font. So there are natural also the character symbols with ordinal numbers between 0..31 available.

If I want to print a text that contain any of those characters, they do not show up when the text is printed into a sprite.

The issue is in Sprite.cpp [here](https://github.com/Bodmer/TFT_eSPI/blob/fa6512faf40594fde13795074e26ef0379708f38/Extensions/Sprite.cpp#L1988C22-L1988C22)
If I see this correctly the `if (c<32) return;` is not needed and prevents the usage of characters less than 32.

So I would suggest to remove it, or check the availability of the characters in the current font here.

Cheers

**Comment by Bodmer** [comment]
ASCII characters less that 32 are control codes and thus are not printable characters and do not exist in fonts.
