### ISSUE TITLE
can not get my st7789V2 worked.

### ISSUE THREAD

**Issue by sithco952** [Bodmer/TFT_eSPI#3043]
I have tried this templete and got no luck. I have seen another use the same and he could at least get it showed content on the display. I have no idea why..

// Setup for the TTGO T Display
#define USER_SETUP_ID 25

// See SetupX_Template.h for all options available

#define ST7789_DRIVER
#define TFT_SDA_READ   // Display has a bidirectional SDA pin

#define TFT_WIDTH  170
#define TFT_HEIGHT 320

#define CGRAM_OFFSET      // Library will add offsets required

#define TFT_MISO 15

#define TFT_MOSI            19
#define TFT_SCLK            18
#define TFT_CS              5
#define TFT_DC              16
#define TFT_RST             23

#define TFT_BL          4  // Display backlight control pin

#define TFT_BACKLIGHT_ON HIGH  // HIGH or LOW are options

//#define TFT_RGB_ORDER TFT_RGB  // Colour order Red-Green-Blue
#define TFT_RGB_ORDER TFT_BGR // Colour order Blue-Green-Red

// Black and white swap option
//#define TFT_INVERSION_ON
#define TFT_INVERSION_OFF

#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7
#define LOAD_FONT8
#define LOAD_GFXFF

#define SMOOTH_FONT

//#define SPI_FREQUENCY  27000000
  #define SPI_FREQUENCY  40000000

#define SPI_READ_FREQUENCY  6000000 // 6 MHz is the maximum SPI read speed for the ST7789V

![unnamed (1)](https://github.com/Bodmer/TFT_eSPI/assets/49581331/486a9e1a-6d79-42c2-acb3-d561de513171)
![unnamed (2)](https://github.com/Bodmer/TFT_eSPI/assets/49581331/dd735c49-114b-43b3-829b-7e924c5bb29f)

**Comment by Bodmer** [comment]
Duplicate?
