### ISSUE TITLE
Can M5Stack createSprite()   more than 238x238?

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eSPI#305]
I use M5Stack to createSprite().
But the largest size of sprite area is 238x238.

Can I create Sprite's area more than 238x238 
 ( such as  240x240 or more than ) ?

Thank you.

**Comment by Bodmer** [comment]
Not unless you have the M5Stack Fire which has extra PSRAM, then you can probable create 10 Sprites of 480x320 pixels!

Alternatively use an 8 bit Sprite or partial screen Sprite and say two screen update cycles for different screen areas.  Writing to a Sprite is fast so clearing, redrawing and pushing elsewhere on the screen may be practical for you. The library crops graphics in a Sprite so you can have a full screen drawing function with an offset of say 0,0 for the top half of the screen and 0, -160 for the bottom half.

**Comment by TridentTD** [comment]
If  I use the M5Stack Fire , 
how can i declare createSprite() for using the extra PSRAM ?
It's automatic for  PSRAM by default ?

**Comment by Bodmer** [comment]
You have to enable the PSRAM in the Arduino  IDE menu then it is automatic.

**Comment by TridentTD** [comment]
Thank you.
