### ISSUE TITLE
use a sprite to push rotated an image and it is getting trails. 

### ISSUE THREAD

**Issue by sithco952** [Bodmer/TFT_eSPI#3060]
Hi, I have just started getting some interesting stuff to work on this fantastic library. However, I could not get the correct transparent back ground. the compass picture is spinning correctly, but it is also giving ghost .here are my codes. I hope you could give me some advices to get this worked correctly. thank you so much and Merry Christmas!
`#include <TFT_eSPI.h>

#include "compass.h"

TFT_eSPI tft = TFT_eSPI();

TFT_eSprite comp = TFT_eSprite(&tft);

void setup() {
  tft.init();
  tft.setRotation(2);
  tft.setPivot(85, 65);
  tft.fillScreen(TFT_BLUE);

  //compass control
  comp.createSprite(24, 43);
  comp.setSwapBytes(true);
  comp.setPivot(12, 33);
  comp.pushImage(0, 0, 24, 43, compass);
}

int x = 0;

void loop() {

  x++;
  if (x == 360)
    x = 0;

  comp.pushRotated(x, TFT_BLACK);
}
`
![compass spining](https://github.com/Bodmer/TFT_eSPI/assets/49581331/7aab5803-9e9f-4435-84ad-18dbec344c8d)

**Comment by Bodmer** [comment]
The background has to be wiped by the sprite, see comments in  examples.
