### ISSUE TITLE
..i tried ILI9335 on R32 but return error upload

### ISSUE THREAD

**Issue by SurenBono** [Bodmer/TFT_eSPI#307]
...the test sketch MCUFRIEND_KBV, ili9335 TFT  shield worked on UNO...but why is it not on esp32 r32 uno style... even after hard solder instruction were applied..? ...
![joxi_screenshot_1540297726106](https://user-images.githubusercontent.com/45394551/52780838-1ce48500-3086-11e9-8003-c031adf22249.png)
![0x9335](https://user-images.githubusercontent.com/45394551/52781813-7b126780-3088-11e9-9d3a-ed25e18cdf5d.jpg)
![dsc00454](https://user-images.githubusercontent.com/45394551/52781827-82397580-3088-11e9-8249-08ab0503d980.JPG)

**Comment by prenticedavid** [comment]
You seem to have opened an issue.   Edited it. Closed it.
Then re-opened.

The original message seems to show a controller with ID = 0x9335 running an example sketch. 
You must have done the hardware mod on the TTGO R32 board correctly.

What is your question?

David.

**Comment by Bodmer** [comment]
Looks like this has been posted in the wrong place.

As David say's, the TFT_eSPI library does not support ILI9335 displays.
