### ISSUE TITLE
M5stickc Plus2 User_Setup.h 

### ISSUE THREAD

**Issue by kazz2020** [Bodmer/TFT_eSPI#3078]
1. A description of the problem: Not working ESP32 Marauder (https://github.com/justcallmekoko/ESP32Marauder) compiled source code for M5Stickc PLUS2. There is fw for plus but plus2 has different pins for tft. No clue why its not working. I have CLI but no screen only black. There is problems to compile this source code with newest TFT_eSPI lib. Changing pin numbers didnt do the trick. Only black screen. Does this screen needs special config? Anyone have same problem?
2. IDE 1.8.19
3. TFT_eSPI library version: 2.5.31
4. Board package version: M5Stack 2.0.9, esp32 espressif 2.0.10 (like dev advice)
5. Procesor: ESP32-PICO-V3-02 chip
6. TFT driver: ST7789V2
7. Interface type: SPI

Plus further information as appropriate to the problem:
1. TFT to processor connections used: changed pin numbers for M5Stickc plus2 from M5Stickc plus

**Comment by xpresas** [comment]
I could have helped you if you would have used the proper issue template.

**Comment by kazz2020** [comment]
> I could have helped you if you would have used the proper issue template.

So no help becouse of that?

**Comment by xpresas** [comment]
> > I could have helped you if you would have used the proper issue template.
> 
> So no help because use of that?

Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.

**Comment by kazz2020** [comment]
> > > I could have helped you if you would have used the proper issue template.
> > 
> > 
> > So no help because use of that?
> 
> Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.

i hope my change will help

**Comment by xpresas** [comment]
> > > > I could have helped you if you would have used the proper issue template.
> > > 
> > > 
> > > So no help because use of that?
> > 
> > 
> > Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.
> 
> i hope my change will help

I had quite a similar experience using a different ESP32. For unknown reasons my TFT screen did not work using the default GPIO23. I search the internet to no end. And I couldnt figure out why this exact board of mine (ESP32-WROOM-32U ch9102x) was not able to run the screen via VSPI pin. 
I had an older ESP32 dev kit board which worked fine with the default configuration.

By looking at the pinout to my specific board I saw that pin 13 on my board was HSPI pin. So I just changed the config and tested it out and it started showing stuff without a problem.

![image](https://github.com/Bodmer/TFT_eSPI/assets/22633775/81baaee7-86e5-4559-9e36-425bb04e13db)

**Comment by kazz2020** [comment]
> > > > > I could have helped you if you would have used the proper issue template.
> > > > 
> > > > 
> > > > So no help because use of that?
> > > 
> > > 
> > > Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.
> > 
> > i hope my change will help
> 
> I had quite a similar experience using a different ESP32. For unknown reasons my TFT screen did not work using the default GPIO23. I search the internet to no end. And I couldnt figure out why this exact board of mine (ESP32-WROOM-32U ch9102x) was not able to run the screen via VSPI pin. 
> I had an older ESP32 dev kit board which worked fine with the default configuration.
> 
> By looking at the pinout to my specific board I saw that pin 13 on my board was HSPI pin. So I just changed the config and tested it out and it started showing stuff without a problem.
> 
> ![image](https://github.com/Bodmer/TFT_eSPI/assets/22633775/81baaee7-86e5-4559-9e36-425bb04e13db)
> 

I will check it but what is strange I've changed pin numbers from plus to plus2 because it's different (docs from m5stack) pins and not working.

**Comment by kazz2020** [comment]
For ili it was siple as f

**Comment by Bodmer** [comment]
I do not provide support for the ESP32 Marauder software.

Compile and run test code provided by M% to make sure the module works.

Since the display is black, this implies the LED backlight is not working or switched on so you will need to investigate this yourself.

**Comment by kazz2020** [comment]
> I do not provide support for the ESP32 Marauder software.
> 
> Compile and run test code provided by M% to make sure the module works.
> 
> Since the display is black, this implies the LED backlight is not working or switched on so you will need to investigate this yourself.

No problem... buuuuut you can provide ST7789v2 support 😉

**Comment by kazz2020** [comment]
> > > > > I could have helped you if you would have used the proper issue template.
> > > > 
> > > > 
> > > > So no help because use of that?
> > > 
> > > 
> > > Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.
> > 
> > i hope my change will help
> 
> I had quite a similar experience using a different ESP32. For unknown reasons my TFT screen did not work using the default GPIO23. I search the internet to no end. And I couldnt figure out why this exact board of mine (ESP32-WROOM-32U ch9102x) was not able to run the screen via VSPI pin. 
> I had an older ESP32 dev kit board which worked fine with the default configuration.
> 
> By looking at the pinout to my specific board I saw that pin 13 on my board was HSPI pin. So I just changed the config and tested it out and it started showing stuff without a problem.
> 
> ![image](https://github.com/Bodmer/TFT_eSPI/assets/22633775/81baaee7-86e5-4559-9e36-425bb04e13db)
> 

You are the expert 🙄 no you aren't I asked q you wrote piece of sh..... And you talk about template? Very shame

**Comment by xpresas** [comment]
> > > > > > I could have helped you if you would have used the proper issue template.
> > > > > 
> > > > > 
> > > > > So no help because use of that?
> > > > 
> > > > 
> > > > Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.
> > > 
> > > 
> > > i hope my change will help
> > 
> > 
> > I had quite a similar experience using a different ESP32. For unknown reasons my TFT screen did not work using the default GPIO23. I search the internet to no end. And I couldnt figure out why this exact board of mine (ESP32-WROOM-32U ch9102x) was not able to run the screen via VSPI pin.
> > I had an older ESP32 dev kit board which worked fine with the default configuration.
> > By looking at the pinout to my specific board I saw that pin 13 on my board was HSPI pin. So I just changed the config and tested it out and it started showing stuff without a problem.
> > ![image](https://private-user-images.githubusercontent.com/22633775/294597059-81baaee7-86e5-4559-9e36-425bb04e13db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTIxNTcsIm5iZiI6MTcwNDQ5MTg1NywicGF0aCI6Ii8yMjYzMzc3NS8yOTQ1OTcwNTktODFiYWFlZTctODZlNS00NTU5LTllMzYtNDI1YmIwNGUxM2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIxNTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjgyZjFjYjViNGRhNmMwNTFhMzJmYjU3Y2U1OGQyY2ZkMjAzYmFlZDNjOGIzMDdmODZiOGI5MDRlNWFlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jDALNovzaPHRDuHo1ckWdgjr8uvT9zHE_tB925cq7nw)
> 
> You are the expert 🙄 no you aren't I asked q you wrote piece of sh..... And you talk about template? Very shame

You seem a bit mental. 
I just told you I went about to try to fix the similar problem. If you are not happy with that. Contact bodmer directly. Pay him a couple of hundred buck and stop crying like a little kid. Do you really expect people to work for you for free? Some people...

**Comment by kazz2020** [comment]
> > > > > > > I could have helped you if you would have used the proper issue template.
> > > > > > 
> > > > > > 
> > > > > > So no help because use of that?
> > > > > 
> > > > > 
> > > > > Not because of that. Because if you would have used the template me and others included would have had basic knowledge on how to debug your problem. Now its impossible to know what, or how to fix the problem.
> > > > 
> > > > 
> > > > i hope my change will help
> > > 
> > > 
> > > I had quite a similar experience using a different ESP32. For unknown reasons my TFT screen did not work using the default GPIO23. I search the internet to no end. And I couldnt figure out why this exact board of mine (ESP32-WROOM-32U ch9102x) was not able to run the screen via VSPI pin.
> > > I had an older ESP32 dev kit board which worked fine with the default configuration.
> > > By looking at the pinout to my specific board I saw that pin 13 on my board was HSPI pin. So I just changed the config and tested it out and it started showing stuff without a problem.
> > > ![image](https://private-user-images.githubusercontent.com/22633775/294597059-81baaee7-86e5-4559-9e36-425bb04e13db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTIxNTcsIm5iZiI6MTcwNDQ5MTg1NywicGF0aCI6Ii8yMjYzMzc3NS8yOTQ1OTcwNTktODFiYWFlZTctODZlNS00NTU5LTllMzYtNDI1YmIwNGUxM2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIxNTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYjgyZjFjYjViNGRhNmMwNTFhMzJmYjU3Y2U1OGQyY2ZkMjAzYmFlZDNjOGIzMDdmODZiOGI5MDRlNWFlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jDALNovzaPHRDuHo1ckWdgjr8uvT9zHE_tB925cq7nw)
> > 
> > You are the expert 🙄 no you aren't I asked q you wrote piece of sh..... And you talk about template? Very shame
> 
> You seem a bit mental. 
> I just told you how I went about to try to fix the similar problem. If you are not happy with that. Contact bodmer directly. Pay him a couple of hundred bucks and stop crying like a little kid. Do you really expect people to work for you for free? Some people...

In the future, don't act like you know something, because throwing random Google results proves that you're a loser. Do you iven know what is plus2? You teach others and you don't know shit yourself. Cheers mtf

**Comment by xpresas** [comment]
I guess you not only unable to write in proper grammar, but at the same time you also have problems with reading too.
Cheers. 
Hope you burn your MCU!
