### ISSUE TITLE
readRect() somehow converts RGB 565 to RGB 332

### ISSUE THREAD

**Issue by Chineko-Koizumi** [Bodmer/TFT_eSPI#3081]
**Issue description**
Downloading part of displayed screen from display memory to ESP32 memory, using readRect() somehow converts RGB range.

**Hardware** 

CPU: ESP-WROOM-32
LCD screen driver: ILI9341

**Library version**
 bodmer/TFT_eSPI 2.5.43

**Example code to trigger behaviour** 

```
uint16_t tab[10000];
TFT_eSprite tempSprite(&tft);

//(...)

//Fill screen with BG image
  tft.setSwapBytes(true); 
  tft.pushImage(0, 0, MAX_IMAGE_WIDTH, MAX_IMAGE_HIGHT, (uint16_t *)Horo_image.pixel_data);
  delay(100);

  tft.readRect(0, 0, 100, 100, tab);
  
  tempSprite.createSprite(100, 100);
  tempSprite.pushImage(0,0,100,100, tab, 16U);
  tempSprite.pushSprite(5,170);
```

**Example code result on photo**
![image](https://github.com/Bodmer/TFT_eSPI/assets/48492992/afe0a79d-d1b4-45ce-86c5-9238d680d64b)

**Comment by Bodmer** [comment]
readRect() stores colours as 16 bit byte swapped values in a 16 bit array. This allows pushrect() to be used without the overhead of swapping bytes.

**Comment by Chineko-Koizumi** [comment]
> readRect() stores colours as 16 bit byte swapped values in a 16 bit array. This allows pushrect() to be used without the overhead of swapping bytes.

So if I swap High byte and Low Byte in a "tab" array (from below code fragment) after data download from screen, it should be compatible with TFT_eSprite. Am I correct?
`uint16_t tab[10000];
TFT_eSprite tempSprite(&tft);

//(...)

//Fill screen with BG image
  tft.setSwapBytes(true); 
  tft.pushImage(0, 0, MAX_IMAGE_WIDTH, MAX_IMAGE_HIGHT, (uint16_t *)Horo_image.pixel_data);
  delay(100);

  tft.readRect(0, 0, 100, 100, tab);
  
  tempSprite.createSprite(100, 100);
  tempSprite.pushImage(0,0,100,100, tab, 16U);
  tempSprite.pushSprite(5,170);`

**Comment by Chineko-Koizumi** [comment]
@Bodmer I really do not want to be insistent, but I did nothing inside code and somehow after changing cpu from esp32 to esp32S3 screen data fixed itself. I'm not sure why. 
![20240120_023017](https://github.com/Bodmer/TFT_eSPI/assets/48492992/3c2c74d8-2a53-423d-9560-ee645484cfd6)
