### ISSUE TITLE
driver of the lcd changing from code

### ISSUE THREAD

**Issue by shalom198** [Bodmer/TFT_eSPI#3083]
i wrote in the beginig of the arduino code  - #define ILI9341_DRIVER
after this  #include <TFT_eSPI.h> 

but the compilation fail, only if i wrote   #define ILI9341_DRIVER   in the user_setup.h its compile

how can i do that i will change driver within the arduino code

thanks alot

**Comment by Bodmer** [comment]
The library does not support that. There are currently no plans to add this support.
