### ISSUE TITLE
STM32 optimized driver not working with ILI9341 on the Electrosmith Daisy Seed

### ISSUE THREAD

**Issue by Oki28z** [Bodmer/TFT_eSPI#3105]
1. Using the generic driver works but not the stm32 optimized version on a ILI9341 Adafafruit screen on the Electrosmith Daisy Seed.
2. PlatformIO core 6.1.13 Home 3.4.4
3. TFT_eSPI library version V2.5.34
4. ST STM32 17.2.0
5. stm32h750ibk6
6. ILI9341 [Adafruit 2.8" resistive touch screen ](https://www.adafruit.com/product/1770)
7. SPI

I'm using the adafruit screen onto the daisy board. When I'm using the generic non optimized driver I can run all the exemples but when I uncomment the #define STM32 the screen stays blank (with or without #define TFT_SPI_PORT 1 uncommented). Is the stm32h750 non compatible with the library ?

1. TFT to processor connections used
2.The Screen is wired like this:
MOSI onto D10
MISO onto D9
CLK onto D8
CS onto D7
DC onto D16
RST onto D22
4. [User_Setup.h.zip](https://github.com/Bodmer/TFT_eSPI/files/13937018/User_Setup.h.zip)
5. [main.cpp.zip](https://github.com/Bodmer/TFT_eSPI/files/13937079/main.cpp.zip)

Here is the output of the read user setup sketch witth and without #define STM32 uncommented
```
  [code]
TFT_eSPI ver = 2.5.34
Processor    = STM32
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 10
MISO    = GPIO 9
SCK     = GPIO 8

>>>>> Note: STM32 pin references above D15 may not reflect board markings <<<<<
TFT_CS   = D7
TFT_DC   = D16
TFT_RST  = D22

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 40.00
[/code]


[code]
TFT_eSPI ver = 2.5.34
Processor    = Generic
Transactions = Yes
Interface    = SPI
Display driver = 9341
Display width  = 240
Display height = 320

MOSI    = GPIO 10
MISO    = GPIO 9
SCK     = GPIO 8
TFT_CS   = GPIO 7
TFT_DC   = GPIO 16
TFT_RST  = GPIO 22

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 40.00
[/code]
```

**Comment by Bodmer** [comment]
The optimised drivers are for the STM32F variants. They may not work with others. I do not recognise the version numbers in your build environment.

Note: New versions of the STM32 Arduino board package (2.7.0, 2.7.1) have also broken the STM32F support but downgrading to 2.6.0 works. The Github master has some minor updates that allow STM32F processors to work with the latest board support package.

The are no plans to provide optimised drivers for STM32H processors.
