### ISSUE TITLE
Sprite can't display smooth font correctly.

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eSPI#311]
When I try smooth fonts by sprite, sprite can't show smooth like normal TFT_eSPI's tft.
Smooth fonts by the sprite when X position is more than about 240-320 can't display correctly.

<p align="center">
  <img src="https://raw.githubusercontent.com/TridentTD/TTest/master/image_cap.png" alt="image"/>
</p>  

The smooth fonts :  https://github.com/TridentTD/TTest/blob/master/NotoSans-Light30.vlw
Hardware : M5Stack
TFT_eSPI version : the current version  1.4.6 ( master)

The code :
```c
#include <TFT_eSPI.h>
#include <FS.h>
#include <SPI.h>

TFT_eSPI    tft = TFT_eSPI();
TFT_eSprite spr = TFT_eSprite(&tft);

String fontname = "NotoSans-Light30";
uint8_t BUTTON_B = 38;

void setup() {
  Serial.begin(921600); Serial.println();
  pinMode(BUTTON_B,INPUT);
  tft.begin(); tft.setRotation(1);

  if(!SPIFFS.begin()) {
    Serial.println("SPIFFS start first");
    return;
  }    
  if(SPIFFS.exists(String("/") + fontname + ".vlw"))
    Serial.println("Found " + fontname);
  else
    Serial.println("Upload Font First");

  tft.fillScreen(TFT_BLACK);

  spr.createSprite( tft.width(), 80);
  spr.loadFont(fontname);
  spr.setTextWrap(false,false);
  spr.setTextColor(TFT_WHITE,TFT_BLACK);

  // drawString by Sprite .....Test1
  spr.fillSprite(TFT_BLACK);
  spr.setTextDatum(TL_DATUM);
  spr.drawString("SPR : Hello Test", 0, 0);
  spr.pushSprite(0,20);

  // drawString by Sprite .....Test2
  spr.fillSprite(TFT_BLACK);
  spr.setTextDatum(TR_DATUM);
  spr.drawString("SPR : Hello Test", spr.width(), 0);
  spr.pushSprite(0,80);  

  // drawString by TFT_eSPI ...Test3
  tft.loadFont(fontname);
  tft.setTextColor(TFT_RED,TFT_BLACK);
  tft.setTextDatum(TL_DATUM);
  tft.drawString("TFT : Hello Test", 0, 140);

  // drawString by TFT_eSPI ...Test4
  tft.setTextDatum(TR_DATUM);
  tft.drawString("TFT : Hello Test", tft.width(), 200);
}

void loop() {
//  if( digitalRead(BUTTON_B) == LOW)
//   screenServer();
}
```

**Comment by TridentTD** [comment]
When I use TFT_eSPI version 1.3.8.
the sprite can display smooth fonts correctly.

<p align="center">
  <img src="https://raw.githubusercontent.com/TridentTD/TTest/master/image_cap_138.png" alt="image"/>
</p>

**Comment by Bodmer** [comment]
This looks like an SPI interface timing issue. What SPI rate are you using? Does it happen at a lower clock rate?

**Comment by TridentTD** [comment]
TFT_eSPI version 1.4.6(master)
all of these configs  still  display incorrectly.

-------------------------------------------------------
#define SPI_FREQUENCY   1000000
#define SPI_FREQUENCY   5000000
#define SPI_FREQUENCY  10000000
#define SPI_FREQUENCY  20000000
#define SPI_FREQUENCY  27000000 // Actually sets it to 26.67MHz = 80/3
#define SPI_FREQUENCY  40000000 // Maximum to use SPIFFS  
#define SPI_FREQUENCY  80000000
----------------------------------------------------

**Comment by Bodmer** [comment]
Thanks for reporting this and for providing an example that demonstrates the problem.

This was a bug in the Sprite drawPixel function for the bounds check.  It is now fixed in the master.

**Comment by TridentTD** [comment]
TFT_eSPI version 1.4.7(master) is OK.

Thank you very much.
