### ISSUE TITLE
Same as 268 - Overlap not working

### ISSUE THREAD

**Issue by mikeruss1** [Bodmer/TFT_eSPI#313]
I seem to have the same problem as 268, Nodemcu v3 +ILI9341, overlap is not working.

TFT display works beautifully but TFT +Touch doesnt work in the same way as described in 268, configured as overlap.

TFT + touch works fine with other libraries.

hope you can help,
Mike

**Comment by Bodmer** [comment]
In overlap mode there can only be one SPI device on the bus unless extra logic is added. The processor only arbitrates for the shared use of the bus with the FLASH memory using Slave Select pin D3.  With additional external logic devices you could arrange to swap this line to other devices and choose the device in the sketch.

Unfortunately this is a limitation of the ESP8266.
