### ISSUE TITLE
ili9486 for uno and esp32

### ISSUE THREAD

**Issue by joe318** [Bodmer/TFT_eSPI#314]
Hello,

I have the ili9486 for uno in shield mode, i'm trying to use ur library with the screen but nothing appear :(
I try thousands things without success, any suggestion?
it's one waveshare for arduino not rpi.

Regards,

**Comment by Bodmer** [comment]
Are you using an UNO format ESP32.  If so have you make the link modifications?

**Comment by joe318** [comment]
No, im using one normal esp32.


![placa-de-desenvolvimento-esp32-c-conectores-femea-espressif](https://user-images.githubusercontent.com/38740665/53121830-0b4f2180-354d-11e9-8bca-bc1aa5869003.jpg)

**Comment by joe318** [comment]
But i'm not the only one to have this problem with specially this tft.

![shield-lcd-4-t-til-p-arduino](https://user-images.githubusercontent.com/38740665/53121936-418ca100-354d-11e9-8c34-7be0042732e3.jpg)

**Comment by Bodmer** [comment]
The display is a 16 bit SPI interfacebased around shift registers so it may not be compatible with TFT_eSPI.

How have you wired the display to the ESP32?

Post your setup file so I can see all the settings you are using.

**Comment by joe318** [comment]
ok, look, i search in your issues and i found a guy with the same tft and same problem, i read ur answers, so i decide to stop spend time but i spend money and i buy one for rpi version loool, so dont worry, i leave this one for play with an arduino.
But thanks coz u answer fast and u are fucking smart lol
