### ISSUE TITLE
Esp32 with ILI9488 touch not working

### ISSUE THREAD

**Issue by luke2023** [Bodmer/TFT_eSPI#3163]
hello, i hope you can help.I have bought 5 screen, one runs touch correctly (normal z raw is around 90) and the others all have 1890 normal z raw value. and they don't work as well(I guess the program thinks I am pressing them but it is the untouched)

**Comment by luke2023** [comment]
![image](https://github.com/Bodmer/TFT_eSPI/assets/110216618/74ec0650-4dd5-4d07-8ad6-424addf74c6a)

this is my circuit diagram
, and i use touch_calibrate example

**Comment by luke2023** [comment]
![image](https://github.com/Bodmer/TFT_eSPI/assets/110216618/8d80fa3b-778a-4438-9f8a-e139a52c45b4)

This is the one with same circuit and calibration code(may be only this screen is OK?

**Comment by luke2023** [comment]
This is the raw and calibration on strange LCD

https://youtu.be/7PVe3VPsW-4?si=7eZyBYNCKUGGZN29[](https://youtu.be/7PVe3VPsW-4?si=7eZyBYNCKUGGZN29)

**Comment by Bodmer** [comment]
Try using the optional touch threshold parameter, by default it is 600, see here:
https://github.com/Bodmer/TFT_eSPI/blob/master/Extensions/Touch.h#L11-L18

Maybe a threshold of 2000 would work.

**Comment by luke2023** [comment]
@Bodmer thank you for replying,so I should simply modify the 600 to 2000?

**Comment by Bodmer** [comment]
Just add the extra parameter to get touch to define the threshold, e.g.:
tft.getTouch(&x, &y, 2000);

**Comment by luke2023** [comment]
@Bodmer thabk you for the suggestion
