### ISSUE TITLE
Blank screen with Nucleo STM32F072RB

### ISSUE THREAD

**Issue by JMattChiam** [Bodmer/TFT_eSPI#3164]
I've been trying to run the UTFT_demo_fast on my Nucleo F072 with no luck. I'm using a 240 x 240 ST7789 with no Chip Select. It works perfectly well on an ESP32 up to 24MHz. The backlight is on but nothing is shown on the screen. I have tried both SPI ports 1 and 2 as well. 

I've tried downgrading the STM32 board package version to 2.6 as #3125 but results are the same. 

IDE: Arduino IDE 2.2.1
TFT_eSPI: Version 2.5.34
STM32 Board package version 2.7.1
Processor: STM32F072RBT6 (Nucleo F072)
TFT Driver: ST7789
Interface: 4-Wire SPI

Pin connections:
| Connection | Pin |
| --- | --- | 
| MOSI | PA7 |
| SCK | PA5 |
| RST | PC9 |
| DC | PC8 | 

My setup file:
[Setup302_NucleoF072_ST7789.zip](https://github.com/Bodmer/TFT_eSPI/files/14178201/Setup302_NucleoF072_ST7789.zip)

**Comment by Bodmer** [comment]
The following STM32 processors are supported with optimised drivers:
STM32F1xx, STM32F2xx, STM32F4xx, STM32F767

Other STM32 variants should work with the slower ardiuno calls. To try that comment out this line on the setup file:
```
#define STM32 
```
You will probably need to use the default Arduino SPI pins. Note this is not tested by me!
