### ISSUE TITLE
Everything appears blue on ILI9481 connected to ESP32 via 8bit parallel

### ISSUE THREAD

**Issue by Freymi** [Bodmer/TFT_eSPI#3175]
Hello,

I connected my ILI9481 display to the ESP32 via 8bit parallel and tried some examples of the library. 
The display does work, however everything appears blue, no other colors are drawn.

I tried setting TFT_INVERSION_ON in the settings, then everything appears yellow with a white background instead of blue on a black background, however other colors are still not possible.

IDE: Arduino IDE
TFT_eSPI: 2.5.34
Board package version: esp32 2.0.14
Processor: ESP32
TFT driver: ILI9481
Interface Type: 8bit parallel (I tried SPI but couldn't get it to work)

[User_Setup.zip](https://github.com/Bodmer/TFT_eSPI/files/14321793/User_Setup.zip)

![photo_2024-02-18_10-02-17](https://github.com/Bodmer/TFT_eSPI/assets/28230903/840aafcb-c3b8-41e6-857d-5702095353ac)
(I am aware the pin desriptions on the tape are wrong)
![photo_2024-02-18_10-02-22](https://github.com/Bodmer/TFT_eSPI/assets/28230903/8c5cb1c0-cb24-43f7-be58-ed2e2e335973)
![photo_2024-02-18_10-02-26](https://github.com/Bodmer/TFT_eSPI/assets/28230903/f2b6fedf-a1b7-485d-90fa-ff0011179da8)
![photo_2024-02-18_10-02-29](https://github.com/Bodmer/TFT_eSPI/assets/28230903/b020eda4-6511-4e51-a04d-a54349163284)

**Comment by Bodmer** [comment]
The display has a 16 bit interface. Only the RP2040 processor is supported with that interface.
