### ISSUE TITLE
MC_DATUM does not work with multi-line string, drawString()

### ISSUE THREAD

**Issue by rtek1000** [Bodmer/TFT_eSPI#3195]
MC_DATUM does not work with multi-line string,

The command '\n' is recognized and breaks the line, but centering does not work.

Apparently the text is scrolled as if it were a single line.

```C++
tft.setTextDatum(MC_DATUM);
tft.drawString("Hello\r\nWorld", 50, 50);
```

**Comment by Bodmer** [comment]
The library does not hande split lines. You will need to split the text into 2 parts in the sketch.
