### ISSUE TITLE
Touch not working with ESP32S3 + ILI9341

### ISSUE THREAD

**Issue by Maverik1408** [Bodmer/TFT_eSPI#3200]
Greetings,
I'm trying to connect my ESP32 S3 with an ILI9341 display but I can't get the touch to work these are the connections I made:

VCC --> 3V3
GND --> GND
CS --> 10
RESET --> 6
DC --> 7
MOSI --> 11
SCK --> 12
LED --> 3V3
MISO --> NO CONNECTED
T_CLK --> 12
T_CS --> 19
T_DIN --> 11
T_C --> 13
T_IRQ --> NO CONNECTED

are the connections correct?

this is my platormio.io config

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/tty.wchusbserial55700034511
upload_speed = 2000000
upload_protocol = esptool
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
lib_deps = 
	ArduinoJson
	TFT_eSPI

monitor_filters = 
	esp32_exception_decoder
build_flags = -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
	-D USER_SETUP_LOADED
	-D ILI9341_DRIVER
	-D TFT_MOSI=11
	-D TFT_SCLK=12
	-D TFT_CS=10
	-D TFT_DC=7
	-D TFT_RST=6
	-D TOUCH_CS=19
	-D SPI_FREQUENCY=40000000
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_FONT8
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	-D ESP32
	-I src

the display shows the image correctly but I can't get the touch to work.
when I launch the calibration it runs automatically as if the four corners were pressed but I don't press anything and once it's finished the display doesn't receive touch.

thanks for the support

**Comment by Bodmer** [comment]
You will have to define the TFT_MISO pin as 19 even though that pin is not connected to the TFT.
