### ISSUE TITLE
Problem related to pushToSprite when deleting the sprite edges.

### ISSUE THREAD

**Issue by goqeq** [Bodmer/TFT_eSPI#3202]
Hello everyone, 

I recently wanted to draw a rectangle within a sprite named "battery" and place it onto the background sprite using the pushToSprite function. However, when I use the "transparent" argument with TFT_BLACK, the rectangle is the correct color and yes, the background is properly removed, but a bug occurs on the rectangle where it seems like lines of black pixels fill the rectangle. I've tried different approaches before asking this question, and nothing else seems to work. So, I'd like to know if I've written something wrong in my test code? I'm new to this library, so I apologize if this is a silly question. 

I'm working on an ESP32 WROOM 32 with a 240x240 screen using the GC9A01.

Thank you in advance!

```c++
#include <TFT_eSPI.h>

TFT_eSPI tft = TFT_eSPI();
TFT_eSprite background = TFT_eSprite(&tft);
TFT_eSprite battery = TFT_eSprite(&tft);

void setup() {
  tft.init();
  tft.setSwapBytes(true);
  tft.fillScreen(TFT_BLACK);

  background.setColorDepth(8);
  background.fillSprite(TFT_RED);
  background.createSprite(240,240);

  battery.setColorDepth(8);
  battery.fillSprite(TFT_BLACK);
  battery.createSprite(100,100);
}

void loop() {
  background.fillSprite(TFT_RED);
  battery.fillSprite(TFT_BLACK);
  battery.fillRect(0,0,50,20,TFT_BLUE);
  battery.pushToSprite(&background,120, 120, TFT_BLACK); // Problem here
  background.pushSprite(0,0);
}
```

![signal-2024-03-02-201417_002](https://github.com/Bodmer/TFT_eSPI/assets/59402067/ffa9e0fe-e19e-4b96-a66b-55edd1306edd)

**Comment by goqeq** [comment]
Finally I found using TFT_TRANSPARENT or at least a different color from the background sprite. I didn't really understand I couldn't use TFT_BLACK but it's not very important, as long as it works.

**Comment by Bodmer** [comment]
Thanks for reporting this, it has been fixed in the Github master.
