### ISSUE TITLE
Grayscale gradient

### ISSUE THREAD

**Issue by momosh13** [Bodmer/TFT_eSPI#323]
Hello,
I found the following code from another library (ILI9341_due http://marekburiak.github.io/ILI9341_due) for grayscale gradient.
-----------------------------------
uint16_t pixels[200];
...
for (byte x = 0; x < 200; x++) { // generate a simple grayscale gradient
   uint16_t color = (uint16_t)(255 * x) / 200;
   pixels[x] = tft.color565(color, color, color);
}
tft.setAddrWindowRect(60, 100, 200, 3); // set the drawing window to a 200x3px rectangle
for (byte y = 0; y < 3; y++) { // 3 lines
   tft.pushColors(pixels, 0, 200); // draw the generated colors
}
-----------------------------------
Is there any way to use same or typical method for your library?
Thanks.

**Comment by Bodmer** [comment]
There is a luminance function in the TFT_eFEX extension library for TFT_eSPI that can be used to generate a greyscale gradient, see [example and relevant code here](https://github.com/Bodmer/TFT_eFEX/blob/master/examples/Rainbow_Luminance/Rainbow_Luminance.ino#L52-L59). In this example you would use white:
fex.luminance(255, 255, 255, lum);

Bear in mind the with the 16 bit "565" colours there are only 31 shades of grey ;-)
