### ISSUE TITLE
[Request]  Request another member function drawBitmap() .

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eSPI#324]
TFT_eSPI is the great library for tft display.
When I want to push bitmap-color16bit array to the specific area.
I found that it takes many steps ... such as   setWindow() &  pushColors()  etc..

TFT_eSPI come with member function  drawBitmap() , 
however the prototype is look like
```C
void drawBitmap(int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color);
```

Request another drawBitmap() too  
that prototype is compatible with ESP-WHO 
```C
void drawBitmap(int16_t x, int16_t y, const uint16_t *bitmap, int16_t w, int16_t h);
```
( https://github.com/espressif/esp-who/blob/master/components/lcd/include/iot_lcd.h#L175 )

or Adafruit_GFX library 
```C
void  drawRGBBitmap(int16_t x, int16_t y, uint16_t *pcolors, int16_t w, int16_t h);
```
https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_SPITFT.h#L227-L228

Thank you.

**Comment by Bodmer** [comment]
[Equivalent functions](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.h#L750-L752) already exist.  Not all examples use this method yet as they were written before the pushImage() functions were created.

Try them and see if they work for you.

If the endianess of the 16 bit image data you can use [setSwapBytes(true or false)](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.h#L762-L764) to correct this.

**Comment by TridentTD** [comment]
Thank you.
