### ISSUE TITLE
What is frame in sprite?

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eSPI#326]
I use ESP32 + 8M PSRAM  and want to create multiple sprites.

such as 
```C
TFT_eSprite spr1, srp2;
```

What is the difference between
```C
spr1.createSprite(120,120, 1);
spr2.createSprite(40,40, 1);
```
and
```C
spr1.createSprite(120,120, 1);
spr2.createSprite(40,40, 2);
```

**Comment by Bodmer** [comment]
Ignore the 3rd parameter and just use width and height.  The frame count is for future use with 2 colour ePaper displays and no example has been released for this yet.
