### ISSUE TITLE
Overwriting text on the display

### ISSUE THREAD

**Issue by pierpe83** [Bodmer/TFT_eSPI#329]
Hi
I have a problem with displaying the variable on the display.
When the variable value changes, it is overwritten to the old value and it becomes cluttered on the display.
I did not find any text cleaning function on the display.
How to deal with this?

`    tft.setTextSize(3);
    tft.setTextColor(TFT_RED); tft.setCursor(0, 10);
    tft.println("Temperature");
    tft.setTextColor(TFT_YELLOW); tft.setTextSize(5); 
    tft.setCursor(0, 40);
    tft.println(pinData);
    tft.setCursor(60, 32);
    tft.println("o");
    tft.setCursor(88, 40);
    tft.println("C");`

**Comment by VikJr** [comment]
> tft.setTextSize(3); tft.setTextColor(TFT_RED); tft.setCursor(0, 10); tft.println("Temperature"); tft.setTextColor(TFT_YELLOW); tft.setTextSize(5); tft.setCursor(0, 40); tft.println(pinData); tft.setCursor(60, 32); tft.println("o"); tft.setCursor(88, 40); tft.println("C");
--------------------

	pierpe83 Try this option -
 tft.setTextSize(3); tft.setTextColor(TFT_RED,TFT_BLACK); tft.setCursor(0, 10); tft.println("Temperature"); tft.setTextColor(TFT_YELLOW,TFT_BLACK); tft.setTextSize(5); tft.setCursor(0, 40); tft.println(pinData); tft.setCursor(60, 32); tft.println("o"); tft.setCursor(88, 40); tft.println("C");


---------------------
 tft.setTextColor(TFT_RED,TFT_BLACK)
TFT_RED - text color is red.
TFT_BLACK - background is black.

**Comment by Bodmer** [comment]
As VikJr mentions you can specify a background colour, however as the digit count changes part of the old longer bumber can be left behind. One way around this is to add padding spaces.

drawNumber(), drawFloat() and drawString() functions can all be used with automatic padding to a defined width and with a defined datum.  See examples:

TFT_String_Align and TFT_Padding_Demo

**Comment by holla2040** [comment]
Bodmer, thanks the padding example reference. setTextPadding works great for me.
