### ISSUE TITLE
Random colored pixels on edges

### ISSUE THREAD

**Issue by hoekbrwr** [Bodmer/TFT_eSPI#33]
#define ESP8266 is missing. I cannot get rid of random colors on the edges.

**Comment by Bodmer** [comment]
ESP8266 is defined by the Arduino IDE automatically if it is setup to compile for the ESP8266. Similarly for the ESP32.

Random pixels at edges indicates your display has an offset, this can be seen if you draw a rectangle of full screen width and height at 0,0.

Some of the ST7735 tab options correct for this offset, however you may have a display with an offset that is different to the ones I tested. |In this case adjusting the vales in the appropriate Init file may help, [see here](https://github.com/Bodmer/TFT_eSPI/blob/53836b6f9d4953421cc6c25ad5f46688a200267b/TFT_Drivers/ST7735_Init.h#L169) for an example

**Comment by Bodmer** [comment]
If you need support to solve this then post back. I am closing this for now.
