### ISSUE TITLE
Strange output tft

### ISSUE THREAD

**Issue by quintendewilde** [Bodmer/TFT_eSPI#331]
I'm having strange output on my tft screen. 

I used this git to get api data on my tft screen using wemos D1 mini.
But I got this weird output on the screen.

https://github.com/scottbez1/espwidget/issues/2#issue-421849989

**Comment by Bodmer** [comment]
Do the TFT_eSPI library examples run correctly?

**Comment by Bodmer** [comment]
Try changing line 90 of client.ino to:

```
          tft.setAddrWindow(0, r, WIDTH, ROW_READ);
```

**Comment by quintendewilde** [comment]
Yes everything compiles perfectly.

Ill try the change in code tomorrow!

De Wilde Quinten

**Comment by Bodmer** [comment]
Let me know if you still have an issue. Closing for now.
