### ISSUE TITLE
setTextDatum not working

### ISSUE THREAD

**Issue by tribly** [Bodmer/TFT_eSPI#334]
I've been trying to use setTextDatum, but it doesn't work.

I have this [Display](https://www.amazon.de/dp/B078JBBPXK) and a NodeMCU esp8266 v2.

#### User_Setup.h
``` c++
#define ST7735_DRIVER
#define TFT_WIDTH  128
#define TFT_HEIGHT 160
#define ST7735_REDTAB
#define TFT_CS   PIN_D8  
#define TFT_DC   PIN_D3  
#define TFT_RST  -1 // Connected to the RST pin
```

#### main.cpp
``` c++
#include <TFT_eSPI.h> // Hardware-specific library
#include <SPI.h>

TFT_eSPI tft = TFT_eSPI();

void setup()
{
  tft.init();
  tft.setRotation(0);
  tft.fillScreen(TFT_BLACK);
}

void loop()
  for(int i = 0; i < 9; i++)
  {
    tft.setTextDatum(i);
    tft.drawNumber(i, 0, 0, 4);
    delay(1000);
}
```

But it always prints in the upper left corner.

**Comment by Bodmer** [comment]
Try printing somewhere else on the screen. The default datum is top left of the character, so all other datums relative to 0,0 will be off the screen. The library automatically moves the datum so characters are not drawn off screen (to avoid showing nothing for sketch errors)
