### ISSUE TITLE
ESP32 TFT ILI9481 Mirrored output

### ISSUE THREAD

**Issue by 68gt500** [Bodmer/TFT_eSPI#335]
Just got my cheap chinese ILI9481 TFT UNO shield.
Works - kind of - but the screen output is mirrored 

![IMG_20190328_142128](https://user-images.githubusercontent.com/35020367/55161304-7c45b280-5165-11e9-82a9-76d6a389d089.jpg)
Really nice colors and good resolution, not bad for the money.
Dont´t mind the slash, just on the protective foil

Any Ideas ?

**Comment by 68gt500** [comment]
A few additional findings:
Demos:
Font1 -- mirror
Font2,3,4 -- ok
Unicode Test -- nothing, white screen
Local Custom Font -- ok
TFT Padding -- ok
TFT Rainbow - mirror -- see above
Free Font Demo -- ok
3D Cube OK

Dark Sky - all mirrored :-(

![IMG_20190328_210233](https://user-images.githubusercontent.com/35020367/55189092-4fad8d00-519d-11e9-8326-ea8e2929c259.jpg)

**Comment by 68gt500** [comment]
Sorry, hit wrong button

**Comment by 68gt500** [comment]
Found out, that using a ILI9486 driver instead of the ILI9481 the mirrored problem is solved.
user_setup.h:
//#define ILI9481_DRIVER  //mirrored
#define ILI9486_DRIVER   //okay

**Comment by josephsr** [comment]
Can you send me link for the display that you are using? We have a similar display (9481) but unable to get it to work

**Comment by 68gt500** [comment]
Suer: https://www.ebay.de/itm/3-5inch-TFT-color-screen-module-320X480-ultra-HD-support-for-Arduino-for-UNO-R/263984004356?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649
This is the display, it claims: IC:ILI9481
Hookup was very easy:  Do the described mods to the board and just plug it in. All pin assignments stay standard.

**Comment by Bodmer** [comment]
@68gt500 Can you post a picture of the back (pcb side) of your display please.

**Comment by 68gt500** [comment]
This is a link to the ebay picture: https://i.ebayimg.com/images/g/2ScAAOSwr9VZ1~yz/s-l1600.jpg

I will check tonight, if it is exactly like the one I received.

**Comment by 68gt500** [comment]
![IMG_20190402_173420](https://user-images.githubusercontent.com/35020367/55415958-442bde80-556e-11e9-937d-a58b73d93fce.jpg)
Here is a pic of my board, which is not exactly as the image from ebay.

**Comment by Bodmer** [comment]
That looks like an ILI9486 board so you have selected the right driver.

It is not unusual for averts from some low cost vendors to be wrong which is not very helpful to buyer!

**Comment by fuxifex** [comment]
Hi, can you please provide a Wiring Diagram? (I'm using a ESP32 DevKit-C) 
Thanks!
