### ISSUE TITLE
Wire CS to ground

### ISSUE THREAD

**Issue by HumamHelfawi** [Bodmer/TFT_eSPI#336]
HI,
in the setup file:
`#define TFT_CS   15  // Chip select control pin (library pulls permanently low)`
Is it OK then to wire CS pin of the LCD to Ground directly ?
If so, should I put `#define TFT_CS   -1` ?
I am using the library with Parallel-8Bit ILI9488  tft & ESP32

Thank you very much!

**Comment by Bodmer** [comment]
Is it OK then to wire CS pin of the LCD to Ground directly ? -  Yes
If so, should I put #define TFT_CS -1 ? - Yes

**Comment by HumamHelfawi** [comment]
@Bodmer  Thank you very much!
