### ISSUE TITLE
ESP32_SDcard_jpeg_ILI9486__ISSUES?

### ISSUE THREAD

**Issue by amirjak** [Bodmer/TFT_eSPI#340]
![01](https://user-images.githubusercontent.com/46311349/56075483-ad1a1e80-5dd8-11e9-8479-c431ff0740ea.jpg)

i have this___**_tft 3.5 lcd ili9486**_____ .
i  want  use ___**sd card**___ on___ **tft 3.5 lcd ili9486**____ and i use ___**DOIT Esp32 DevKit v1**__? 
how i can use?
I USE THIS PIN
___**tft 3.5 lcd ili9486**_________ *****DOIT Esp32 DevKit v1*****         
_______TFT_CS___________________D33 
_______TFT_DC___________________D15
_______TFT_RST__________________D32
_______TFT_WR__________________D4
_______TFT_RD___________________D2
_______TFT_D0___________________D12
_______TFT_D1____________________D13
_______TFT_D2____________________D26
_______TFT_D3___________________D25
_______TFT_D4___________________D17
_______TFT_D5___________________D16
_______TFT_D6___________________D27
_______TFT_D7___________________D14
**********************************************
_______TFT SD_SS ____________D5____cs
_______TFT SD_DI ____________D19____MISO
_______TFT SD_DO____________D23 ___MOSI
_______TFT SD_SCK___________D18 ____CLK

NOT WORKING

but with **sd card module** connect to **DOIT Esp32 DevKit v1** work correctly

**Comment by Bodmer** [comment]
How have you wired the ESP32 to the shield?

Do the TFT_eSPI library examples display correctly?

**Comment by amirjak** [comment]
hi
thank for answering
How have you wired the ESP32 to the shield?
in file **User_Setup.h**
#define ILI9486_DRIVER
#define ESP32_PARALLEL

// The ESP32 and TFT the pins used for testing are:
#define TFT_CS   33  // Chip select control pin (library pulls permanently low
#define TFT_DC   15  // Data Command control pin - must use a pin in the range 0-31
#define TFT_RST  32  // Reset pin, toggles on startup

#define TFT_WR    4  // Write strobe control pin - must use a pin in the range 0-31
#define TFT_RD    2  // Read strobe control pin

#define TFT_D0   12  // Must use pins in the range 0-31 for the data bus
#define TFT_D1   13  // so a single register write sets/clears all bits.
#define TFT_D2   26  // Pins can be randomly assigned, this does not affect
#define TFT_D3   25  // TFT screen update performance.
#define TFT_D4   17
#define TFT_D5   16
#define TFT_D6   27
#define TFT_D7   14
Do the TFT_eSPI library examples display correctly? **YES**

![STORAGE 1-500x500](https://user-images.githubusercontent.com/46311349/56059165-b1aeea80-5d78-11e9-9bda-925a8c12e128.jpg)
with sd card module connect to DOIT Esp32 DevKit v1 work correctly
_______SD_SS ________________D5____cs
______SD_DI _________________D19____MISO
______SD_DO________________D23 ___MOSI
______SD_SCK_______________D18 ____CLK


But with  sd card on tft module  not working
i wired like this
_______SD_SS ________________D5____cs
______SD_DI _________________D19____MISO
______SD_DO________________D23 ___MOSI
______SD_SCK_______________D18 ____CLK

**Comment by Bodmer** [comment]
If you only connect power (+5V and 0V) and SPI lines to the TFT shield SD card pins does the SD Card interface work?

**Comment by pipi61** [comment]
Hi!
This sdcard module contain power regulator, and level converter.
Try another simple sdcard module without regulator and without converter

**Comment by amirjak** [comment]
> If you only connect power (+5V and 0V) and SPI lines to the TFT shield SD card pins does the SD Card interface work?

NOT WORKING

**Comment by Bodmer** [comment]
It looks like a hardware fault or an incompatibilty for some reason.

J1-4 are simply reference names for the header strips so youcan identify their position and reference the schematic.

I will close as the problem you have does not appear tobe due to the library.

**Comment by amirjak** [comment]
Thanks😁
