### ISSUE TITLE
Cubed symbol (0x00B3) has top few pixels chopped off

### ISSUE THREAD

**Issue by thearduinoguy** [Bodmer/TFT_eSPI#342]
If I enable the Unicode cubed symbol 0x00B3 the top 1 or 2 pixels of the character 3 are chopped off.

**Comment by Bodmer** [comment]
If you change this line. to:
```
//*
```
Then the height of the font will be derived from the maximum in the character set rather than the top of the "d" character.

**Comment by thearduinoguy** [comment]
Great. Thanks.
