### ISSUE TITLE
Multiple Displays and different CS

### ISSUE THREAD

**Issue by marcwolf1960** [Bodmer/TFT_eSPI#347]

**Comment by Bodmer** [comment]
If you wish to use multiple displays with one processor board then use:

#define TFT-CS -1

in setup and toggle the chip selectlines for the appropriate display in the sketch.

**Comment by marcwolf1960** [comment]
Many thanks for replying.  Which Setup are you talking about. The one in my actual program.. or the one in  the libraries.

Again thanks

**Comment by Bodmer** [comment]
User_Setup.h or your own setup called by User_Setup_Select.h in the library folder.
