### ISSUE TITLE
Colors from hex values are wrong

### ISSUE THREAD

**Issue by emilekm2142** [Bodmer/TFT_eSPI#35]
When I want to do: `tft.fillScreen(0x3498db)`, instead of light blue I get magenta. The problem does not occur when I do the following:
```
int32_t toInt(r,g,b) {
			
			return (((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3));
		}
tft.fillScreen(toInt(52, 152, 219));
```
The color differs only a little probably due to a dirt cheap display. How can I fix that? I am on ESP32 and ST7735 BLACKTAB display from aliexpress

**Comment by Bodmer** [comment]
Colours are expected to be specified in 16 bit 565 format.  The value 0x3498db is 24 bits so will get truncated to 16 bits. This is why converting to 16 bits with the toInt() function works as it produces a 16 bit colour value from the 8 bit rgb values.

The key advantage of using 16 bit colour is the improved performance (fewer bits need to be sent to the display).
