### ISSUE TITLE
Some artifacts redering JPEG in a sprite

### ISSUE THREAD

**Issue by JavierPascual** [Bodmer/TFT_eSPI#359]
Hi @Bodmer!!

I've doing more tests and with some little JPEG files, I'm seeing new artifacts in screen on the right side of the images. I'm loading and painting it with:

`lcd_fx.drawJpeg("/heart.jpg", x, v, _buffer_sprite);`

Some real examples here, in a ILI9341 320x240 display:

![IMG_3479](https://user-images.githubusercontent.com/207247/57439932-5a048180-7247-11e9-9c6c-5b6de8b3e482.jpeg)
![heart_failed](https://user-images.githubusercontent.com/207247/57440158-c67f8080-7247-11e9-8ca0-770833ef3b09.jpg)
![logo_failed](https://user-images.githubusercontent.com/207247/57440159-c67f8080-7247-11e9-8516-5db7223e3427.jpg)

💯 THANKS!

_Originally posted by @JavierPascual in https://github.com/Bodmer/TFT_eSPI/issues/289#issuecomment-490816157_

**Comment by Bodmer** [comment]
Thanks for reporting this.

I see an issue in the function, due to some urgent work I will not be able to fix it and test for 2 weeks.

**Comment by JavierPascual** [comment]
Great! thank you Bodmer! 👍 👍 👍

**Comment by Bodmer** [comment]
This was a bug in the TFT_eFEX library that has now been corrected. Please download and try the latest version.

**Comment by JavierPascual** [comment]
Hi @Bodmer! Yes, the bug has been fixed! Thank you very much!!
