### ISSUE TITLE
BRG to RGB in function pushImage with ili9486, ili9488

### ISSUE THREAD

**Issue by ali-batkhed** [Bodmer/TFT_eSPI#367]
If you have shifted color palette when use function "pushImage" from RGB to BRG with ili9486, ili9488  driver in parallel 8-bit mode with esp32 - you should remove swapping bytes in this function.

in TFT_eSPI.cpp in line 1010 was:

  while (dh--)
  {
    pushColors(data, dw, _swapBytes);
    data += w;
  }

, must be:

  while (dh--)
  {
    pushColors(data, dw);
    data += w;
  }.

Good luck to everyone!

**Comment by Bodmer** [comment]
Do not modify the code, use the setSwapBytes(true/false) function in your sketch.

by default _swapBytes is set to false. See [prototypes here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.h#L762-L764).

**Comment by ali-batkhed** [comment]
thank you very much! i'm a beginner in arduino - that's why i missed.

вс, 26 мая 2019 г. в 19:51, Bodmer <notifications@github.com>:
