### ISSUE TITLE
wrap issue with ST7735

### ISSUE THREAD

**Issue by spyder0069** [Bodmer/TFT_eSPI#372]
If I have wrap disabled and print text beyond the boundaries on the display I get corruption.  I understand this is a "don't do it" situation but wanted to mention it.   I did try multiple fonts and it does it in both portrait and landscape.  I am using the Greentab3 128x128 setup.   In this example i print "00.12" knowing the decimal will push the 2 off the display some.  

![broken2](https://user-images.githubusercontent.com/8635214/58750982-618e0380-845e-11e9-839c-d0c5b828485f.jpg)

**Comment by Bodmer** [comment]
Yes, the corruption is expected, it could be eliminated but there would be a performance impact on characters rendered within the screen area. Printing via a Sprite will crop characters if that is what you need.
