### ISSUE TITLE
PNG 

### ISSUE THREAD

**Issue by Blackmamba3356** [Bodmer/TFT_eSPI#374]
Good day!
1) Is it possible to display PNG icons with a transparent background? Also, I wanted to know the possibility of displaying a simple animation or a sequence of frames. Screen IPS 1.3 ST7789

2) Is it possible to draw a shape with a translucent fill. As an example

https://ibb.co/Hn3TpVh

3) Faced a problem. I print the line with the PrintToSprite command over a colored jpeg background. The text background option is transparent, but the resulting sprite is filled with `black.

https://ibb.co/gvhWnfH

**Comment by Bodmer** [comment]
Building a PNG library is on my low priority to do list

An ESP32 with PSRAM is likely to be needed.
