### ISSUE TITLE
Another RPI 3.5" TFT

### ISSUE THREAD

**Issue by kuzmanzs** [Bodmer/TFT_eSPI#377]
Hi,

I have similat display to https://github.com/Bodmer/TFT_eSPI/blob/master/Tools/RPi_TFT_Connections.png
My looks like:
https://www.dropbox.com/s/69zb8hrcvlu9r62/IMG_20190613_093832.jpg?dl=0

T_CS, L_CS, IRQ look different.

I have connected follwing way to Wemos mini.
Display SDO/MISO  to NodeMCU pin D6
Display SCK       to NodeMCU pin D5
Display SDI/MOSI  to NodeMCU pin D7
Display IRQ to NodeMCU pin D3
NO reset
Display CS        to NodeMCU pin D8
Display GND       to NodeMCU pin GND (0V)
Display VCC       to NodeMCU 5V or 3.3V
Display Touch_CD to NodeMCU pin D1

But nothing happens. Display is full black, LCD backlight is on.. with User_Setups/Setup10_RPi_touch_ILI9486.h include

**Comment by Bodmer** [comment]
Unfortunately different RPi screen use different interface circuits and TFT drivers so you may have an incompatible display.
