### ISSUE TITLE
ILI9486 8 bit & touch

### ISSUE THREAD

**Issue by kuzmanzs** [Bodmer/TFT_eSPI#380]
Hi,

I have ESP32 Uno Style board. I have done IO15 wired to IO35, IO33 wired to IO34, IO32 wired to IO36 wireing.
I am using #define ESP32_PARALLEL and #define ILI9488_DRIVER and dispaly looks good.

I am unable configure with touch sensing. I checked repo https://github.com/s60sc/Adafruit_TouchScreen and I made  pin 4 and analog pin 39 wireing as well. 
I am running https://github.com/s60sc/Adafruit_TouchScreen/blob/master/examples/ESP32testTouch/ESP32testTouch.ino but no touching detected. 

I have following display
https://es.aliexpress.com/item/3-2-inch-TFT-LCD-screen-module-Ultra-HD-320X480-for-Arduino-MEGA-2560-R3-Board/32605255967.html?spm=a219c.10010108.1000016.1.474b1359PHPlgq&isOrigTitle=true

EDIT: I tried to run TouchScreen_Calibr_native.ino but it does not run with ESP32 or?
`
void setup()
{
    Serial.begin(9600);
    Serial.println(TITLE);
    bool ret = true;
#if defined(__arm__) || defined(ESP32)
    Serial.println(F("Not possible to diagnose Touch pins on ARM or ESP32"));  !!!!!!!!!!!!!!!!!!!!
#else
    ret = diagnose_pins();
#endif

`

pls help

**Comment by Bodmer** [comment]
The library only supports SPI touch screens based on the XPT2046. Typically the 8 bit screens have a resistance sending interface that must be read using an ADC.

You could try the library [here](https://github.com/s60sc/Adafruit_TouchScreen).

**Comment by kuzmanzs** [comment]
I have tryied this library already..

See above:
"I am running https://github.com/s60sc/Adafruit_TouchScreen/blob/master/examples/ESP32testTouch/ESP32testTouch.ino but no touching detected."

Could you give me hint what can be wrong?

**Comment by Bodmer** [comment]
I have not tried that library do I am not in a position to help. I suggest you raise an issue on the libraries repository and hopefully the author will help.
