### ISSUE TITLE
Support for Eclipse with C/C++ compiler

### ISSUE THREAD

**Issue by Hak4Kidz** [Bodmer/TFT_eSPI#381]
I got the TFT_eSPI libraries to work with an ili9341 and ESP32 using the Arduino IDE. It's fast!!

Currently, working on a project with the same hardware but using Eclipse and C. Before spending the time to make it work, only to find out that it's not supported, will the TFT_eSPI libraries work on an ESP32 using Eclipse?

Thank you!
Hak4Kidz

**Comment by Bodmer** [comment]
Yes, there are likely to be problems with environments other than the Arduino IDE. I expect this is the same issue as #288.

The library used the underlying Arduino board package libraries too so getting the library to work under Eclipse will need intrusive changes 

One option for you might be to use the PlatformIO environment.
