### ISSUE TITLE
Seek not working?

### ISSUE THREAD

**Issue by JimDrewGH** [Bodmer/TFT_eSPI#383]
Is the seek function broken?  I get this error message when using the example:  TFT_SPIFFS_BMP

MP_functions:38: error: no matching function for call to 'fs::File::seek(uint32_t&)'

       bmpFS.seek(seekOffset);

It seems that any of the examples that try to use Seek() generate the same error.  Read() works, but obviously Seek() is needed to skip headers and such.

I am using v2.3.0 of the ESP8266 libraries (because of bugs in later versions).

**Comment by Bodmer** [comment]
Bersion 2.3.0 is around 3 years old now and does not have the seek. You will need to use at least version 2.4.0 I suspect.

I am currently using 2.5.2 and it seems stable.
