### ISSUE TITLE
Missing character Celsius

### ISSUE THREAD

**Issue by cawena** [Bodmer/TFT_eSPI#384]
The character Celsius (°) is missing. How to add this character on FONT2 and FONT4?

Thx for help

**Comment by Bodmer** [comment]
The fonts only include characters up to ASCII 127 so the Celsius symbol would not normally be included in that range.

However for font 4 I made the "grave" accent into a Celcius symbol, so you can write  `C for example.

The grave accent is normally on the key next to the 1 on a keyboard.

Font 2 does not contain a Celsius symbol.

**Comment by Bodmer** [comment]
If you replace Font16.h in the Fonts folder of the library with the attached then the grave accent will be a Celsius symbol in font 2 as well.

[Font16.zip](https://github.com/Bodmer/TFT_eSPI/files/3318538/Font16.zip)
