### ISSUE TITLE
Sorry not a real issue but How could i ADD MCP_23S17 for parallel interface

### ISSUE THREAD

**Issue by arnold-b** [Bodmer/TFT_eSPI#393]
Hello, 

i have a few ILI9488 TFT but without SPI breakout. I would like to use it with mcp23S17. 
Could you give me some hint, how to do this ?

May you could tell me, where is the best place to edit your code and add this function 

Hardware: ESP32, mcp23s17, ILI9488

I tested a few libraries. I like your one the most.

thanks

**Comment by Bodmer** [comment]
The library uses a mix of SPI library calls and direct ESP32 register access, this complicates the code adaption. One way to identify the code that would need to be changed is to look for the sections that are conditionally compiled for the RPI board, I.e. look for RPI_ILI9486_DRIVER conditional statements.

Make sure you fully understand what each affected code section does before making changes. It is probably best to write independant test software to communicate with the TFT via the SPI to parallel chip first.

The way I would adapt the TFT_eSPI code is to first change it to make all communication via the SPI library, then rewrite the SPI library to make the use of the mcp23s17 transparent to the graphics library.

**Comment by arnold-b** [comment]
Thanks for advice
