### ISSUE TITLE
frame rotation problem in EPD

### ISSUE THREAD

**Issue by littlepinecone** [Bodmer/TFT_eSPI#398]
HI,
    i'm using a 2.13 inch EPD with esp8266. the problem is there is a Incomplete display when rotation is set to 1 and 3( landscape). Any suggestions?
    thanks.
![IMG_20190720_220018](https://user-images.githubusercontent.com/8842321/61579701-34df9980-ab3b-11e9-958f-aceb510dcbba.jpg)

**Comment by Bodmer** [comment]
Thanks for reporting this. I expect this is a bug as END code is experimental. I will investigate.

**Comment by Bodmer** [comment]
Thanks for pointing out this issue. It was a bug and hopefully has now been fixed. If you are still having a problem please reopen the issue.

**Comment by littlepinecone** [comment]
yeah, now it works fine. Thanks.
