### ISSUE TITLE
Smooth Font Without Background

### ISSUE THREAD

**Issue by BleepBlonk** [Bodmer/TFT_eSPI#412]
I've noticed that if i have a background color the smooth font shows nicely as it should, but if i print it without a background color it doesn't look right. For example if i want to print over whats already on the screen it looks blocky and jagged like the default fonts enlarged.

**Comment by Bodmer** [comment]
Look at examples Font_demo_1-4 and read the comments to see different methods of rendering smooth fonts. The edges of the characters must be blended with the bacground so you always need to specify the background colour.

**Comment by Bodmer** [comment]
The library does not currently allow aliasing over "on screen images" since this would require reading the pixel colour for each antialiased character pixel to derive the blended colour. So if that is what you were asking about then this is not currently supported.

**Comment by BleepBlonk** [comment]
That is what I was looking for, would have made great eye candy but I can always work around it. Thanks for the lib and reply!
