### ISSUE TITLE
Text flicker and chart flicker 

### ISSUE THREAD

**Issue by ThatBigPrint** [Bodmer/TFT_eSPI#414]
i hope you can help me and my `friend` are doing a project that requires us to update the 240x240 lcd and what ever we try we are not able to get rid of the flicker can you help us fix this ?

most of the code has been ported from our oled version and we have tried rectangles etc ata loss would appreciate a fix or help 

being run on an eps 32

this is the arduino code 

 `#include <Arduino.h>
#include <SPI.h>
#include <TFT_eSPI.h> // Graphics and font library for ST7735 driver chip
#include <Wire.h>

TFT_eSPI tft = TFT_eSPI();  // Invoke library, pins defined in User_Setup.h

#define ADC_BITS    12
//U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);
//U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);
//U8G2_SH1106_128X64_NONAME_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ PB6, /* data=*/ PB5, /* cs=*/ PB10, /* dc=*/ PA2, /* reset=*/ PA3);
//U8G2_SSD1306_128X64_NONAME_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ PB6, /* data=*/ PB5, /* cs=*/ PB10, /* dc=*/ PA2, /* reset=*/ PA3);
//U8G2__MIDAS_128X128_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ PB13, /* data=*/ PB15, /* cs=*/ PB12, /* dc=*/ PB14, /* reset=*/ PA8);

int count = 0;
const int cycleDelay = 20;      // Change to adjust cycle time

// offset var (multiply by 100)
int offset = 0;
String stat;
const int numReadings = 10;
int mode = 1;
// 1 = Bar
// 2 = PSI
// 3 = kPa

//int Bar = 0;
int Bar = 1;
int PSI = 0;
int kPa = 0;

int boostPressure;
int boostMax = 0;
int boostMin = 0;

int readings[numReadings];
int readIndex = 0;
int total = 0;
int average = 0;

unsigned long startMillis;
unsigned long currentMillis;
const unsigned long period = 5;

const int sensorHistoryLength = 240;
int sensorHistory[sensorHistoryLength];
int sensorHistoryPos = sensorHistoryLength - 1;

bool injector = false;          // are we using injectors
float ONCycle = 0;              // oncycle variable 
float OFFCycle = 0;             // offcycle variable got microsecond
float T = 0;                    // tota l time to one cycle ONCycle + OFFcycle
int F = 0;                      // Frequency = 1/T
int RPM = 0;                    // RPM (Frequency * 60)
float DutyCycle = 0;            // D = (TON/(TON+TOFF))*100 %
float dutyMax = 0;
float onMin = 0;

void setup(void) {
  tft.init();
  tft.setRotation(4);
  tft.fillScreen(TFT_BLACK);
  
  startMillis = millis();
  
  for (int thisReading = 0; thisReading < numReadings; thisReading++) {
    readings[thisReading] =0;
  }
  
  pinMode(12, INPUT); 
  // Check for Injector input
  ONCycle = pulseIn(12, HIGH, 100);  // wait 100ms for High pulse to start
  if (ONCycle != 0){                  // If no pulse is detected in 100ms OnCycle will be 0
    injector = true;                  // If OnCyle is not 0 there must be an injector input
  }
}

void loop(void) {  
  // Only read from the sensors every 50 ms
  currentMillis = millis();
  //tft.fillScreen(TFT_BLACK);

  if (currentMillis - startMillis >= period) {
    readSensorData();
    //tft.fillScreen(TFT_BLACK);
    startMillis = currentMillis;
  }
    // Switch Code Start
    if ((digitalRead(27)==HIGH) && Bar != 1){
      mode = 1;
      Bar = 1;
      PSI = 0;
      kPa = 0;
      
      boostMax = 0;
      boostMin = 0;
      for (int i = 0; i < 240; i++) {
        sensorHistory[i] = 0;
      }
    }
    else if ((digitalRead(26)==HIGH) && PSI != 1){
      mode = 2;
      Bar = 0;
      PSI = 1;
      kPa = 0;

      boostMax = 0;
      boostMin = 0;
      for (int i = 0; i < 240; i++) {
        sensorHistory[i] = 0;
      }
    }
    else if ((digitalRead(25)==HIGH) && kPa != 1){
      mode = 3;
      PSI = 0;
      Bar = 0;
      kPa = 1;

      boostMax = 0;
      boostMin = 0;
      for (int i = 0; i < 240; i++) {
        sensorHistory[i] = 0;
      }
    }
    else if (mode == 0)

    // Switch Code END

    // PWN Measure

    if (injector == true){
      ONCycle = pulseIn(12, HIGH);
      OFFCycle = pulseIn(12, LOW);
    
      T = ONCycle + OFFCycle;
      DutyCycle = (ONCycle / T) * 100;
      F = 1000000 / T;

      RPM = F * 60;

      // Update max Duty
      if (DutyCycle > dutyMax) dutyMax = DutyCycle;
    }

    char cstr[6];
      
    if (mode == 1) {
      //Draw current pressure Bar

      dtostrf((float)boostPressure/100, 1, 1, cstr);      // Bar shown to 1dp
      tft.drawCentreString(cstr, 0, 80, 6);
      
      if (count == 0)
      {
        tft.setTextColor(TFT_BLACK);
        tft.drawCentreString("BOOST", 178, 24, 4);
        tft.drawCentreString("STATUS", 178, 60, 4);
        delay(10);
        tft.setTextColor(TFT_WHITE);
        tft.drawCentreString("DISPLAY", 178, 24, 4); 
        tft.drawCentreString("UNITS", 178, 60, 4);
        tft.drawCentreString("BAR", 178, 90, 4);
      }
      //if (count <= cycleDelay)
      //{
      //  tft.setTextColor(TFT_BLACK);
      //  tft.drawCentreString("BOOST", 178, 24, 4);
      //  tft.drawCentreString("STATUS", 178, 60, 4);
      //  tft.setTextColor(TFT_WHITE);
      //  tft.drawCentreString("DISPLAY", 178, 24, 4); 
      //  tft.drawCentreString("UNITS", 178, 60, 4);
      //  tft.drawCentreString("BAR", 178, 90, 4);
      //}
      if (count == 40)
      {
        tft.setTextColor(TFT_BLACK);
        tft.drawCentreString("DISPLAY", 178, 24, 4); 
        tft.drawCentreString("UNITS", 178, 60, 4);
        tft.drawCentreString("BAR", 178, 90, 4);
        delay(10);
        tft.setTextColor(TFT_WHITE);
        tft.drawCentreString("MAXIMUM", 178, 24, 4);
        tft.drawCentreString("PRESSURE", 178, 60, 4);
      }
      //else if (count > cycleDelay && count <= (cycleDelay*2))
      //{
      //  tft.setTextColor(TFT_BLACK);
      //  tft.drawCentreString("DISPLAY", 178, 24, 4); 
      //  tft.drawCentreString("UNITS", 178, 60, 4);
      //  tft.drawCentreString("BAR", 178, 90, 4);
      //  tft.setTextColor(TFT_WHITE);
      //  tft.drawCentreString("MAXIMUM", 178, 24, 4);
      //  tft.drawCentreString("PRESSURE", 178, 60, 4);
      //}
      if (count == 80)
      {
        tft.setTextColor(TFT_BLACK);
        tft.drawCentreString("MAXIMUM", 178, 24, 4);
        tft.drawCentreString("PRESSURE", 178, 60, 4);
        delay(10);
        tft.setTextColor(TFT_WHITE);
        tft.drawCentreString("DUTY",178, 24, 4);
        tft.drawCentreString("CYCLE %", 178, 60, 4);
      }
      //else if (count > (cycleDelay*2) && count <= (cycleDelay*3))
      //{
      //  tft.setTextColor(TFT_BLACK);
      //  tft.drawCentreString("MAXIMUM", 178, 24, 4);
      //  tft.drawCentreString("PRESSURE", 178, 60, 4);
      //  tft.setTextColor(TFT_WHITE);
      //  tft.drawCentreString("DUTY",178, 24, 4);
      //  tft.drawCentreString("CYCLE %", 178, 60, 4);
      //}
      if (count == 120)
      {
        tft.setTextColor(TFT_BLACK);
        tft.drawCentreString("DUTY",178, 24, 4);
        tft.drawCentreString("CYCLE %", 178, 60, 4);
        delay(10);
        tft.setTextColor(TFT_WHITE);
        tft.drawCentreString("PULSE", 178, 24, 4);
        tft.drawCentreString("WIDTH MS", 178, 60, 4);
      }
      //else if (count > (cycleDelay*3) && count <= (cycleDelay*4))
      //{
      //  tft.setTextColor(TFT_BLACK);
      //  tft.drawCentreString("DUTY",178, 24, 4);
      //  tft.drawCentreString("CYCLE %", 178, 60, 4);
      //  tft.setTextColor(TFT_WHITE);
      //  tft.drawCentreString("PULSE", 178, 24, 4);
      //  tft.drawCentreString("WIDTH MS", 178, 60, 4);
      //}
      if (count == 160)
      {
        tft.setTextColor(TFT_BLACK);
        tft.drawCentreString("PULSE", 178, 24, 4);
        tft.drawCentreString("WIDTH MS", 178, 60, 4);
        delay(10);
        tft.setTextColor(TFT_WHITE);
        tft.drawCentreString("BOOST", 178, 24, 4);
        tft.drawCentreString("STATUS", 178, 60, 4);
      }
      //else if (count > (cycleDelay*4) && count <= (cycleDelay*5))
      //{
      //  tft.setTextColor(TFT_BLACK);
      //  tft.drawCentreString("PULSE", 178, 24, 4);
      //  tft.drawCentreString("WIDTH MS", 178, 60, 4);
      //  tft.setTextColor(TFT_WHITE);
      //  tft.drawCentreString("BOOST", 178, 24, 4);
      //  tft.drawCentreString("STATUS", 178, 60, 4);
      //}
      if (count == 200)
      {
        count=0;
      }
      //else
      //{
      //  count =0;
      //}
       
      // Boost / CRUSE / VAC CODE
      if (((float)boostPressure/100) <= -0.4 ) {
        stat = "IDLE";
      }
      else if (((float)boostPressure/100) >= 0 ) {
        stat = "BOOST";
      }
      else{
        stat = "CRUISE";
      }
    }
    
    if (mode == 2) {
      //Draw current pressure Psi

      char cstr[6];
      dtostrf((float)boostPressure/100, 1, 0, cstr);      // PSI shown to 0dp
      tft.drawCentreString(cstr, 0, 80, 6);
      
      if (count <= cycleDelay)
      {
        tft.drawCentreString("DISPLAY", 178, 24, 4); 
        tft.drawCentreString("UNITS", 178, 60, 4);
        tft.drawCentreString("PSI", 178, 90, 4);
      }
      else if (count > cycleDelay && count <= (cycleDelay*2))
      {
        tft.drawCentreString("MAXIMUM", 178, 24, 4);
        tft.drawCentreString("PRESSURE", 178, 60, 4);
      }
      else if (count > (cycleDelay*2) && count <= (cycleDelay*3))
      {
        tft.drawCentreString("DUTY",178, 24, 4);
        tft.drawCentreString("CYCLE %", 178, 60, 4);
      }
      else if (count > (cycleDelay*3) && count <= (cycleDelay*4))
      {
        tft.drawCentreString("PULSE", 178, 24, 4);
        tft.drawCentreString("WIDTH MS", 178, 60, 4);
      }
      else if (count > (cycleDelay*4) && count <= (cycleDelay*5))
      {
        tft.drawCentreString("BOOST", 178, 24, 4);
        tft.drawCentreString("STATUS", 178, 60, 4);
      }
      else
      {
        count =0;
      }
      // Boost / CRUSE / VAC CODE
      if ((boostPressure/100) <= -6 ) {
        stat = "IDLE";
       }
      else if ((boostPressure/100) >= 0 ) {
        stat = "BOOST";
      }
      else{
        stat = "CRUISE";

      }
    }

    if (mode == 3) {
      // Draw current pressure kPa

      char cstr[6];
      dtostrf((float)boostPressure/100, 1, 0, cstr);      // kPa shown to 1dp
      tft.drawCentreString( cstr, 0, 80, 6);
      
      if (count <= cycleDelay)
      {
        tft.drawCentreString("DISPLAY", 178, 24, 4); 
        tft.drawCentreString("UNITS", 178, 60, 4);
        tft.drawCentreString("KPA", 178, 90, 4);
      }
      else if (count > cycleDelay && count <= (cycleDelay*2))
      {
        tft.drawCentreString("MAXIMUM", 178, 24, 4);
        tft.drawCentreString("PRESSURE", 178, 60, 4);
      }
      else if (count > (cycleDelay*2) && count <= (cycleDelay*3))
      {
        tft.drawCentreString("DUTY",178, 24, 4);
        tft.drawCentreString("CYCLE %", 178, 60, 4);
      }
      else if (count > (cycleDelay*3) && count <= (cycleDelay*4))
      {
        tft.drawCentreString("PULSE", 178, 24, 4);
        tft.drawCentreString("WIDTH MS", 178, 60, 4);
      }
      else if (count > (cycleDelay*4) && count <= (cycleDelay*5))
      {
        tft.drawCentreString("BOOST", 178, 24, 4);
        tft.drawCentreString("STATUS", 178, 60, 4);
      }
      else
      {
        count =0;
      }
      // Boost / CRUSE / VAC CODE
      if ((boostPressure/100) <= 40 ) {
        stat = "IDLE";
      }
      else if ((boostPressure/100) >= 100 ) {
        stat = "BOOST";
      }
      else{
        stat = "CRUISE";
      }
    }

    // Draw max pressure & Scrolling data
    char duty[6];
    char period[6];
    if (mode == 1) {
      dtostrf((float)boostMax / 100, 1, 1, cstr);   // Bar 1dp
    }
    if (mode == 2) {
      dtostrf((float)boostMax / 100, 1, 0, cstr);   // PSI 0dp
    }
    if (mode == 3) {
      dtostrf((float)boostMax / 100, 1, 0, cstr);   // kPa 0dp
    }
    dtostrf((float)dutyMax, 1, 0, duty);            // max duty written to 0dp
    dtostrf((float)ONCycle/1000, 1, 0, period);     // ONCycle written to 0dp  
    

//      if (count <= cycleDelay) // change this to alter delay
//      {
//
//     }
//      else if (count > cycleDelay && count <= (cycleDelay*2))
//      {
//        tft.drawCentreString(cstr, 178, 90, 4);
//      }
//      else if (count > (cycleDelay*2) && count <= (cycleDelay*3))
//      {
//        tft.drawCentreString(duty ,178, 90, 4);
//      }
//      else if (count > (cycleDelay*3) && count <= (cycleDelay*4))
//      {
//        tft.drawCentreString(period, 178, 90, 4);
//      }
//      else if (count > (cycleDelay*4) && count <= (cycleDelay*5))
//      {
//        char str1[7];
//        stat.toCharArray(str1,7);
//        tft.drawCentreString(str1, 178, 120, 4);     // Draw Boost status (IDLE/CRUISE/BOOST)
//      }
//      else
//      {
//        count =0;
//      }
    drawGraph(0, 140, 240, 100);
    
    count++;
  }
  
void readSensorData(void) {  
    //int ADC = analogRead(PA0);
    // Dual ADC
    int ADC_1 = analogRead(0);
    int ADC_2 = analogRead(1);
    float ADC = (ADC_1 + ADC_2)/2;
    
    total = total - readings[readIndex];
    readings[readIndex] = ADC;
    total = total + readings[readIndex];
    readIndex = readIndex + 1;

    if (readIndex >= numReadings) {
      readIndex = 0;
    }

    average = total / numReadings;
  
    float Vin = (float)((average / 4096.0))*3.3;
    
    int P = Vin * 100;
    
    // Pressure = ((Vin - (0.1 * Vsup)) * Pmax) / (0.8 * Vsup)) - Poffset
    // Multiply by 100 to use int with 2dp
    int Ppsi = ((((P - 33)*15000)/264)) - offset;
    int Pbar = ((((P - 33)*1034)/264)) - offset;
    int Pkpa = ((((P - 33)*103421)/264)+10000) - offset;

    // Log outputs for graph
    boostPressure = 0;
    if (mode == 1) {
      // Bar
      boostPressure = Pbar;
    }

    if (mode == 2) {
      // PSI
      boostPressure = Ppsi; 
    }

    if (mode == 3) {
      // kPa
      boostPressure = Pkpa;  
    }
    
    // Update max and min
    if (boostPressure < boostMin) boostMin = boostPressure;
    
    if (boostPressure > boostMax) boostMax = boostPressure;

    // Log the history
    addSensorHistory(boostPressure);
}

void addSensorHistory(int val) {
  sensorHistory[sensorHistoryPos] = val;
  sensorHistoryPos--;
  if (sensorHistoryPos < 0) sensorHistoryPos = sensorHistoryLength - 1;
}

int getSensorHistory(int index) {
  index += sensorHistoryPos;
  if (index >= sensorHistoryLength) index = index - sensorHistoryLength;
  return sensorHistory[index];
}

// Display functions

void drawGraph(int x, int y, int len, int height1) {
  // Draw the lines
  drawHorizontalDottedLine(x, y, len);
  drawHorizontalDottedLine(x, y + height1, len);

  //var absMin = Math.abs(boostMin);
  int absMin = abs(boostMin);
  int range = absMin + boostMax;

  // Draw 0 line
  int zeroYPos = mapValueToYPos(absMin, range, y, height1);
  drawHorizontalDottedLine(x, zeroYPos, len);

  // Draw the graph line
  for (int i = 0; i < 240; i++) {
    // Scale the values so that the min is always 0
    int valueY = getSensorHistory(i) + absMin;

    // Calculate the coordinants
    int yPos = mapValueToYPos(valueY, range, y, height1);
    int xPos = len - i;
    if (yPos < zeroYPos) {
      // Point is above zero line, fill in space under graph
      tft.drawFastVLine(xPos, yPos, zeroYPos + 1 - yPos, TFT_RED);
      //tft.drawLine(xPos, yPos, zeroYPos + 1 - yPos);
    } else {
      // Point is below zero line, draw graph line without filling in
      tft.drawPixel(xPos, yPos, TFT_BLUE);
    }
  }
}

// Maps a value to a y height
int mapValueToYPos(int val, int range, int y, int height1) {
  float valueY = ((float)val / range) * height1;
  return y + height1 - (int)valueY;
}

void drawHorizontalDottedLine(int x, int y, int len) {
  for (int i = 0; i < len; i++) {
    if (!(i % 4)) tft.drawPixel(x + i, y, TFT_WHITE);
    //delay(15);
  }
}`

this is the user set up 

`//                            USER DEFINED SETTINGS
//   Set driver type, fonts to be loaded, pins used and SPI control method etc
//
//   See the User_Setup_Select.h file if you wish to be able to define multiple
//   setups and then easily select which setup file is used by the compiler.
//
//   If this file is edited correctly then all the library example sketches should
//   run without the need to make any more changes for a particular hardware setup!
//   Note that some sketches are designed for a particular TFT pixel width/height

// ##################################################################################
//
// Section 1. Call up the right driver file and any options for it
//
// ##################################################################################

// Only define one driver, the other ones must be commented out
//#define ILI9341_DRIVER
//#define ST7735_DRIVER      // Define additional parameters below for this display
//#define ILI9163_DRIVER     // Define additional parameters below for this display
//#define S6D02A1_DRIVER
//#define RPI_ILI9486_DRIVER // 20MHz maximum SPI
//#define HX8357D_DRIVER
//#define ILI9481_DRIVER
//#define ILI9486_DRIVER
//#define ILI9488_DRIVER     // WARNING: Do not connect ILI9488 display SDO to MISO if other devices share the SPI bus (TFT SDO does NOT tristate when CS is high)
//#define ST7789_DRIVER      // Full configuration option, define additional parameters below for this display
#define ST7789_2_DRIVER    // Minimal configuration option, define additional parameters below for this display
//#define R61581_DRIVER
//#define RM68140_DRIVER

// Some displays support SPI reads via the MISO pin, other displays have a single
// bi-directional SDA pin and the library will try to read this via the MOSI line.
// To use the SDA line for reading data from the TFT uncomment the following line:

// #define TFT_SDA_READ      // This option is for ESP32 ONLY, tested with ST7789 display only

// For ST7789 ONLY, define the colour order IF the blue and red are swapped on your display
// Try ONE option at a time to find the correct colour order for your display

 #define TFT_RGB_ORDER TFT_RGB  // Colour order Red-Green-Blue
//  #define TFT_RGB_ORDER TFT_BGR  // Colour order Blue-Green-Red

// For M5Stack ESP32 module with integrated ILI9341 display ONLY, remove // in line below

// #define M5STACK

// For ST7789, ST7735 and ILI9163 ONLY, define the pixel width and height in portrait orientation
//#define TFT_WIDTH  80
// #define TFT_WIDTH  128
#define TFT_WIDTH  240 // ST7789 240 x 240 and 240 x 320
//#define TFT_HEIGHT 160
// #define TFT_HEIGHT 128
#define TFT_HEIGHT 240 // ST7789 240 x 240
// #define TFT_HEIGHT 320 // ST7789 240 x 320

// For ST7735 ONLY, define the type of display, originally this was based on the
// colour of the tab on the screen protector film but this is not always true, so try
// out the different options below if the screen does not display graphics correctly,
// e.g. colours wrong, mirror images, or tray pixels at the edges.
// Comment out ALL BUT ONE of these options for a ST7735 display driver, save this
// this User_Setup file, then rebuild and upload the sketch to the board again:

// #define ST7735_INITB
// #define ST7735_GREENTAB
// #define ST7735_GREENTAB2
// #define ST7735_GREENTAB3
// #define ST7735_GREENTAB128    // For 128 x 128 display
// #define ST7735_GREENTAB160x80 // For 160 x 80 display (BGR, inverted, 26 offset)
// #define ST7735_REDTAB
// #define ST7735_BLACKTAB
// #define ST7735_REDTAB160x80   // For 160 x 80 display with 24 pixel offset

// If colours are inverted (white shows as black) then uncomment one of the next
// 2 lines try both options, one of the options should correct the inversion.

// #define TFT_INVERSION_ON
// #define TFT_INVERSION_OFF

// If a backlight control signal is available then define the TFT_BL pin in Section 2
// below. The backlight will be turned ON when tft.begin() is called, but the library
// needs to know if the LEDs are ON with the pin HIGH or LOW. If the LEDs are to be
// driven with a PWM signal or turned OFF/ON then this must be handled by the user
// sketch. e.g. with digitalWrite(TFT_BL, LOW);

// #define TFT_BACKLIGHT_ON HIGH  // HIGH or LOW are options

// ##################################################################################
//
// Section 2. Define the pins that are used to interface with the display here
//
// ##################################################################################

// We must use hardware SPI, a minimum of 3 GPIO pins is needed.
// Typical setup for ESP8266 NodeMCU ESP-12 is :
//
// Display SDO/MISO  to NodeMCU pin D6 (or leave disconnected if not reading TFT)
// Display LED       to NodeMCU pin VIN (or 5V, see below)
// Display SCK       to NodeMCU pin D5
// Display SDI/MOSI  to NodeMCU pin D7
// Display DC (RS/AO)to NodeMCU pin D3
// Display RESET     to NodeMCU pin D4 (or RST, see below)
// Display CS        to NodeMCU pin D8 (or GND, see below)
// Display GND       to NodeMCU pin GND (0V)
// Display VCC       to NodeMCU 5V or 3.3V
//
// The TFT RESET pin can be connected to the NodeMCU RST pin or 3.3V to free up a control pin
//
// The DC (Data Command) pin may be labeled AO or RS (Register Select)
//
// With some displays such as the ILI9341 the TFT CS pin can be connected to GND if no more
// SPI devices (e.g. an SD Card) are connected, in this case comment out the #define TFT_CS
// line below so it is NOT defined. Other displays such at the ST7735 require the TFT CS pin
// to be toggled during setup, so in these cases the TFT_CS line must be defined and connected.
//
// The NodeMCU D0 pin can be used for RST
//
//
// Note: only some versions of the NodeMCU provide the USB 5V on the VIN pin
// If 5V is not available at a pin you can use 3.3V but backlight brightness
// will be lower.

// ###### EDIT THE PIN NUMBERS IN THE LINES FOLLOWING TO SUIT YOUR ESP8266 SETUP ######

// For NodeMCU - use pin numbers in the form PIN_Dx where Dx is the NodeMCU pin designation
//#define TFT_CS   PIN_D15  // Chip select control pin D8
//#define TFT_DC   PIN_D2  // Data Command control pin
//#define TFT_RST  PIN_D4  // Reset pin (could connect to NodeMCU RST, see next line)
//#define TFT_RST  -1    // Set TFT_RST to -1 if the display RESET is connected to NodeMCU RST or 3.3V

//#define TFT_BL PIN_D1  // LED back-light (only for ST7789 with backlight control pin)

//#define TOUCH_CS PIN_D2     // Chip select pin (T_CS) of touch screen

//#define TFT_WR PIN_D2       // Write strobe for modified Raspberry Pi TFT only

// ######  FOR ESP8266 OVERLAP MODE EDIT THE PIN NUMBERS IN THE FOLLOWING LINES  ######

// Overlap mode shares the ESP8266 FLASH SPI bus with the TFT so has a performance impact
// but saves pins for other functions.
// Use NodeMCU SD0=MISO, SD1=MOSI, CLK=SCLK to connect to TFT in overlap mode

// In ESP8266 overlap mode the following must be defined
//#define TFT_SPI_OVERLAP

// In ESP8266 overlap mode the TFT chip select MUST connect to pin D3
//#define TFT_CS   PIN_D3
//#define TFT_DC   PIN_D5  // Data Command control pin
//#define TFT_RST  PIN_D4  // Reset pin (could connect to NodeMCU RST, see next line)
//#define TFT_RST  -1  // Set TFT_RST to -1 if the display RESET is connected to NodeMCU RST or 3.3V

// ###### EDIT THE PIN NUMBERS IN THE LINES FOLLOWING TO SUIT YOUR ESP32 SETUP   ######

// For ESP32 Dev board (only tested with ILI9341 display)
// The hardware SPI can be mapped to any pins

 #define TFT_MISO 10
 #define TFT_MOSI 13
 #define TFT_SCLK 14
 //#define TFT_CS   15      // Chip select control pin
 #define TFT_CS   -1      // Set TFT_CS to -1 if the display CS is connected to GND
 #define TFT_DC    32      // Data Command control pin
 #define TFT_RST   33      // Reset pin (could connect to RST pin)
 //#define TFT_RST  -1      // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST
#define TFT_BL   35  // LED back-light

// For the M5Stack module use these #define lines
//#define TFT_MISO 19
//#define TFT_MOSI 23
//#define TFT_SCLK 18
//#define TFT_CS   14  // Chip select control pin
//#define TFT_DC   27  // Data Command control pin
//#define TFT_RST  33  // Reset pin (could connect to Arduino RESET pin)
//#define TFT_BL   32  // LED back-light (required for M5Stack)

// ######       EDIT THE PINs BELOW TO SUIT YOUR ESP32 PARALLEL TFT SETUP        ######

// The library supports 8 bit parallel TFTs with the ESP32, the pin
// selection below is compatible with ESP32 boards in UNO format.
// Wemos D32 boards need to be modified, see diagram in Tools folder.
// Only ILI9481 and ILI9341 based displays have been tested!

// Parallel bus is only supported on ESP32
// Uncomment line below to use ESP32 Parallel interface instead of SPI

//#define ESP32_PARALLEL

// The ESP32 and TFT the pins used for testing are:
//#define TFT_CS   33  // Chip select control pin (library pulls permanently low
//#define TFT_DC   15  // Data Command control pin - must use a pin in the range 0-31
//#define TFT_RST  32  // Reset pin, toggles on startup

//#define TFT_WR    4  // Write strobe control pin - must use a pin in the range 0-31
//#define TFT_RD    2  // Read strobe control pin

//#define TFT_D0   12  // Must use pins in the range 0-31 for the data bus
//#define TFT_D1   13  // so a single register write sets/clears all bits.
//#define TFT_D2   26  // Pins can be randomly assigned, this does not affect
//#define TFT_D3   25  // TFT screen update performance.
//#define TFT_D4   17
//#define TFT_D5   16
//#define TFT_D6   27
//#define TFT_D7   14

// ##################################################################################
//
// Section 3. Define the fonts that are to be used here
//
// ##################################################################################

// Comment out the #defines below with // to stop that font being loaded
// The ESP8366 and ESP32 have plenty of memory so commenting out fonts is not
// normally necessary. If all fonts are loaded the extra FLASH space required is
// about 17Kbytes. To save FLASH space only enable the fonts you need!

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
//#define LOAD_FONT8N // Font 8. Alternative to Font 8 above, slightly narrower, so 3 digits fit a 160 pixel TFT
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

// Comment out the #define below to stop the SPIFFS filing system and smooth font code being loaded
// this will save ~20kbytes of FLASH
//#define SMOOTH_FONT

// ##################################################################################
//
// Section 4. Other options
//
// ##################################################################################

// Define the SPI clock frequency, this affects the graphics rendering speed. Too
// fast and the TFT driver will not keep up and display corruption appears.
// With an ILI9341 display 40MHz works OK, 80MHz sometimes fails
// With a ST7735 display more than 27MHz may not work (spurious pixels and lines)
// With an ILI9163 display 27 MHz works OK.
// The RPi typically only works at 20MHz maximum.

// #define SPI_FREQUENCY   1000000
// #define SPI_FREQUENCY   5000000
// #define SPI_FREQUENCY  10000000
// #define SPI_FREQUENCY  20000000
#define SPI_FREQUENCY  27000000 // Actually sets it to 26.67MHz = 80/3
// #define SPI_FREQUENCY  40000000 // Maximum to use SPIFFS
// #define SPI_FREQUENCY  80000000

// Optional reduced SPI frequency for reading TFT
#define SPI_READ_FREQUENCY  20000000

// The XPT2046 requires a lower SPI clock rate of 2.5MHz so we define that here:
#define SPI_TOUCH_FREQUENCY  2500000

// The ESP32 has 2 free SPI ports i.e. VSPI and HSPI, the VSPI is the default.
// If the VSPI port is in use and pins are not accessible (e.g. TTGO T-Beam)
// then uncomment the following line:
#define USE_HSPI_PORT

// Comment out the following #define if "SPI Transactions" do not need to be
// supported. When commented out the code size will be smaller and sketches will
// run slightly faster, so leave it commented out unless you need it!

// Transaction support is needed to work with SD library but not needed with TFT_SdFat
// Transaction support is required if other SPI devices are connected.

// Transactions are automatically enabled by the library for an ESP32 (to use HAL mutex)
// so changing it here has no effect

// #define SUPPORT_TRANSACTIONS
`

**Comment by Bodmer** [comment]
Your code is jumbled by formatting issues. Please create a zip of you sketch and drag to the comment window to upload.

**Comment by ThatBigPrint** [comment]
[WORKING_1.4_atempt_lcd 2.zip](https://github.com/Bodmer/TFT_eSPI/files/3513466/WORKING_1.4_atempt_lcd.2.zip)

**Comment by ThatBigPrint** [comment]
also there will be a chart displayed but we are not sure how we can update this and the non static text ie pressure readings etc my friend mentioned we will need to keep the previus reading in buffer and turn it white ?

**Comment by ThatBigPrint** [comment]
any updates please ? we are stumped still

**Comment by Bodmer** [comment]
I have run your example code and there are multiple issues:

1. Text leaving remnants on the  screen - use tft.setTextPadding() and setTextDatum() functions, see examples
2. High screen update rate - humans cannot read rapidly updated numbers, add a delay(250) at the end of the loop.

As I am busy with paid work at the moment I have very limited spare time to support your sketch development. Look at the examples and see how they work.
