### ISSUE TITLE
Library is slow in combination with PaulStoffregen / XPT2046_Touchscreen and ESP8266

### ISSUE THREAD

**Issue by Nulista** [Bodmer/TFT_eSPI#42]
Hello,

In combination with the PaulStoffregen / XPT2046_Touchscreen, the library becomes slow,
I have added the following in the TFT_eSPI.cpp init section, (after #ifdef ESP32...)

#ifdef ESP8266 // Unlock the SPI hal mutex and set the lock management flags
    SPI.beginTransaction(SPISettings(SPI_FREQUENCY, MSBFIRST, SPI_MODE0));
    inTransaction = true; // Flag to stop intermediate spi_end calls
    locked = false;       // Flag to stop repeat beginTransaction calls
  #endif_**

and now al works fine...
Is it correct what i have done?

thx.
Nulista

**Comment by Nulista** [comment]
Hello,

Sorry but my previous note is not correct, after a while it don't work fast, and now it is run fast again..
I don't no what it could be... Does anyone have a suggestion?
TFT_eSPI is so a great library!! 

thx
Nulista

**Comment by Bodmer** [comment]
It is not clear what processor you are using, I assume an ESP32.

The TFT_eSPI library is correctly using the ESP32 mutex as far as I am aware. The ESP32 has a dual core processor and I/O resources are shared, hence the need for a mutex. The ESP8266 does not use a mutex as it has a single processor.

I suspect the XPT2046_Touchscreen library is the one that is causing the problem and is not written to support the ESP32 which has special requirements for SPI access. Another issue could be that it is changing the SPI clock rate to a much lower value and is not changing it back.

**Comment by Nulista** [comment]
Hey,
I use both, the ESP32 and the ESP8266. Both of them have the same problem.
A tft.fillScreen takes more than 1 sec. ... If I use "tft.init" for a fillScreen, it will be working correctly, very fast.
It will probably be on the XPT2046_Touchscreen library.
Do you have a good XPT2046 library that works correctly?

Thx
Nulista

**Comment by maxpautsch** [comment]
i just created a pull request for my patch which includes this touch controller in the library.

**Comment by Bodmer** [comment]
Touch screen code by Max merged into library. Thanks.
