### ISSUE TITLE
plot area not centered question

### ISSUE THREAD

**Issue by DaveNorth866** [Bodmer/TFT_eSPI#420]
First of all thank you for this great project you've clearly put a lot of work in to it and its working perfectly for me, however I have just one question, Im using a wemos Lolin 2.4 TFT directly attached a wemos di mini pro but the screen plotting area is not quite central on the screen theirs a bigger gap on the right-hand side of the screen, is there anyway to calibrate the screen to move the whole plotting area over a bit ? or is it just a case of how the screen is manufactured ?
![image](https://user-images.githubusercontent.com/53313554/64031990-77849080-cb41-11e9-86ef-7ecea6855441.png)

**Comment by Bodmer** [comment]
That is how the displays are made. There are Chip-on-Glass driver ICs in that area to drive the pixels.  There's nothing you can do about it apart from make a bezel that has a window for just the display area.
