### ISSUE TITLE
setAddrWindow() troubles

### ISSUE THREAD

**Issue by themakerbro** [Bodmer/TFT_eSPI#424]
Hi! I suspect updates to the Adafruit library may need addressing(?). In issue #309 you helped me solve the skewing issue by using different parameters in the setAddrWindow() function. I tried uploading the updated example code and I see a similar skew than I did originally:

![IMG_8852](https://user-images.githubusercontent.com/7302561/64492529-a7125780-d229-11e9-8d0f-6a74e2b52759.JPG)

Moreover if I try different parameters on the function (e.g., `setAddrWindow(20,10,128,128);`), the image becomes garbled: 

![IMG_8853](https://user-images.githubusercontent.com/7302561/64492543-bee9db80-d229-11e9-8964-ccc9bd8a8195.JPG)

Any suggestion are much appreciated!

**Comment by Bodmer** [comment]
I will investigate, it may be that the library example needs to be updated.

**Comment by Bodmer** [comment]
Now fixed in the Github copy of the example. Thanks for reporting the problem.
