### ISSUE TITLE
initButton text alignment

### ISSUE THREAD

**Issue by justcallmekoko** [Bodmer/TFT_eSPI#425]
Not sure if this is the appropriate place for this question.

Is there a method I overlooked which allows me to align the text of a button to the left of the button rather than the center?

I want the entire button to extend from one end of the display to the other, but I want the text of the button to be aligned to the left of the button (with some additional padding).

**Comment by Bodmer** [comment]
The button class always centers the text by [setting the datum](https://github.com/Bodmer/TFT_eSPI/blob/master/Extensions/Button.cpp#L59). There is also a label size limit of 8 characters.

The only way around this without changing the library is to write a function in your she th using the library code as a guide. You could also add your own left justified button function by extending the [TFT_eFX library](https://github.com/Bodmer/TFT_eFX).

**Comment by justcallmekoko** [comment]
> The button class always centers the text by [setting the datum](https://github.com/Bodmer/TFT_eSPI/blob/master/Extensions/Button.cpp#L59). There is also a label size limit of 8 characters.
> 
> The only way around this without changing the library is to write a function in your she th using the library code as a guide. You could also add your own left justified button function by extending the [TFT_eFX library](https://github.com/Bodmer/TFT_eFX).

I did what you said and extended the library. I didn't notice you had the datum text alignments in TFT_eSPI.h. Thanks for the help and the awesome library.
