### ISSUE TITLE
Arduino Mega code request

### ISSUE THREAD

**Issue by mib1978** [Bodmer/TFT_eSPI#434]
Hello Bodmer! You can help me with a arduino mega code using your TFT-HX8357? 
I realize an 16 channel analog voltmeter with arduino mega. I display my information in text mode, and i wish displayng that, like in your exemple from this library, Meters, in bargraph mode for all 16 channels. If you want and can, please help me with this code. Thank you!

**Comment by Bodmer** [comment]
Try the attached, note that the meter positions are hard coded and thus you will need to understand how it works if you want to move them elsewhere on the display.
[TFT_Meters16.zip](https://github.com/Bodmer/TFT_eSPI/files/3697217/TFT_Meters16.zip)
