### ISSUE TITLE
Example issue with touch

### ISSUE THREAD

**Issue by Terixxx** [Bodmer/TFT_eSPI#435]
Hello,

My setup is:
TFT_eSPI ver = 1.4.16
Processor    = ESP32
Frequency    = 240 MHz
Transactions = Yes 
Interface    = SPI 
Display driver = 9341
Display width  = 240 
Display height = 320 

MOSI    = D23 (GPIO 23)
MISO    = D5 (GPIO 5)
SCK     = D18 (GPIO 18)
TFT_CS   = D15 (GPIO 15)
TFT_DC   = D2 (GPIO 2)
TOUCH_CS = D21 (GPIO 21)

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.0 MHz 
Touch SPI frequency   = 2.5 MHz

I am trying example "Touch_calibrate" and everything is good and this is serial output:
// Use this calibration code in setup():
  uint16_t calData[5] = { 493, 3260, 431, 3204, 7 };
  tft.setTouch(calData);

 But when i try example "Keypad_240x320" I don't have working touch. What is wrong?

**Comment by Bodmer** [comment]
Unfortunately, due to the way the library evolved, the "Keypad_240x320" example has it's own different calibrate function that must be run.

at some point I will update the example.
