### ISSUE TITLE
PFont Antialiased font

### ISSUE THREAD

**Issue by PBearSolutions** [Bodmer/TFT_eSPI#443]
Did you every get the pfont Antialiasing processing working on the arduinos ? looking fro a solution to help smooth out some fonts.

https://forum.arduino.cc/index.php?topic=519297.0

**Comment by Bodmer** [comment]
Yes, the fonts are working with this TFT_eSPI library and ESP8266 and ESP32 processor boards.

See [examples](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Smooth%20Fonts).
