### ISSUE TITLE
println generates exception when calling it with a string that contains a multi-byte-emoji-character

### ISSUE THREAD

**Issue by pvangeel** [Bodmer/TFT_eSPI#445]
I tried printing a list of wifi names and one of them looks like this: "#9 👨‍🎓👩‍🎓"
which then fails if it is passed to the println function.

I see there's a decodeUTF8 function but I think it is not working properly in this case.

**Comment by Bodmer** [comment]
I have tried the character sequence and it did not cause a crash.

How are the characters saved, if they are in a char array then make sure the array is big enough?  Bear in mind that as a byte sequence the example character sequence above looks like this when UTF8 encoded:

```
0x23 0x39 0x20 0xf0 0x9f 0x91 0xa8 0xe2 0x80 0x8d 0xf0 0x9f 0x8e 0x93 0xf0 0x9f 0x91 0xa9 0xe2 0x80 0x8d 0xf0 0x9f 0x8e 0x93 0x0a
```
So a char array would need a size of at least 27.
