### ISSUE TITLE
Request: Draw a rectangle of a sprite, not the whole thing

### ISSUE THREAD

**Issue by Lebo77** [Bodmer/TFT_eSPI#450]
Maybe there is already a way to do this, but I can't seem to find it.

I would like to push a rectangular section of a sprite (defined by one corner and a height and width) without pushing the whole sprite. This would be useful for scrolling text, as you could draw all the text to the sprite, leaving space on say the left. Then you could scroll the text into the area of the sprite drawn each time you called the push command. 

Alternatively you could fill the sprite with the text, then draw a sliding window onto the screen, to make it appear the text was scrolling. 

If there is a better way to do this, please feel free to ignore this, but I have been hitting a wall on how to do this, despite looking at the examples.

**Comment by Bodmer** [comment]
Thereis no function to do this in the library.

The method used by the "Sprite_scroll_16bit" example to scroll text is to keep erasing the content of a sprite then draw text over the sprite in a new position. Note that you can start and end a cursor position outside of the sprite area and only the characters and character portions that cover the sprite area will be plotted in the sprite. So say you create a sprite 100 pixels wide, start with the cursor at say 100, 0 draw the text, plot the sprite to the screen.  Then clear the sprite, and draw the text 1 pixel to the left e.g. 99,0  then plot the sprite again to the screen, repeat as needed to scroll the complete line. This means you do not waste a lot of RAM holding bits of sprite that are not displayed on screen.

Having said that this sketch does what you ask for 16 bit sprites:
```
/*
  Draw a rectangular portion of a sprite
  Created by Bodmer 27/10/19
*/

// Size of sprite image
#define IWIDTH  160
#define IHEIGHT 26

#include <TFT_eSPI.h>                 // Include the graphics library (this includes the sprite functions)

TFT_eSPI    tft = TFT_eSPI();         // Create object "tft"

TFT_eSprite img = TFT_eSprite(&tft);  // Create Sprite object "img" with pointer to "tft" object
//                                    // the pointer is used by pushSprite() to push it onto the TFT

uint16_t* sprite;

// -------------------------------------------------------------------------
// Setup
// -------------------------------------------------------------------------
void setup(void) {
  tft.init();
  tft.setRotation(0);

  tft.fillScreen(TFT_BLUE);

  // Create sprite and save pointer to image area
  sprite = (uint16_t*)img.createSprite(IWIDTH, IHEIGHT);

  img.setCursor(0, 2);          // Position cursor in sprite
  img.setTextFont(4);           // Font 4 selected
  img.setTextColor(TFT_WHITE);  // White text, no background colour
  img.print("Hello World");     // Print text
}

// -------------------------------------------------------------------------
// Main loop
// -------------------------------------------------------------------------
void loop() {
  // Push whole sprite to screen
  pushSpriteRect( 0, 0, IWIDTH, IHEIGHT, 0, 0);

  // Push a portion of the sprite to the screen at 80, 120
  pushSpriteRect( 10, 5, 100, 12, 80, 120);

  while(1) yield();
}

/* Draw a rectangular portion of the sprite to the TFT
xs = sprite x
ys = sprite y
ws = width of rectangle
hs = height of rectangle
xt = tft x position
yt = tft y position
*/
void pushSpriteRect(uint16_t xs, uint16_t ys, uint16_t ws, uint16_t hs, int16_t xt, int16_t yt)
{
  // Do nothing if any part of rectangle is outside sprite
  if ( ((xs + ws) > IWIDTH) || ((ys + hs) > IHEIGHT) ) return;

  uint16_t dh = 0;

  while(dh < hs) {
    // Push to TFT 1 line at a time
    tft.pushImage( xt, yt + dh, ws, 1, sprite + xs + ((ys + dh) * IWIDTH) );
    dh++;
  }
}
```
