### ISSUE TITLE
'class TFT_eSPI' has no member named 'setTouch'

### ISSUE THREAD

**Issue by Paul-Ernest** [Bodmer/TFT_eSPI#454]
Hi Bodmer and thanks a lot for the library.

I have a esp32 TTGO-T1, use with ili9431

---------------------
 User_Setup.h 

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   22  
#define TFT_DC   21 
#define TOUCH_CS 16
---------------------

 User_Setup_Select.h 

#include <User_Setups/Setup1_ILI9341.h>

---------------------------------------------

TFT_eSPI.h

#define ESP32 

------------------------------------------

I receive this: 'class TFT_eSPI' has no member named 'setTouch'
when to try upload file = Touch_Controler_Demo 

Thanks

**Comment by Paul-Ernest** [comment]
Sorry, i use with ili9431

**Comment by Paul-Ernest** [comment]
I found my bug, thanks for all Bodmer.

**Comment by Bodmer** [comment]
You need to comment out [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L22), enable [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L24) and add your TOUCH_CS pin definition to [Setup1_ILI9341.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup1_ILI9341.h)

**Comment by Paul-Ernest** [comment]
thank you very much from Montréal.

**Comment by philoupsss** [comment]
bonjour j'ai un esp32 flasher avec marauder, un flipper zero et un ecran TFT SPI, j'ai trouvé comment faire tous les câblages mais il me manque la partie code, pourriez vous m'indiquer un tuto débutant svp ?

**Comment by Trinnss** [comment]
> I've find my bug, thanks for all Bodmer.



> You need to comment out [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L22), enable [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L24) and add your TOUCH_CS pin definition to [Setup1_ILI9341.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup1_ILI9341.h)



> You need to comment out [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L22), enable [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L24) and add your TOUCH_CS pin definition to [Setup1_ILI9341.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup1_ILI9341.h)

I could not find the lines. Pls help

**Comment by HUGH-TEMPS** [comment]
> > I've find my bug, thanks for all Bodmer.
> 
> > You need to comment out [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L22), enable [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L24) and add your TOUCH_CS pin definition to [Setup1_ILI9341.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup1_ILI9341.h)
> 
> > You need to comment out [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L22), enable [this line](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L24) and add your TOUCH_CS pin definition to [Setup1_ILI9341.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup1_ILI9341.h)
> 
>just uncomment "#include <User_Setups/Setup1_ILI9341.h>" then modify your touch pins in [Setup1_ILI9341.h](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup1_ILI9341.h)
