### ISSUE TITLE
Adding some Color possible?

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#455]
Hello,

is it possible to add some color ind the <TFT_eSPI.h>?
#define TFT_GREY        0x6B6D      /* 108, 108, 108 */

Should I add an PR?

**Comment by Bodmer** [comment]
You can create you own custom colours and add them to your sketch or the setup file.

You can also create colours in the sketch using the functions provided.

**Comment by hasenradball** [comment]
Thanks, where would you place the definition?
In the user_setup_select.h?

**Comment by Bodmer** [comment]
Yes, that would be a good place and the new colour will be available to all sketches.
