### ISSUE TITLE
Question: default Font used 

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#457]
Hi,

I have a short question.
Which font is used a default, when no specific font is set?

The set of a specific font is this done by`tft.setFont()`?

**Comment by Bodmer** [comment]
The default font if none is specified is the "Adafruit" GLCD font which is 7x5 pixels.

tft.setFont( f ); sets the font number, f can be 0, 2, 4, 6, 7 or 8. Fonts 6, 7 an 8 are essentially numeric only fonts.

Font 6 only contains characters [space] 0 1 2 3 4 5 6 7 8 9 : - . a p m
Font 7 (seven segment style) only contains characters [space] 0 1 2 3 4 5 6 7 8 9 0  .  : -
Font 8 only contains characters [space] 0 1 2 3 4 5 6 7 8 9 0 .  : -

If you want to use the Adafruit_GFX style fones then you select the font with setFreeFont(), see examples.

There are also antialiased fonts, see examples.
