### ISSUE TITLE
Question: Class Instantiation

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#458]
Hi I have a short question.

By invoking the class via `TFT_eSpi tft = TFT_eSPI()` is there the copy constructor mechanism used?

Ist it possible to call or set directly a specific rotation?
Like this:

`TFT_eSPI tft = TFT_eSPI() :: setRotation(3)`

Thanks for supporting.

**Comment by Bodmer** [comment]
Instantiating the class only sets up the basic software environment. At that time the display is not initialised, so no display access functions will work until tft.begin() is called.

**Comment by hasenradball** [comment]
So you mean, moving the position definitions to the Haeder file is not possible?
Or is it possible to move the tft.init()` and `tft.setRotatio()` also to the instansiation part in the header file? 

![grafik](https://user-images.githubusercontent.com/26808969/68087092-b17c5680-fe52-11e9-815d-9454d7ae04c3.png)
