### ISSUE TITLE
Screen Orientation problem with ESP32 module and ILI9341 SPI Display.

### ISSUE THREAD

**Issue by fdxrate** [Bodmer/TFT_eSPI#459]
Hi Bodmer,

Thank you for your attention and your work on this library.

This may not be an issue with the library but perhaps more about my lack of understanding the finer points of setup when using TFT_eSPI and M5Stack libraries.

I have attached my Display_Test.ino sketch, my (TFT_eSPI) User_Setup.h and photos of the output showing the screen orientation problem I am experiencing.

Firstly, I have loaded the sketch onto a M5Stack Core and it displays no problem.  When I load the exact same sketch using the same User_Setup.h onto an ESP32 Dev module with an ILI9341 SPI display I get a screen orientation that is flipped and 90deg rotated. Obviously the flipping is fixed by a set.Rotation(5) but I have had no success in my efforts looking for a way to correct the screen orientation. One of the things I did try changing was the orientation in the (TFT_eSPI) ILI9341_Defines.h file but without effect.

Could it have something to do with my ILI9341 SPI Display module or, something in the M5Stack Library?

Any assistance you can provide would be much appreciated. Thank you.

Regards

Geoff

[User_Setup.txt](https://github.com/Bodmer/TFT_eSPI/files/3801336/User_Setup.txt)
[Display_Test.txt](https://github.com/Bodmer/TFT_eSPI/files/3801337/Display_Test.txt)
![ESP32 no rotation](https://user-images.githubusercontent.com/8214848/68081959-6a01c480-fe6a-11e9-82fa-c47574f6e836.jpg)
![ESP32 Rotated](https://user-images.githubusercontent.com/8214848/68081962-6ff7a580-fe6a-11e9-806e-b629c5190899.jpg)

**Comment by Bodmer** [comment]
You are using the M5 Stack library, the M5Stack team have embedded a copy of the TFT_eSPI library and tailored it for their products. Unfortunately that library also incorporates the examples which refer to the original library here... I do not provide support to the M5Stack library!
If you use an ESP32 dev board then load a copy of the TFT_eSPI and use those Config files and examples.
