### ISSUE TITLE
Small Graphics Issue When Showing Time

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#462]
Hi,
when showing time with the following code:
```
  tft.setFreeFont(FSS12);
  tft.setTextColor(color0, color1);
  tft.drawString(timestr, time_in.x, time_in.y, GFXFF);
```

I get the following issue when the second switches from 00 -> 01 (see pic).
How can I solve this?

![grafik](https://user-images.githubusercontent.com/26808969/68091351-e2728080-fe7e-11e9-9a67-e683147989ee.png)

Thanks for your support!

**Comment by Bodmer** [comment]
This occurs because proportion font strings have different lengths. Typically this can be handled by padding with spaces or use the built in setTextPadding() function, [see example](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/320%20x%20240/Free_Font_Demo/Free_Font_Demo.ino#L132).

Also consider setting the datum using [setTextDatum().](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/320%20x%20240/Free_Font_Demo/Free_Font_Demo.ino#L180)

**Comment by hasenradball** [comment]
Thanks :-)

**Comment by hasenradball** [comment]
Is there s possibility to clear a field before drawing a float value like drawfloat(20.5, 1,.... and later float(5.4, 1, ....
Then the display shows 5.45 then.
Or has this also to be done with a padding setting?

**Comment by Bodmer** [comment]
Do it with padding, this is a modified version of an example that will run on a 320x240 display. Read all the comments.
[TFT_Padding_demo_320.zip](https://github.com/Bodmer/TFT_eSPI/files/3809488/TFT_Padding_demo_320.zip)

**Comment by hasenradball** [comment]
Thank you very much for This demo. :-)
This is a perfect learning sketch!

**Comment by hasenradball** [comment]
What exactely does the TextDatum?
This is not really clear to me.
It does not set the floating point decimal point, right?

**Comment by hasenradball** [comment]
To keep the decimal point always at the same possition (1.4 -> 99.4) has nothing to do with setTextDatum, right?

**Comment by Bodmer** [comment]
Correct, however the datum can be used with [the right side position function](https://github.com/Bodmer/DarkSkyWeather/blob/master/examples/TFT_eSPI_weather/TFT_eSPI_weather.ino#L557-L568) to position a float type with a fixed number of decimal places.

**Comment by hasenradball** [comment]
Ist it correct, that the setTextDatum changes the referencePoint of the TFT Display?
Does it have an influence of the axes directions, then?

**Comment by Bodmer** [comment]
A block of text is plotted relative to a point x,y, [see here](https://learn.adafruit.com/adafruit-gfx-graphics-library/graphics-primitives).

TFT_eSPI allows you to change that point to others, say bottom right with setTextDatum.

**Comment by hasenradball** [comment]
Ok thanks the setTextDatum is to makes it easy for programmers to handle the positions.

Thanks

**Comment by hasenradball** [comment]
After looking much lines of code is my understanding right, that with the function drawfloat() it is not possible to align the decimal point.
I musst use a string for the value, right?

**Comment by hasenradball** [comment]
One Question I have actually.
Can your lib also used with an Arduino nano?
