### ISSUE TITLE
R61509V Chip TFT Display Driver

### ISSUE THREAD

**Issue by Jxid** [Bodmer/TFT_eSPI#464]
I like your library very much.
Is there any chance to support the R61509V controler?
I have a 3.0" tft touch display with R61509V chip driver and i would like to use it with your library.
Thank you,
Yannis

**Comment by Bodmer** [comment]
I do not have one of those displays so testing would be a problem. I think that driver needs 16 bit commands so that complicates matters a bit.
Where did you get the display from?

**Comment by Jxid** [comment]
I had bought it from eBay.
I will post the link when I get home and I will post a photo to see how it is. It is an open-smart display.
Thanks for your consern.
Yannis

**Comment by Jxid** [comment]
These are the photos of my display.

![IMG_20191107_202114](https://user-images.githubusercontent.com/57443053/68416448-2e823580-019d-11ea-92cc-a6edb7ea2c4a.jpg)
![IMG_20191107_202106](https://user-images.githubusercontent.com/57443053/68416449-2e823580-019d-11ea-981b-9fbd3bc7e5a2.jpg)
![IMG_20191107_202127](https://user-images.githubusercontent.com/57443053/68416450-2e823580-019d-11ea-8570-6a5bd885eb44.jpg)
![IMG_20191107_202050](https://user-images.githubusercontent.com/57443053/68416451-2e823580-019d-11ea-9eb2-aadd7cc40c8e.jpg)

**Comment by Bodmer** [comment]
OK, it is an 8 bit parallel display. Wiring these to an ESP32 is rather problematic due to the high edge speeds of the signals. I suggest you get an ESP32 UNO style board and ILI9481 board as that will be more reliable.

**Comment by Jxid** [comment]
OK thank you for the info.
I will try something else.
