### ISSUE TITLE
how to make Image array

### ISSUE THREAD

**Issue by rgujju** [Bodmer/TFT_eSPI#47]
How do i make the image array that can be drawn by drawArrayJpeg function?

**Comment by Bodmer** [comment]
There is a function included in the examples folder 160x128 called "TFT_SPIFFS_Jpeg".

Use the IDE to copy the image from you PC into the SPIFFS filinf system that is within the memory of the ESP8266. Then call the createArray("/xxxxx.jpg"); function and the jpeg file will be sent to the serial monitor window in the correct format.  See the comments in the example for more information.

**Comment by rgujju** [comment]
I have made a simple tool to help with this https://github.com/rgujju/jpeg2array

**Comment by Bodmer** [comment]
Great. Thanks for the code.
