### ISSUE TITLE
initButton() doesn't work with antialiased fonts

### ISSUE THREAD

**Issue by PLSousa** [Bodmer/TFT_eSPI#473]
I was not able to use initButton() with antialiased fonts. Could you please check it or provide us an example? Thanks

**Comment by Bodmer** [comment]
Yes, you are right it does not work. The button code needs to be updated to support the new Smooth fonts. I will see what needs to be done.

**Comment by Bodmer** [comment]
OK, I have fixed and tested it. If it still does not work then post back.
