### ISSUE TITLE
SPI devices softmutex

### ISSUE THREAD

**Issue by kostuch** [Bodmer/TFT_eSPI#478]
Hi,
In your code you have function to cover two SPI devices - TFT and TOUCH.
Many boards have three devices - these above and SDcard.
Do you have a plan to implement some mechanism in this lib to allow coexistence on one bus?
I used to use bool flags in main app to cover this problem, but it would be nice if library take care about it.
Maybe by reading SDcard CS line first and deciding if transaction is allowed?

**Comment by Bodmer** [comment]
TFT_eSPI will coexist with a chip select controlled by the SD library.
Enable transactions in the setup for ESP8266, transactions are enabled automatically for ESP32.

[Example here](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Generic/ESP32_SDcard_jpeg/ESP32_SDcard_jpeg.ino) for ESP32, principles are the same for ESP8266.
