### ISSUE TITLE
'class TFT_eSPI' has no member named 'getTouch'

### ISSUE THREAD

**Issue by finchamp** [Bodmer/TFT_eSPI#480]
Hello all,
On compiling any of the examples involving touch, I get compile errors for the public touch functions. Using Arduino 1.8.9, current TFT_eSPI.

**Comment by Bodmer** [comment]
This happens if you do not define a pin  (#define TOUCH_CS xxx), in the setup file.

When no pin is defined the support functions are not compiled in to save FLASH space.

**Comment by finchamp** [comment]
Super, thanks. Working now, of course.
