### ISSUE TITLE
draw gradient line

### ISSUE THREAD

**Issue by tobozo** [Bodmer/TFT_eSPI#483]
Hey @Bodmer and thanks for your marvelous library.

Would you be interested in a PR that implements gradient lines?

https://github.com/tobozo/ESP32-Chimera-Core/pull/6/commits/1c2c182e6ea6670c7973b8908c44ce2a18ca572e

![image](https://user-images.githubusercontent.com/1893754/69815723-37dc4c00-11f7-11ea-842c-9e7968d26a39.png)

**Comment by Bodmer** [comment]
Yes, I am interested but not within the TFT_eSPI library. A good place would be in the graphics extension library [TFT_eFEX.](https://github.com/Bodmer/TFT_eFEX) via a pull request. A simple example will also be needed to show users how to use the functions.

**Comment by tobozo** [comment]
ok the example has been created and a PR ic available here https://github.com/Bodmer/TFT_eFEX/pull/10 

but I'm not happy with the speed so there's probably room for improvement
