### ISSUE TITLE
Character background issue.

### ISSUE THREAD

**Issue by Fredy12335** [Bodmer/TFT_eSPI#487]
First of all thanks for the lib. The best I've ever used. I like it!
When I overwrite another character that is already on the screen, the background of the current character, or glyph, is not cleared, and so the previous character shows through...
 I set to background color black tft.setTextColor(TFT_WHITE, TFT_BLACK); I generated font with Processing 3. To get a better view, I set the screen background to yellow and the font background black. (sorry my english is not the best)

`tft.setTextWrap(true, true);
  String fileName = "Cambria-Bold-32";
  tft.loadFont(fileName);
  tft.setTextColor(TFT_WHITE, TFT_BLACK);
  tft.setCursor(230, 14);
  tft.println(temp);`

![Névtelecn](https://user-images.githubusercontent.com/58340950/70093406-9e5ed100-1620-11ea-95ca-b31ca3eb86fa.jpg)

**Comment by Fredy12335** [comment]
I forget I use ILI9341 (SPI) with Wemos D1 mini pro, (ESP8266).

**Comment by Fredy12335** [comment]
I found this solution in Font_Demo_1 
`tft.fillRect (50, 90, 60, 40, TFT_BLACK); // Overprint with a filled rectangle
 tft.setTextColor(TFT_GREEN, TFT_BLACK);
 tft.setCursor(50, 90);`
But it caused flickering. Is there any easier way?

**Comment by Bodmer** [comment]
Look at the other Font_Demo_2/3/4 examples and you will find a solution. Thesketch  header comments provide help too.

**Comment by Fredy12335** [comment]
Thanks i'm sorry to bother you with such a basic thing. But I think we really need a good documentation. In fact everything is in it the examples, but it's often not easy to find what I'm looking for. Thanks again your jobs and time.

**Comment by Bodmer** [comment]
No problem. documentation is now high on the TO DO list see #415
