### ISSUE TITLE
examples/160x128/RLE_font_test.ino crash

### ISSUE THREAD

**Issue by lumostor** [Bodmer/TFT_eSPI#49]
Good work, really fast.

Just to let you know that the example RLE_font_test in 160x128, crash when a font it use has been commented out in User_setup.h. Not a big deal, but it was my first test with your library, not a good first impression. But, after that, I think I prefer yours to the teensy TFT one.

BTW I'm using it on ESP32 (DOIT devkit V1), with a 1.8" ST7735 display which seems to be GREENTAB2.

Thanks

**Comment by Bodmer** [comment]
Hi,
Thanks for reporting this. It is now fixed.
