### ISSUE TITLE
FS.h missing?

### ISSUE THREAD

**Issue by wmacturk** [Bodmer/TFT_eSPI#492]
This is (from what I'm told) THE library to use for ILI9486, like the 3.5" TFT touchscreen I got. However, the touchscreen examples included all #include FS.h, a header I don't have which wasn't included in the .zip. Where do I get it?

**Comment by Bodmer** [comment]
FS.h is part of the Arduino IDE ESP32 and ESP8266 board packages, currently those are the only processors supported by the library. Check you have the appropriate board package loaded.

I am currently updating the library to support other processors, in particular the STM32, but it will be a few weeks before that is ready for release.

**Comment by Akrai** [comment]
Hi! So if i'm currently using an STM32, can I use the touch functionality of the TFT?

**Comment by Bodmer** [comment]
Yes with some caveats. Yes, support is built in the library if the display is SPI and the touch controller is XPT2046.

**Comment by Akrai** [comment]
Okay but how do I get the FS.h library? Or is it not needed?

**Comment by Bodmer** [comment]
The FS.h library is for ESP32 and ESP8266 processors so that Filing Systems such as SPIFFS or LittleFS can be used. It is not needed for many examples and it is not needed for STM32 processors (which do not have SPIFFS or LittleFS support).

**Comment by Tiramisumisu** [comment]
I wanted to use my font ,so I #define SMOOTH_FONT, but I missing FS.h. My board is Repberry RP2040. If I don't #define SMOOTH_FONT I can't use loadfont function.

**Comment by Bodmer** [comment]
You need to load Earle Philhower's board package to use LittleFS on the RP2040.

**Comment by Tiramisumisu** [comment]
> 

I have load Earle Philhower's board,but how to install LittleFS? I download https://github.com/littlefs-project/littlefs/releases and add to my project, it also have error with #include <LittleFS.h>

**Comment by Bodmer** [comment]
LittleFS is built into Earle's board package so an extra library is not needed and may cause conflicts.

**Comment by ariefazzmi** [comment]
How can we calibrate touchscreen using blue-pill STM32 if we can't access the FS.h file?
