### ISSUE TITLE
Text not centered on button

### ISSUE THREAD

**Issue by Lebo77** [Bodmer/TFT_eSPI#494]
I am attempting to craw a button using the following code:

```
tft.setFreeFont(FSS9);
hoursUp.initButton(&tft, 40, 150, 40, 30, TFT_WHITE, TFT_BLACK, TFT_WHITE, "+", 1);
hoursUp.drawButton();
```

However the + is not centered in the button. It is offset to the bottom third of the button. I have tried using larger font sizes (like FSSB24) but they actually extend beyond the button boundaries. I suspect the center-point of the "+" symbol is not centered on the center of the +. Is there some way (perhaps using fontHeight?) that this could be adjusted?

Thanks. Awesome library.

**Comment by Bodmer** [comment]
Hi,
The library does use the font height metrics to determine the centre and plot the character position. Unfortunately the Adafruit font format has a larger than necessary height allocated above the baseline so there is no simple solution that will work with all fonts.  One approach would be to add extra position adjust parameters to the call. The space in the fonts are quite narrow so left<>right adjustment can be made by adding trailing or leading spaces e.g. "+ ".
You could [change the line](https://github.com/Bodmer/TFT_eSPI/blob/master/Extensions/Button.cpp#L60) here to subtract 4 from the y position of the button text (I added the -4 to do this):
```
  _gfx->drawString(_label, _x1 + (_w/2), _y1 + (_h/2) - 4 );
```
