### ISSUE TITLE
Touch XPT2046 dont work. No touch

### ISSUE THREAD

**Issue by arnold-b** [Bodmer/TFT_eSPI#498]
Hello, 
ESP32
XPT2046 
ST7789_DRIVER

there i don´t find the Problem. For now i changed your touch and using 
https://github.com/PaulStoffregen/XPT2046_Touchscreen

But it is destoyed on every update. May you can help to find my Problem. 

Thanks

//                            USER DEFINED SETTINGS
//   Set driver type, fonts to be loaded, pins used and SPI control method etc
//
//   See the User_Setup_Select.h file if you wish to be able to define multiple
//   setups and then easily select which setup file is used by the compiler.
//
//   If this file is edited correctly then all the library example sketches should
//   run without the need to make any more changes for a particular hardware setup!
//   Note that some sketches are designed for a particular TFT pixel width/height

// ##################################################################################
//
// Section 1. Call up the right driver file and any options for it
//
// ##################################################################################
//
//#define MCP_DRIVER

// Only define one driver, the other ones must be commented out
//#define ILI9341_DRIVER
//#define ST7735_DRIVER      // Define additional parameters below for this display
//#define ILI9163_DRIVER     // Define additional parameters below for this display
//X  #define S6D02A1_DRIVER  // Für 1.8 SPI 128X160 geht Braun
//#define RPI_ILI9486_DRIVER // 20MHz maximum SPI
//#define HX8357D_DRIVER
//#define ILI9481_DRIVER
//#define ILI9486_DRIVER
//#define ILI9488_DRIVER     // WARNING: Do not connect ILI9488 display SDO to MISO if other devices share the SPI bus (TFT SDO does NOT tristate when CS is high)
#define ST7789_DRIVER      // Define additional parameters below for this display
//#define R61581_DRIVER

// Some displays support SPI reads via the MISO pin, other displays have a single
// bi-directional SDA pin and the library will try to read this via the MOSI line.
// To use the SDA line for reading data from the TFT uncomment the following line:

 //#define TFT_SDA_READ      // This option if for ESP32 ONLY, tested with ST7789 display only

// For ST7789 ONLY, define the colour order IF the blue and red are swapped on your display
// Try ONE option at a time to find the correct colour order for your display

 //#define TFT_RGB_ORDER TFT_RGB  // Colour order Red-Green-Blue
//  #define TFT_RGB_ORDER TFT_BGR  // Colour order Blue-Green-Red

// For M5Stack ESP32 module with integrated ILI9341 display ONLY, remove // in line below

// #define M5STACK

// For ST7789, ST7735 and ILI9163 ONLY, define the pixel width and height in portrait orientation
// #define TFT_WIDTH  80
// #define TFT_WIDTH  128
// #define TFT_WIDTH  240 // ST7789 240 x 240 and 240 x 320
// #define TFT_HEIGHT 160
// #define TFT_HEIGHT 128
 #define TFT_HEIGHT 240 // ST7789 240 x 240
 #define TFT_HEIGHT 320 // ST7789 240 x 320

// For ST7735 ONLY, define the type of display, originally this was based on the
// colour of the tab on the screen protector film but this is not always true, so try
// out the different options below if the screen does not display graphics correctly,
// e.g. colours wrong, mirror images, or tray pixels at the edges.
// Comment out ALL BUT ONE of these options for a ST7735 display driver, save this
// this User_Setup file, then rebuild and upload the sketch to the board again:

// If colours are inverted (white shows as black) then uncomment one of the next
// 2 lines try both options, one of the options should correct the inversion.

// #define TFT_INVERSION_ON
 #define TFT_INVERSION_OFF

// If a backlight control signal is available then define the TFT_BL pin in Section 2
// below. The backlight will be turned ON when tft.begin() is called, but the library
// needs to know if the LEDs are ON with the pin HIGH or LOW. If the LEDs are to be
// driven with a PWM signal or turned OFF/ON then this must be handled by the user
// sketch. e.g. with digitalWrite(TFT_BL, LOW);

 //#define TFT_BACKLIGHT_ON HIGH  // HIGH or LOW are options

// ##################################################################################
//
// Section 2. Define the pins that are used to interface with the display here
//
// ##################################################################################

// We must use hardware SPI, a minimum of 3 GPIO pins is needed.
// Typical setup for ESP8266 NodeMCU ESP-12 is :
//
// Display SDO/MISO  to NodeMCU pin D6 (or leave disconnected if not reading TFT)
// Display LED       to NodeMCU pin VIN (or 5V, see below)
// Display SCK       to NodeMCU pin D5
// Display SDI/MOSI  to NodeMCU pin D7
// Display DC (RS/AO)to NodeMCU pin D3
// Display RESET     to NodeMCU pin D4 (or RST, see below)
// Display CS        to NodeMCU pin D8 (or GND, see below)
// Display GND       to NodeMCU pin GND (0V)
// Display VCC       to NodeMCU 5V or 3.3V
//
// The TFT RESET pin can be connected to the NodeMCU RST pin or 3.3V to free up a control pin
//
// The DC (Data Command) pin may be labeled AO or RS (Register Select)
//
// With some displays such as the ILI9341 the TFT CS pin can be connected to GND if no more
// SPI devices (e.g. an SD Card) are connected, in this case comment out the #define TFT_CS
// line below so it is NOT defined. Other displays such at the ST7735 require the TFT CS pin
// to be toggled during setup, so in these cases the TFT_CS line must be defined and connected.
//
// The NodeMCU D0 pin can be used for RST
//
//
// Note: only some versions of the NodeMCU provide the USB 5V on the VIN pin
// If 5V is not available at a pin you can use 3.3V but backlight brightness
// will be lower.

// ###### EDIT THE PIN NUMBERS IN THE LINES FOLLOWING TO SUIT YOUR ESP8266 SETUP ######

#define TFT_RST -1//27
#define TFT_DC 19//16//26  //RS
#define TFT_CS 5//15   // -CS
#define TFT_MISO 26//12//19
#define TFT_MOSI 25//13//23
#define TFT_SCLK 14//14 //18
//HSPI SPI.begin(14, 12, 13, 5);  //void begin(int8_t sck = -1, int8_t miso = -1, int8_t mosi = -1, int8_t ss = -1);
//vspi SPI.begin(18, 19, 23, 15);//void begin(int8_t sck = -1, int8_t miso = -1, int8_t mosi = -1, int8_t ss = -1);

#define TFT_BL 0  // LED back-light (only for ST7789 with backlight control pin)

#define TOUCH_CS 17     // Chip select pin (T_CS) of touch screen

// ######  FOR ESP8266 OVERLAP MODE EDIT THE PIN NUMBERS IN THE FOLLOWING LINES  ######

// Overlap mode shares the ESP8266 FLASH SPI bus with the TFT so has a performance impact
// but saves pins for other functions.
// Use NodeMCU SD0=MISO, SD1=MOSI, CLK=SCLK to connect to TFT in overlap mode

// In ESP8266 overlap mode the following must be defined
//#define TFT_SPI_OVERLAP

// In ESP8266 overlap mode the TFT chip select MUST connect to pin D3
//#define TFT_CS   PIN_D3
//#define TFT_DC   PIN_D5  // Data Command control pin
//#define TFT_RST  PIN_D4  // Reset pin (could connect to NodeMCU RST, see next line)
//#define TFT_RST  -1  // Set TFT_RST to -1 if the display RESET is connected to NodeMCU RST or 3.3V

// ###### EDIT THE PIN NUMBERS IN THE LINES FOLLOWING TO SUIT YOUR ESP32 SETUP   ######

// For ESP32 Dev board (only tested with ILI9341 display)
// The hardware SPI can be mapped to any pins

// For the M5Stack module use these #define lines
//#define TFT_MISO 19
//#define TFT_MOSI 23
//#define TFT_SCLK 18
//#define TFT_CS   14  // Chip select control pin
//#define TFT_DC   27  // Data Command control pin
//#define TFT_RST  33  // Reset pin (could connect to Arduino RESET pin)
//#define TFT_BL   32  // LED back-light (required for M5Stack)

// ##################################################################################
//
// Section 3. Define the fonts that are to be used here
//
// ##################################################################################

// Comment out the #defines below with // to stop that font being loaded
// The ESP8366 and ESP32 have plenty of memory so commenting out fonts is not
// normally necessary. If all fonts are loaded the extra FLASH space required is
// about 17Kbytes. To save FLASH space only enable the fonts you need!

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
//#define LOAD_FONT8N // Font 8. Alternative to Font 8 above, slightly narrower, so 3 digits fit a 160 pixel TFT
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

// Comment out the #define below to stop the SPIFFS filing system and smooth font code being loaded
// this will save ~20kbytes of FLASH
//#define SMOOTH_FONT

// ##################################################################################
//
// Section 4. Other options
//
// ##################################################################################

// Define the SPI clock frequency, this affects the graphics rendering speed. Too
// fast and the TFT driver will not keep up and display corruption appears.
// With an ILI9341 display 40MHz works OK, 80MHz sometimes fails
// With a ST7735 display more than 27MHz may not work (spurious pixels and lines)
// With an ILI9163 display 27 MHz works OK.
// The RPi typically only works at 20MHz maximum.

// #define SPI_FREQUENCY   1000000
// #define SPI_FREQUENCY   5000000
// #define SPI_FREQUENCY  10000000
 #define SPI_FREQUENCY  20000000
// #define SPI_FREQUENCY  27000000 // Actually sets it to 26.67MHz = 80/3
// #define SPI_FREQUENCY  40000000 // Maximum to use SPIFFS
// #define SPI_FREQUENCY  80000000

// Optional reduced SPI frequency for reading TFT
#define SPI_READ_FREQUENCY  20000000

// The XPT2046 requires a lower SPI clock rate of 2.5MHz so we define that here:
#define SPI_TOUCH_FREQUENCY  2000000 //2500000

// The ESP32 has 2 free SPI ports i.e. VSPI and HSPI, the VSPI is the default.
// If the VSPI port is in use and pins are not accessible (e.g. TTGO T-Beam)
// then uncomment the following line:
//#define USE_HSPI_PORT

// Comment out the following #define if "SPI Transactions" do not need to be
// supported. When commented out the code size will be smaller and sketches will
// run slightly faster, so leave it commented out unless you need it!

// Transaction support is needed to work with SD library but not needed with TFT_SdFat
// Transaction support is required if other SPI devices are connected.

// Transactions are automatically enabled by the library for an ESP32 (to use HAL mutex)
// so changing it here has no effect

 #define SUPPORT_TRANSACTIONS

**Comment by Bodmer** [comment]
[Run this sketch](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Test%20and%20diagnostics/Read_User_Setup) to verify the settings are being picked up correctly. Post the serial output here.

Then [run this sketch](https://github.com/Bodmer/TFT_eSPI/tree/master/examples/Test%20and%20diagnostics/Test_Touch_Controller), touch the screen and verify the values output to the serial port change. Post some of the readings here.

**Comment by Bodmer** [comment]
Closing as without feedback this will not get solved.

**Comment by hrauch** [comment]
Hello,
I do have the same problem, but I am using an ILI9341 chip.

These are my changes in User_Setup.h:

// ###### EDIT THE PIN NUMBERS IN THE LINES FOLLOWING TO SUIT YOUR ESP32 SETUP   ######

// For ESP32 Dev board (only tested with ILI9341 display)
// The hardware SPI can be mapped to any pins

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   15  // Chip select control pin
#define TFT_DC    2  // Data Command control pin
#define TFT_RST   4  // Reset pin (could connect to RST pin)
//#define TFT_RST  -1  // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST

#define TOUCH_CS 21     // Chip select pin (T_CS) of touch screen

Here you can see the output of your read_info-sketch:

[code]
TFT_eSPI ver = 2.2.0
Processor    = ESP50
Frequency    = 240 MHz
Transactions = Yes 
Interface    = SPI 
Display driver = 9341
Display width  = 240 
Display height = 320 

MOSI    = D-1 (GPIO 23)
MISO    = D-1 (GPIO 19)
SCK     = D-1 (GPIO 18)
TFT_CS   = D8 (GPIO 15)
TFT_DC   = D4 (GPIO 2)
TFT_RST  = D2 (GPIO 4)

TOUCH_CS = D-1 (GPIO 21)

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.0 MHz 
Touch SPI frequency   = 2.5 MHz 
[/code]

I hope you can give me a hint for solving my touch-problem.
Hans

**Comment by arnold-b** [comment]
Hello, 

i change the code in eSpi to use XPT2046_Touchscreen

Since this i dont have problem

 

#ifdef TOUCH_CS

  #include <XPT2046_Touchscreen.h>

  #ifdef TIRQ_PIN

  XPT2046_Touchscreen ts(TOUCH_CS, TIRQ_PIN);  // Param 2 - Touch IRQ Pin - interrupt enabled polling

#else

XPT2046_Touchscreen ts(TOUCH_CS, 255);  // Param 2 - Touch IRQ Pin - interrupt enabled polling

 

 

 

uint8_t TFT_eSPI::getTouch(uint16_t *x, uint16_t *y, uint16_t threshold){

  uint16_t x_tmp, y_tmp;

  uint8_t valid = 0;

  

  #ifdef TIRQ_PIN 

   if (ts.tirqTouched()) { xx

  #endif

    if (ts.touched()) {

    TS_Point p = ts.getPoint();

  

  if (threshold<20) threshold = 20;

  if (_pressTime > millis()) threshold=20;

uint8_t n = 5;

  x_tmp = p.x;

  y_tmp = p.y;

/* Serial.print(", x = ");

      Serial.print(p.x);

      Serial.print(", y = ");

      Serial.print(p.y);

      

      Serial.println();

                */  

  /*

  while (n--)

  {

    if (validTouch(&x_tmp, &y_tmp, threshold)) valid++;;

  }

*/

/* if (valid<1) { _pressTime = 0; return false; }

  

  _pressTime = millis() + 50;

*/

  convertRawXY(&x_tmp, &y_tmp);

 

  if (x_tmp >= _width || y_tmp >= _height) return valid;

 

  _pressX = x_tmp;

  _pressY = y_tmp;

/*  Serial.print(", tmpx = ");

      Serial.print(x_tmp);

      Serial.print(", tmpy = ");

      Serial.print(y_tmp);

      

      Serial.println();

  */

  valid = 1;

  *x = _pressX;

  *y = _pressY;

  //Serial.printf("Get Touch %d %d  %d\n",_pressX,_pressY,valid);

  

                }

                #ifdef TIRQ_PIN 

   }

   #endif

  return valid; 

}

 

 

Von: hrauch <notifications@github.com> 
Gesendet: Sonntag, 12. April 2020 16:20
An: Bodmer/TFT_eSPI <TFT_eSPI@noreply.github.com>
Cc: arnold-b <arnold.braun@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Bodmer/TFT_eSPI] Touch XPT2046 dont work. No touch (#498)

 

Hello,
I do have the same problem, but I am using an ILI9341 chip.

These are my changes in User_Setup.h:

// ###### EDIT THE PIN NUMBERS IN THE LINES FOLLOWING TO SUIT YOUR ESP32 SETUP ######

// For ESP32 Dev board (only tested with ILI9341 display)
// The hardware SPI can be mapped to any pins

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS 15 // Chip select control pin
#define TFT_DC 2 // Data Command control pin
#define TFT_RST 4 // Reset pin (could connect to RST pin)
//#define TFT_RST -1 // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST

#define TOUCH_CS 21 // Chip select pin (T_CS) of touch screen

Here you can see the output of your read_info-sketch:

[code]
TFT_eSPI ver = 2.2.0
Processor = ESP50
Frequency = 240 MHz
Transactions = Yes
Interface = SPI
Display driver = 9341
Display width = 240
Display height = 320

MOSI = D-1 (GPIO 23)
MISO = D-1 (GPIO 19)
SCK = D-1 (GPIO 18)
TFT_CS = D8 (GPIO 15)
TFT_DC = D4 (GPIO 2)
TFT_RST = D2 (GPIO 4)

TOUCH_CS = D-1 (GPIO 21)

Font GLCD loaded
Font 2 loaded
Font 4 loaded
Font 6 loaded
Font 7 loaded
Font 8 loaded
Smooth font enabled

Display SPI frequency = 27.0 MHz
Touch SPI frequency = 2.5 MHz
[/code]

I hope you can give me a hint for solving my touch-problem.
Hans

**Comment by hrauch** [comment]
Thank you Arnold for your hint.
In the end this info
https://github.com/Bodmer/TFT_eSPI/issues/498#issuecomment-612622537
solved my problem.
May be it should be in the documentation ...
Hans

**Comment by arnold-b** [comment]
I´m happy that i could help you

**Comment by Patman2862** [comment]
Hi Guys, would you please be able to let me know where I need to add Arnolds code?

I am having the same problem as hrauch and Arnolds code seemed to work, but I cant figure out where I need to add it.
Is it in the main code or the TFT_eSPI Cpp file?

Any help would be great, thank you.

**Comment by arnold-b** [comment]
Sorry that i can not help just now. I m far away from my developmentsVon meinem iPhone gesendetAm 28.12.2023 um 00:01 schrieb Patman2862 ***@***.***>:﻿
Hi Guys, would you please be able to let me know where I need to add Arnolds code?
I am having the same problem as hrauch and Arnolds code seemed to work, but I cant figure out where I need to add it.
Is it in the main code or the TFT_eSPI Cpp file?
Any help would be great, thank you.
