### ISSUE TITLE
Lost user settings on library update - not an issue, just how do others save their user settings

### ISSUE THREAD

**Issue by beegee-tokyo** [Bodmer/TFT_eSPI#50]
I had defined my settings for a ILI9163 display connected to an ESP32 in the libraries User_Setups folder and then added it in **`User_Setup_Select.h`**
Using PlatformIO, the library was updated to the latest version today and (of course) the file I created with my display and connection settings was deleted in the process. So I needed to create it again (stupid me didn't have a backup of the file).

Just asking other users if they found a solution to keep their user settings file secure over an update of the library.

I tried to keep my settings file in the project folder and include it just before the **`TFT_eSPI.h`,** and then don't include any standard setting in **`User_Setup_Select.h`**, but that doesn't work.

**Comment by Bodmer** [comment]
One approach is to create a backup copy of the example setup with your changes with a new file name (perhaps just add My to the start of the name = MySetup...) as the existing examples can easily get overwritten when updating. Of course you will still have to make a small edit to call up your particular setup file.

Unfortunately the Arduino IDE that I use does not allow library level configuration from the sketch, hence the rather inelegant method used for tailoring the library to your needs :-(

**Comment by beegee-tokyo** [comment]
Ok, thanks for the feedback. I created my settings.h in my project folder and will copy it to the library folder after an update. I am using PlatformIO and it looks like PIO deletes the folder and replaces it with the new version. My settings had already a unique name and still got deleted.

**Comment by Bodmer** [comment]
A change has been made to User_Setup_Select.h as a recent pull request. This will allow your sketch in PlatformIO to define the settings.

Include:

#define USER_SETUP_LOADED

and define the settings.

**Comment by beegee-tokyo** [comment]
Sounds good. I'll test tomorrow and give u feedback.

**Comment by Bodmer** [comment]
Info from the originator of the pull request [here](https://github.com/Bodmer/TFT_eSPI/pull/67).

**Comment by beegee-tokyo** [comment]
My feedback [here](https://github.com/Bodmer/TFT_eSPI/pull/67)
