### ISSUE TITLE
Available fonts showroom?

### ISSUE THREAD

**Issue by bogus105** [Bodmer/TFT_eSPI#501]
I'd like to pick a proper fonts for my project. However there are lot of fonts and i can not find a convenient way to see them. The only way i know is to make a sketch to load some fonts and send it to esp8266 and see the result on the display.
Major drawbacks of this approach are:
- time consuming
- i'm working on the code now but i do not have a esp8266 w/TFT with me so i can not test the fonts...

Is there some kind on table/photos showing available fonts? 
Thanks.

**Comment by Bodmer** [comment]
Showing the fonts on the screen is the best way to select a font as the appearance is dependent on the screen resolution and pixel size.
Try the examples:
TFT_Rainbow_one_lib - for built in fonts
All_Free_Fonts_Demo -  for free fonts

For Smooth (antialiased) fonts you can choose the font (e.g. Noto) using online resources and then use the processing sketch provided to create the font files needed.
