### ISSUE TITLE
How to config  for 3.5" ILI9486  and TTGO-T Cell (T18)  ?

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eSPI#502]
![image](https://user-images.githubusercontent.com/15370479/71506921-5cd6e400-28b5-11ea-92d1-e9d86efdef85.png)

Hi,
I have tried to config **TFT 3.5" 480x320  ILI9486** from
https://www.aliexpress.com/item/33005785723.html?spm=a2g0s.9042311.0.0.158a4c4dors4ko
to **ESP32 TTGO-T Cell.**

The connections as the upper picture.
And config at `User_Setup.h` like the following code

```c
#define ILI9486_DRIVER

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS    5  // Chip select control pin
#define TFT_DC   22  // Data Command control pin
#define TFT_RST   4  // Reset pin (could connect to RST pin)


#define SPI_FREQUENCY  27000000 // Actually sets it to 26.67MHz = 80/3
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY  2500000

```

When I test by `example > 480x320 > TFT_Rainbow480`,
the result can't show anything.

How to config for **TFT 3.5" 480x320  ILI9486**?
Thank you very much.

**Comment by Bodmer** [comment]
The heading for the advert says it is an ILI9486 but the electrical specs say ILI9488 which is very different.

Try ILI9488_DRIVER

Unfortunately there are many adverts from low cost vendors that quote the wrong driver.

Note the comment associated with this driver in the original setup file. It could be the case that the SD card slot uses the MISO signal:
**WARNING: Do not connect ILI9488 display SDO to MISO if other devices share the SPI bus (TFT SDO does NOT tristate when CS is high)**

**Comment by TridentTD** [comment]
It's worked!  
Driver is LI9488 

Thank you very much for advise and warning

**Comment by Bodmer** [comment]
Thanks for letting me know.
