### ISSUE TITLE
ST7735 1.44" 128x128 weird results

### ISSUE THREAD

**Issue by keejayzee** [Bodmer/TFT_eSPI#507]
I got this ST7735 working nicely with Adafruit's library. Using TFT_eSPI produces weird results using the examples with Arduino IDE with Setup7_ST7735_128x128.h

Any suggestions ? May this be a bug or perhaps an unsupported board ?

. Please, see attached pics.

**BOARD:**
![img1](https://user-images.githubusercontent.com/59285630/71597586-1814ac80-2b44-11ea-9f88-fba1c03204ef.jpg)

**LocalCustomFonts example:**
![img2](https://user-images.githubusercontent.com/59285630/71597690-83f71500-2b44-11ea-87be-d08b92a89062.jpg)

**DrawXBitmap example:**
![img3](https://user-images.githubusercontent.com/59285630/71597841-097ac500-2b45-11ea-9fd1-013816f70e13.jpg)

**UncannyEyes example:**
![img4](https://user-images.githubusercontent.com/59285630/71598202-367ba780-2b46-11ea-9b7f-a19480e3f459.jpg)

**Comment by keejayzee** [comment]
Not sure if I'm violating some github rule, but it is exactly this:
https://www.aliexpress.com/item/32947890530.html?spm=a2g0s.9042311.0.0.49d24c4djwx4hT

**Comment by keejayzee** [comment]
Output from Read_User_Setup:

```
TFT_eSPI ver = 1.4.21
Processor    = ESP8266
Frequency    = 80 MHz
Voltage      = 3.30 V
Transactions = No 
Interface    = SPI 
SPI overlap  = No 

Display driver = 7735
Display width  = 128 
Display height = 128 

R0 y offset = 32 
TFT_CS   = D8 (GPIO 15)
TFT_DC   = D1 (GPIO 5)
TFT_RST  = D0 (GPIO 16)

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.0 MHz 
```

**Comment by Bodmer** [comment]
The problem is that the ST7735 controller supports displays up to 132x160. You have a 128x128 display and manufacturers map this to different positions in the 132x160 area available. So you have yet another variant of the possible mapping.

As the colours look OK, you will have to experiemtn to determine the offsets your display needs. To do this use the a setup like this:

#define ST7735_DRIVER

#define ST7735_GREENTAB

In rotation 0 try to establish where the corner pixels are, I can then create add this display variant to those available.

**Comment by Bodmer** [comment]
Other settings to try are:

// #define ST7735_GREENTAB2
// #define ST7735_GREENTAB3

**Comment by keejayzee** [comment]
It's apparently working now. Changing the define ST7735_GREENTAB128 for ST7735_GREENTAB3
as you said did the trick, so I guess it's a 128x128 GRENTAB3 variant. If you want me to do some more tests to check if this is really a new model or whatever, let met know.

```
TFT_eSPI ver = 1.4.21
Processor    = ESP8266
Frequency    = 80 MHz
Voltage      = 3.30 V
Transactions = No 
Interface    = SPI 
SPI overlap  = No 

Display driver = 7735
Display width  = 128 
Display height = 128 

R0 x offset = 2 
R0 y offset = 3 
TFT_CS   = D8 (GPIO 15)
TFT_DC   = D1 (GPIO 5)
TFT_RST  = D0 (GPIO 16)

Font GLCD   loaded
Font 2      loaded
Font 4      loaded
Font 6      loaded
Font 7      loaded
Font 8      loaded
Smooth font enabled

Display SPI frequency = 27.0 MHz 

```
`

**Comment by Bodmer** [comment]
OK, as it is a square display you will probably not need to use setRotation() for a different orientation but if you did you would get the odd behavior again.

To check if the offsets are indeed OK try:
tft.fillScreen(TFT~_BLACK);
tft.drawRect(0,0,128,128,TFT_GREEN);

You should see a green rectangle with no missing sides.

**Comment by keejayzee** [comment]
This is the result.

![IMG_20200101_204806](https://user-images.githubusercontent.com/59285630/71645409-475c2280-2cd8-11ea-9e5a-9e794eb3d321.jpg)

**Comment by Bodmer** [comment]
Looks good. So I will close.
