### ISSUE TITLE
Horizon Demo?

### ISSUE THREAD

**Issue by Snowflake6** [Bodmer/TFT_eSPI#512]
Hi bodmer, you indicated on the Arduino forum (https://forum.arduino.cc/index.php?topic=417918.45) that you created an artificial horizon demo, and would upload it to github... Did you ever find that code?

**Comment by Bodmer** [comment]
Unfortunately I have no idea where that example went. Sorry.

**Comment by Snowflake6** [comment]
Bummer.  Thanks for checking!
