### ISSUE TITLE
Link multiple TTGO Tdisplays

### ISSUE THREAD

**Issue by thedreygen** [Bodmer/TFT_eSPI#516]
Hello, and firstly thank you for the great library! I am currently working on a project using two TTGO Tdisplays and the uncanny eye code by Mysterion, found here https://github.com/Mystereon/TTGO-TDISPLAY-EYES. I am wondering if it is possible to link two displays together to run a single sketch over both displays. I want to have two eyes, but one on each chip (for L and R eye of costume). It would also be fine to do something like reverse the render on the second screen to only generate a single image. I can use wired connections if needed. I am not too adept at coding, so am looking for any guidance or help as I do not know the best way to approach this task.   Thanks again!

**Comment by Bodmer** [comment]
You can do that but you will need to get one processor to communicate the required "look" direction to the other to coordinate eye movement. At the moment eye movements are random.

Bear in mind the "eye" is only 128 pixels across, you can work out the physical displayed size from this, expect the eyes to be very small on the TTGO T display - maybe 15mm from corner to corner (~half human eye size).  A mirrored image will not work unless you want the eyes to look in different directions (cross and splay) which will look very strange.
