### ISSUE TITLE
Question about default fonts

### ISSUE THREAD

**Issue by JPMJPM** [Bodmer/TFT_eSPI#518]
Hi,

Is it possible to add  "º" and "C" to FONT8 default font ? .

Which file I have to edit ?.

Regards.

**Comment by Bodmer** [comment]
The font file is run length encoded so it is difficult to add new characters. Maybe use the small "o" from font 4?

**Comment by JPMJPM** [comment]
Ok, I will look for a large font that includes the centigrade degree character, thanks.
