### ISSUE TITLE
Request: a functions to return current font settings

### ISSUE THREAD

**Issue by Lebo77** [Bodmer/TFT_eSPI#522]
It would be helpful if there were functions that returned the current font, Text Datum, colors, padding, etc. I have multiple tasks making use of them, so I sometimes want to check they are the way I left them when I get to a specific spot in the code. This is mostly for debugging use.

**Comment by Bodmer** [comment]
In some cases there are functions that return the values. In other cases you can access the public global variables in the TFT_eSPI class by using for example "tft.varaiable". Here are some examples:

```
  tft.setTextDatum(TR_DATUM);
  Serial.println(tft.getTextDatum());
  Serial.println(tft.textdatum);

  tft.setTextPadding(123);
  Serial.println(tft.padX);

  Serial.println(tft.textfont);
  Serial.println(tft.textsize);

  Serial.println(tft.getRotation());
  Serial.println(tft.rotation);

  Serial.println(tft.getCursorX());
  Serial.println(tft.cursor_x);

  Serial.println(tft.getCursorY());
  Serial.println(tft.cursor_y);

  Serial.println(tft.textcolor);
  Serial.println(tft.textbgcolor);

  Serial.println(tft.bitmap_fg);
  Serial.println(tft.bitmap_bg);
```
