### ISSUE TITLE
TFT_eSPI with roger's Arduino_stm32 core compatability

### ISSUE THREAD

**Issue by gsaikiran29** [Bodmer/TFT_eSPI#527]
hello,
I tried to compile the example code with roger's Arduino_stm32 core.
getting compilation error 

> SPI_HandleTypeDef not declared in this scope

**Comment by Bodmer** [comment]
The library is not intended to be compatible with Roger Clarke's core.  It is compatible with the [new "official" STM core](https://github.com/stm32duino/Arduino_Core_STM32).
