### ISSUE TITLE
Small bug & fix : GfXUI.cpp

### ISSUE THREAD

**Issue by Gerry33** [Bodmer/TFT_eSPI#53]
Hi,
and big thank for your libs ! 

Here is a small one found in GfxUI.cpp from the examples:
GfxUI.cpp->drawBmp() 
last lines :
```
.... 
 if(!goodBmp) {
	  Serial.print(F("BMP format not recognised. File:"));
	  Serial.println(filename);
  }
  else	// gsi: bug fix: if bmp is faulty, rotation is not set back correctly
	  _tft->setRotation(rotation); // Put back original rotation
}
```
In case of a non- supported BMP ( in my case only 256 colors), the _tft->setRotation() is exexuted even with a faulty bmp. That spoils the whole screen as the rotation is not initialised  then.

br 
Gerry

**Comment by Bodmer** [comment]
Hi Gerry, thanks, I have corrected this.
