### ISSUE TITLE
Qestion regardin uptade of Library

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#533]
Hi,
one short question regarding the the updating of the library.

I do update the TFT_eSPI lib using Arduino IDE.
When updating the lib up to a newer version are my user defined  files in the folder `User_Setups` overwritten or deleted?

**Comment by TonyKenny666** [comment]
I'm using Visual Studio Code and PlatformIO, for me they were overwritten including any files & folders i'd created in the library's folder. I'd suggest taking a backup / copy and then upgrading to find out :)

**Comment by Bodmer** [comment]
Yes.
See the "Tips" I added to the main "ReadMe" page.

**Comment by hasenradball** [comment]
Cool 😎 thanks...
