### ISSUE TITLE
Question re RPI 9486 and CS pin

### ISSUE THREAD

**Issue by TonyKenny666** [Bodmer/TFT_eSPI#534]
Hi again,
I had an interesting accident that I'm curious about with V2.0.

Setup was:
#define RPI_DRIVER
#define RPI_ILI9486_DRIVER // 20MHz maximum SPI
#define TFT_CS   PIN_D8  
#define TFT_DC   PIN_D3  
#define TFT_RST  PIN_D4
... fonts lines as default
#define SPI_FREQUENCY  20000000
 read & touch defaults.

This works fine, the 480x320 demo completes in around 3400ms. 

Discovering this by accident,  increasing the SPI clock to 27MHz, against your advice and get a scrambled screen, but then it got interesting. I changed the CS pin to GPIO 1 , which is not connected to anything and the demo runs fine and completes in 2863ms which is significantly faster.

Pushing it,  I increased to 40MHz which completed the demo in 2323ms but resulted in some loss of quality. But I wonder how much of that is due to hardware limitations and how much to cable quality and cross talk. I'll see if I can get time to attach some shielded cables to the SPI pins to avoid crosstalk and see if we can push this to 40MHz and get back to you, if this is of interest to you, of course.

I've not bought that oscilloscope yet to see what's happening on the outputs but might do that soon.

Thought this might be of interest to you, not sure what the cause is, yet, but a very interesting increase in performance.

**Comment by Bodmer** [comment]
I would check again as the figures you quote do not make sense to me. The RPi boards I have [like this one](https://github.com/Bodmer/TFT_eSPI/blob/master/Tools/RPi_TFT_Connections.png) do not work reliably above 20MHz, especially for block fills. If you want to improve performance then the MHS 4.0 style RPi displays based on the ST7796 are good as an ESP32 can clock them reliably at 80MHz.
