### ISSUE TITLE
Flip screen function

### ISSUE THREAD

**Issue by eugenner** [Bodmer/TFT_eSPI#544]
Hi, thanks for nice working library, 
but is there any simple workaround to get possibility to flip screen content? 
It is useful sometimes when text should be reflected by mirror...

**Comment by Bodmer** [comment]
There is a control register 0x36 (MADCTL) that sets mirroring, it is used by the rotation function, for [example here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/ILI9341_Rotation.h) for the ILI9341 driver. The bits in the data byte are [define here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/ILI9341_Defines.h#L46-L51) for the ILI9341. The bit functions are:

#define TFT_MAD_MY  0x80 // Mirror rows
#define TFT_MAD_MX  0x40 // Mirror columns
#define TFT_MAD_MV  0x20 // Row and column exchange
#define TFT_MAD_ML  0x10 // Vertical refresh order
#define TFT_MAD_BGR 0x08 // RGB or BRG colour order
#define TFT_MAD_MH  0x04 // Horizontal refresh order

Check the data sheet for your TFT controller.
