### ISSUE TITLE
it gives an error while compiling example sketches in the latest commit

### ISSUE THREAD

**Issue by canerblymzlr** [Bodmer/TFT_eSPI#546]
I am trying to upload some example sketches to my ttgo t-display esp32 board but it gives following error. everthing was working in the prior version. can you help with that? thanks

![image](https://user-images.githubusercontent.com/36793593/74581913-170bd300-4f6a-11ea-9820-eb24bd84b03a.png)

**Comment by mr-stivo** [comment]
Same problem. MacOS X. Arduino 1.8.10. Reverting to an older version of the library the example sketch compiles and runs ok.

**Comment by Bodmer** [comment]
Fixed, see latest commit.

**Comment by mr-stivo** [comment]
All good. Compiles ok. Thanks for the quick response and fix!
