### ISSUE TITLE
Multiple or dissimilar screens with separately defined TFT_DC & TFT_CS pins

### ISSUE THREAD

**Issue by BackupAI** [Bodmer/TFT_eSPI#549]
Thank you for putting together such an excellent library. 

I would like to use the TFT_eSPI library to drive both the build-in M5stack core display (ILI9341) as well as a 2nd, external, display (could be another ILI9341- or f.e. HX8357D-based). I have read some of the related issues on your repository, but all of these dealt with multiple TFT_CS only, which could be controlled by setting the signal low for the respective display before writing to it. However, in the case of the M5stack core, the TFT_DC signal for the built-in screen is NOT accessible on the M5stack bus, so in this case I have to be able to specify a separate pair of TFT_DC, TFT_CS signals, not just the TFT_CS,  for the 2nd screen.

What options are there to have two separate TFT_DC, TFT_CS signal pairs defined? 
Would instantiating another copy of the TFT_eSPI library be a possible approach, and if so, what has to be done to make them co-exist (e.g. would parts of the library have to be renamed)? Finally, I do have some flexibility in picking the 2nd display; to this end, is there anything to be gained by picking another ILI9341-based display (as opposed to a dissimilar display like the HX8357D)?

Any pointers to solve this would be greatly appreciated. Thank you.

**Comment by Bodmer** [comment]
The TFT_eSPI library has no built in support for multiple displays. Given your situation I suggest you use two libraries that have different names. The M5Stack library could be used to drive the build in display and the TFT_eSPI library to drive the second display.

Note that the M5Stack library has a built in copy of the TFT_eSPI library which has been renamed so it will not conflict with TFT_eSPI. Given the relatively unique nature of your project I am unable to help further.
