### ISSUE TITLE
STM32F1 - Build flags (BluePill)

### ISSUE THREAD

**Issue by boboxx** [Bodmer/TFT_eSPI#551]
Do I have the correct configuration for a STM32F108 (BluePill), the display is running but it is fairly slow.

[env:stable]
platform = ststm32
framework = arduino
board = bluepill_f103c8 ; STM32 Arduino Core
build_flags =
  -Os
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -D USER_SETUP_LOADED=1
  -D ILI9488_DRIVER=1
  ;-D TFT_WIDTH=480
  ;-D TFT_HEIGHT=320
  -D TFT_MISO=PA6
  -D TFT_MOSI=PA7
  -D TFT_SCLK=PA5
  -D TFT_CS=PA0
  -D TFT_DC=PA1
  -D TFT_RST=PA2
  -D STM32
  -D LOAD_GFXFF

[src.zip](https://github.com/Bodmer/TFT_eSPI/files/4225770/src.zip)

**Comment by Bodmer** [comment]
Add:
-D STM32=1

**Comment by Bodmer** [comment]
Also:
-D SPI_FREQUENCY=36000000

**Comment by boboxx** [comment]
Thank you Bodmer, I had actually already tried with those 2 value also. The gauge and letter drawing seem to be pretty good, it's the reset of drawing a blank square or filling the screen that seem slow.

**Comment by Bodmer** [comment]
Most SPI TFT dispays take 16 bits per pixel, but the ILI9488 requires 3 bytes, so this has a performance impact. To clear the screen you have to send 320*480*3*8 = 3686400 bits to the display. At 36 MHz spi clock 1 bit time is 27.8 ns, so the theoretical minimum  time to clear the screen is 102.4 ms. Smaller rectangles take less time pro rata with area.  If you run the grapics test example it will report the total time to clear the screen 5 times.

You can get higher screen update performance with 8 bit parallel displays.

**Comment by boboxx** [comment]
Ok thank you Bodmer, I guess I will stick to using the ESP32 for this project :)

**Comment by Bodmer** [comment]
I have looked at the code and updated the library to improve the rendering performance for STM32 processors with SPI interface ILI9488 displays (now about 2.5 times faster).
