### ISSUE TITLE
Can examples be compiled for 240x135 screens? (e.g. TTGO T-Display)

### ISSUE THREAD

**Issue by spiff72** [Bodmer/TFT_eSPI#554]
I find that the resolution specific examples from this library don't work well with the TTGO T-display because of its "in-between" resolution.  I would love to see a section of examples tuned for the 240x135 resolution!

Thanks!

**Comment by Bodmer** [comment]
The specific examples have evolved over many years for particular displays and new variants now abound. Ideally I would like to make a set of display resolution agnostic sketches but currently I am busy with other paid for projects!  The ILI9341  based 240x320 displays are very cheap and the TTGO T4 and TM are supported so make good setups to experiment with.
