### ISSUE TITLE
PR Request

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#556]
Hi can I make a Pullrequest?

-> Sorting the Keyword List?

**Comment by Bodmer** [comment]
Check Github tutorials, however a sorted keywords list is not something I am interestes in adding. Originally the list was in the same order as that in the header which groups functions by there functionality. You should use the header files as the function reference si you can see the parameters needed and returned type.

**Comment by Bodmer** [comment]
Check Github tutorials, however a sorted keywords list is not something I am interestes in adding. Originally the list was in the same order as that in the header files which groups functions by there functionality. You should use the header files as the function reference si you can see the parameters needed and returned type.
