### ISSUE TITLE
clear sprites to free up ram while using web server 

### ISSUE THREAD

**Issue by ThatBigPrint** [Bodmer/TFT_eSPI#569]
we are having an issue where the ram is running out preventing us from loading jquery properly we comment out the larger sprites and it returns we have tried to use delete sprite to no avail ?

**Comment by Bodmer** [comment]
The Sprite class uses malloc() and free() so that is all the library can do.  You may find re-organising your software to be more sympathetic to the way the memory is handled and re-allocated may help (e.g. minimize the function calls to memory demanding code while the Sprite exists).
