### ISSUE TITLE
Delete sprite not working ?

### ISSUE THREAD

**Issue by ThatBigPrint** [Bodmer/TFT_eSPI#570]
Hi again we are trying to use the delete sprite but it doesn't seem to clear ram as intending are we misusing the function ? we have stripped as much as we can from the rest of the code and cleared most of the ram intensive libraries we were using 

the main issue we are getting is our embedded jquery is not loading but it will if we manually comment out most of the sprites 

`  /*
  if (updateProg == 1)
  {
    //graph1.fillSprite(bgColour);
    graph1.deleteSprite();
    //graph2.fillSprite(bgColour);
    graph2.deleteSprite();
    //stext1.fillSprite(bgColour);
    
    stext3.fillSprite(bgColour);
    stext3.drawString("Update Page in use", 0, 0, 2);         // SPlash text
    stext3.pushSprite(0, 110);                             // clear to update again
    delay(500);
  }
  */`

**Comment by Bodmer** [comment]
The deleteSprite() function is working. The problem you are seeing is memory fragmentation which can be managed to an extent by using embedded programming techniques. Ultimately it implies that there is not enough RAM on the processor to support the tasks and program memory demands.  Typically the aim is to only use ~50% of RAM when allocating and de-allocating memory is not managed sequentially in a deterministic manner.

You have 2 simple options:
1. Avoid the use of Sprites
2. Use an ESP32 board that has PSRAM fitted as Sprite will automatically use that

You can show the deleteSprite function works by reading the free memory:

```
  Serial.print("Before: "); Serial.println(ESP.getFreeHeap());

  // Create a sprite of defined size
  spr.createSprite(WIDTH, HEIGHT);

  Serial.print("After creation 1: "); Serial.println(ESP.getFreeHeap());

  spr.deleteSprite();

  Serial.print("After deletion 1: "); Serial.println(ESP.getFreeHeap());
```
