### ISSUE TITLE
printToSprite doesn't print first character (Demo 4).

### ISSUE THREAD

**Issue by Gnitry** [Bodmer/TFT_eSPI#572]
2.2 TFT SPI 240x320. ILI9341 is used.

Steps to reproduce:
* Open `examples\Smooth Fonts\FLASH_Array\Font_Demo_4_Array\Font_Demo_4_Array.ino`
* Change line 
`spr.printToSprite("Small 15pt font");    // Prints to tft cursor position, tft cursor NOT moved`
to 
`spr.printToSprite("AA");    // Prints to tft cursor position, tft cursor NOT moved`
* Run
* The display will show only one character "A".

If I try to print "ABC", it will be printed correctly.
If I try to print "A", nothing will be printed.

Test project (using PlatformIO) is attached:
[testespi.zip](https://github.com/Bodmer/TFT_eSPI/files/4356157/testespi.zip)

**Comment by Bodmer** [comment]
I have updated the Sprite.cpp file to fix this.
Thanks for reporting this issue.

**Comment by NYFB8888** [comment]
I have a similar problem using V2.5.34.
Sp.printToSprite(text) where text is a text string = "0" gives nothing, but spr.printToSprite("0"+text) gives me 00 as required.
Moreover, spr.printToSprite(" "+text) does not display any text.

I think that
    while (n < len)
    {
      uint16_t unicode = decodeUTF8((uint8_t*)cbuffer, &n, len - n);
      //Serial.print("Decoded Unicode = 0x");Serial.println(unicode,HEX);
      //Serial.print("n = ");Serial.println(n);
      drawGlyf(Unicode);
    }
DrawGlyph does not print spaces.
