### ISSUE TITLE
LS020 display driver

### ISSUE THREAD

**Issue by Simmm11** [Bodmer/TFT_eSPI#576]
Good afternoon, dear Bodmer!
Is it possible to add LS020 display driver support to the library?

Sincerely, Maxim.

**Comment by Bodmer** [comment]
That driver seems to be a bit of an odd one in that the register select line (RS or DC) is inverted. This means that adding the drivers will not be sufficient and each processor driver would need to be updated.  The display also seems to be a rare.

The process of adding drivers is:
1. Add the following driver specific files to the [TFT_Drivers folder](https://github.com/Bodmer/TFT_eSPI/tree/master/TFT_Drivers):
    a) xxxx_Defines.h
    b) xxx_Init.h
    c) xxx_Rotation.h
2. List the driver in User_Setup_Select.h [here](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup_Select.h#L150) to call up the xxxx_Defines.h.
3.  Call up the  xxx_Init.h for the [display initialisation here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.cpp#L401). Make sure the initi code in xxx_Init.h respects and delays required during initialisation.
4. Call up the xxx_Rotation.h for [rotations here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.cpp#L477).

The code for the processors may also need to be adapted.  If the RS/DC control line is indeed inverted than the driver specific inversion will need to be added.
