### ISSUE TITLE
Lolin (esp32) and ESP8266 for SPFD54124B Driver

### ISSUE THREAD

**Issue by AlshainAvior** [Bodmer/TFT_eSPI#577]
Hi There,

Is it possible to run the 9-bit Software SPI (using 3-Wire) for SPFD54124B Driver, I found there is one library (in below) that run in STM Core.

https://github.com/badgeteam/ugfx/blob/master/boards/addons/gdisp/board_SPFD54124B_stm32f3.h

Would you help to add this driver also so that can running in ESP32 & ESP8266?

Thank you in advance

**Comment by Bodmer** [comment]
Supporting 9 bit SPI displays would require significant changes to the library, so it is not something I would be prepared to do. The 4 wire SPI displays are low cost and commonly available.
