### ISSUE TITLE
Scrolling banner within a square

### ISSUE THREAD

**Issue by stonefire** [Bodmer/TFT_eSPI#579]
Hi Bodmer
Thanks for at great library....working great..
Are there a way to make a scroling text in a square, where the text-length is longer than the square?
In one of your samples you make "Hello" scroling to the left, disapearing and starting allover. I want to make a sentence scrolling in a box/square, like "Breaking news" at the TV....
I've succeded with pushing 8bit - printing the next letter, but ran into troubles that not all characters is 8bit width....
Do tyou have any surgestions ?

Sincerly
Steen
Denmark

**Comment by Bodmer** [comment]
Look at the Sprite_scroll_16bit example.  You should be able to modify that example.
