### ISSUE TITLE
Touch function for ESP32_PARALLEL config is missing in Touch.h

### ISSUE THREAD

**Issue by IndyGoofy** [Bodmer/TFT_eSPI#582]
Dear programmer,

I´m looking for a getTouch-function with using ESP32_PARALLEL connection (no SPI!).

Thanks
Regards
IndyGoofy

**Comment by Bodmer** [comment]
The TFT_eSPI library does not support the resistive touch screens found on typical shields. You can [use this library](https://github.com/s60sc/Adafruit_TouchScreen), an extra wire is needed as shown in that libraries readMe.

Do NOT include a touch pin #define in the TFT_eSPI setup to use that support library.
