### ISSUE TITLE
Setup22_TTGO_T4 Version 1.3 Pin Change

### ISSUE THREAD

**Issue by pascaltippelt** [Bodmer/TFT_eSPI#585]
The Pin #define TFT_DC has changed to 32 in borad version 1.3 ("V13"). See: https://github.com/Xinyuan-LilyGO/LilyGo_Txx

https://github.com/Bodmer/TFT_eSPI/blob/fa2727b51112986d48d8bece45dded754ea0f64a/User_Setups/Setup22_TTGO_T4.h#L12

Info by the way: To activate LCD backlight it is required to set Pin 4 to High:
`pinMode(4,OUTPUT);
  digitalWrite(4,true);`

**Comment by Bodmer** [comment]
Thanks. Added new setup file: Setup22_TTGO_T4_v1.3.h
