### ISSUE TITLE
Button overdraw in Keypad example

### ISSUE THREAD

**Issue by mmmilan** [Bodmer/TFT_eSPI#588]
Hi!

This is my first touch display, so I might be missing something important. Could someone help me, please?

This is an ILI9341 connected to ESP32. I'm using Arduino IDE 1.8.12, ESP32 1.0.4, TFT_eSPI 2.1.4. I've uploaded Keypad_240x320.ino, calibration seems OK, and the keypad shows up properly:
![IMG_20200329_004008](https://user-images.githubusercontent.com/6588203/77836488-db624c80-7156-11ea-94d1-23b300969b27.jpg)

But when I press 1:
![IMG_20200329_004036](https://user-images.githubusercontent.com/6588203/77836489-dbfae300-7156-11ea-8a74-8b6e63d26afd.jpg)

And then 5:
![IMG_20200329_004052](https://user-images.githubusercontent.com/6588203/77836491-dc937980-7156-11ea-8ef6-8c3dddd654e2.jpg)

And then 9:
![IMG_20200329_004108](https://user-images.githubusercontent.com/6588203/77836492-dd2c1000-7156-11ea-84d6-8ea8f2f4005f.jpg)
...the buttons draw over each other and everything.

**Comment by videobuff** [comment]
I have exactly the same issue. Latest library from github

Verstuurd vanaf mijn telefoon
Groeten
Erik

**Comment by Bodmer** [comment]
Thanks for reporting this.
Should now be fixed.

**Comment by mmmilan** [comment]
It's fixed. Thank you!
