### ISSUE TITLE
screen getting stuck on black

### ISSUE THREAD

**Issue by Topgearfanboy** [Bodmer/TFT_eSPI#590]
I am using the TTGO Tdisplay and I am having issues with it occasionally locking the screen up on black. It even happens on the default ttgo screen demo.  The esp32 itself still responds to commands just not the screen. I am not sure what is causing this and i was wondering if there was a way to hard reset the screen through code. Any help with this would be greatly appreciated.

**Comment by Bodmer** [comment]
This library does not have a ttgo screen demo so I suspect you are using a fork of the library... you may need to consult the maintainer of that fork.

TFT_eSPI does support the reinitialisation of a display. You can call tft.init() and that will reselt the display but you really ought to find the cause of the issue.  Possible causes are other libraries that perhaps use the SPI bus or the power supply being inadequate.
