### ISSUE TITLE
3-line Serial Communication

### ISSUE THREAD

**Issue by kdidi** [Bodmer/TFT_eSPI#592]
Hi,

I have an LCD display with an ST7789V Controller in it. The problem I am having is that the LCD does not have a DC/X pin on it. Instead, the only pins it has are: 
SDA - Serial data input/output pin
WR - Second Data lane in 2 data lane serial interface
SCL - Serial Clock Input pin
CS - Chip select signal input 

Any ideas on what I need to do to make this work?

**Comment by Bodmer** [comment]
TFT_eSPI does not support that interface type. I am not aware of any library that does handle the 2 lane data interface.
