### ISSUE TITLE
White screen with Raspberry display and STM32F767ZI

### ISSUE THREAD

**Issue by albertomercurio** [Bodmer/TFT_eSPI#601]
Hello,
i can use perfectly this library with ESP32. Now i want to use it with STM32. I know how to edit the User_Setup_Select.h and the User_Setup files, and i folowed the pin connection expressed in Setup 33. My only question is why i don't need to declare my MISO, MOSI and SCLK pin? Are maybe these the cause of the white screen?

**Comment by Bodmer** [comment]
The Arduino default pins are assumed, e.g.:  Standard Arduino SPI pins are(SCK=D13, MOSI=D11) this is port pins PA5 and PA7 on Nucleo-F767ZI. I used setup 33 for tests.

Unfortunately there are a lot of RPi screen around with different interface circuits. Post a link to the exact display you have.
