### ISSUE TITLE
problem ILI9163 

### ISSUE THREAD

**Issue by Schmithtrigger** [Bodmer/TFT_eSPI#608]
MY TFT  ILI 9163 don't work and i read everithing...

So is a ESP 32 to send informatio to LCD is a custom pcb, 
Result from scketch

16:15:33.817 -> [code]
16:15:33.817 -> TFT_eSPI ver = 2.2.0
16:15:33.817 -> Processor    = ESP50
16:15:33.817 -> Frequency    = 240 MHz
16:15:33.817 -> Transactions = Yes 
16:15:33.817 -> Interface    = SPI 
16:15:33.817 -> Display driver = 9163
16:15:33.817 -> Display width  = 128 
16:15:33.817 -> Display height = 160 
16:15:33.817 -> 
16:15:33.817 -> MOSI    = D7 (GPIO 13)
16:15:33.851 -> MISO    = D6 (GPIO 12)
16:15:33.851 -> SCK     = D5 (GPIO 14)
16:15:33.851 -> TFT_CS   = D4 (GPIO 2)
16:15:33.851 -> TFT_DC   = D2 (GPIO 4)
16:15:33.851 -> TFT_RST  = D3 (GPIO 0)
16:15:33.851 -> 
16:15:33.851 -> Font GLCD   loaded
16:15:33.851 -> Font 2      loaded
16:15:33.851 -> Font 4      loaded
16:15:33.851 -> Font 6      loaded
16:15:33.851 -> Font 7      loaded
16:15:33.851 -> Font 8      loaded
16:15:33.851 -> Smooth font enabled
16:15:33.851 -> 
16:15:33.851 -> Display SPI frequency = 27.0 MHz 
16:15:33.851 -> [/code]

i change in  User_Setup.h the line referent to ILI9163 and uncoment the lines in User_Setup_Select

// Only ONE line below should be uncommented.  Add extra lines and files as needed.

//#include <User_Setup.h>           // Default setup is root library folder

//#include <User_Setups/Setup1_ILI9341.h>  // Setup file configured for my ILI9341
//#include <User_Setups/Setup2_ST7735.h>   // Setup file configured for my ST7735
#include <User_Setups/Setup3_ILI9163.h>  // Setup file configured for my ILI9163 THIS IS MINE

it is possible to Define the pins in the head of my code???like 
#define mosi     = 13
#define miso     = 12
#define SCK       = 14
#define TFT_CS  = 2
#define TFT_DC  =4
#define TFT_RST = 0

**Comment by Bodmer** [comment]
You cannot define the pins in the sketch. I have updated the "Read_User_Setup" sketch in the latest Github copy which would need to be downloaded as a zip file. Keep a copy of your setup somewhere as it may get over-written when you load a new library copy.
