### ISSUE TITLE
Uno D1 ESP8266 and Kedei 3.5" TFT SPI 480x320

### ISSUE THREAD

**Issue by jack2675** [Bodmer/TFT_eSPI#610]
Hello,
First thanks for the great job done!
I'm trying to use Uno D1 ESP8266 with "Kedei 3.5" 480x320 16bit/18bit version 5.0 2016/3/1".
I can't find the right settings to see the TFT working.
On TFT there is only a 8-pin connector (+ power supply) described as below where it's difficult to link to the firmware:
GND       
L_CS (TFT CS?)
CLK         
T_CS (TOUCH CS?)
MISO      
IRQ (Not described?)
MOSI      
GND
I dont' know which is the TFT controller too? ILI9488 or ILI9486? I checked both configurations without success.
I also checked "test and diagnosis" "Read user set-up" and the board returns information which seem not compliant with hardware set-up...
Could you please kindly help?
Thanks and best regards.

**Comment by Bodmer** [comment]
You have identified the pins OK, the IRQ is not needed and is part of the touch interface.

What setup have you used, and what setup is reported?
