### ISSUE TITLE
Use library without Arduino 

### ISSUE THREAD

**Issue by cs3sw** [Bodmer/TFT_eSPI#613]
Hi, 

Is it passable to use your library without Arduino, my mcu is MT7697, it has its own SDK,
not Arduino, Also has his own SPI driver, TFT LCD driver is ILI9341, I would to import your library to
my sdk, is it passable?

Thanks.

BR,
Jack

**Comment by Bodmer** [comment]
You can get an Arduino package to add to the SDK. The library may work with that but may be slow due to the use of generic SPI calls. I have not tried using the library with that processor myself.
