### ISSUE TITLE
TFT_eSPI_ESP32.h  and  ILI9488

### ISSUE THREAD

**Issue by mr-miky** [Bodmer/TFT_eSPI#617]
The combination esp32 with ILI9488 creates misunderstandings.

In TFT_eSPI_ESP32.h in section ILI9488 an empty define should be added:

#define DMA_BUSY_CHECK

Otherwise the compilation fails with undefined DMA_BUSY_CHECK

**Comment by Bodmer** [comment]
Thanks, this should now be fixed.
