### ISSUE TITLE
touch screen in ili9341 esp32 parallel 8 bit mode error 

### ISSUE THREAD

**Issue by adnanhack** [Bodmer/TFT_eSPI#621]
i get this error 'class TFT_eSPI' has no member named 'getTouchRaw' when i try to use Test_Touch_Controller example how to setup it in 8 bit parallel mode 
[User_Setup.zip](https://github.com/Bodmer/TFT_eSPI/files/4607603/User_Setup.zip)

**Comment by Bodmer** [comment]
The library does not support the XPT2046 touch controller or resistive touch screens in parallel mode.

If you are using an MCUfriend UNO style screen then it is likely to have a resisitve screen. In that case [this library ](https://github.com/s60sc/Adafruit_TouchScreen)may work.
