### ISSUE TITLE
drawPixel problem

### ISSUE THREAD

**Issue by cs3sw** [Bodmer/TFT_eSPI#622]
Hi,

Why drawPixel function not use tft_Write_16 or tft_Write_8 to write pixel?
it use sprite class and img8.. to do that, I am a little confused about this,
My MCU is not ESP32 or ESP8266, it is MediaTeK(MT7697) solution by using SPI with ILI9341,
 but I would like implement your library into my project, It worked success with below library, https://github.com/Bodmer/TFT_ILI9341
But now I would like to add custom Fonts, so I would like to use TFT_eSPI library,
Could you gibe me some suggestion with my problem?

Thanks a lot.
BR,
Jack

**Comment by Bodmer** [comment]
img8 is only for Sprites, it is a pointer to memory so pixels can be drawn direct to the Sprite in memory rather than to the screen.
