### ISSUE TITLE
readRect(), pushImage(), setSwapBytes() compatibility

### ISSUE THREAD

**Issue by jpasqua** [Bodmer/TFT_eSPI#625]
During long running operations such as hitting a REST API on a remote server, I provide a visual indication by overlaying an info icon on the screen. Before doing so I read the pixels under the icon position so I can write them back later. I do this using readRect(). I then display the icon and later, when the long operation is over, I replace the icon with the pixels I read earlier.

I have used both pushRect (which is deprecated) and pushImage() to push the pixels back. Both result in pixels exhibiting the swapped bytes effect. My display normally has swpaBytes == true. To work around this I set swapBytes to false, perform the pushImage, then restore swapBytes to true.

**Comment by Bodmer** [comment]
I have updated the lbrary to reinstate pushRect() for use, so it can be used as with the partner function readREct() and so setting swapBytes to false will not be needed.

Thanks for raising this.

**Comment by jpasqua** [comment]
Works great. Thank you for the quick update.

**Comment by jpasqua** [comment]
@bodmer, if you'd like to see the project I'm building with your library, check out the [repo](https://github.com/jpasqua/MultiMon) or this [video](https://www.youtube.com/watch?v=MYjuCYKBxmM)
