### ISSUE TITLE
Word Wrap with Smooth Fonts on TFT?

### ISSUE THREAD

**Issue by TSJim** [Bodmer/TFT_eSPI#626]
I'm using smooth large fonts on a 240x320 TFT, and the text looks SO good!  Thank you for this feature!

Does the library have a function to do word wrapping?  I know it does text wrapping, but it introduces breaks in the middle of words.

Having proper word wrapping would make this smooth font feature even more amazing.

What are your thoughts on this?

**Comment by Bodmer** [comment]
I think this type of function belongs in a companion library such as TFT_eFEX.
You can write a function, for example try this sketch:
[Issue_626.zip](https://github.com/Bodmer/TFT_eSPI/files/4622620/Issue_626.zip)
