### ISSUE TITLE
Screen flickering .. using Font_Demo_1

### ISSUE THREAD

**Issue by schimkat** [Bodmer/TFT_eSPI#633]
Hi Bodmer .. and everyone else. :-)

I'm struggling with screen flickering, which appears every time objects are on top of each other. Right now I'm testing the [Font_Demo_1](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Smooth%20Fonts/SPIFFS/Font_Demo_1/Font_Demo_1.ino) (SPIFFS), and the problem appears it this demo, as well as with my own code.

For reproducing, I just alter line 152 (in [Font_Demo_1](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Smooth%20Fonts/SPIFFS/Font_Demo_1/Font_Demo_1.ino)), for displaying the same string every time, which helps showing the issue:

Line 152:     tft.print("Test");

When printing the same string each time, it's easy to see that flickering appears in the area, that has been "erased" by the fillRect method on line 149.

I'm using the [2.2" inch display](https://www.elektor.com/media/catalog/product/cache/1404d1bfd8e1ad71cc6f16950ff5c805/l/c/lcdisplay_spi_tft_a-web.jpg) on a [NodeMCU](https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/67/10/0e04f320-e4f9-45bb-a24e-0b66a9000dee.JPG) board.

Any hints anyone? :-)

**Comment by schimkat** [comment]
Found the solution .. wrap everything in sprites. :-)

**Comment by Bodmer** [comment]
Well done was about to suggest that.
