### ISSUE TITLE
How to add driver for R61509  8-bits paralell controller?

### ISSUE THREAD

**Issue by ghosttk** [Bodmer/TFT_eSPI#634]
TFT_eSPI works well on my ili9341 display.
I also have a R61509 shield board, it's demo programs work on uno by MCUFRIEND_kbv library.
And I found two header files alongside the demo directory, but I guess they are not used  by the uno demos and not match the "*_Define.h *_Init.h and *_Rotation.h" format.
Could you tell me what to do to add the drivers?
Below are the diver files:
[initialization.zip](https://github.com/Bodmer/TFT_eSPI/files/4647888/initialization.zip)

![O1CN01Sp4op128hYprphlbI_!!22407964](https://user-images.githubusercontent.com/2270028/82276993-60c8e700-99b9-11ea-9636-53160b49b764.jpg)

**Comment by Bodmer** [comment]
The drivers need to be re-written in the *_Define.h *_Init.h and *_Rotation.h format the same as the other drivers.  Also the R61509 is odd in that it expects 16 bit commands, this means the processor specific drivers in the "Processors" folder will also need to be adapted.

The simplest way forward is to get a library compatible display.
