### ISSUE TITLE
JPG to BMP

### ISSUE THREAD

**Issue by mrstanlez** [Bodmer/TFT_eSPI#643]
Hello Mr. Bodmer,

please can you make a simple function for convert JPG to BMP file from SD card to SD card ?
Or any other function to get RGB array for processing ?
This would be really most helpfull.
Thank you.

**Comment by kamorris** [comment]
Hello Mr Stanlez,  It's not so simple to write code to convert jpg to bmp files; looking at https://en.wikipedia.org/wiki/JPEG, the file format is more complex than bmp.  I generally use gimp (which is free) to open the files and save as bmp format.  There are other solutions for converting bmp files to arrays if needed.

**Comment by mrstanlez** [comment]
Hello Kate Morris,
thank you for answering my question. But I wish to do with ESP32, without
any other computer or software. Only read jpeg from SD card and convert it,
save to the SD card.

With java I can write PC program within  5 minute.

Thank you in advance.

št 28. 5. 2020 o 5:33 Kate Morris <notifications@github.com> napísal(a):

**Comment by kamorris** [comment]
Hello Mr Stanlez,

Have you looked at https://github.com/Bodmer/TJpg_Decoder ?

**Comment by mrstanlez** [comment]
Hello Kate,
yes, but I dont know how to get rgb from each pixel from the picture.
So I decided to create own function for converting jpg2bmp wirh esp32.

Thank you. Have a nice day.

Dňa so, 30. máj 2020, 5:21 Kate Morris <notifications@github.com>
napísal(a):

**Comment by kamorris** [comment]
Sounds like you have resolved your issue then?

**Comment by Bodmer** [comment]
If you are using the TJpg_Decoder library then you can get the 24 bit colors output during the decoding [by changing this line](https://github.com/Bodmer/TJpg_Decoder/blob/master/src/tjpgd.h#L10) to:
```
#define JD_FORMAT       0
```
You then get 3 bytes per pixel (R+G+B).
