### ISSUE TITLE
Licence not present?

### ISSUE THREAD

**Issue by NdK73** [Bodmer/TFT_eSPI#65]
Hello.

Could you please specify the licensing terms of the library? GPL? Apache? MIT? PD?

Tks.

**Comment by Bodmer** [comment]
The license info is scattered about in the code based on where the original files came from. I see some of it got accidentally deleted when I pasted in the Sprite class at the end of the .cpp file a few weeks ago.

To try to make it clearer I have added a "license.txt" file.
