### ISSUE TITLE
STM32F103 and ILI9341 driver LCD 8bit parallel mode

### ISSUE THREAD

**Issue by marcomanolo** [Bodmer/TFT_eSPI#653]
Hello,

i need to interface STM32F103 with a ILI9341 driver LCD in 8bit parallel mode.
Can you help me to start? 
Thank you
Marco

**Comment by marcomanolo** [comment]
Hello, now STM32F103 and ILI9341 8 bit parallel mode works well. I also added resistive touch screen.
Now i am trying to use SPI2 withan external EEPROM (SPI1 port is not accessible). How can i use SPI2 (PB12--PB15) ?
Thank you
Marco

**Comment by Bodmer** [comment]
Unfortunately I do not have time to support your project unless you find an issue with the TFT_eSPI library. Maybe there is an EEPROM library you can use?  Maybe use SPI port 2 for the TFT and SPI port 1 for the EEPROM?
