### ISSUE TITLE
4 bit sprites with rotation seems broken

### ISSUE THREAD

**Issue by 0x00null** [Bodmer/TFT_eSPI#654]
Hi,
This is my first dive into this stuff, so please be gentle!

I'm using the TTGO T-Display board (an ESP32 based board with an ST7789V driving a 135x240 TFT screen). I've been happily creating sprites, using the pushRotated(...) functions to generate 'spinning' effects for a small game I'm writing.

I'm trying to move to using 4 bit sprites, as I only need 16 colours and am finding that due to the size of some of the sprites I'm beginning to run into screen tearing issues.

I've found that pushRotated doesn't seem to work for any sprites I've created with a color depth of 4 bits.

Peering into the `sprite.cpp` file, I see in the implementation of `pushRotated` ([line 398](https://github.com/Bodmer/TFT_eSPI/blob/master/Extensions/Sprite.cpp#L398)) we're simply returning false if `_bpp == 4`. Reading through I can't see why this is the case (because I'm a bit slow, I think... I'm used to higher level languages :p).

So my questions are:
- is this right? Is there a reason why I can't use rotation with a 4bpp sprite?
- is there an alternative way to do this?

Thanks!

**Comment by Bodmer** [comment]
The library has been updated to allow rotation of 4bpp Sprites.
