### ISSUE TITLE
Calling setTextColor(xx, xx) after the edge font display error

### ISSUE THREAD

**Issue by LusterWong** [Bodmer/TFT_eSPI#662]
The program uses \examples\160 x 128\Arduino_Life、RLE_Font_test.ino without any modification.

It is found that there are many screens with flower screen phenomenon, two of which display the same content and font, but there is a display error on the edge.

![1](https://user-images.githubusercontent.com/56709609/84368868-b3886e00-ac08-11ea-8813-1315c21c7d85.jpg)

This is the code used in the picture above
 ```
tft.fillScreen(TFT_BLACK);
tft.setTextColor(TFT_BLUE, TFT_BLACK);
tft.drawString("012345", 0, 0, 6);
tft.drawString("6789", 0, 40, 6);
tft.drawString("apm-:.", 0, 80, 6);
delay(WAIT);
```
![2](https://user-images.githubusercontent.com/56709609/84368888-baaf7c00-ac08-11ea-902c-b2548237a3e8.jpg)

This is the code used in the picture above
```
tft.fillScreen(TFT_BROWN);
tft.setTextColor(TFT_BLUE);
tft.drawString("012345", 0, 0, 6);
tft.drawString("6789", 0, 40, 6);
tft.drawString("apm-:.", 0, 80, 6);
delay(WAIT);
```

You can see from the two pictures above that the 5 character on the first line is incorrect, while the other is correct.
The difference is that when calling setTextColor one uses the bgcolor parameter and the other does not. Why does using bgcolor cause wrong characters to be displayed on the edges?

**Comment by LusterWong** [comment]
I use the ESP32 platform, the LCD display chip is st7735, the resolution is 128x160
IDE is eclipse.

**Comment by Bodmer** [comment]
This is a restriction in the way the RLE fonts are rendered for speed since the fonts were originally developed for the humble UNO where every line of code mattered.  When plotting the RLE fonts direct to the screen (i.e. not via a Sprite) then you must ensure all font characters are positioned completely within the screen area.

**Comment by Bodmer** [comment]
I have updated the library to allow partially off screen RLE font rendering.
