### ISSUE TITLE
👉 Upright Mirror Text Option ?

### ISSUE THREAD

**Issue by truonghoangduy** [Bodmer/TFT_eSPI#669]
Hi, @Bodmer  !
I'm using the **ST7735 160x80**
How could i make the text to be **upright mirror** for the prism 🌁
( what are the the option which i has to set )
I look up in the datasheet it said there some things about the **MV MX MY** option
![image](https://user-images.githubusercontent.com/42218324/85194572-16a88d80-b2f8-11ea-8183-ccb19f63718e.png)
![image](https://user-images.githubusercontent.com/42218324/85194506-01cbfa00-b2f8-11ea-92ab-9d76760f2926.png)
if so could you have some snippets which allow the display ( Initialization ) with invoke on a **String**  to view like it to be upright mirror ?
```c
// what are the command for MV MX MY ?
tft.writecommand(...)
// Or
tft.writedata(....)
```
then invoke the [     ] the display will output the following picture ?
```c
tft.drawString(..,..,...,)
```
I really sorry for the misunderstanding of concept I justing started microcontroller from a software guys 🤕 
**Thank you for your advance** ⭐️

![The-three-different-text-transforms-normal-backward-and-mirrored-in-their-two](https://user-images.githubusercontent.com/49011681/85193615-71d88100-b2f4-11ea-9897-7d36bb3cd88f.png)

This is my User Config which **work fine on normal display on the ESP32** ( text orientation, fill rect, color is right )

> Board ESP32-LOLIN
> Platform Arduino framework
> Coding : with PlatfromIO

```c
#define ST7735_DRIVER

#define TFT_WIDTH 80
#define TFT_HEIGHT 160
#define ESP32
#define ST7735_GREENTAB160x80

#ifdef ESP32
#define TFT_MISO 19
#define TFT_MOSI 23 // Data out
#define TFT_SCLK 18
#define TFT_CS 5
#define TFT_RST 2
#define TFT_DC 4 // Reset pin (could connect to RST pin)
//#define TFT_RST  -1  // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST
// Reset pin (could connect to NodeMCU RST, see next line)
#endif

#define LOAD_GLCD  // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2 // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_GFXFF // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts
#define SMOOTH_FONT

//#define SPI_FREQUENCY  20000000
#define SPI_FREQUENCY 27000000 // Actually sets it to 26.67MHz = 80/3
```

**Comment by Bodmer** [comment]
The mirror bits MX, MY, MH and MV are set or cleared when a rotation command is sent [in this code here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/ST7735_Rotation.h), so you could experiment with those bits.

In setup() call setRotation(n) to ensure the mirror bits are updated.

The mirror bits are[ initialised here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/ST7735_Init.h#L27).
