### ISSUE TITLE
Question: Updating

### ISSUE THREAD

**Issue by hasenradball** [Bodmer/TFT_eSPI#670]
Hi I wanna update from 1.4.xx to the latest version.

is there anything to consider when I use esp32 or esp8266?

**Comment by Bodmer** [comment]
No changes to the sketch or hardware should be necessary. To get the latest version you will need to download the zip file from Github.

Make sure you keep a copy of your setup file safe as it settings will be overwritten by the new library image. The library will need to have the setup defined agian if you do not use the default settings.
