### ISSUE TITLE
Matrix demo does not scroll on the new Seeed Wio Terminal - with fix!

### ISSUE THREAD

**Issue by JustAskSmith** [Bodmer/TFT_eSPI#674]
The Matrix demo for the Wio Terminal uses hardware scrolling on the TFT display but it was not working as supplied.

Seeed_forked and supplied your library with their new Wio Terminal. They configured it to use SPI transactions. The Matrix demo is using tft.writecommand() and tft.writedata() which does not start and end a transaction even if they are configured.  Thinking about this I don't see it as a bug in the functions. These low level functions have no idea how many parameters you are going to write. But because of this the chip select was inactive during the command writes and the hardware scroll never happened.

My fix was to add a tft.startWrite() at the beginning and a tft.endWrite() at the end of these two functions in TFT_Matrix.ino:
setupScrollArea()
scroll_slow()

I don't consider myself a good enough C++ programmer or github user to do a pull request on your great work. But If I did I would add those calls to your example wrapped in
     #if defined (SPI_HAS_TRANSACTION) && defined (SUPPORT_TRANSACTIONS) && (HASSPI)
blocks.

I learned a lot going through your code. Thanks for the contribution.

**Comment by Bodmer** [comment]
I suspect this is just a problem with the modified fork you mention, so you ought to post an issue on that forks repository.

The required start and end functions are in the TFT_eSPI library, [see here](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.cpp#L541-L549), so no changes to the sketch included in the master are needed.
