### ISSUE TITLE
How to properly use User_Setup_Select.h under version control?

### ISSUE THREAD

**Issue by vanklompf** [Bodmer/TFT_eSPI#68]
In platformIO User_Setup_Select.h and other driver config headers goes into .piolibdeps folder which should not be under version control. But this causes that every time I reset repo clone, I need to update User_Setup_Select.h with specific driver selection (and other settings like SPI clock frequency).

Is there any way to make those settings be part of project and not library itself? Maybe header that is part of project and overrides at least driver selection?

Great work with library by the way!

**Comment by Bodmer** [comment]
Yes, [see this pull request](https://github.com/Bodmer/TFT_eSPI/pull/67).
