### ISSUE TITLE
TFT_eSPI and SPI_2

### ISSUE THREAD

**Issue by marcomanolo** [Bodmer/TFT_eSPI#690]
Hello, now STM32F103 and ILI9341 8 bit parallel mode works well. I also added resistive touch screen.
Now i am trying to use SPI2 withan external EEPROM (SPI1 port is not accessible). How can i use SPI2 (PB12--PB15) ?
Thank you
Marco

**Comment by Bodmer** [comment]
Define in the setup file. [See here](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h#L241-L250).
