### ISSUE TITLE
API support for custom touchscreen library

### ISSUE THREAD

**Issue by Triangulix** [Bodmer/TFT_eSPI#695]
Hi
I'm using TFT_eSPI in an ESP32 project with as XPT2046 based touchscreen.
Unfortunately the touchscreen library supplied with TFT_eSPI doesn't fit my needs and I have to replace it. Since I still need the SPI sharing between display and touch chip this turns out to be a bit difficult:
The methods for synchronizing the communication are private and entangled with the display library files, forcing me to modify the TFT_eSPI files which will create update issues in the future. I also read the comment by the maintainer that he doesn't use touchscreens by himself and therefore the touch library isn't developed anymore.
For this reason I would like to suggest to expose the necessary functions for sharing the SPI interface with other libaries.

Thanks

**Comment by Bodmer** [comment]
I think you have misunderstood how TFT_eSPI works. It can be used with other touch libraries [such as this one](https://github.com/achillhasler/TFT_eTouch) which was developed as an alternative to the built in one. The only condition is the you do NOT define TOUCH_CS in the setup file, then no touch code is compiled.

Other SPI libraries such as SD and the Adafruit touch can also be used.
