### ISSUE TITLE
A few warnings (not critical) reported by cppcheck

### ISSUE THREAD

**Issue by m-menon** [Bodmer/TFT_eSPI#702]
Thanks for this cool TFT library. I came across a few warnings when I ran a cppcheck from PlatformIO and I thought I'd let you know. None of these are critical but you might want to KIV for future refactoring or something.

Thanks again for the amazing work. This is now my go-to library for all TFT displays :-)
![TFT_eSPI_warnings](https://user-images.githubusercontent.com/10776430/88269489-b21d8b80-cd06-11ea-923b-8e498e9fbfb6.jpg)

**Comment by Bodmer** [comment]
Have removed medium warnings.
