### ISSUE TITLE
Is display initialized function

### ISSUE THREAD

**Issue by daniel-davidsen** [Bodmer/TFT_eSPI#703]
Is there a function there makes a return if the display communication is OK.

Many times the begin() function returns true or false if the initialization was successful or not.
Is there a similar function in the TFT_eSPI library.

**Comment by Bodmer** [comment]
A prerequisite for this to work is that the display can be read. Some displays do not support reading, others have bi-directional SPI interfaces so this complicates matters. A better option is a diagnostic sketch that reads back selected registers based on the displays type.
