### ISSUE TITLE
[Help Needed] Using manual Chip Select

### ISSUE THREAD

**Issue by SunboX** [Bodmer/TFT_eSPI#711]
Hi Bodmer,

I've an issue using manual CS. The issue looks like this:
https://youtu.be/zeu1qS6oa04

I'm using a display with touch. Both display driver and touch controller are running on the same SPI. I want to do the CS manually, because I have to use a GPIO Expander later on. But the issue happens already using only a ESP32. (simplest setup possible) Using your library with the exact same setup, but without manual CS, all works fine.

I'm using TFT_eSPI's built-in ILI9341 driver together with such a "generic" 2.4" touch display:
![87918704-19251100-ca77-11ea-8a43-6dd1385df777](https://user-images.githubusercontent.com/83344/88667928-4199b480-d0e2-11ea-8b3f-a8ee6aeacd9f.png)

I have three of them from different sources and for different prices. Also one from a German seller for "a lot of" money. They behave all the same.

Attached you will find my sample code:
[DisplayTest.zip](https://github.com/Bodmer/TFT_eSPI/files/4988391/DisplayTest.zip)

The Hardware setup looks like this:
![87920545-a8332880-ca79-11ea-98cc-5becc8a6335d](https://user-images.githubusercontent.com/83344/88668030-642bcd80-d0e2-11ea-8acf-161e06efce7f.jpg)

Do you have any clue why it does not work or how I can get it to work? I have no clue whats going wrong here.

**Comment by Bodmer** [comment]
Look at the Arduino Blink example. You will see you need to configure the GPIO pins for output using pinMode. Also you must initialise all chip select pins to the high state at the beginning of setup, otherwise you do not know what state they may be in.

**Comment by SunboX** [comment]
Ahh, I'm an idiot. 😅 You are right, I will try it. Thanks for your support!

**Comment by Bodmer** [comment]
No problem. Hope it works for you. Only other point is the touch screen should be calibrated by running the calibration sketch with the rotation set in that sketch to the rotation you will use in your final project. Let me know how it goes.

**Comment by SunboX** [comment]
It works now, great! Now I can go to the next step and add the GPIO Expander. After that, I will add the second screen. And if this works, I will try to get GUISlice running with it.
