### ISSUE TITLE
M5Stack TFT display type ILI9342C

### ISSUE THREAD

**Issue by patfelst** [Bodmer/TFT_eSPI#713]
I note TFT_eSPI has a setup file M5 stack, just wondering how this works because [M5 stack uses a ILI9342C](https://docs.m5stack.com/#/en/core/fire?id=schematic) and your library does not list this as a supported type:

"The library includes drivers for ILI9341, ILI9163, ST7735, S6D02A1, ILI9481, ILI9486, ILI9488, HX8357D, ST7789 and ST7796".

Are there any compromises or issues using TFT_eSPI on M5 stack? Do sprites work ok - I'm intending on using the "Fire" version of the M5 Stack which has PSRAM.

Thanks

**Comment by Bodmer** [comment]
The original M5Stack modules used an ILI9341 320x240 display. This is supported by TFT_eSPI.

The M5Stack team copied an earlier version of TFT_eSPI into [their own product library](https://github.com/m5stack/M5Stack/tree/master/src/utility) (renamed In_eSPI) but I do not support that library copy. The required setup code appears to be added their to support the new M5Stack teams library, so you could adapt TFT_eSPI.
