### ISSUE TITLE
Nodemcu-8266 and HX8357B Can't show anything

### ISSUE THREAD

**Issue by FantasyGmm** [Bodmer/TFT_eSPI#724]
This screen has only four wires,3.3V GND CLK(D5) MOSI(D7),I changed the display driver to hx8357 on the basis of my previous configuration file. This configuration file was used for ili9314 before and it works
But I changed it to the driver of hx8357, and the screen can't display anything. I tried many examples

**Comment by Bodmer** [comment]
The library does not support that "B" display type or the reduced pin set.
