### ISSUE TITLE
18-bit colour support

### ISSUE THREAD

**Issue by x567234** [Bodmer/TFT_eSPI#725]
I read the documentation and Issues, and I think I understood that the TFT_eSPI supports 18-bit colour for ILI9488. However in your code, the setTextColour uses int16_t for the color, in the colour defines in tft_eSPI.h use 16 bits.
My question: Does the tft_eSPI support 18-bit colours ? WHat do I have to change to get 18-bit Colours?
Thank you for a nice library
Sam

**Comment by Bodmer** [comment]
The ILI9488 uses 18 bit colour in SPI mode. The library converts the 16 bit colour to an 18 bit value. You do not have to do anything.
