### ISSUE TITLE
How to use DMA esp32 with full frame sprite buffer?

### ISSUE THREAD

**Issue by JakubRybakowski** [Bodmer/TFT_eSPI#734]
Hello, I am using 240x320 full frame sprite as buffer with psram. I would like to use DMA but it is limited to 64k. It is posible to use benefits of DMS with that large buffer?

**Comment by Bodmer** [comment]
The STM32 processor is limited to 64K but I think the ESP32 can handle larger buffers. Try it.

**Comment by Bodmer** [comment]
I ran a test and the biggest DMA transaction that proceeded without error was about 124kbytes for a sprite in PSRAM. The maximum 16 bit Sprite size is therefore 240x258.  This means you will have to DMA a full screen buffer for a 240x320 display in two chunks, say 240x160 each.

I do not know what is the limiting factor for the ESP32.

**Comment by JakubRybakowski** [comment]
Thank you for your answer.
I came to the same conclusion that DMA does not work with such a large buffer.
I do not know why. Are you able to confirm that DMA works for PSRAM? I found unofficial information on the internet that DMA only works for Flash in ESP32.

**Comment by Bodmer** [comment]
Yes, DMA works with PSRAM. The Espressif guide is misleading, here is my explanation (based on a limited understanding of the software I think is hidden behind the scenes).

The ESP32 does not use a pure hardware DMA like an STM32 would, instead it uses software to manage the DMA. An ESP32 can only DMA 4Kbytes to the SPI, so there is interrupt driven software running in the background to fill that 4K buffer in normal RAM and manage the copying of data from PSRAM into that buffer. The DMA descriptors are created by the DMA API software in normal RAM and so is the 4K DMA buffer, thus the user manual conditions are not violated. As the buffer management happens in parallel with the SPI DMA transfer you will not see the overhead of the slower PSRAM access and PSRAM to 4K RAM buffer copying.

A 240 x 258 Sprite can be created in PSRAM and DMA'ed to the SPI. This is 124kbytes and would not be possible in normal RAM. When PSRAM is read the processor first moves block of the PSRAM data in sequence into a temporary normal RAM buffer, to the sketch and library never accesses the PSRAM directly. See the discussion in issue #536
