### ISSUE TITLE
Sprite behaving strange

### ISSUE THREAD

**Issue by videobuff** [Bodmer/TFT_eSPI#738]
I have both a 2.8 and 3.5 inch dispay with either the ILI9341 or the  ILI9488. Both work with touch as well.
I like to combine the animated dial and the keypad, but i didn't get that far. With the animated dial (with both screens and libraries)  the dial is eating up the numbers. The video shows clearly what i mean. I haven't been able to solve the issue so far. Latest library installed again today. Help is much appreaciated......

Erik

Here is the YouTube video showing the issue
[https://youtu.be/l1MuyuVZ7D8](https://youtu.be/l1MuyuVZ7D8)

And here the pin assignments
ESP32 WROOM

// #define TFT_MISO 19 // (I leave TFT SDO disconnected)
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS    15  // Chip select control pin
#define TFT_DC    2  // Data Command control pin
#define TFT_RST   4  // Reset pin 

#define TOUCH_CS 21     // Chip select pin (T_CS) of touch screen

**Comment by Bodmer** [comment]
The screen CGRAM must be readable for the animated dial code to work, so you have to connect TFT SDO. This should work fine with the ILI9341.  The ILI9488 does not tristate the SDO line so add a 1K Ohm series resistor at the TFT SDO pin end of the connection.

**Comment by videobuff** [comment]
Thanks very much. It works. Now i will combine the animated dial in compass lay-out together with the keypad to control a hamradio rotor. The screen works, now the functions. I really like your library a lot.
Erik, PA0ESH
<img width="400" alt="Hamradio Rotor Cotroller" src="https://user-images.githubusercontent.com/3132953/91357890-3b3a4d80-e7f2-11ea-8498-2c130b927b50.png">
