### ISSUE TITLE
Cyrillic symbol on screen

### ISSUE THREAD

**Issue by PavelAravin** [Bodmer/TFT_eSPI#742]
Hello. I try to print Cyrillic on screen with TFT_eSPI library but doesn't work.
Using [this font](https://github.com/immortalserg/AdafruitGFXRusFonts/blob/master/FontsRus/TimesNRCyr8.h) and println function. If use write(hex), for example tft.write(0xAF) i see corresponding symbol "Я" or 0xAE - "Ю" etc, it is right, if using tft.print or println symbol not printing, for example tft.println("Библиотека для TFT") on screen render only "TFT". How can this problem be solved?

**Comment by Bodmer** [comment]
This is because the library by default assumes UTF-8 encoding for characters outside the normal ASCII range 32-127.

To switch off the UTF-8 decoding use the following command:
```
tft.setAttribute(UTF8_SWITCH, false);
```
The print strings should then work. Report back if it does or does not work.

**Comment by PavelAravin** [comment]
Yes, it work. Thanks for feedback and good library. 
![IMG_20200907_071057](https://user-images.githubusercontent.com/65659723/92345134-56059f80-f0d9-11ea-8d6c-84458af194da.jpg)
