### ISSUE TITLE
Text background on free fonts

### ISSUE THREAD

**Issue by PavelAravin** [Bodmer/TFT_eSPI#744]
If using free fonts and print function text background does not appear, when updating the text is superimposed on the previous one. How to make the text not overlap without using the fill function?

I almost forgot, for my display to work properly on st7789, you need to enable color inversion in the library settings.

**Comment by Bodmer** [comment]
Fill function is not supported for the print class since caharacters arrive one by one and may overlap.

Use drawString functions, see examples. You can then also set "padding" toso small numbers over-write large ones, see examples.
