### ISSUE TITLE
Using modified glcd font

### ISSUE THREAD

**Issue by PavelAravin** [Bodmer/TFT_eSPI#747]
Dear Bodomer, i try find method to display cyrrilic with fill background, i found on internet modified glcd font for adafruit library with support cyrrilic symbols and backgroung, but adafruit library less stable.
How can connect it with TFT_eSPI? I replace file glcdfont.c and comment all stroke related with font in user_setting except first stroke #define LOAD_GLCD  and compile this code 
 tft.init();
 tft.setTextFont(1);
 tft.setAttribute(UTF8_SWITCH, false);
 tft.fillScreen(TFT_WHITE);
 tft.setCursor(0, 0, 4);
  tft.setTextColor(TFT_RED, TFT_BLACK);
  tft.println("Привет, hello");

But it no work. No display any symbols.
What am I doing wrong?

**Comment by Bodmer** [comment]
See #742 

I assume you can display other Latin ASCII characters (32-127)?

**Comment by PavelAravin** [comment]
No display, clear white screen, if remove comment slash next to font2,
font3, 4, 5,6,7,8 then Latin symbol is visible, Cyrrilic none

пт, 11 сент. 2020 г., 17:14 Bodmer <notifications@github.com>:

**Comment by Bodmer** [comment]
To use background you must use the drawString() functions, this is because the print class sends 1 character at a time and since the character bounding boxes may overlap (e.g. itallic fonts) a simple algorithms to determine the blanking area does not work well.

**Comment by PavelAravin** [comment]
I understand, but this is an alternative to the standard font, namely its replacement. There is no slope, and the symbols are specially made as simple as possible. It's weird that it doesn't work.

**Comment by Bodmer** [comment]
Provide a copy of the font file and I will see if it is in a compatible format.

**Comment by Bodmer** [comment]
Note that:

tft.setTextFont(0);

Selects the glcd font.

**Comment by PavelAravin** [comment]
Yes! It work. I use this glcd.c file [glcdfont.txt](https://github.com/Bodmer/TFT_eSPI/files/5212175/glcdfont.txt)  and utf8rus function.



```
String utf8rus(String source)
{
  int i,k;
  String target;
  unsigned char n;
  char m[2] = { '0', '\0' };

  k = source.length(); i = 0;

  while (i < k) {
    n = source[i]; i++;

    if (n >= 0xC0) {
      switch (n) {
        case 0xD0: {
          n = source[i]; i++;
          if (n == 0x81) { n = 0xA8; break; }
          if (n >= 0x90 && n <= 0xBF) n = n + 0x30;
          break;
        }
        case 0xD1: {
          n = source[i]; i++;
          if (n == 0x91) { n = 0xB8; break; }
          if (n >= 0x80 && n <= 0x8F) n = n + 0x70;
          break;
        }
      }
    }
    m[0] = n; target = target + String(m);
  }
return target;
}
```
Example: 
tft.setTextColor(TFT_WHITE, TFT_BLACK);
tft.setTextFont(0);
tft.setTextSize(2);
tft.setAttribute(UTF8_SWITCH, false);
tft.printl(utf8rus("Мама мыла Милу мылом"));

Symbols displayed with worked background. May be this way to make any language character set?

Showed up1 bug or not bug. The setTextFont parameter must be specified in each function separately, before println.
If it's not difficult, describe an example of using padding in order not to use fillRect if the line has become shorter.
![IMG_20200912_080057](https://user-images.githubusercontent.com/65659723/92987318-9480cd00-f4d2-11ea-9d53-f07f566dd167.jpg)

![IMG_20200912_081736](https://user-images.githubusercontent.com/65659723/92987387-fb9e8180-f4d2-11ea-8311-6856aacd6338.jpg)

**Comment by Bodmer** [comment]
If I understand correctly you have solved it now.

Great!
