### ISSUE TITLE
TJpg_Decoder.h file missing

### ISSUE THREAD

**Issue by guelweles** [Bodmer/TFT_eSPI#750]
Hello there,

First of all, thanks for this amazing library, it helped with some issues I was having while using the adafruit libraries.

I'm trying to run the Animated_dial sketch but the compile says the TJpg_Decoder.h file is missing, I couldn't find it in my folders, not even in your repository, am I doing something wrong?

I'd like to ask you something if you don't mind, the font "7" (digital clock) is something I was looking for and thankfully it comes already with your library, is there any easy way to resize it? It doesn't fit properly on my 128x160 ST7735 screen, I'd like to display numbers such as "-250.00" as I'm building a voltmeter, I tried to use a custom digital font but it flickers a bit, while using yours it doesn't happen.

Thanks

**Comment by Bodmer** [comment]
You need to download the [TJpg_Decoder library](https://github.com/Bodmer/TJpg_Decoder).

The library does not provide functions to reduce the font size.

Incidentally, you would need a 17 bit ADC minimum or oversampling to get 5 digit resolution 0 - 999.99, so the 5th digit is unlikely to be accurate anyway.
