### ISSUE TITLE
MAR3953 (ST7796S) Parallel only module (for MEGA250) - compatibility with BluePill or BlackPill

### ISSUE THREAD

**Issue by baniaque** [Bodmer/TFT_eSPI#757]
Hi,

Have a question about LCD Screen module developed for Arduino MEGA2560. I see that TFT_eSPI support ST7796S chip in 8bit parallel mode. Can I use this LCD module with TFT_eSPI? Somebody tried to use this module with TFT_eSPI and STM32f103 or STM32F411?

http://www.lcdwiki.com/3.95inch_Arduino_Display-Mega2560

**Comment by Bodmer** [comment]
The display driver is supported in 8 bit parallel mode. Parallel mode does work on F103 and F411.
