### ISSUE TITLE
Need an advice for nice video effect/transition

### ISSUE THREAD

**Issue by sensboston** [Bodmer/TFT_eSPI#758]
Hi guys, I working on my version of digital "magic 8 ball". Fortunately, I got my TFT working (thanks to @sukesh-ak!). I have no issue to draw blue filled triangle with random texts but need an advice about nice, "looks like real", transition for appearing a new random "prediction". I googled for similar projects (there are some) but I don't like how these projects implemented. I wanna reach "like real ball" simulation level but with some advantages provided by ESP32: "predictions" on different languages (not English only), custom prediction texts etc. This project should be fun (I hope so!).

So, fade in or zoom in should work nice but I don't know how to implement it with @Bodmer's library. Could you please share your ideas (with samples, if possible)?

**Comment by Bodmer** [comment]
Ask for project help on the Arduino forum. Only raise issues directly associated with the library here on Github.
