### ISSUE TITLE
Flip Horizontal or Flip Vertical

### ISSUE THREAD

**Issue by jkcrbn** [Bodmer/TFT_eSPI#761]
I have a sprite with mirror symmetry that I was going to only put half into memory and push a second rotated sprite adjacent to.  Unfortunately, it is a "flip vertical" transformation, not a rotation, so I will have to make twice as large a sprite.  Perhaps there is a clever workaround, but without a function to do this I don't know how.  However, this would be a nice feature!  Thank you!

**Comment by Bodmer** [comment]
There is no function to do this so you will need to write your own. One approach is to scan the source sprite using spr.readPixel(x,y) and incrementing y coordinates and then draw tft.drawPixel(x2,y2) with decrementing y coordinates.

One day I may write a companion library that does image manipulation but I do not have a project that needs such functions and I am very busy with other tasks!

**Comment by jkcrbn** [comment]
Thank you!
