### ISSUE TITLE
ST7796 in parallel mode and spi touch screen - any posiibility to run?

### ISSUE THREAD

**Issue by baniaque** [Bodmer/TFT_eSPI#765]
Can't compile code when trying to setup touch screen working on ST7796 screen - this screen working only in parallel mode, SPI is used only for SDCard and touch screen. 

Setup:
// The TFT can be connected to SPI port 1 or 2
#define TFT_SPI_PORT 1 // SPI port 1 maximum clock rate is 55MHz
#define TFT_MOSI PA7
#define TFT_MISO PA6
#define TFT_SCLK PA5
#define TOUCH_CS PA4

Error mesage:

In file included from C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\TFT_eSPI.cpp:4279:
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'void TFT_eSPI::begin_touch_read_write()':
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:22:34: error: 'spi' was not declared in this scope; did you mean 'sbi'?
   22 |     if (locked) {locked = false; spi.beginTransaction(SPISettings(SPI_TOUCH_FREQUENCY, MSBFIRST, SPI_MODE0));}
      |                                  ^~~
      |                                  sbi
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'void TFT_eSPI::end_touch_read_write()':
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:37:54: error: 'spi' was not declared in this scope; did you mean 'sbi'?
   37 |     if(!inTransaction) {if (!locked) {locked = true; spi.endTransaction();}}
      |                                                      ^~~
      |                                                      sbi
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'uint8_t TFT_eSPI::getTouchRaw(uint16_t*, uint16_t*)':
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:61:3: error: 'spi' was not declared in this scope; did you mean 'sbi'?
   61 |   spi.transfer(0xd0);                    // Start new YP conversion
      |   ^~~
      |   sbi
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp: In member function 'uint16_t TFT_eSPI::getTouchRawZ()':
C:\Users\baniaque\Documents\Arduino\libraries\TFT_eSPI\Extensions/Touch.cpp:104:3: error: 'spi' was not declared in this scope; did you mean 'sbi'?
  104 |   spi.transfer(0xb0);               // Start new Z1 conversion
      |   ^~~
      |   sbi
exit status 1
Error compiling for board Generic STM32F4 series.

**Comment by Bodmer** [comment]
The library currently does not support a SPI touch controller when the TFT interface is parallel as the support for parallel screen was primarily added for UNO format displays that I use without touch screens.

There are third party libraries ([such as this one](https://github.com/achillhasler/TFT_eTouch/issues/5)) that support SPI touch controllers and can be used in conjunction with a parallel display.

The touch controller support in TFT_eSPI will be deprecated at some point in the future and separate libraries will be recommended, so touch support within TFT_eSPI will not be updated. I now have a screen with capacitive touch so will at some point write a library for that.
