### ISSUE TITLE
Flickering even when draw same number/text in the same place

### ISSUE THREAD

**Issue by baniaque** [Bodmer/TFT_eSPI#766]
I have issue with flickering when refreshing number or text in this same area, even if number or text is identical. This is visible even in very fast parallel connection on STM32F411 with defined STM_PORTA_DATA_BUS. 
Recorded video: 
https://www.youtube.com/watch?v=v2wKwjL2EeQ
It's look identical on much slower microcontroller setup, identical. I use this code to display:
........
  tft.setTextColor(TFT_RED, TFT_BLACK);
  tft.setTextSize(4);
  tft.setTextDatum(2);
  sprintf(speed_tab, "%03d", gps_speed);
  yield(); tft.drawString(speed_tab, 460, 60, speed_font);
  tft.setTextColor(TFT_WHITE, TFT_BLACK);
  tft.setTextSize(2);
........
it's look like function fill all pixels in TFT_BLACK color and drawing new signs with TFT_RED without any sync. Any option to change this flickering? If not i propose to make option to drawing only changed pixels without filling all with background color and drawing full text/number again.

**Comment by Bodmer** [comment]
Yes, the library blanks each digit for any text size greater than 1. This is a behaviour inherited from an early simpler version of the library.

I will have a look at the code as I suspect it will be easy to modify and reduce flicker.
