### ISSUE TITLE
Is it possible to use this library to send command values?

### ISSUE THREAD

**Issue by rorosaurus** [Bodmer/TFT_eSPI#767]
Hello, thanks for the awesome library!

According to my datasheet, some commands require you to send additional information:
https://newhavendisplay.com/appnotes/datasheets/LCDs/ST7789V.pdf

For example, I'd like to adjust the backlight brightness, detailed on page 233.

I see the tft.writeCommand() and tft.writeData() functions, but I was not able to use them as I expected. Am I just meant to call them one after the other? Is this even possible or intended with this library?

Thanks,
Rory

**Comment by Bodmer** [comment]
Yes, you can use update command registers, e.g:
```
tft.writecommand(0x36);
tft.writedata(0xCC);
```
You will probably find the brightness control does not control the back-light LEDs. More likely it controls the pixel level transparency.
