### ISSUE TITLE
Driver 7789 non centered img

### ISSUE THREAD

**Issue by pocketPlay** [Bodmer/TFT_eSPI#768]
hi there,
I wrote a small example in July that showed an img in the center of the display.
With the update to the 7789 drivers no longer see the centered image, it is shifted up by about 40 pixels

I loaded the old drivers and the image is centered.

hardware always the same and no changes to the code

I also loaded the examples and the problem is the same, the screen is not centered.

esp32
TFT 7789 - 240X240
Any idea? Bug?

All the best

**Comment by Bodmer** [comment]
This may be related to #763 which TFT_eSPI version worked.

**Comment by pocketPlay** [comment]
hi,
the version of library is: 2.2.14

Regards

**Comment by Bodmer** [comment]
There is no change to the drivers that I can see between 2.2.14 and the latest 2.2.21.

Are you sure that it is version 2.2.14 that worked for you?

**Comment by Bodmer** [comment]
Note you must [include the display size](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setups/Setup24_ST7789.h#L5-L6) in your setup file to invoke the offsets.

**Comment by pocketPlay** [comment]
![IMG_4686](https://user-images.githubusercontent.com/44997687/95058547-f7433e00-06f7-11eb-95ed-e22dcb080565.jpg)
![IMG_4687](https://user-images.githubusercontent.com/44997687/95058553-f9a59800-06f7-11eb-90a4-f835ba217cf2.JPG)

Sorry for the wait. Yes the old driver works for me.
I just overwrote the old driver folder on the new one (I always make a backup) and everything is back to working.

Here correct img with old driver 2.2.14 and new driver (img shifted)

All the best

![IMG_4687](https://user-images.githubusercontent.com/44997687/95058595-07f3b400-06f8-11eb-8c42-b73275fe31f5.JPG)
![IMG_4686](https://user-images.githubusercontent.com/44997687/95058600-088c4a80-06f8-11eb-9a3e-edd00f519545.jpg)

**Comment by Bodmer** [comment]
Without an example sketch that demonstrates the problem I am unable to advise.

**Comment by Bodmer** [comment]
Without an example sketch that demonstrates the problem I am unable to advise.
