### ISSUE TITLE
Sprite transparent

### ISSUE THREAD

**Issue by ZhenyaGrinev** [Bodmer/TFT_eSPI#771]
Hi. Idea next. The display is full screen. I create a 40x40 sprite with a transparent background. Then I print a line with a number (with a transparent background spr.setTextColor (TFT_RED)). When I write a new number in that place it overwrites  old and it turns out to be porridge. At the beginning of the cycle I always write spr.fillSprite (TFT_TRANSPARETN) and at the end spr.pushSprite (0,0, TFT_TRANSPARENT).
 The idea is as in the picture. Please tell me
![IMG_20201003_194031](https://user-images.githubusercontent.com/61008356/94999115-c2cc6680-05bf-11eb-8a84-b5a72fac67c5.jpg)
![ckImiW5un5I](https://user-images.githubusercontent.com/61008356/94999117-c95ade00-05bf-11eb-9680-9e0d04657b63.jpg)

**Comment by Bodmer** [comment]
That is correct behaviour.
The screen memory is like a piece of paper, if you write a number then another number on top you will still see the remains of the previous number. You have to erase or redraw the original background colour to remove the old numbers.
