### ISSUE TITLE
TFT_eSPI touch long press

### ISSUE THREAD

**Issue by dienikolai** [Bodmer/TFT_eSPI#773]
Wie kann man mit TFT_eSPI long press bzw. double press abfragen

**Comment by Bodmer** [comment]
The library does not provide function for this. You may find a third party library that has such features but I have not looked myself.

**Comment by dienikolai** [comment]
Vielen Dank für die schnelle Anwort und Dank für die Library sehr gut gemacht und ich werde sie weiter Verwenden.
Es gibt eine library für den xpt2046, aber getTouch verträgt sich nicht damit.
Ich werde eine andere Möglichkeit finden um das Problem zu lösen.
