### ISSUE TITLE
I can't implementing the library

### ISSUE THREAD

**Issue by ahmetOzby** [Bodmer/TFT_eSPI#776]
I want to use stm32f103c series and I think I've done all the includes correctly. When I try to compile, I got this.

In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:25:0:
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:17:46: error: no matching function for call to 'SPIClass::SPIClass(<anonymous enum>, <anonymous enum>, <anonymous enum>)'
     SPIClass spi(TFT_MOSI, TFT_MISO, TFT_SCLK);
                                              ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:17:46: note: candidates are:
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.h:28:0,
                 from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:17:
C:\Users\Ahmet\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2020.8.9\libraries\SPI\src/SPI.h:176:5: note: SPIClass::SPIClass(uint32)
     SPIClass(uint32 spiPortNumber);
     ^
C:\Users\Ahmet\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2020.8.9\libraries\SPI\src/SPI.h:176:5: note:   candidate expects 1 argument, 3 provided
C:\Users\Ahmet\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2020.8.9\libraries\SPI\src/SPI.h:170:7: note: constexpr SPIClass::SPIClass(const SPIClass&)
 class SPIClass {
       ^
C:\Users\Ahmet\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2020.8.9\libraries\SPI\src/SPI.h:170:7: note:   candidate expects 1 argument, 3 provided
C:\Users\Ahmet\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2020.8.9\libraries\SPI\src/SPI.h:170:7: note: constexpr SPIClass::SPIClass(SPIClass&&)
C:\Users\Ahmet\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2020.8.9\libraries\SPI\src/SPI.h:170:7: note:   candidate expects 1 argument, 3 provided
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:25:0:
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:20:3: error: 'SPI_HandleTypeDef' does not name a type
   SPI_HandleTypeDef spiHal;
   ^
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:25:0:
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c: In member function 'void TFT_eSPI::pushBlock(uint16_t, uint32_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:349:23: error: 'spiHal' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY);
                       ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:349:54: error: 'HAL_MAX_DELAY' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY);
                                                      ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:349:67: error: 'HAL_SPI_Transmit' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY);
                                                                   ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:355:23: error: 'spiHal' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, BUF_SIZE<<1, HAL_MAX_DELAY);
                       ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:355:59: error: 'HAL_MAX_DELAY' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, BUF_SIZE<<1, HAL_MAX_DELAY);
                                                           ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:355:72: error: 'HAL_SPI_Transmit' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, BUF_SIZE<<1, HAL_MAX_DELAY);
                                                                        ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:359:30: error: 'spiHal' was not declared in this scope
   if (len) HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY); //*/
                              ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:359:61: error: 'HAL_MAX_DELAY' was not declared in this scope
   if (len) HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY); //*/
                                                             ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:359:74: error: 'HAL_SPI_Transmit' was not declared in this scope
   if (len) HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY); //*/
                                                                          ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c: In member function 'void TFT_eSPI::pushPixels(const void*, uint32_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:374:25: error: 'spiHal' was not declared in this scope
       HAL_SPI_Transmit(&spiHal, (uint8_t*)col, BUF_SIZE<<1, HAL_MAX_DELAY);
                         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:374:61: error: 'HAL_MAX_DELAY' was not declared in this scope
       HAL_SPI_Transmit(&spiHal, (uint8_t*)col, BUF_SIZE<<1, HAL_MAX_DELAY);
                                                             ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:374:74: error: 'HAL_SPI_Transmit' was not declared in this scope
       HAL_SPI_Transmit(&spiHal, (uint8_t*)col, BUF_SIZE<<1, HAL_MAX_DELAY);
                                                                          ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:378:23: error: 'spiHal' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY);
                       ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:378:54: error: 'HAL_MAX_DELAY' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY);
                                                      ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:378:67: error: 'HAL_SPI_Transmit' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)col, len<<1, HAL_MAX_DELAY);
                                                                   ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:384:25: error: 'spiHal' was not declared in this scope
       HAL_SPI_Transmit(&spiHal, (uint8_t*)data, 0x800<<1, HAL_MAX_DELAY);
                         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:384:59: error: 'HAL_MAX_DELAY' was not declared in this scope
       HAL_SPI_Transmit(&spiHal, (uint8_t*)data, 0x800<<1, HAL_MAX_DELAY);
                                                           ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:384:72: error: 'HAL_SPI_Transmit' was not declared in this scope
       HAL_SPI_Transmit(&spiHal, (uint8_t*)data, 0x800<<1, HAL_MAX_DELAY);
                                                                        ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:388:23: error: 'spiHal' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)data, len<<1, HAL_MAX_DELAY);
                       ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:388:55: error: 'HAL_MAX_DELAY' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)data, len<<1, HAL_MAX_DELAY);
                                                       ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.c:388:68: error: 'HAL_SPI_Transmit' was not declared in this scope
     HAL_SPI_Transmit(&spiHal, (uint8_t*)data, len<<1, HAL_MAX_DELAY);
                                                                    ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'void TFT_eSPI::begin_tft_read()':
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:82:9: error: 'class SPIClass' has no member named 'setFrequency'
     spi.setFrequency(SPI_READ_FREQUENCY);
         ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'void TFT_eSPI::end_tft_read()':
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:104:9: error: 'class SPIClass' has no member named 'setFrequency'
     spi.setFrequency(SPI_FREQUENCY);
         ^
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.h:55:0,
                 from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:17:
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'void TFT_eSPI::init(uint8_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:188:33: error: 'spiHal' was not declared in this scope
       #define INIT_TFT_DATA_BUS spiHal.Instance = SPI1
                                 ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:319:5: note: in expansion of macro 'INIT_TFT_DATA_BUS'
     INIT_TFT_DATA_BUS;
     ^
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.h:55:0,
                 from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:17:
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'void TFT_eSPI::setWindow(int32_t, int32_t, int32_t, int32_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2659:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(x0, x1);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2659:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(x0, x1);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2661:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(y0, y1);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2661:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(y0, y1);
         ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'void TFT_eSPI::readAddrWindow(int32_t, int32_t, int32_t, int32_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2696:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(xs, xe);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2696:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(xs, xe);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2700:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(ys, ye);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1080:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2700:9: note: in expansion of macro 'tft_Write_32C'
   DC_D; tft_Write_32C(ys, ye);
         ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::drawPixel(int32_t, int32_t, uint32_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1084:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2741:11: note: in expansion of macro 'tft_Write_32D'
     DC_D; tft_Write_32D(x);
           ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1084:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2741:11: note: in expansion of macro 'tft_Write_32D'
     DC_D; tft_Write_32D(x);
           ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1084:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2748:11: note: in expansion of macro 'tft_Write_32D'
     DC_D; tft_Write_32D(y);
           ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1084:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 4, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2748:11: note: in expansion of macro 'tft_Write_32D'
     DC_D; tft_Write_32D(y);
           ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1068:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 2, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2754:9: note: in expansion of macro 'tft_Write_16'
   DC_D; tft_Write_16(color);
         ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1068:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 2, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2754:9: note: in expansion of macro 'tft_Write_16'
   DC_D; tft_Write_16(color);
         ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'void TFT_eSPI::pushColor(uint16_t)':
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1068:21: error: 'spiHal' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 2, 10); }
                     ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2767:3: note: in expansion of macro 'tft_Write_16'
   tft_Write_16(color);
   ^
C:\Arduino\libraries\TFT_eSPI-master\Processors/TFT_eSPI_STM32.h:1068:45: error: 'HAL_SPI_Transmit' was not declared in this scope
   HAL_SPI_Transmit(&spiHal, spiBuffer, 2, 10); }
                                             ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:2767:3: note: in expansion of macro 'tft_Write_16'
   tft_Write_16(color);
   ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'int16_t TFT_eSPI::drawNumber(long int, int32_t, int32_t)':
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:3990:25: error: 'ltoa' was not declared in this scope
   ltoa(long_num, str, 10);
                         ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'int16_t TFT_eSPI::drawNumber(long int, int32_t, int32_t, uint8_t)':
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:3998:25: error: 'ltoa' was not declared in this scope
   ltoa(long_num, str, 10);
                         ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp: In member function 'int16_t TFT_eSPI::drawFloat(float, uint8_t, int32_t, int32_t, uint8_t)':
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:4047:27: error: 'ltoa' was not declared in this scope
   ltoa(temp, str + ptr, 10);
                           ^
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:4309:0:
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp: In member function 'bool TFT_eSprite::pushSprite(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)':
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:834:67: error: call of overloaded 'pushImage(int32_t&, int32_t&, int32_t&, int32_t&, uint8_t*, int)' is ambiguous
       _tft->pushImage(tx, ty, sw, sh, _img8 + _iwidth * _ys, true );
                                                                   ^
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:834:67: note: candidates are:
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:1135:6: note: void TFT_eSPI::pushImage(int32_t, int32_t, int32_t, int32_t, uint8_t*, bool, uint16_t*)
 void TFT_eSPI::pushImage(int32_t x, int32_t y, int32_t w, int32_t h, uint8_t *data, bool bpp8,  uint16_t *cmap)
      ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:1292:6: note: void TFT_eSPI::pushImage(int32_t, int32_t, int32_t, int32_t, uint8_t*, uint8_t, bool, uint16_t*)
 void TFT_eSPI::pushImage(int32_t x, int32_t y, int32_t w, int32_t h, uint8_t *data, uint8_t transp, bool bpp8, uint16_t *cmap)
      ^
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:4309:0:
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:837:76: error: call of overloaded 'pushImage(int32_t&, int32_t, int32_t&, int, uint8_t*, int)' is ambiguous
       _tft->pushImage(tx, ty++, sw, 1, _img8 + _xs + _iwidth * _ys++, true );
                                                                            ^
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:837:76: note: candidates are:
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:1135:6: note: void TFT_eSPI::pushImage(int32_t, int32_t, int32_t, int32_t, uint8_t*, bool, uint16_t*)
 void TFT_eSPI::pushImage(int32_t x, int32_t y, int32_t w, int32_t h, uint8_t *data, bool bpp8,  uint16_t *cmap)
      ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:1292:6: note: void TFT_eSPI::pushImage(int32_t, int32_t, int32_t, int32_t, uint8_t*, uint8_t, bool, uint16_t*)
 void TFT_eSPI::pushImage(int32_t x, int32_t y, int32_t w, int32_t h, uint8_t *data, uint8_t transp, bool bpp8, uint16_t *cmap)
      ^
In file included from C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:4309:0:
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:873:73: error: call of overloaded 'pushImage(int32_t&, int32_t&, int32_t&, int32_t&, uint8_t*, int)' is ambiguous
       _tft->pushImage(tx, ty, sw, sh, _img8 + (_iwidth>>3) * _ys, false );
                                                                         ^
C:\Arduino\libraries\TFT_eSPI-master\Extensions/Sprite.cpp:873:73: note: candidates are:
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:1135:6: note: void TFT_eSPI::pushImage(int32_t, int32_t, int32_t, int32_t, uint8_t*, bool, uint16_t*)
 void TFT_eSPI::pushImage(int32_t x, int32_t y, int32_t w, int32_t h, uint8_t *data, bool bpp8,  uint16_t *cmap)
      ^
C:\Arduino\libraries\TFT_eSPI-master\TFT_eSPI.cpp:1292:6: note: void TFT_eSPI::pushImage(int32_t, int32_t, int32_t, int32_t, uint8_t*, uint8_t, bool, uint16_t*)
 void TFT_eSPI::pushImage(int32_t x, int32_t y, int32_t w, int32_t h, uint8_t *data, uint8_t transp, bool bpp8, uint16_t *cmap)
      ^
exit status 1

**Comment by Bodmer** [comment]
The library requires the official STM32 board package, not third party libraaries.

Install the STM32 board support from the Arduino IDE menu option. You should then have a package path like this:

```
C:\Users\xxxx\AppData\Local\Arduino15\packages\STM32\hardware\stm32\1.9.0\libraries\SPI
                                               ^^^^^ Note!
```

**Comment by ahmetOzby** [comment]
Thank you so much. You solved this immediately.
