### ISSUE TITLE
#define TFT_CS, TFT_RST, TFT_DC and TFT_RD as -1 ? 

### ISSUE THREAD

**Issue by quangvankts** [Bodmer/TFT_eSPI#779]
Hi
Will a ILI9481 - ESP32 setup still work in 8 bit parallel mode if I connect the LCD's CS pin to GND, DC and RD pin to Vcc, RST to EN and define them in User_Setup.h as -1 ?
Thanks

**Comment by Bodmer** [comment]
No. As a minimum DC, WR and the data pins must be driven with CS pulled low, RST and RD pulled high.
CS, RST and RD can  then be defined  as -1

**Comment by quangvankts** [comment]
Thank you 
Is it possible to drive LCD’s DC pin through a shift register ?  If yes which part of the library can I modify to do so ?

**Comment by Bodmer** [comment]
Yes, [these are the lines to adapt](https://github.com/Bodmer/TFT_eSPI/blob/master/Processors/TFT_eSPI_ESP32.h#L81-L87), they are the macros that toggle the DC pin for an 8 bit parallel interface on an ESP32.

**Comment by quangvankts** [comment]
Got it ! 
Thanks again
