### ISSUE TITLE
Push a Sprite to a Sprite

### ISSUE THREAD

**Issue by DrJaymz** [Bodmer/TFT_eSPI#787]
I searched for an example of pushing sprite to sprite and have been using pushRotated to do that.  I am now trying to push a sprite to another sprite that isn't rotated and you'd think was simpler.  I am using pushToSprite and I didn't find it in the examples.

  spr_alt.creatSprite(40,40);

  TFT_eSprite spr_numbers(&tft);
  spr_numbers.setColorDepth(8);
  spr_numbers.createSprite(10, 10);
  spr_numbers.fillSprite(TFT_MAGENTA);
  spr_numbers.pushToSprite(&spr_alt,10, 10);     <----  This doesn't plot onto spr_alt.
  spr_numbers.deleteSprite();

  spr_alt.pushSprite(260, 20);
  spr_alt.deleteSprite();

If I push to &tft then its pushing it to the main screen just fine but I want it on that sprite.
Is it me being dumb again?

**Comment by Bodmer** [comment]
pushToSprite currently has no example, it is a new function added on request.

The function has restrictions on the bpp of each sprite so you cannot push an 8 bit sprite to a 16 bit type. [See restrictions here](https://github.com/Bodmer/TFT_eSPI/blob/master/Extensions/Sprite.cpp#L735-L740).
