### ISSUE TITLE
Get the cursor position?

### ISSUE THREAD

**Issue by JamesNewton** [Bodmer/TFT_eSPI#79]
I'd like to keep track of where the printing stopped so that I can go print something over the top and then go back and restore the position for the next line of text. e.g.

````
// when we get a new reading
debug_y = tft.getTextLine(); // returns current cursor y position
debug_x = tft.getTextColumn();// returns current cursor x position
tft.setCursor(reading_x,reading_y,reading_font); tft.println(reading);
tft.setCursor(debug_x,debug_y);
// elsewhere:
tft.println(debug_msg);
````

Do those sound like good names for the functions? Worth adding? If so, I'll just fork, add, and request pull. 

Or did I miss something that does the same thing?

**Comment by Bodmer** [comment]
I've added two new functions. These are named to be compatible with the Adafruit_GFX library to ease migration of sketches to this library.
