### ISSUE TITLE
ili9486 + 74hc595

### ISSUE THREAD

**Issue by clear-sky** [Bodmer/TFT_eSPI#791]
hi all
i have a ili9486 lcd 
http://aitendo3.sakura.ne.jp/aitendo_data/product_img/lcd/tft2/Z350IT002/Z350IT002_aitendo.pdf
i want to interface it in spi mode in 8 bit bus interface base on this circuit
https://github.com/ioxhop/Adafruit-ILI9481-ESP32-SPI
is this lcd supported with bodmer driver?

**Comment by Bodmer** [comment]
The library supports the ILI9486.

It does not support that circuit design. Note that circuit design uses a 5V supply for the 74HC595 and this will damage the display if connected directly to it. I suspect the design is for UNO display shields that use 5V to 3.3V buffers and is not suitable for direct connection to the ILI9486.
