### ISSUE TITLE
Can't get negative number sign in the dial example using AA_FONT_LARGE NotoSansBold36

### ISSUE THREAD

**Issue by jlder** [Bodmer/TFT_eSPI#792]
Hello,
I am in the learning process and probably making mistakes...
I modified the dial example to get a display that goes from negative to positive numbers.
However, when a negative number is printed, instead of the negative sign, I get a vertical rectangle in front of the number (white border black filled).
Thanks for help.
JL

**Comment by Bodmer** [comment]
The example font file only contains digits 0 to 9 to minimise the array size for smaller memory capacity processors. The box (tofu symbol) indicates the character does not exist in the font file. If you need further characters then you will need to create a new font file.
