### ISSUE TITLE
How to determine chipset at runtime

### ISSUE THREAD

**Issue by brownjd** [Bodmer/TFT_eSPI#793]
Is there a way to determine if you have an ILI9341 or HX8357 featherwing connected to an ESP8266 at runtime? Perhaps a way to check a chip ID?

**Comment by Bodmer** [comment]
Providing the display supports reading of registers and they provide a recognisable ID (some clone chips do not) then you could determine the display type at runtime. Some libraries such as Mcufriend_kbv do this.

TFT_eSPI does not support the selection of the initialisation code at runtime.
