### ISSUE TITLE
drawChar overwritting background, contrary to comment in example

### ISSUE THREAD

**Issue by riban-bw** [Bodmer/TFT_eSPI#795]
In the example, "160 x 128/TFT_CLOCK_DIGITAL" there is a comment, "Note: the new fonts do not draw the background colour" and the code uses this feature to allow "ghost" background of text. This does not seem to work. The background colour is drawn which overwrites the ghost. I guess there was a change of behaviour since the example was written. Is there a way to invoke the previous behaviour, i.e. to draw text without drawing its background?

**Comment by Bodmer** [comment]
Your guess is right.

Change line 102 to:
```
      tft.setTextColor(0xFBE0); // Orange
```
I will update the exmaple.

**Comment by riban-bw** [comment]
Excellent, thanks!
