### ISSUE TITLE
Feature request - Draw quadlirateral

### ISSUE THREAD

**Issue by georgegohl888** [Bodmer/TFT_eSPI#797]
Good Afternoon,

Love using your code!

Would it be possible to make a fill quadilateral function. Like the fill triangle but with 4 arbitary points. I have tried using 2 triangles to make the same shape but am finding this fairly slow and i imagine it would be quicker to do it in one specirfic function.

Thanks! 

Im loooking at the C++ code myself but it will likley take me a while to do it myself and id imagine you could do it much wuicker. If i figure it out ill let you know.

**Comment by Bodmer** [comment]
I think functions like this belong in a companion library that provides 2D shapes since the list of shapes requestd could end up being rather long!

Try this [TFTShape companion library](https://github.com/androdlang/TFTShape) which has a good performance for drawing all sorts of shapes.
