### ISSUE TITLE
Doubt about print and DrawString

### ISSUE THREAD

**Issue by Girum** [Bodmer/TFT_eSPI#798]
Follow the example, to send long texts and override then (to clean the screen without fillScreen), when I use:

```
tft.drawString(msg, 0, 0);
tft.setTextPadding(tft.textWidth(msg));
}
```

The message not break line, llike in tft.print. How to breakline automaticaly like print?

Ex: if message was 1234567891234, is only shows 12345678912, and the rest of the text goes to the right and lost.

**Comment by Bodmer** [comment]
You will need to write a function to break the string at a convenient point, usually at a space character and add hyphens if you need them.
See #558 and #626 .
