### ISSUE TITLE
HSPI and VSPI. TFT and TOUCH in esp32

### ISSUE THREAD

**Issue by eb4cuv** [Bodmer/TFT_eSPI#804]
Hi bodmer

My tft is a 480x320 spi module with touch.

I am developing an application where the spi is used intensively with numbers that need to be updated very quickly. So far everything is perfect.

The problem comes when I incorporate touch into the sketch. The numbers go by jumps and much slower even if I don't touch the screen.
I think the problem is the sharing of the spi: tft and touch. That's why I would like to ask you if is there any way to use the other SPI port that esp32 has. That way the tft would be in one of them HSPI  and touch in VSPI.

Thank you.
Julio

**Comment by Bodmer** [comment]
The library can only use a single SPI port and I do not plan to change this. One option is to use a third party touch library for the TFT_eSPI can use a different port.

Eventually the built in touch function will be deprecated and separate libraries developed, hence there are no plans to add new touch options.
