### ISSUE TITLE
DrawString does not wrap text

### ISSUE THREAD

**Issue by offgabriele** [Bodmer/TFT_eSPI#806]
How can I display a long string in the center of the screen with text wrapping? I was thinking of splitting the string at the space if the string is too long but then i would have to have the length of the string in pixels to set the cursor. How can I do this? There is any simpler way?

**Comment by Bodmer** [comment]
You will have to write your own function for this.
Use textLenght() to get the pixel length. See also [example code here](https://github.com/Bodmer/TFT_eSPI/issues/558#issuecomment-593147012).
