### ISSUE TITLE
Rotated_Sprite_1.ino problem ? 

### ISSUE THREAD

**Issue by sbonaime** [Bodmer/TFT_eSPI#808]
Hi,
I am learning Sprite with your library. In Rotated_Sprite_1.ino, the code is
```
  spr.setColorDepth(8);      // Create an 8bpp Sprite of 60x30 pixels
  spr.createSprite(64, 30);  // 8bpp requires 64 * 30 = 1920 bytes
```
I am wondering why you create a 64x30 Sprite after wrote that you wanted to create a 60x30 pixels Sprite. Is there a typo ? 
Thanks

**Comment by Bodmer** [comment]
I expect I just forgot to update the comment. Similarly at line 69 and 125 :-)
