### ISSUE TITLE
Issue Rendering JPG Files

### ISSUE THREAD

**Issue by tonyc770** [Bodmer/TFT_eSPI#810]
I am using the ILI9488 480x320 display with NodeMCU 1.0.
The display seems to work fine with text and graphics, buy when reading jpg images from SPIFFS, the image appears corrupt.
The sketch that I am using is NodeMCU_Jpeg_ESP - JPEG_Functions.ino

In the user_setup.h file I select the ILI9488_DRIVER and follow the appropriate pin connections to the TFT and NodeMCU.

Any suggestions?

Thanks

**Comment by Bodmer** [comment]
I see that example references an early library that is not deprecated. I will update the example to work with TFT_eSPI.

**Comment by Bodmer** [comment]
I have updated the example, you can[ find it here](https://github.com/Bodmer/JPEGDecoder/tree/master/examples/Other%20libraries/NodeMCU_Jpeg_ESP).
