### ISSUE TITLE
Problem with 'setSwapBytes' in newest version

### ISSUE THREAD

**Issue by Tinkerpete** [Bodmer/TFT_eSPI#812]
In my program I have a bitmap. In the newer versions I needed 'setSwapBytes' to display the colors from this bitmap correctly. In the latest version 2.2.23 the function 'setSwapBytes' seems to reset the program. Now I use version 2.2.14 again and my program runs ok.

**Comment by Bodmer** [comment]
The earlier versions of the library had an inconsistency in the way setSwapBytes was implemented. This has not been corrected.

The rule is that swap bytes must be set true if the bytes need to be swapped to be accepted by the SPI registers.

Updating your sketch in line with the library update will correct the rendered images.
