### ISSUE TITLE
Test touch controller 

### ISSUE THREAD

**Issue by baniaque** [Bodmer/TFT_eSPI#818]
Hi,

Is this normal that example code for testing touch screen, showing me y result about 3600 when i don't touch the screen?
x: 0     y: 3592     z: 2 

best regards

**Comment by Bodmer** [comment]
The resistive screen gives values in the range 0 to 4095, the x,y  readings when the screen is not being touched may be invalid and are of little use. The readings when the screen is touched (z reading increases significantly) are the important ones.
