### ISSUE TITLE
RPi 3.5” (C) Display Compatibility - 125 MHz SPI)

### ISSUE THREAD

**Issue by Guerillah** [Bodmer/TFT_eSPI#819]
Is this display supported by the library? Waveshare 3.5inch RPi LCD (C) 320X480 Resolution Touch Screen TFT Display Designed for Any Revision of Raspberry Pi 4 125MHz High-Speed SPI Directly-pluggable Waveshare 3.5inch RPi LCD (C) 320X480 Resolution Touch Screen TFT Display Designed for Any Revision of Raspberry Pi 4 125MHz High-Speed SPI Directly-pluggable https://www.amazon.com/dp/B07L1215W5/

I see that the 4.0” MHI of the same speed is brought up in the read me, but wanted to make sure before I purchase. It seems they are the same minus the display size.  Thanks!

**Comment by Bodmer** [comment]
The [such as this one ](https://www.aliexpress.com/item/33011046810.html)is supported, It must be of the MHS-4.0 inch Display-B type. Other displays may not work as they may have a different controller.
