### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by nmelectronics3** [Bodmer/TFT_eSPI#822]
i am getting the following errors when compiling

'class TFT_eSPI' has no member named 'setTouch'
'class TFT_eSPI' has no member named 'getTouch'

can anyone help

**Comment by Bodmer** [comment]
This suggests you are running a sketch that requires a screen with a touch interface. In this case you MUST [define the chip select ](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h#L163 )for the touch controler in the setup file.
