### ISSUE TITLE
Getting library to work with a user defined SPI interface.

### ISSUE THREAD

**Issue by HobbyEE** [Bodmer/TFT_eSPI#840]
Greetings. This is a fantastic library! I have tested it with my NodeMCU and it was working great. Now, I try to port it to a non standard SAMD21G board driving an ILI9341 screen. This one (for a reason beyond my understanding) has the default SPI ports unsoldered... Adafruit's library works great after defining a new SERCOM but your **tft.init()** accepts no arguments. I went to TFT_eSPI_Generic.c and added this code:
`
SPIClass mySPI (&sercom1, 12, 13, 11, SPI_PAD_0_SCK_1, SERCOM_RX_PAD_3);
SPIClass& spi = mySPI;
`
In my sketch I include:

`#include "wiring_private.h" // pinPeripheral() function`

Then in my setup() I add:

`pinPeripheral(11, PIO_SERCOM);
  pinPeripheral(12, PIO_SERCOM);
  pinPeripheral(13, PIO_SERCOM);`

I comment all FS.h code. The code compiles successfully but the screen is not displaying anything... I have defined the pins I use for CS etc. I will try to get to the bottom of this because I really prefer this lib over Adafruit's but I would like a starting point regarding my handling of SERCOM SPI. 
Thanks in advance.

**Comment by Bodmer** [comment]
I am not familiar with the SAMD21G  so am unable to advise on adaption.
The standard SPI instance [is picked up here](https://github.com/Bodmer/TFT_eSPI/blob/master/Processors/TFT_eSPI_Generic.c#L10) and should work if the correct DPI port is connected up.
