### ISSUE TITLE
Touch function is always on

### ISSUE THREAD

**Issue by JeroenvandenBerg** [Bodmer/TFT_eSPI#86]
I tried to calibrate my touch function on a ily9341 screen. It's working with your old driver. But when i run the calibrate function. It's not waiting for a touch, i have the idea that the program thinks that it continues touching? I tried a second screen with the same results...

thnx

Im sorry was to fast, my t_CS was connected to the RX and the program didn't liked that, changing it to D3 solved my problem. Great work this library!

**Comment by Bodmer** [comment]
Glad to hear you have it working!
