### ISSUE TITLE
drawXBitmap with GC9A01

### ISSUE THREAD

**Issue by poky** [Bodmer/TFT_eSPI#867]
Hi, thanks for the great library & driver!
I have some issues running the drawXBitmap example, it only shows the blue lines jumping in different locations, was wondering how to debug, any thoughts will be appreciated!

![13220119604071](https://user-images.githubusercontent.com/138415/102503619-df564600-40ba-11eb-9a32-601221a7319d.jpg)

_Originally posted by @poky in https://github.com/Bodmer/TFT_eSPI/issues/774#issuecomment-747488090_

**Comment by Bodmer** [comment]
See #774

**Comment by Bodmer** [comment]
I have ordered one of those displays but it will probably be a few weeks before it arrives. Maybe then I can figure out what is wrong.

The changes I made based on@freemanzwin here suggestions have not been tested unfortunately and @freemanzwin has not responded to the issue yet or the request for testing.

**Comment by Bodmer** [comment]
Still waiting for my display to arrive...

**Comment by Bodmer** [comment]
Still waiting for my display to arrive...

**Comment by nickschot** [comment]
I have one arriving tomorrow. Will see what happens.

**Comment by Bodmer** [comment]
Stiil waiting for mine to arrive from China, suspect it may be lost in the post :-(

**Comment by Bodmer** [comment]
Package tracking indicates it arrived in the UK 8 days ago, so there is hope!

**Comment by nickschot** [comment]
Could it be that the GC9A01 does not support reading from the screen? I tried scrolling a sprite and nothing happened. tft.readPixel seems to return 0 in any case.

**Comment by Bodmer** [comment]
Mine has arrived and I have got it working up to a point. The Orrery example leaves a trail of pixels so this indicates some issues writing to the screen. The same sketch works fine on other displays so this is something to do with the GC9A01 behaviour, it looks like itmisses every other pixel line. I will need to study the data sheet and investigate further. Some things seem to work OK, others have corrupted grpahics. It will be a while before I can investigate.

I have not been able to read from the screen, this is probably due to the IM(x) configuration pins being in a mode that does not allow SDA bidirectional reads. This is just a guess and I see no way of over-riding this to permit screen CGRAM reads.

**Comment by nickschot** [comment]
> Mine has arrived and I have got it working up to a point. The Orrery example leaves a trail of pixels so this indicates some issues writing to the screen. The same sketch works fine on other displays so this is something to do with the GC9A01 behaviour, it looks like it misses every other pixel line. I will need to study the data sheet and investigate further. Some things seem to work OK, others have corrupted graphics. It will be a while before I can investigate.
> 
> 
> 
> I have not been able to read from the screen, this is probably due to the IM(x) configuration pins being in a mode that does not allow SDA bidirectional reads. This is just a guess and I see no way of over-riding this to permit screen CGRAM reads.
> 
> 

Cool! Look forward to what else you find. Another thing I've spotted is that transparent sprites also seem to behave weirdly. I've also seen those display alternating lines and other weird glitches. I've yet to try an example with transparency, but it didn't seem like I was doing much different from those.

**Comment by freemanzwin** [comment]
This Chinese LCD module does not have MISO pin. So I don't think I can read CGRAM.

**Comment by Bodmer** [comment]
Some displays operate in bidirectional mode, where the MOSI line changes from input to output at the display during a read, typically the pin is then called SDA. The library supports this type of interface for ESP32 only, however I have tried this mode on the GC9A01 and it does not return sensible data. The GC9A01 can operate in bidirectional mode but this is controlled by hardware set pins that, as far as I can see, are not accessible on these displays.

**Comment by MisterAG** [comment]
Has any progress been made on this? I tried the animated dial example and the needle overwrites the background image.

![IMG_20210525_220938](https://user-images.githubusercontent.com/1371445/119562081-3bc63b80-bda6-11eb-83dc-2d91570dd764.jpg)

**Comment by Bodmer** [comment]
drawXBitmap example now works with GC9A01.

**Comment by summerfind** [comment]
Hi Bodmer, 
To open this for a similar question, I am using matouch_esp32_s3_round which used ESP32S3+GC9A01, that can't show drawXBitmap example. 
and also do you have a solution for it to show JPG? 
Thanks.
Summer

**Comment by spanja05** [comment]
> Has any progress been made on this? I tried the animated dial example and the needle overwrites the background image.
> 
> ![IMG_20210525_220938](https://user-images.githubusercontent.com/1371445/119562081-3bc63b80-bda6-11eb-83dc-2d91570dd764.jpg)

Hello Bodmer,

To follow up on this comment, have there been any updates to this? I'm facing the same issue where the needle overwrites the background image. Any advice is appreciated. Thank you!
