### ISSUE TITLE
Images in esp32 TTGO TM board

### ISSUE THREAD

**Issue by A-Cheikh** [Bodmer/TFT_eSPI#885]
Hi All,
When I use this library to display images with TTGO TM board, the colors the image displayed change, eg: Black becomes White SO I don't know why this issues?

**Comment by Bodmer** [comment]
Please add this line in the setup file:
```
#define TFT_INVERSION_OFF
```
Thanks for reporting this.

**Comment by Bodmer** [comment]
Setup 23 has been updated.

Thanks for reporting this.
