### ISSUE TITLE
Error compiling for stm32f103 and ili9225 driver

### ISSUE THREAD

**Issue by bluexp1** [Bodmer/TFT_eSPI#890]
I am trying to build my app in pio IDE but I receive this error:
```
In file included from .pio\libdeps\genericSTM32F103C8\TFT_eSPI\TFT_eSPI.cpp:24:
.pio\libdeps\genericSTM32F103C8\TFT_eSPI\Processors/TFT_eSPI_STM32.c:597:6: error: no declaration matches 'bool TFT_eSPI::initDMA()'
```
I am using stm32duino library from ST.

**Comment by Bodmer** [comment]
Which version of the library are you using?

**Comment by Bodmer** [comment]
I have spotted the problem and updated the master on github.

Let me know if this is now OK.

**Comment by bluexp1** [comment]
Yep, the problem is solved, thanks for your fast response
