### ISSUE TITLE
Setup11_Rpi do not work 

### ISSUE THREAD

**Issue by Nulista** [Bodmer/TFT_eSPI#892]
Hallo Bodmer, 
Great library, Congrats!!

My project works fine with VERSION "2.3.2" and a 3.5" RPi display.
But when I install version 3.2.54 it doesn't work anymore .... only white screen.

For your information, if I omit lines 118 to 121 in User_Setup_Select.h, (just to find the problem..)
following lines:
----------------------
// Invoke 18 bit colour for selected displays
#if (defined (ILI9481_DRIVER) || defined (ILI9486_DRIVER) || defined (ILI9488_DRIVER)) && !defined (TFT_PARALLEL_8_BIT) && !defined (ESP32_PARALLEL)
  #define SPI_18BIT_DRIVER
#endif
--------------------
 then I get an incomplete black/white image.

Do you now wat i do wrong?
thanks

**Comment by Bodmer** [comment]
Which processor are you using?

**Comment by Nulista** [comment]
Esp32


Verstuurd vanaf mijn iPhone

**Comment by Bodmer** [comment]
I have updated the master and this should be OK now.
