### ISSUE TITLE
How to check if display is connected?

### ISSUE THREAD

**Issue by MariusVB** [Bodmer/TFT_eSPI#918]
Hi,

Title says it. I want to check if the display is connected or not. Both init and begin are voids, they don't return a bool to tell if the initialization was a success. How do I check that?

Regards,
Marius

**Comment by Bodmer** [comment]
It depend on what is regarded as "success". Assuming you have a display that allows reading of registers (not all do) then you could read back some control registers. You will need to check the display driver data sheet as not all registers can be read back and the data format varies. Another simple approach is to write a pixel and read back the colour.
These tests only indicate communication with the display has been achieved, and might or might not indicate the right driver has been selected (some different hardware drivers have the same register set). Some displays have a supplier dependant signature register that can be read  but this does not show if the display has been correctly configured.  Ultimately you will have to visually check if the correct image is being displayed to confirm the setup is a total success.
