### ISSUE TITLE
Problem with multiple displays

### ISSUE THREAD

**Issue by jamclaug** [Bodmer/TFT_eSPI#928]
Hi!  Nice lib, thanks for all your hard work.  I am using two .96 80x160 displays and they both work (same SPI, different CS) but it seems they are a bit different from each other - one is a red tab and one appears to be a green tab.  How is this supported by the lib?

Right now both work but one is inverted black/white.

**Comment by Bodmer** [comment]
See[ these setup file comments](https://github.com/Bodmer/TFT_eSPI/blob/master/User_Setup.h#L83-L104).

**Comment by Bodmer** [comment]
From the sketch you can also use an invert colours function, e.g.
```
tft.invertDisplay(true); // Also try false - different displays may require a different setting 
```

**Comment by Bodmer** [comment]
I assume all is OK now.
