### ISSUE TITLE
TFT_eSPI.h and MFRC522.h SPI RFID sensor slows down TFT

### ISSUE THREAD

**Issue by ismaelit** [Bodmer/TFT_eSPI#94]
Hello guys. This is my first post here and I hope to contribute in some way.

I'm developing an application using ILI9341 with this spectacular Bodmer TFT_eSPI library. Now I am integrating with an RFID-RC522, including the MFRC522.h library and instantiate without any problems. 

But after starting the RFID sensor - mfrc522.PCD_Init() in the setup() section and receive any data from the sensor, like using mfrc522.PCD_DumpVersionToSerial(), the TFT speed drops to the original SPI standards: without acceleration.

Does anyone see any solution to this problem?

*Using ESP8266, ILI9341 and RFID-RC522.

**Comment by Bodmer** [comment]
You need to enable transaction support in the setup file, see the end of that file.

**Comment by ismaelit** [comment]
Crying of happiness! It Works! 
Thank you very much @Bodmer :))
