### ISSUE TITLE
drawNumber works but doesn't erase trailing digits

### ISSUE THREAD

**Issue by rowifi** [Bodmer/TFT_eSPI#945]
Using the draw number works, and erases the previous image providing the digits are the same length.
If I display a sequence 0 to 250, then the end digit ( a zero ) is left on screen when decreasing the number from say 100 to 99,  or similarly from 10 to 9.

This means I need to draw a clear area before I draw whereas the function could/should include a digit size parameter so a blank digit(s) can be drawn automatically when drawing the number.
Or perhaps I'm missing something?

**Comment by Bodmer** [comment]
Look at the setTextPadding(w) function, the will cause an area of width w to be cleared. You can use the getTextWidth("8888") to find out the width of the characters, in that case a 4 digit number. There are examples that use these functions.
