### ISSUE TITLE
How to draw bitmaps from SD Card

### ISSUE THREAD

**Issue by gamecompiler** [Bodmer/TFT_eSPI#95]
How do i draw bitmaps from SD Card?
I didnt got it working. I even didnt got the JPEGDecoder example to work (Changed it to SD card filesystem instead of SPIFFS).

Im using an ESP32.

**Comment by Bodmer** [comment]
Does the sd test example in th SD library run OK.?

**Comment by gamecompiler** [comment]
Yes, I can mount the SD card correctly and read/write files. Am 11.02.2018 12:10 schrieb Bodmer <notifications@github.com>:Does the sd test example in th SD library run OK.?

**Comment by Bodmer** [comment]
Which pins are you using to connect to the display and SD card?

Can you post a basic sketch that you are trying to get working?

**Comment by gamecompiler** [comment]
Yes, really really bad coding style, i can do that better. Displaying a bitmap from sd card was just a small thought in the break of my lectures. Id never coded C++. Only Java.
 This code is completly copied fro the Adafruit ILI9341 library. There is a lot i misunderstood i guarantee.


TFT_eSPI.cpp
```
void TFT_eSPI::startWrite(void){
  spi_begin();
}

void TFT_eSPI::endWrite(void){
  spi_end();
}

void TFT_eSPI::writePixel(uint16_t color){
    spiwrite(color);
}

```

spitftbitmap.cpp
```
#include <Arduino.h>

#define FS_NO_GLOBALS
#include <FS.h>
#include <SD.h>
#include <SPI.h>
#include <TFT_eSPI.h>
#include <Adafruit_GFX.h>
TFT_eSPI tft = TFT_eSPI();

//Code copied from https://github.com/adafruit/Adafruit_ILI9341/blob/master/examples/spitftbitmap/spitftbitmap.ino
//Changed in mind, it MAY display bmp images from the sd card.
void setup(){

  Serial.begin(115200);

  tft.init();
  tft.setRotation(3);

  tft.fillScreen(TFT_BLACK);

  if (!SD.begin()) {
    Serial.println("SD Card initialisation failed!");
    while (1) yield(); // Stay here twiddling thumbs waiting
  }
  Serial.println("\r\nInitialisation done.");

  uint8_t cardType = SD.cardType();

  if(cardType == CARD_NONE){
      Serial.println("No SD card attached");
      return;
  }

  Serial.print("SD Card Type: ");
  if(cardType == CARD_MMC){
      Serial.println("MMC");
  } else if(cardType == CARD_SD){
      Serial.println("SDSC");
  } else if(cardType == CARD_SDHC){
      Serial.println("SDHC");
  } else {
      Serial.println("UNKNOWN");
  }

  uint64_t cardSize = SD.cardSize() / (1024 * 1024);
  Serial.printf("SD Card Size: %lluMB\n", cardSize);

}

// These read 16- and 32-bit types from the SD card file.
// BMP data is stored little-endian, Arduino is little-endian too.
// May need to reverse subscript order if porting elsewhere.

uint16_t read16(File &f) {
  uint16_t result;
  ((uint8_t *)&result)[0] = f.read(); // LSB
  ((uint8_t *)&result)[1] = f.read(); // MSB
  return result;
}

uint32_t read32(File &f) {
  uint32_t result;
  ((uint8_t *)&result)[0] = f.read(); // LSB
  ((uint8_t *)&result)[1] = f.read();
  ((uint8_t *)&result)[2] = f.read();
  ((uint8_t *)&result)[3] = f.read(); // MSB
  return result;
}

#define BUFFPIXEL 20

void bmpDraw(char *filename, int16_t x, int16_t y) {

  File     bmpFile;
  int      bmpWidth, bmpHeight;   // W+H in pixels
  uint8_t  bmpDepth;              // Bit depth (currently must be 24)
  uint32_t bmpImageoffset;        // Start of image data in file
  uint32_t rowSize;               // Not always = bmpWidth; may have padding
  uint8_t  sdbuffer[3*BUFFPIXEL]; // pixel buffer (R+G+B per pixel)
  uint8_t  buffidx = sizeof(sdbuffer); // Current position in sdbuffer
  boolean  goodBmp = false;       // Set to true on valid header parse
  boolean  flip    = true;        // BMP is stored bottom-to-top
  int      w, h, row, col, x2, y2, bx1, by1;
  uint8_t  r, g, b;
  uint32_t pos = 0, startTime = millis();

  if((x >= tft.width()) || (y >= tft.height())) return;

  Serial.println();
  Serial.print(F("Loading image '"));
  Serial.print(filename);
  Serial.println('\'');

  // Open requested file on SD card
  if ((bmpFile = SD.open(filename)) == NULL) {
    Serial.print(F("File not found"));
    return;
  }

  // Parse BMP header
  if(read16(bmpFile) == 0x4D42) { // BMP signature
    Serial.print(F("File size: ")); Serial.println(read32(bmpFile));
    (void)read32(bmpFile); // Read & ignore creator bytes
    bmpImageoffset = read32(bmpFile); // Start of image data
    Serial.print(F("Image Offset: ")); Serial.println(bmpImageoffset, DEC);
    // Read DIB header
    Serial.print(F("Header size: ")); Serial.println(read32(bmpFile));
    bmpWidth  = read32(bmpFile);
    bmpHeight = read32(bmpFile);
    if(read16(bmpFile) == 1) { // # planes -- must be '1'
      bmpDepth = read16(bmpFile); // bits per pixel
      Serial.print(F("Bit Depth: ")); Serial.println(bmpDepth);
      if((bmpDepth == 24) && (read32(bmpFile) == 0)) { // 0 = uncompressed

        goodBmp = true; // Supported BMP format -- proceed!
        Serial.print(F("Image size: "));
        Serial.print(bmpWidth);
        Serial.print('x');
        Serial.println(bmpHeight);

        // BMP rows are padded (if needed) to 4-byte boundary
        rowSize = (bmpWidth * 3 + 3) & ~3;

        // If bmpHeight is negative, image is in top-down order.
        // This is not canon but has been observed in the wild.
        if(bmpHeight < 0) {
          bmpHeight = -bmpHeight;
          flip      = false;
        }

        // Crop area to be loaded
        x2 = x + bmpWidth  - 1; // Lower-right corner
        y2 = y + bmpHeight - 1;
        if((x2 >= 0) && (y2 >= 0)) { // On screen?
          w = bmpWidth; // Width/height of section to load/display
          h = bmpHeight;
          bx1 = by1 = 0; // UL coordinate in BMP file
          if(x < 0) { // Clip left
            bx1 = -x;
            x   = 0;
            w   = x2 + 1;
          }
          if(y < 0) { // Clip top
            by1 = -y;
            y   = 0;
            h   = y2 + 1;
          }
          if(x2 >= tft.width())  w = tft.width()  - x; // Clip right
          if(y2 >= tft.height()) h = tft.height() - y; // Clip bottom

          // Set TFT address window to clipped image bounds
          tft.startWrite(); // Requires start/end transaction now
          tft.setAddrWindow(x, y, w, h);

          for (row=0; row<h; row++) { // For each scanline...

            // Seek to start of scan line.  It might seem labor-
            // intensive to be doing this on every line, but this
            // method covers a lot of gritty details like cropping
            // and scanline padding.  Also, the seek only takes
            // place if the file position actually needs to change
            // (avoids a lot of cluster math in SD library).
            if(flip) // Bitmap is stored bottom-to-top order (normal BMP)
              pos = bmpImageoffset + (bmpHeight - 1 - (row + by1)) * rowSize;
            else     // Bitmap is stored top-to-bottom
              pos = bmpImageoffset + (row + by1) * rowSize;
            pos += bx1 * 3; // Factor in starting column (bx1)
            if(bmpFile.position() != pos) { // Need seek?
              tft.endWrite(); // End TFT transaction
              bmpFile.seek(pos);
              buffidx = sizeof(sdbuffer); // Force buffer reload
              tft.startWrite(); // Start new TFT transaction
            }
            for (col=0; col<w; col++) { // For each pixel...
              // Time to read more pixel data?
              if (buffidx >= sizeof(sdbuffer)) { // Indeed
                tft.endWrite(); // End TFT transaction
                bmpFile.read(sdbuffer, sizeof(sdbuffer));
                buffidx = 0; // Set index to beginning
                tft.startWrite(); // Start new TFT transaction
              }
              // Convert pixel from BMP to TFT format, push to display
              b = sdbuffer[buffidx++];
              g = sdbuffer[buffidx++];
              r = sdbuffer[buffidx++];
              tft.writePixel(tft.color565(r,g,b));
            } // end pixel
          } // end scanline
          tft.endWrite(); // End last TFT transaction
        } // end onscreen
        Serial.print(F("Loaded in "));
        Serial.print(millis() - startTime);
        Serial.println(" ms");
      } // end goodBmp
    }
  }

  bmpFile.close();
  if(!goodBmp) Serial.println(F("BMP format not recognized."));
}

void loop(){
  for(uint8_t r=0; r<4; r++) {
    tft.setRotation(r);
    tft.fillScreen(TFT_BLACK);
    for(int8_t i=-2; i<1; i++) {
      bmpDraw("/purple.bmp",
        (tft.width()  / 2) + (i * 120),
        (tft.height() / 2) + (i * 160));
    }
  }
}

```

This is the image i tryed to display:
https://cdn-learn.adafruit.com/assets/assets/000/013/448/original/adafruit_products_purple.bmp?1388768741

The code just renders some random noise on the screen.

**Comment by gamecompiler** [comment]
Yup, found two errors just a after posting. Changing the method writePixel:

```
void TFT_eSPI::writePixel(uint16_t color){
    writedata(color);
}
```
I can at least identify the flower.... The next problem is the conversation from 16 to 8 bit i forgot i guess.

**Comment by gamecompiler** [comment]
Got it working, but i really dont know why it works now.
```
void TFT_eSPI::startWrite(void){
  digitalWrite(TFT_CS, LOW);
  spi_begin();
}

void TFT_eSPI::endWrite(void){
  digitalWrite(TFT_CS, HIGH);
  spi_end();
}

void TFT_eSPI::writePixel(uint16_t color){
    pushColor(color);
}
```

Please leave this issue open. I thing theres data transmitted where it shouldnt.

**Comment by gamecompiler** [comment]
Works....
Just changed:
```
//b = sdbuffer[buffidx++];
//g = sdbuffer[buffidx++];
//r = sdbuffer[buffidx++];
//to
r = sdbuffer[buffidx++];
g = sdbuffer[buffidx++];
b = sdbuffer[buffidx++];
```

**Comment by Bodmer** [comment]
The file seek is very slow so the attached approach will probably draw the image ~4x faster:

[TFT_SD_BMP.zip](https://github.com/Bodmer/TFT_eSPI/files/1746283/TFT_SD_BMP.zip)

Drawing jpeg will probably be faster too as the files are smaller.

**Comment by PumaFPV** [comment]
Hello, I am using an esp32 with 240x240 st7789 but it is not working, i have a white screen with weird black moving lines, any idea why? it is the stock code, i have tried with several pictures, bmp, jpg and png, all of them the size of my screen 
thank you

**Comment by Bodmer** [comment]
Since this topic is bitmaps from SD cards, do I assume the other library examples run fine and you are just having trouble with bitmap images?

**Comment by PumaFPV** [comment]
Yes I can display anything but image from sd card (I can display images that are stored in the progmem but after 7 images, my memory is full) thus the need for using an sd card

**Comment by Bodmer** [comment]
Have you run the SD library sketches successfully with your SD card setup?

If yes:
Which version of TFT_eSPI are you running?
Which version of the Arduino IDE?
Which version of the ESP32 board package.
Which SD library are you using?
Which example sketch are you trying to run?
Is anything reported to the Serial Monitor window by your test sketch, if so what?

**Comment by PumaFPV** [comment]
Yes my SD card is working properly alone.
TFT_eSPI: 1.4.20
Arduino IDE: 1.8.10
ESP32 package: ESP32-WROOM-32 seems to be version 1.0.4
SD lib: included with esp32 package
Serial output: Loaded in 526 ms
That's it ^^'

**Comment by Bodmer** [comment]
Which example sketch are you trying to run?

**Comment by PumaFPV** [comment]
TFT_SD_BMP
I've tried with bmp, jpg and png images

**Comment by Bodmer** [comment]
What are your connections from the ESP32 to the TFT and also to the SD Card?

**Comment by PumaFPV** [comment]
SPI, each work independently, but it seems  like the drawBmp function doesnt work properly here

**Comment by Bodmer** [comment]
Try a lower SPI clock rate in your setup file, say 10MHz and test that.

**Comment by PumaFPV** [comment]
Now I get a black screen, i dont know if it means any good

**Comment by Bodmer** [comment]
Which pins have you used for the chip select on the SD card and display?

**Comment by PumaFPV** [comment]
sd card cs: 4
st7789 cs: 5

**Comment by PumaFPV** [comment]
Found an issue that might be linked, whatever #define TFT_DS I use, only the pin 5 will work, and nothing else

**Comment by Bodmer** [comment]
Thi si te way the SD library works. If you use:
```
 SD.begin();
```
then the default is pin 5.
If you use this:
```
SD.begin(SD_CS); // or say SD.begin(22) for gpio 22
```
Then the SD_CS pin you have defined will be used as the chip select.

**Comment by PumaFPV** [comment]
Yes I know that, I've choosen the pin 4 so SD.begin(4);
And this works fine since the SD card is working with other sketches, and the tft too... I would think that the problem comes from the conversion of the image from the sd to the tft, as if either my images are not compatible or if doesnt convert them the right way

**Comment by Bodmer** [comment]
In that case I do not understand what you mean by "whatever #define TFT_DS I use, only the pin 5 will work". The example TFT_SD_BMP uses:
```
#define SD_CS 22
```
at line 16...

The example TFT_SD_BMP came with an image parrot.bmp, have you tried that?

**Comment by Bodmer** [comment]
Note that in some pre-defined user setups pin 4 is used as the TFT_RST (reset)! List all ESP32 pins you have used and what they are connected to.

Make sure the power supply is adequate to power everything. Make sure you have good electrical connections for GND to all boards, preferably GND lines should be short and not use thin wire.

**Comment by Bodmer** [comment]
I just ran the example from the zip file attached to the post on 22/2/18 and it ran fine with Setup24_ST7789.h

**Comment by mcufriend** [comment]
Thanks, Bodmer ，
 reading  BMP     images file from SD card, the display speed is greatly improved. I used  TFT-ESPI library, 3.5 "SPI display 480 X 320  ，Especially the one that was provided at the end，“TFT_SD_BMP.zip”  ，And it's very effective,，Originally wanted to abandon BMP and use JPEG files directly.

**Comment by mcufriend** [comment]
stm32f103rbt6  + 3.5 inch tftlcd  (spi ),  cpld -spi   ,480  x 320 
tft-espi,   guislice ,

**Comment by Bodmer** [comment]
Yes, same pins, use 18,19,23 for SPI bus. Get SD library examples working first with the TFT_CS signal pulled or driven to logic 1. Then try that example.

Note that removing power while an SD card read is in progress can corrupt the SD card files, so then the card needs to be reformatted and files written again.

**Comment by Anxodia** [comment]
Hallo Bodmer.

I am really sorry to bring this up again. I have been browsing the web the past three days not finding a solution to my problem. I've seen the many things that you have already achieved so maybe it is easy to provide an answer for me.

I am currently studying mechanical engineering and Im woking on my diploma-thesis at the moment. My project involves a 3.5inch 320x480 touch screen HX8357D from Adafruit with SD Card (in SPI mode) and an Arduino Mega. 

I need to draw bitmaps and have a menu with buttons that you can click trough. The menu needs to look pretty clean so I designed the menu-screens bitmaps myself. Just drawing texts isnt enough for my project.

My problem is, as to be expected loading time of the BMP24. Its just so clunky to navigate trough the menu at that speed.

I read about raw files, PNG conversion and all that stuff but I didnt find anything that suits my HX8357D.

Is there a method to achieve faster draw speed with reasonable amount of effort? I have no experience in coding btw, this is my first time. Im building a micrometer precise XY-Stage which goes under a microscope and its controlled trough the touch panel menu.

My menu screens only have three colours so maybe drawing a BMP16 oe even 8 would do the job, if thats possible?

Im happily awaiting your response
Thanks im advance,
Louis
