### ISSUE TITLE
ILI9481 white screen on ESP32

### ISSUE THREAD

**Issue by pedro371** [Bodmer/TFT_eSPI#960]
Hello,

i have connected a ili9481 on a ESP32 with this settings in the User_Setup.h

`#define ILI9481_DRIVER`

`// Tell the library to use 8 bit parallel mode (otherwise SPI is assumed)
#define TFT_PARALLEL_8_BIT

// The ESP32 and TFT the pins used for testing are:
#define TFT_CS   33  // Chip select control pin (library pulls permanently low
#define TFT_DC   15  // Data Command control pin - must use a pin in the range 0-31
#define TFT_RST  32  // Reset pin, toggles on startup

#define TFT_WR    4  // Write strobe control pin - must use a pin in the range 0-31
#define TFT_RD    2  // Read strobe control pin

#define TFT_D0   12  // Must use pins in the range 0-31 for the data bus
#define TFT_D1   13  // so a single register write sets/clears all bits.
#define TFT_D2   26  // Pins can be randomly assigned, this does not affect
#define TFT_D3   25  // TFT screen update performance.
#define TFT_D4   17
#define TFT_D5   16
#define TFT_D6   27
#define TFT_D7   14`

But my screen is always white... do you have an idea what I have done wrong?

![IMG_8340](https://user-images.githubusercontent.com/46385595/105972759-40931100-608c-11eb-8a35-86240d08ed12.jpg)
![IMG_8341](https://user-images.githubusercontent.com/46385595/105972801-48eb4c00-608c-11eb-9e86-c3eb6cf000c8.jpg)

**Comment by Bodmer** [comment]
First run the Read_User_Setup diagnostic sketch, this outputs the configuration values picked up by the compiler and prints output to the Serial Monitor window, nothing is shown on the display. Check the output against your expected settings, post output here if you are not sure.

The simplest way to connect a display to an ESP32 is to use the UNO formay ESP32, see readme. Connecting by wires can be problematic due  to ground bounce. Use short signal wires and at least 2 short GND wires.

**Comment by pedro371** [comment]
@Bodmer First of all thanks for your great library!

No it's working but I also have an another problem. How can I use touch in the parallel TFT setup?

**Comment by Bodmer** [comment]
You can use a touch support library. The choice is dependant on the type of touch interface your display has.
