### ISSUE TITLE
[Question] 16 bits color mode on ILI9481 / 88

### ISSUE THREAD

**Issue by Koxx3** [Bodmer/TFT_eSPI#971]
Hello !

In the ILI9481 datasheet, I see that the drivers support 16bits color mode :
![image](https://user-images.githubusercontent.com/11454444/106382166-258f0c80-63be-11eb-8d49-6044610404e3.png)

and it's forced to 18 bits in the lib.
![image](https://user-images.githubusercontent.com/11454444/106382178-39d30980-63be-11eb-9453-7e21dc8c2ca5.png)

Would it be possible to change to 16 bits mode ?

Of course, I tried, to force SPI_16BIT_DRIVER and the display is ugly ;)

**Comment by Koxx3** [comment]
hummmm ... DBI Type C is limited to 18bits ? 

![image](https://user-images.githubusercontent.com/11454444/106382402-b1edff00-63bf-11eb-9123-b53edbe92648.png)

**Comment by Bodmer** [comment]
Yes, with a SPI interface the display does not support 16 bit colours. In parallel mode it does.
