### ISSUE TITLE
Error compiling for board WEMOS mini - OpenWeather.cpp

### ISSUE THREAD

**Issue by gmkyte** [Bodmer/TFT_eSPI#972]
Hi, I am trying to compile TFT_eSPI_OpenWeather on my Wemos D1 Mini and TFT display which was formerly running the DarkSky code with no issues. When I try to now compile the OpenWeatherMap version using Arduino IDE V 1.8.13, I get the following errors:

C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp: In member function 'bool OW_Weather::parseRequest(String)':

C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:180:45: error: 'parseRequestSecure' was not declared in this scope
   if (Secure) return parseRequestSecure(&url);
                                             ^
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:181:40: error: 'parseRequestInsecure' was not declared in this scope
   else return parseRequestInsecure(&url);
                                        ^
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp: At global scope:
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:184:48: error: no 'bool OW_Weather::parseRequestSecure(String*)' member function declared in class 'OW_Weather'
 bool OW_Weather::parseRequestSecure(String* url) {
                                                ^
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:269:50: error: no 'bool OW_Weather::parseRequestInsecure(String*)' member function declared in class 'OW_Weather'
 bool OW_Weather::parseRequestInsecure(String* url) {
                                                  ^
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.
---------------------------------------------------------------------

I have looked at the code but cannot identify where the issue is. Any assistance would be gratefully received, thanks.

**Comment by Bodmer** [comment]
This has been fixed in the OpenWeather library.

Thanks for reporting this.
